attribute               = "lilac"
keyword                 = "almond"
"keyword.directive"     = "lilac"    # -- preprocessor comments (#if in C)
namespace               = "lilac"
operator                = "lilac"
punctuation             = "lavender"
"punctuation.delimiter" = "lavender"
special                 = "honey"
variable                = "lavender"
"variable.other.member" = "white"
# variable = "almond" # TODO: metavariables only
# "variable.parameter" = { fg = "lavender", modifiers = ["underlined"] }
comment                     = "sirocco"
constant                    = "white"
"constant.builtin"          = "white"
"constant.character.escape" = "honey"
"constant.numeric"          = "chamois"
constructor                 = "lilac"
function                    = "white"
"function.builtin"          = "white"
"function.macro"            = "lilac"
string                      = "silver"
tag                         = "almond"
type                        = "white"
"type.builtin"              = "white"             # TODO: distinguish?
"variable.builtin"          = "mint"
"variable.parameter"        = { fg = "lavender" }
# used for lifetimes
label   = "honey"
tabstop = { bg = "bossanova", modifiers = [ "italic" ] }

"markup.bold"          = { modifiers = [ "bold" ] }
"markup.heading"       = "lilac"
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.link.text"     = "almond"
"markup.link.url"      = { fg = "silver", modifiers = [ "underlined" ] }
"markup.raw"           = "almond"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "#6f44f0"
"diff.minus" = "#f22c86"
"diff.plus"  = "#35bf86"

# TODO: differentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background"           = { bg = "midnight" }
"ui.background.separator" = { fg = "comet" }
"ui.button"               = { bg = "revolver", fg = "lavender" }
"ui.button.highlight"     = { fg = "lilac" }
"ui.help"                 = { bg = "#7958DC", fg = "#171452" }
"ui.linenr"               = { fg = "comet" }
"ui.linenr.selected"      = { fg = "lilac" }
"ui.picker.selected"      = { bg = "#3a2a4c", fg = "lilac" }
"ui.picker.selected.text" = { fg = "white" }
"ui.popup"                = { bg = "revolver" }
"ui.statusline"           = { bg = "revolver", fg = "lilac" }
"ui.statusline.inactive"  = { bg = "revolver", fg = "lavender" }
"ui.text"                 = { fg = "lavender" }
"ui.text.directory"       = { fg = "lilac" }
"ui.text.focus"           = { fg = "white" }
"ui.text.inactive"        = "sirocco"
"ui.virtual"              = { fg = "comet" }
"ui.virtual.jump-label"   = { fg = "apricot", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "bossanova" }
"ui.window"               = { fg = "bossanova" }

"ui.virtual.indent-guide" = { fg = "comet" }

"ui.selection"         = { bg = "#540099" }
"ui.selection.primary" = { bg = "#540099" }
"ui.selection.glow"    = { bg = "#9F7FFF" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor"                = { modifiers = [ "reversed" ] }
"ui.cursor.insert"         = { bg = "white" }
"ui.cursor.match"          = { bg = "#6C6999", fg = "#212121" }
"ui.cursor.primary.insert" = { bg = "white" }
"ui.cursor.primary.select" = { bg = "delta" }
"ui.cursor.select"         = { bg = "delta" }
"ui.cursorline.primary"    = { bg = "bossanova" }
"ui.debug"                 = { fg = "#634450" }
"ui.debug.breakpoint"      = { fg = "apricot" }
"ui.highlight"             = { bg = "bossanova" }
"ui.highlight.frameline"   = { bg = "#634450" }
"ui.menu"                  = { bg = "revolver", fg = "lavender" }
"ui.menu.scroll"           = { bg = "comet", fg = "lavender" }
"ui.menu.selected"         = { bg = "white", fg = "revolver" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "apricot", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "silver", style = "curl" } }
"diagnostic.info"        = { underline = { color = "delta", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "lightning", style = "curl" } }

error   = "apricot"
hint    = "silver"
info    = "delta"
warning = "lightning"

[palette]
bossanova = "#452859"
comet     = "#5a5977"
lavender  = "#a4a0e8"
lilac     = "#dbbfef"
midnight  = "#3b224c"
revolver  = "#281733"
white     = "#ffffff"

almond  = "#eccdba"
chamois = "#E8DCA0"
honey   = "#efba5d"
mint    = "#9ff28f"
silver  = "#cccccc"
sirocco = "#697C81"

apricot   = "#f47868"
delta     = "#6F44F0"
lightning = "#ffcd1c"
