# Author: Two-Six<twopsix@duck.com>

"comment"                = "green"
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { bg = "red", fg = "white", modifiers = [ "bold" ] }
"diagnostic.hint"        = { fg = "gray", modifiers = [ "bold" ] }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { bg = "orange", fg = "black", modifiers = [ "bold" ] }
"diff.delta"             = { fg = "acme_bar_bg" }
"diff.minus"             = { fg = "red" }
"diff.plus"              = { fg = "green" }
"string"                 = "red"
"ui.background"          = { bg = "acme_bg" }
"ui.bufferline"          = { bg = "acme_bar_bg", fg = "black" }
"ui.bufferline.active"   = { bg = "acme_bg", fg = "black" }
"ui.cursor"              = { bg = "cursor", fg = "white" }
"ui.cursor.match"        = { bg = "acme_bar_bg" }
"ui.cursorline"          = { bg = "acme_bar_bg" }
"ui.debug"               = { fg = "orange" }
"ui.help"                = { bg = "acme_bg", fg = "black" }
"ui.highlight.frameline" = { bg = "#da8581" }
"ui.linenr"              = { bg = "acme_bg", fg = "black" }
"ui.linenr.selected"     = { bg = "acme_bg", fg = "black" }
"ui.menu"                = { bg = "acme_bg", fg = "black" }
"ui.menu.selected"       = { bg = "selected" }
"ui.popup"               = { bg = "acme_bg", fg = "black" }
"ui.selection"           = { bg = "selected" }
"ui.statusline"          = { bg = "acme_bar_bg", fg = "black" }
"ui.statusline.inactive" = { bg = "acme_bar_inactive", fg = "black" }
"ui.text"                = "black"
"ui.virtual"             = "indent"
"ui.virtual.ruler"       = { bg = "acme_bar_bg" }
"ui.window"              = { bg = "acme_bg" }

[palette]
acme_bar_bg       = "#aeeeee"
acme_bar_inactive = "#eaffff"
acme_bg           = "#ffffea"
black             = "#000000"
cursor            = "#444444"
gray              = "#777777"
green             = "#065905"
indent            = "#aaaaaa"
orange            = "#f0ad4e"
red               = "#a0342f"
selected          = "#eeee9e"
white             = "#ffffff"
