"attribute" = "orange_5"
inherits    = "adwaita-dark"

"type"         = "teal_4"
"type.builtin" = "teal_4"

"constructor" = "blue_4"

"constant"                  = "violet_4"
"constant.builtin"          = { fg = "violet_4", modifiers = [ "bold" ] }
"constant.character"        = "teal_5"
"constant.character.escape" = "violet_4"
"constant.numeric"          = { fg = "teal_5", modifiers = [ "bold" ] }

"string"         = "teal_3"
"string.regexp"  = "purple_4"
"string.special" = "blue_4"

"comment" = "light_6"

"variable"              = "dark_5"
"variable.builtin"      = "orange_4"
"variable.other"        = "teal_4"
"variable.other.member" = "teal_5"
"variable.parameter"    = "orange_4"

"label" = "purple_4"

"punctuation"           = "dark_4"
"punctuation.bracket"   = "dark_4"
"punctuation.delimiter" = "dark_4"
"punctuation.special"   = "red_5"

"keyword"           = { fg = "orange_4", modifiers = [ "bold" ] }
"keyword.control"   = { fg = "orange_4", modifiers = [ "bold" ] }
"keyword.directive" = { fg = "orange_4", modifiers = [ "bold" ] }
"keyword.function"  = "orange_4"
"keyword.operator"  = "purple_4"
"keyword.storage"   = { fg = "orange_4", modifiers = [ "bold" ] }

"operator" = "purple_4"

"function"         = "blue_4"
"function.builtin" = "blue_4"
"function.macro"   = { fg = "blue_4", modifiers = [ "bold" ] }
"function.special" = { fg = "blue_4", modifiers = [ "bold" ] }

"tag" = "teal_4"

"namespace" = "orange_4"

"diff.delta"       = "orange_5"
"diff.delta.moved" = "orange_4"
"diff.minus"       = "red_3"
"diff.plus"        = "teal_5"
"markup"           = "dark_4"
"markup.bold"      = { fg = "dark_4", modifiers = [ "bold" ] }
"markup.heading"   = { fg = "teal_4", modifiers = [ "bold" ] }
"markup.italic"    = { fg = "dark_4", modifiers = [ "italic" ] }
"markup.link"      = { fg = "blue_5", modifiers = [ "underlined" ] }
"markup.list"      = { fg = "orange_4", modifiers = [ "bold" ] }
"markup.quote"     = { fg = "dark_3", modifiers = [ "italic" ] }

"ui.background"            = { bg = "light_1", fg = "dark_4" }
"ui.background.separator"  = { bg = "light_2", fg = "split_and_borders" }
"ui.cursor"                = { bg = "dark_5", fg = "light_2" }
"ui.cursor.insert"         = { bg = "dark_4", fg = "light_2" }
"ui.cursor.match"          = { bg = "blue_1", fg = "light_2" }
"ui.cursor.primary"        = { bg = "dark_6", fg = "light_2" }
"ui.cursor.primary.insert" = { bg = "yellow_5", fg = "light_2" }
"ui.cursor.select"         = { bg = "dark_5", fg = "light_2" }
"ui.cursorline.primary"    = { bg = "light_3" }
"ui.help"                  = { bg = "light_3" }
"ui.linenr"                = "light_5"
"ui.linenr.selected"       = { bg = "light_3", fg = "dark_2", modifiers = [ "bold" ] }
"ui.menu"                  = { bg = "light_3", fg = "dark_4" }
"ui.menu.scroll"           = { bg = "light_3", fg = "dark_6" }
"ui.menu.selected"         = { bg = "blue_1", fg = "dark_4" }
"ui.popup"                 = { bg = "light_3" }
"ui.selection"             = { bg = "blue_0" }
"ui.selection.primary"     = { bg = "blue_0" }
"ui.statusline"            = { bg = "light_4", fg = "dark_4" }
"ui.statusline.inactive"   = { bg = "light_3", fg = "dark_3" }
"ui.statusline.insert"     = { bg = "teal_3", fg = "light_5" }
"ui.statusline.select"     = { bg = "blue_3", fg = "light_4" }
"ui.text"                  = "dark_4"
"ui.virtual"               = "light_1"
"ui.virtual.jump-label"    = { modifiers = [ "reversed" ] }
"ui.virtual.ruler"         = { bg = "light_5" }
"ui.virtual.whitespace"    = "light_7"
"ui.window"                = "split_and_borders"

"error"   = "red_5"
"hint"    = "blue_3"
"info"    = "purple_3"
"warning" = "yellow_4"

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { fg = "red_5", modifiers = [ "underlined" ] }
"diagnostic.hint"        = { fg = "blue_4", modifiers = [ "dim" ] }
"diagnostic.info"        = { fg = "purple_4", modifiers = [ "dim" ] }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { fg = "yellow_4", modifiers = [ "underlined" ] }

"ui.bufferline"        = { bg = "light_2", fg = "light_7" }
"ui.bufferline.active" = { bg = "light_4", fg = "dark_4", modifiers = [ "bold" ] }

[palette]
blue_0 = "#d3e4f9"
