
"attribute"                   = { fg = "blue", modifiers = [ "italic" ] }
"keyword"                     = "keyword"
"keyword.control.conditional" = { fg = "conditional", modifiers = [ "italic" ] }
"keyword.directive"           = "magenta"                                        # -- preprocessor comments (#if in C)
"ui.virtual.wrap"             = "softwrap"

"namespace" = { fg = "namespace", modifiers = [ "italic" ] }

"punctuation"           = "gray06"
"punctuation.delimiter" = "gray06"

"operator" = "operator"
"special"  = "yellow"

"variable"              = { fg = "fg" }
"variable.builtin"      = "bright_blue"
"variable.other.member" = "white"
"variable.parameter"    = { fg = "white", modifiers = [ "italic" ] }

"type"              = "bright_blue"
"type.builtin"      = "magenta"
"type.enum.variant" = "magenta"

"constructor" = "yellow"

"function"         = { fg = "function", modifiers = [ "italic" ] }
"function.builtin" = "support_function"
"function.macro"   = "bright_cyan"

"comment" = { fg = "comment", modifiers = [ "italic" ] }
"tag"     = "tag"

"string"         = "string"
"string.regexp"  = "green"
"string.special" = "yellow"

"constant"                  = "constant"
"constant.builtin"          = "yellow"
"constant.character.escape" = "cyan"
"constant.numeric"          = "numeric"

# used for lifetimes
"label" = "yellow"

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading"        = { fg = "bright_blue", modifiers = [ "bold" ] }
"markup.heading.marker" = { fg = "gray06" }
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = { fg = "blue", modifiers = [ "italic" ] }
"markup.link.url"       = { fg = "green", modifiers = [ "underlined" ] }
"markup.list"           = "gray06"
"markup.raw"            = "yellow"

"diff.delta" = "bright_blue"
"diff.minus" = "red"
"diff.plus"  = "bright_green"

"ui.background"           = { bg = "bg" }
"ui.background.separator" = { fg = "fg" }

"ui.linenr"          = { fg = "gray04" }
"ui.linenr.selected" = { fg = "fg" }

"ui.statusline"          = { bg = "gray01", fg = "status_line_fg" }
"ui.statusline.inactive" = { bg = "gray01", fg = "fg", modifiers = [ "dim" ] }
"ui.statusline.insert"   = { bg = "blue", fg = "bg", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "cyan", fg = "bg", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "magenta", fg = "bg", modifiers = [ "bold" ] }

"ui.help"   = { bg = "gray01", fg = "white" }
"ui.popup"  = { bg = "gray01" }
"ui.window" = { fg = "gray02" }

"ui.text"       = { fg = "fg" }
"ui.text.focus" = { fg = "fg" }

"ui.virtual"              = { fg = "gray02" }
"ui.virtual.indent-guide" = { fg = "gray02" }
"ui.virtual.inlay-hint"   = { fg = "gray03" }
"ui.virtual.ruler"        = { bg = "gray02" }


"ui.selection"         = { bg = "gray03" }
"ui.selection.primary" = { bg = "gray03" }

"ui.cursor"             = { bg = "cursor", fg = "bg" }
"ui.cursor.match"       = { fg = "yellow", modifiers = [ "bold", "underlined" ] }
"ui.cursorline.primary" = { bg = "gray01" }

"ui.highlight" = { bg = "gray02" }

"ui.menu"          = { bg = "gray01", fg = "white" }
"ui.menu.scroll"   = { bg = "gray01", fg = "gray04" }
"ui.menu.selected" = { bg = "gray03", fg = "bright_white" }

diagnostic               = { modifiers = [ "underlined" ] }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }

error   = "error"
hint    = "bright_cyan"
info    = "bright_blue"
warning = "yellow"

[palette]
bg               = "#0F1014"
blue             = "#aca1cf"
bright_blue      = "#b9aeda"
bright_cyan      = "#f591b2"
bright_green     = "#9dc6ac"
bright_white     = "#cac9dd"
comment          = "#808080"
conditional      = "#a8a29e"
constant         = "#8eb6f5"
cursor           = "#e5c890"
cyan             = "#ea83a5"
error            = "#fca5a5"
fg               = "#c9c7cd"
function         = "#e5c890"
gray01           = "#1b1b1d"
gray02           = "#2a2a2d"
gray03           = "#3e3e43"
gray04           = "#57575f"
gray06           = "#9998a8"
gray07           = "#c1c0d4"
green            = "#90b99f"
keyword          = "#8eb6f5"
magenta          = "#e29eca"
namespace        = "#c58fff"
numeric          = "#e9c46a"
operator         = "#8eb6f5"
red              = "#e78284"
softwrap         = "#808080"
status_line_fg   = "#e5c890"
string           = "#9898a6"
support_function = "#9898a6"
tag              = "#9898a6"
white            = "#c1c0d4"
yellow           = "#e5c890"
