# Ashen for Helix
# -------------------
# Author: Daniel Fichtinger <daniel@ficd.ca>
# License: MIT License
# Upstream: https://sr.ht/~ficd/ashen
# -------------------
# Sections:
# - Syntax highlighting
# - User interface
# - Palette

# Syntax highlighting
# -------------------
"attribute" = "g_4"

"type"              = "blue"
"type.builtin"      = "blue"
"type.enum.variant" = "orange_blaze"
"type.parameter"    = "orange_glow"

"constructor" = "g_1"

"constant"                  = "orange_blaze"
"constant.builtin"          = "blue"
"constant.character"        = { fg = "red_glowing", modifiers = [ "bold" ] }
"constant.character.escape" = "g_2"
"constant.numeric"          = "blue"

"string"                = "red_glowing"
"string.regexp"         = "orange_glow"
"string.special"        = "g_2"
"string.special.path"   = { fg = "red_glowing", modifiers = [ "bold" ] }
"string.special.symbol" = "orange_smolder"
"string.special.url"    = { fg = "red_glowing", modifiers = [ "bold" ] }

"comment"                     = { fg = "g_6", modifiers = [ "italic" ] }
"comment.block.documentation" = { fg = "g_5", modifiers = [ "italic" ] }
"comment.line.documentation"  = { fg = "g_5", modifiers = [ "italic" ] }

"variable"              = "g_3"
"variable.builtin"      = "blue"
"variable.other.member" = { fg = "g_2" }
"variable.parameter"    = { fg = "g_2", modifiers = [ "italic" ] }

"label" = "red_ember" # used for lifetimes

"punctuation"           = "g_2"
"punctuation.bracket"   = "g_6"
"punctuation.delimiter" = "orange_smolder"
"punctuation.special"   = "orange_golden"


"keyword"                  = "red_ember"
"keyword.directive"        = { fg = "red_ember", modifiers = [ "italic" ] }
"keyword.operator"         = "orange_blaze"
"keyword.storage.modifier" = { fg = "red_ember", modifiers = [ "italic" ] }

"operator" = "orange_glow"

"function"         = { fg = "g_3", modifiers = [ "bold" ] }
"function.builtin" = { fg = "g_3", modifiers = [ "bold", "italic" ] }
"function.macro"   = "red_ember"

"tag" = { fg = "orange_glow", modifiers = [ "italic" ] }

"namespace" = { fg = "orange_glow", modifiers = [ "bold" ] }

"special" = "orange_smolder" # fuzzy highlight

"markup.bold"      = { modifiers = [ "bold" ] }
"markup.heading"   = { fg = "red_glowing", modifiers = [ "bold" ] }
"markup.italic"    = { modifiers = [ "italic" ] }
"markup.link.text" = "red_ember"
"markup.link.url"  = { fg = "red_glowing", modifiers = [ "italic", "underlined" ] }
"markup.list"      = "orange_glow"
"markup.quote"     = { modifiers = [ "italic" ] }
"markup.raw"       = { bg = "g_10", fg = "g_2" }

"diff.delta" = "brown"
"diff.minus" = "red_ember"
"diff.plus"  = "g_6"

# User Interface
# --------------
"ui.background" = { bg = "background", fg = "text" }

"ui.linenr"          = { fg = "g_8" }
"ui.linenr.selected" = { fg = "g_6" }

"ui.statusline"          = { bg = "g_9", fg = "g_3" }
"ui.statusline.inactive" = { bg = "g_10", fg = "g_5" }
"ui.statusline.insert"   = { bg = "g_7", fg = "g_1", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "orange_blaze", fg = "background", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "orange_golden", fg = "background", modifiers = [ "bold" ] }

"ui.help"   = { bg = "g_10", fg = "text", modifiers = [ "bold" ] }
"ui.info"   = { bg = "g_10", fg = "orange_blaze" }
"ui.popup"  = { bg = "g_10", fg = "text" }
"ui.window" = { fg = "g_7" }

"ui.bufferline"            = { bg = "background", fg = "text" }
"ui.bufferline.active"     = { bg = "g_10", fg = "g_2", underline = { color = "orange_blaze", style = "line" } }
"ui.bufferline.background" = { bg = "background" }

"ui.text" = "text"
"ui.text.directory" = { fg = "red_ember" }
"ui.text.focus" = { bg = "g_10", fg = "g_2", modifiers = [
  "bold",
], underline = { color = "red_ember", style = "line" } }
"ui.text.inactive" = { fg = "g_7" }

"ui.virtual"              = "g_5"
"ui.virtual.indent-guide" = "g_7"
"ui.virtual.inlay-hint"   = { fg = "g_6", modifiers = [ "italic" ] }
"ui.virtual.jump-label"   = { bg = "orange_blaze", fg = "background", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "cursorline" }
"ui.virtual.whitespace"   = "g_7"
"ui.virtual.wrap"         = "g_7"

"ui.selection" = { bg = "brown_dark" }

"ui.cursor.insert"         = { bg = "g_7", fg = "background" }
"ui.cursor.match"          = { fg = "orange_smolder", modifiers = [ "underlined" ] }
"ui.cursor.normal"         = { bg = "orange_muted", fg = "background" }
"ui.cursor.primary.insert" = { bg = "g_3", fg = "background", modifiers = [ "bold" ] }
"ui.cursor.primary.normal" = { bg = "orange_blaze", fg = "background", modifiers = [ "bold" ] }
"ui.cursor.primary.select" = { bg = "orange_golden", fg = "background", modifiers = [ "bold" ] }
"ui.cursor.select"         = { bg = "golden_muted", fg = "background" }

"ui.cursorline"         = { bg = "g_12" }
"ui.cursorline.primary" = { bg = "cursorline" }

"ui.highlight" = { bg = "cursorline", fg = "orange_blaze", modifiers = [
  "bold",
], underline = { color = "red_ember", style = "line" } }

"ui.menu"          = { bg = "g_10", fg = "g_2" }
"ui.menu.selected" = { bg = "orange_blaze", fg = "background", modifiers = [ "bold" ] }

"diagnostic.error"       = { underline = { color = "red_flame", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "g_5", style = "dotted" } }
"diagnostic.info"        = { underline = { color = "g_4", style = "dotted" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange_golden", style = "curl" } }

error   = { bg = "g_10", fg = "red_flame" }
hint    = { bg = "g_10", fg = "g_4" }
info    = { bg = "g_10", fg = "g_2" }
warning = { bg = "g_10", fg = "orange_golden" }

[palette]
background     = "#121212"
blue           = "#4A8B8B"
brown          = "#89492a"
brown_dark     = "#322119"
cursorline     = "#191919"
g_1            = "#e5e5e5"
g_10           = "#1d1d1d"
g_11           = "#191919"
g_12           = "#151515"
g_2            = "#d5d5d5"
g_3            = "#b4b4b4"
g_4            = "#a7a7a7"
g_5            = "#949494"
g_6            = "#737373"
g_7            = "#535353"
g_8            = "#323232"
g_9            = "#212121"
golden_muted   = "#6D4D0D"
orange_blaze   = "#C4693D"
orange_glow    = "#D87C4A"
orange_golden  = "#E5A72A"
orange_muted   = "#6D3B22"
orange_smolder = "#E49A44"
red_ember      = "#B14242"
red_flame      = "#C53030"
red_glowing    = "#DF6464"
text           = "#b4b4b4"
