# The structure is based on `base16_default_dark` by Ray Gervais.  Most of
# the colors come from the so called Autumn theme, a color scheme inspired by
# the colors you can find in the autumn. Originally it was designed as a
# color scheme for the Komodo IDE and then ported to Vim by Kenneth Love
# and Chris Jones. Later, Yorick Peterse improved their work. See:
# <https://github.com/YorickPeterse/Autumn.vim>
# Jens Getreu ported and optimised the color theme for the Helix editor.
# Author: Jens Getreu <getreu at web.de>

"attribute" = "my_turquoise1"
"comment" = { fg = "my_gray5" }
"constant" = "my_white3"
"constant.character.escape" = "my_turquoise1"
"constant.numeric" = "my_turquoise1"
"constructor" = "my_yellow1"
"debug" = "my_yellow2"
"diagnostic" = { bg = "my_black", underline = { color = "my_gray5", style = "line" } }
"diagnostic.deprecated" = { modifiers = [ "crossed_out" ] }
"diagnostic.error" = { underline = { color = "my_red", style = "curl" } }
"diagnostic.hint" = { bg = "my_black", underline = { color = "my_gray5", style = "line" } }
"diagnostic.info" = { underline = { style = "line" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning" = { underline = { color = "my_yellow2", style = "curl" } }
"diff.delta" = "my_gray5"
"diff.minus" = "my_red"
"diff.plus" = "my_green"
"error" = "my_red"
"function" = "my_yellow1"
"hint" = "my_gray6"
"info" = "my_yellow2"
"keyword" = "my_red"
"label" = "my_red"
"markup.bold" = { modifiers = [ "bold" ] }
"markup.heading" = "my_yellow1"
"markup.italic" = { modifiers = [ "italic" ] }
"markup.link.text" = "my_white2"
"markup.link.url" = "my_turquoise2"
"markup.list" = "my_white2"
"markup.quote" = "my_brown"
"markup.raw" = "my_green"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }
"namespace" = "my_white3"
"operator" = "my_white1"
"special" = "my_yellow1"
"string" = "my_green"
"type" = { fg = "my_white3", modifiers = [ "italic" ] }
"ui.background" = { bg = "my_gray0" }
"ui.cursor" = { bg = "my_white4", fg = "my_black" }
"ui.cursor.match" = { bg = "my_black", fg = "my_white1", modifiers = [
  "bold",
], underline = { color = "my_white1", style = "double_line" } }
"ui.cursor.primary" = { fg = "my_white1", modifiers = [ "reversed" ] }
"ui.cursorline" = { bg = "my_gray3" }
"ui.cursorline.primary" = { bg = "my_black" }
"ui.cursorline.secondary" = { bg = "my_black" }
"ui.debug" = { bg = "my_gray0", fg = "my_yellow1" }
"ui.gutter" = { bg = "my_gray0" }
"ui.help" = { bg = "my_gray2", fg = "my_gray7" }
"ui.highlight.frameline" = { bg = "#8b6904" }
"ui.linenr" = { bg = "my_gray0", fg = "my_gray3" }
"ui.linenr.selected" = { bg = "my_gray0", fg = "my_gray7" }
"ui.menu" = { bg = "my_gray2", fg = "my_white1" }
"ui.menu.selected" = { bg = "my_gray6", fg = "my_gray2" }
"ui.popup" = { bg = "my_gray2" }
"ui.selection" = { bg = "my_gray3" }
"ui.statusline" = { bg = "my_gray2", fg = "my_gray7" }
"ui.statusline.inactive" = { bg = 'my_gray2', fg = 'my_gray5' }
"ui.statusline.insert" = { bg = "my_gray6", fg = "my_black", modifiers = [ "bold" ] }
"ui.statusline.normal" = { bg = "my_gray2", fg = "my_gray7" }
"ui.statusline.select" = { bg = "my_black", fg = "my_gray7", modifiers = [ "bold" ] }
"ui.text" = "my_white1"
"ui.text.focus" = "my_white1"
# Invalid modifier: "normal". See 'https://github.com/helix-editor/helix/issues/5709'
"ui.virtual.inlay-hint" = { bg = "my_black", fg = "my_gray4" } #, modifiers = ["normal"] }
# "ui.virtual.inlay-hint.parameter" = { fg = "my_gray4", modifiers = ["normal"] }
"ui.virtual.inlay-hint.parameter" = "my_gray4"
"ui.virtual.inlay-hint.type"      = { fg = "my_gray4", modifiers = [ "italic" ] }
"ui.virtual.jump-label"           = { fg = "my_yellow2", modifiers = [ "bold" ] }
"ui.virtual.ruler"                = { bg = "my_gray1" }
"ui.virtual.whitespace"           = { fg = "my_gray6" }
"ui.virtual.wrap"                 = "my_gray4"
"ui.window"                       = { bg = "my_gray2", fg = "my_gray3" }
"variable"                        = "my_white3"
"variable.other.member"           = "my_brown"
"warning"                         = "my_yellow2"

[palette]
my_black      = "#212121" # Cursorline
my_brown      = "#cfba8b" # Member variables, Quotes
my_gray0      = "#232323" # Default Background
my_gray1      = "#2b2b2b" # Ruler
my_gray2      = "#323232" # Lighter Background (Used for status bars, line number and folding marks)
my_gray3      = "#404040" # Selection Background
my_gray4      = "#646f69" # Inlay-hint
my_gray5      = "#646f69" # Comments, Invisibles, Line Highlighting
my_gray6      = "#a8a8a8" # Dark Foreground (Used for status bars)
my_gray7      = "#c8c8c8" # Light Foreground
my_gray8      = "#e8e8e8" # Light Background
my_green      = "#99be70" # Strings, Inherited Class, Markup Code, Diff Inserted
my_red        = "#F05E48" # Keywords, Storage, Selector, Diff Changed
my_turquoise1 = "#86c1b9" # Support, Regular Expressions, Escape Characters
my_turquoise2 = "#72a59e" # URL
my_white1     = "#F3F2CC" # Default Foreground, Caret, Delimiters, Operators
my_white2     = "#F3F2CC" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
my_white3     = "#F3F2CC" # Classes, Markup Bold, Search Text Background
my_white4     = "#7e7d6a" # Cursor match
my_yellow1    = "#FAD566" # Functions, Methods, Attribute IDs, Headings
my_yellow2    = "#ffff9f" # Debug, Info
