# Author: André Sá <enkodr@outlook.com>
# Based on the AYU theme colors from https://github.com/dempfi/ayu

# Syntax highlighting
"comment"              = { fg = "gray", modifiers = [ "italic" ] }
"constant"             = "magenta"
"constructor"          = "green"
"diff.delta"           = "yellow"
"diff.minus"           = "red"
"diff.plus"            = "green"
"function"             = "yellow"
"keyword"              = "orange"
"keyword.control"      = "yellow"
"keyword.directive"    = "yellow"
"label"                = "orange"
"markup.bold"          = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading"       = "orange"
"markup.italic"        = { fg = "orange", modifiers = [ "italic" ] }
"markup.link.label"    = "green"
"markup.link.text"     = "yellow"
"markup.link.url"      = "blue"
"markup.list"          = "yellow"
"markup.quote"         = "yellow"
"markup.raw.block"     = "orange"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }
"namespace"            = "blue"
"operator"             = "orange"
"punctuation"          = "foreground"
"string"               = "green"
"string.regexp"        = "orange"
"string.special"       = "yellow"
"tag"                  = "blue"
"type"                 = "blue"
"type.builtin"         = "blue"
"variable"             = "foreground"

# Interface
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }
"error"                  = { fg = "red", modifiers = [ "bold" ] }
"hint"                   = { fg = "blue", modifiers = [ "bold" ] }
"info"                   = { fg = "blue", modifiers = [ "bold" ] }
"ui.background"          = { bg = "background" }
"ui.bufferline"          = { bg = "background", fg = "gray" }
"ui.bufferline.active"   = { bg = "dark_gray", fg = "foreground" }
"ui.cursor"              = { bg = "yellow", fg = "dark_gray" }
"ui.cursor.match"        = "orange"
"ui.cursor.primary"      = { bg = "orange", fg = "dark_gray" }
"ui.cursorline"          = { bg = "black" }
"ui.debug"               = { bg = "background", fg = "orange" }
"ui.help"                = { bg = "black", fg = "#7B91b3" }
"ui.highlight.frameline" = { bg = "#0067a3" }
"ui.linenr"              = "dark_gray"
"ui.linenr.selected"     = "gray"
"ui.menu"                = { bg = "black", fg = "foreground" }
"ui.menu.selected"       = { bg = "gray", fg = "background" }
"ui.popup"               = { bg = "black", fg = "#7B91b3" }
"ui.selection"           = { bg = "dark_gray" }
"ui.statusline"          = { bg = "black", fg = "foreground" }
"ui.statusline.insert"   = { bg = "orange", fg = "black" }
"ui.statusline.normal"   = { bg = "blue", fg = "black" }
"ui.statusline.select"   = { bg = "magenta", fg = "black" }
"ui.text"                = "foreground"
"ui.text.focus"          = { bg = "dark_gray", fg = "foreground" }
"ui.text.info"           = "foreground"
"ui.virtual.inlay-hint"  = { bg = "#302a20", fg = "#e6b450" }                   # original bg #e6b45033
"ui.virtual.jump-label"  = { fg = "red", modifiers = [ "italic", "bold" ] }
"ui.virtual.ruler"       = { bg = "black" }
"ui.virtual.whitespace"  = "dark_gray"
"ui.window"              = "dark_gray"
"warning"                = "yellow"

"special" = "orange"

[palette]
background = "#0f1419"
foreground = "#bfbdb6"

black     = "#131721"
blue      = "#59c2ff"
cyan      = "#73b8ff"
dark_gray = "#2d3640"
gray      = "#5c6773"
green     = "#aad94c"
magenta   = "#d2a6ff"
orange    = "#ff8f40"
red       = "#f07178"
yellow    = "#e6b450"
