inherits = 'ayu_dark'

"constructor"              = "magenta"
"keyword.control"          = "orange"
"keyword.storage"          = "yellow"
"keyword.storage.modifier" = "magenta"
"type.builtin"             = { fg = "blue", modifiers = [ "italic" ] }
"variable"                 = "light_gray"

# Gutters and editing area
"diagnostic.error"   = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"    = { underline = { color = "vibrant_yellow", style = "curl" } }
"diagnostic.info"    = { underline = { color = "white", style = "curl" } }
"diagnostic.warning" = { underline = { color = "vibrant_orange", style = "curl" } }
"error"              = "red"
"hint"               = "vibrant_yellow"
"info"               = "white"
"warning"            = "vibrant_orange"

"markup.raw.block"  = { bg = "black" }
"markup.raw.inline" = { bg = "black" }

"ui.bufferline"            = { bg = "background", fg = "light_gray" }
"ui.bufferline.active"     = { bg = "dark_gray", fg = "light_gray" }
"ui.cursor"                = { bg = "light_gray", fg = "dark_gray" }
"ui.cursor.primary"        = { bg = "orange", fg = "dark_gray" }
"ui.cursor.primary.insert" = { bg = "green", fg = "dark_gray" }
"ui.cursor.primary.select" = { bg = "magenta", fg = "dark_gray" }
"ui.text.inactive"         = "gray"
"ui.virtual.jump-label"    = { fg = "red", modifiers = [ "italic", "bold" ] }

[palette]
background     = '#020202'
black          = "#0D0D0D"
light_gray     = "#dedede"
red            = "#DD3E25"
vibrant_orange = "#FF8732"
vibrant_yellow = "#CFCA0D"
