# Author: NNB <nnbnh@protonmail.com>

"attribute"                 = "base09"
"comment"                   = { fg = "base03", modifiers = [ "italic" ] }
"constant"                  = "base09"
"constant.character.escape" = "base0C"
"constant.numeric"          = "base09"
"constructor"               = "base0D"
"function"                  = "base0D"
"keyword"                   = "base0E"
"label"                     = "base0E"
"namespace"                 = "base0E"
"operator"                  = "base05"
"special"                   = "base0D"
"string"                    = "base0B"
"type"                      = "base0A"
"ui.background"             = { bg = "base00" }
"ui.cursor"                 = { fg = "base04", modifiers = [ "reversed" ] }
"ui.cursor.match"           = { fg = "base0A", modifiers = [ "underlined" ] }
"ui.cursor.primary"         = { fg = "base05", modifiers = [ "reversed" ] }
"ui.help"                   = { bg = "base01", fg = "base06" }
"ui.linenr"                 = { bg = "base01", fg = "base03" }
"ui.linenr.selected"        = { bg = "base01", fg = "base04", modifiers = [ "bold" ] }
"ui.menu"                   = { bg = "base01", fg = "base05" }
"ui.menu.selected"          = { bg = "base04", fg = "base01" }
"ui.popup"                  = { bg = "base01" }
"ui.selection"              = { bg = "base02" }
"ui.statusline"             = { bg = "base01", fg = "base04" }
"ui.text"                   = "base05"
"ui.text.focus"             = "base05"
"ui.virtual.jump-label"     = { fg = "blue", modifiers = [ "bold", "underlined" ] }
"ui.virtual.ruler"          = { bg = "base01" }
"ui.virtual.whitespace"     = "base03"
"ui.window"                 = { bg = "base01" }
"variable"                  = "base08"
"variable.other.member"     = "base0B"

"markup.bold"          = { fg = "base0A", modifiers = [ "bold" ] }
"markup.heading"       = "base0D"
"markup.italic"        = { fg = "base0E", modifiers = [ "italic" ] }
"markup.link.text"     = "base08"
"markup.link.url"      = { fg = "base09", modifiers = [ "underlined" ] }
"markup.list"          = "base08"
"markup.quote"         = "base0C"
"markup.raw"           = "base0B"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus"  = "base0B"

"debug"      = "base03"
"diagnostic" = { modifiers = [ "underlined" ] }
"error"      = "base08"
"hint"       = "base03"
"info"       = "base0D"
"ui.gutter"  = { bg = "base01" }
"warning"    = "base09"

"ui.bufferline"        = { bg = "base01", fg = "base04" }
"ui.bufferline.active" = { bg = "base00", fg = "base07" }

[palette]
base00 = "#f8f8f8" # Default Background
base01 = "#e8e8e8" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#d8d8d8" # Selection Background
base03 = "#b8b8b8" # Comments, Invisibles, Line Highlighting
base04 = "#585858" # Dark Foreground (Used for status bars)
base05 = "#383838" # Default Foreground, Caret, Delimiters, Operators
base06 = "#282828" # Light Foreground (Not often used)
base07 = "#181818" # Light Background (Not often used)
base08 = "#ab4642" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#dc9656" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f7ca88" # Classes, Markup Bold, Search Text Background
base0B = "#a1b56c" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#86c1b9" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#7cafc2" # Functions, Methods, Attribute IDs, Headings
base0E = "#ba8baf" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
