# Author: NNB <nnbnh@protonmail.com>

"attribute"                 = "yellow"
"comment"                   = { fg = "light-gray", modifiers = [ "italic" ] }
"constant"                  = "yellow"
"constant.character.escape" = "light-cyan"
"constant.numeric"          = "yellow"
"constructor"               = "light-blue"
"function"                  = "light-blue"
"keyword"                   = "light-magenta"
"label"                     = "light-magenta"
"namespace"                 = "light-magenta"
"special"                   = "light-blue"
"string"                    = "light-green"
"type"                      = "light-yellow"
"ui.cursor"                 = { fg = "light-gray", modifiers = [ "reversed" ] }
"ui.cursor.match"           = { fg = "light-yellow", modifiers = [ "underlined" ] }
"ui.cursor.primary"         = { fg = "light-gray", modifiers = [ "reversed" ] }
"ui.help"                   = { bg = "black", fg = "white" }
"ui.linenr"                 = { bg = "black", fg = "light-gray" }
"ui.linenr.selected"        = { bg = "black", fg = "white", modifiers = [ "bold" ] }
"ui.menu"                   = { bg = "gray", fg = "light-gray" }
"ui.menu.selected"          = { modifiers = [ "reversed" ] }
"ui.popup"                  = { bg = "black" }
"ui.selection"              = { fg = "gray", modifiers = [ "reversed" ] }
"ui.statusline"             = { bg = "black", fg = "white" }
"ui.statusline.inactive"    = { bg = "black", fg = "gray" }
"ui.virtual.jump-label"     = { fg = "blue", modifiers = [ "bold", "underlined" ] }
"ui.virtual.ruler"          = { bg = "black" }
"ui.virtual.whitespace"     = "light-gray"
"ui.window"                 = { bg = "black" }
"variable"                  = "light-red"
"variable.other.member"     = "light-green"

"markup.bold"          = { fg = "light-yellow", modifiers = [ "bold" ] }
"markup.heading"       = "light-blue"
"markup.italic"        = { fg = "light-magenta", modifiers = [ "italic" ] }
"markup.link.text"     = "light-red"
"markup.link.url"      = { fg = "yellow", modifiers = [ "underlined" ] }
"markup.list"          = "light-red"
"markup.quote"         = "light-cyan"
"markup.raw"           = "light-green"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "yellow"
"diff.minus" = "light-red"
"diff.plus"  = "light-green"

"debug"      = "gray"
"diagnostic" = { modifiers = [ "underlined" ] }
"error"      = "light-red"
"hint"       = "gray"
"info"       = "light-blue"
"ui.gutter"  = { bg = "black" }
"warning"    = "yellow"
