# Beans
# A slightly modified Jellybeans with better support for multi-cursor and multiple selections
#
# Original repository: nanotech/jellybeans.vim
# Contributors:
# @cemalokten
# @gnur


"attribute"         = "green"
"constant"          = "dark_orange"
"constructor"       = "yellow"
"type"              = "light_blue"
"type.enum.variant" = "purple"

"comment"                   = "light_gray"
"constant.builtin.boolean"  = "yellow"
"constant.character"        = "yellow"
"constant.character.escape" = "red_error"
"constant.numeric"          = "dark_orange"
"string"                    = "dark_green"
"string.regexp"             = "light_purple"
"string.special"            = { fg = "yellow", modifiers = [ "underlined" ] }

"function"                  = "yellow"
"function.builtin"          = "green"
"function.macro"            = "green"
"function.method"           = "yellow"
"function.special"          = "green"
"keyword"                   = "mid_blue"
"keyword.control.exception" = "purple"
"label"                     = "yellow"
"namespace"                 = "light_purple"
"operator"                  = "light_purple"
"punctuation"               = "mid_blue"
"special"                   = "green"
"tag"                       = "light_blue"
"variable"                  = "light_yellow"
"variable.builtin"          = { fg = "dark_green", modifiers = [ "underlined" ] }
"variable.other.member"     = "light_purple"
"variable.parameter"        = "yellow"

"markup.bold"            = { fg = "white", modifiers = [ "bold" ] }
"markup.heading"         = { fg = "mid_blue", modifiers = [ "bold" ] }
"markup.italic"          = { modifiers = [ "italic" ] }
"markup.link.label"      = "purple"
"markup.link.text"       = "mid_blue"
"markup.link.url"        = { fg = "dark_green", modifiers = [ 'italic', 'underlined' ] }
"markup.list"            = "dark_green"
"markup.list.numbered"   = "mid_blue"
"markup.list.unnumbered" = "mid_blue"
"markup.quote"           = "dark_green"
"markup.raw"             = "dark_green"
"markup.raw.block"       = "dark_green"
"markup.raw.inline"      = "mid_blue"
"markup.strikethrough"   = { modifiers = [ "crossed_out" ] }

"diff.delta" = "blue_accent"
"diff.minus" = "red_accent"
"diff.plus"  = "diff_plus"

# ui specific
"diagnostic"             = { modifiers = [  ] }
"diagnostic.error"       = { underline = { color = "red_error", style = "line" } }
"diagnostic.hint"        = { underline = { color = "white", style = "line" } }
"diagnostic.info"        = { underline = { color = "blue_accent", style = "line" } }
"diagnostic.warning"     = { underline = { color = "yellow_accent", style = "line" } }
"error"                  = "red_error"
"hint"                   = "blue"
"info"                   = "yellow_accent"
"ui.background"          = { bg = "background" }
"ui.cursor"              = { bg = "purple", fg = "selectionfg" }
"ui.cursor.insert"       = { bg = "light_yellow", fg = "background" }
"ui.cursor.match"        = { bg = "dark_orange", fg = "background" }
"ui.cursor.normal"       = { bg = "purple", fg = "selectionfg" }
"ui.cursor.primary"      = { bg = "dark_blue", fg = "white" }
"ui.cursorline"          = { bg = "darker" }
"ui.help"                = { bg = "darkest", fg = "light_yellow" }
"ui.linenr"              = "dark_gray"
"ui.linenr.selected"     = { bg = "darker", fg = "light_yellow" }
"ui.menu"                = { bg = "darkest", fg = "light_purple" }
"ui.menu.selected"       = { bg = "dark_blue", fg = "white" }
"ui.popup"               = { bg = "darkest", fg = "light_yellow" }
"ui.selection"           = { bg = "light_blue", fg = "darkest" }
"ui.selection.primary"   = { bg = "light_purple", fg = "darkest" }
"ui.statusline"          = { bg = "darker", fg = "light_yellow" }
"ui.statusline.inactive" = { bg = "darker", fg = "dark" }
"ui.statusline.insert"   = { bg = "purple", fg = "darker" }
"ui.statusline.normal"   = { bg = "darker", fg = "light_yellow" }
"ui.statusline.select"   = { bg = "selection", fg = "selectionfg" }
"ui.text"                = "light_yellow"
"ui.text.focus"          = { bg = "dark_blue", fg = "white" }
"ui.virtual"             = "dark"
"ui.virtual.jump-label"  = { bg = "light_blue", fg = "darkest", modifiers = [ "bold" ] }
"ui.virtual.ruler"       = { bg = "darker" }
"ui.window"              = { bg = "darkest", fg = "dark" }
"warning"                = "orange_accent"

[palette]
background = "#111111"
dark       = "#898989"
dark_gray  = "#535353"
darker     = "#292929"
darkest    = "#1c1c1c"
light_gray = "#6d6d6d"
white      = "#ffffff"

light_purple = "#be67e1"
purple       = "#833c9f"

blue        = "#048ac7"
blue_accent = "#63e7f0"
dark_blue   = "#0ac1cd"
light_blue  = "#48c6ff"
mid_blue    = "#8197bf"

dark_green = "#cee318"
green      = "#ccff00"

red        = "#cc7c8a"
red_accent = "#f44747"
red_error  = "#902020"

dark_orange   = "#ff005b"
orange        = "#ff9f00"
orange_accent = "#ee7f25"

light_yellow  = "#ebebd8"
yellow        = "#fad07a"
yellow_accent = "#dea407"

diff_plus   = "#5a9f81"
selection   = "#37232d"
selectionfg = "#e5e5e5"
