# Author : Wojciech Kępka <wojciech@wkepka.dev>

"attribute"                 = "bogster-orange"
"comment"                   = "bogster-base5"
"constant"                  = "bogster-teal"
"constant.builtin"          = "bogster-teal"
"constant.character.escape" = { fg = "bogster-lgreen", modifiers = [ "bold" ] }
"constant.numeric"          = "bogster-blue"
"constructor"               = "bogster-lred"
"function"                  = "bogster-lblue"
"function.builtin"          = { fg = "bogster-lblue", modifiers = [ "bold" ] }
"function.macro"            = { fg = "bogster-orange", modifiers = [ "bold" ] }
"keyword"                   = { fg = "bogster-yellow", modifiers = [ "bold" ] }
"keyword.directive"         = "bogster-yellow"
"label"                     = "bogster-blue"
"module"                    = "bogster-red"
"namespace"                 = "bogster-red"
"operator"                  = { fg = "bogster-orange", modifiers = [ "bold" ] }
"punctuation"               = "bogster-orange"
"punctuation.delimiter"     = "bogster-orange"
"special"                   = "bogster-lgreen"
"string"                    = "bogster-teal"
"type"                      = "bogster-lred"
"type.builtin"              = { fg = "bogster-red", modifiers = [ "bold" ] }
"variable"                  = "bogster-fg0"
"variable.builtin"          = "bogster-fg0"
"variable.other.member"     = "bogster-fg0"
"variable.parameter"        = "bogster-fg0"

"markup.bold"          = { fg = "bogster-yellow", modifiers = [ "bold" ] }
"markup.heading"       = "bogster-blue"
"markup.italic"        = { fg = "magenta", modifiers = [ "italic" ] }
"markup.link.text"     = "bogster-red"
"markup.link.url"      = { fg = "bogster-yellow", modifiers = [ "underlined" ] }
"markup.list"          = "bogster-red"
"markup.quote"         = "bogster-lblue"
"markup.raw"           = "bogster-teal"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "bogster-orange"
"diff.minus" = "bogster-lred"
"diff.plus"  = "bogster-teal"

"ui.background"          = { bg = "bogster-base0" }
"ui.cursorline"          = { bg = "bogster-base00" }
"ui.help"                = { bg = "bogster-base1", fg = "bogster-fg1" }
"ui.linenr"              = { fg = "bogster-base3" }
"ui.linenr.selected"     = { fg = "bogster-fg1" }
"ui.popup"               = { bg = "bogster-base1" }
"ui.statusline"          = { bg = "bogster-base1", fg = "bogster-fg1" }
"ui.statusline.inactive" = { bg = "bogster-base1", fg = "bogster-fg0" }
"ui.window"              = { bg = "bogster-base1" }

"ui.statusline.insert" = { bg = "bogster-lgreen", fg = "bogster-base0", modifiers = [ "bold" ] }
"ui.statusline.normal" = { bg = "bogster-blue", fg = "bogster-base0", modifiers = [ "bold" ] }
"ui.statusline.select" = { bg = "bogster-red", fg = "bogster-base0", modifiers = [ "bold" ] }

"ui.text"               = { fg = "bogster-fg1" }
"ui.text.focus"         = { fg = "bogster-fg1", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "bogster-base00" }
"ui.virtual.whitespace" = "bogster-base5"

"ui.cursor"       = { fg = "bogster-gray", modifiers = [ "reversed" ] }
"ui.cursor.match" = { bg = "bogster-orange", fg = "bogster-base2" }
"ui.selection"    = { bg = "bogster-base1" }

"ui.menu"          = { bg = "bogster-base1", fg = "bogster-fg1" }
"ui.menu.selected" = { bg = "bogster-base2" }

"error"   = "bogster-lred"
"hint"    = "bogster-blue"
"info"    = "bogster-teal"
"warning" = "bogster-orange"

# make diagnostic underlined, to distinguish with selection text.
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "bogster-lred", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "bogster-blue", style = "curl" } }
"diagnostic.info"        = { underline = { color = "bogster-teal", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "bogster-orange", style = "curl" } }

[palette]
bogster-blue   = "#59c0dc"
bogster-gray   = "#abb2bf"
bogster-lblue  = "#289cbc"
bogster-lgreen = "#7fdc59"
bogster-lred   = "#dc597f"
bogster-orange = "#dc7759"
bogster-red    = "#d32c5d"
bogster-teal   = "#23a580"
bogster-yellow = "#a58023"

bogster-fg0 = "#232d38"
bogster-fg1 = "#161c23"

bogster-base0  = "#f6fbd6"
bogster-base00 = "#d7dbbb"
bogster-base1  = "#c7c7ba"
bogster-base2  = "#aaaa97"
bogster-base3  = "#415367"
bogster-base5  = "#627d9d"
