# made by bootra

"attribute"        = { fg = "lilac" }
"comment"          = { fg = "berry_desaturated" }
"constant"         = { fg = "gold" }
"function"         = { fg = "mint" }
"function.macro"   = { fg = "bubblegum" }
"keyword"          = { fg = "bubblegum" }
"label"            = { fg = "gold" }
"module"           = { fg = "lilac" }
"namespace"        = { fg = "lilac" }
"operator"         = { fg = "bubblegum" }
"punctuation"      = { fg = "lilac" }
"string"           = { fg = "gold" }
"tag"              = { fg = "gold" }
"type"             = { fg = "violet" }
"variable"         = { fg = "lilac" }
"variable.builtin" = { fg = "violet" }

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading"        = { fg = "gold", modifiers = [ "bold" ] }
"markup.heading.marker" = { fg = "berry_desaturated" }
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = { fg = "violet" }
"markup.link.url"       = { fg = "violet", modifiers = [ "underlined" ] }
"markup.list"           = { fg = "bubblegum" }
"markup.quote"          = { fg = "berry_desaturated" }
"markup.raw"            = { fg = "mint" }
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"ui.background"           = { bg = "berry" }
"ui.cursor"               = { bg = "lilac", fg = "berry" }
"ui.cursor.insert"        = { bg = "mint", fg = "berry" }
"ui.cursor.match"         = { bg = "berry_desaturated", fg = "berry" }
"ui.cursor.select"        = { bg = "violet", fg = "berry" }
"ui.cursorline"           = { bg = "berry_dim", fg = "lilac" }
"ui.help"                 = { bg = "berry_saturated", fg = "lilac" }
"ui.linenr"               = { fg = "berry_desaturated" }
"ui.linenr.selected"      = { fg = "lilac" }
"ui.menu"                 = { bg = "berry_saturated", fg = "lilac" }
"ui.menu.selected"        = { bg = "berry_saturated", fg = "mint" }
"ui.popup"                = { bg = "berry_saturated", fg = "lilac" }
"ui.selection"            = { bg = "berry_saturated" }
"ui.statusline"           = { bg = "berry_saturated", fg = "lilac" }
"ui.statusline.inactive"  = { bg = "berry_saturated", fg = "berry_desaturated" }
"ui.statusline.insert"    = { bg = "mint", fg = "berry_saturated" }
"ui.statusline.normal"    = { bg = "lilac", fg = "berry_saturated" }
"ui.statusline.select"    = { bg = "violet", fg = "berry_saturated" }
"ui.text"                 = { fg = "lilac" }
"ui.text.focus"           = { fg = "mint" }
"ui.virtual.indent-guide" = { fg = "berry_fade" }
"ui.virtual.inlay-hint"   = { fg = "berry_desaturated" }
"ui.virtual.ruler"        = { bg = "berry_dim" }
"ui.virtual.whitespace"   = { fg = "berry_desaturated" }
"ui.window"               = { bg = "berry", fg = "berry_desaturated" }

"diff.delta" = { fg = "gold" }
"diff.minus" = { fg = "bubblegum" }
"diff.plus"  = { fg = "mint" }

"error"   = { fg = "bubblegum" }
"hint"    = { fg = "lilac" }
"info"    = { fg = "lilac" }
"warning" = { fg = "gold" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "gold", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "lilac", style = "curl" } }
"diagnostic.info"        = { underline = { color = "lilac", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "bubblegum", style = "curl" } }

[palette]
berry             = "#3A2A4D"
berry_desaturated = "#886C9C"
berry_dim         = "#47345E"
berry_fade        = "#5A3D6E"
berry_saturated   = "#2B1C3D"
bubblegum         = "#D678B5"
gold              = "#E3C0A8"
lilac             = "#C7B8E0"
mint              = "#7FC9AB"
violet            = "#C78DFC"
