inherits = "catppuccin_mocha"

[palette]
base      = "#24273a"
blue      = "#8aadf4"
crust     = "#181926"
flamingo  = "#f0c6c6"
green     = "#a6da95"
lavender  = "#b7bdf8"
mantle    = "#1e2030"
maroon    = "#ee99a0"
mauve     = "#c6a0f6"
overlay0  = "#6e738d"
overlay1  = "#8087a2"
overlay2  = "#939ab7"
peach     = "#f5a97f"
pink      = "#f5bde6"
red       = "#ed8796"
rosewater = "#f4dbd6"
sapphire  = "#7dc4e4"
sky       = "#91d7e3"
subtext0  = "#a5adcb"
subtext1  = "#b8c0e0"
surface0  = "#363a4f"
surface1  = "#494d64"
surface2  = "#5b6078"
teal      = "#8bd5ca"
text      = "#cad3f5"
yellow    = "#eed49f"

cursorline              = "#303347"
secondary_cursor        = "#b6a6a7"
secondary_cursor_insert = "#80a57a"
secondary_cursor_normal = "#8b91bf"
