# NOTE: For contributors looking to modify the theme, please submit a pull request at https://github.com/catppuccin/helix instead of updating this file. Changes are frequently synchronized from the catppuccin/helix theme repository.
# Syntax highlighting
# -------------------
"attribute" = "yellow"

"type"              = "yellow"
"type.enum.variant" = "teal"

"constructor" = "sapphire"

"constant"                  = "peach"
"constant.character"        = "teal"
"constant.character.escape" = "pink"

"string"                = "green"
"string.regexp"         = "pink"
"string.special"        = "blue"
"string.special.symbol" = "red"

"comment" = { fg = "overlay2", modifiers = [ "italic" ] }

"variable"              = "text"
"variable.builtin"      = "red"
"variable.other.member" = "blue"
"variable.parameter"    = { fg = "maroon", modifiers = [ "italic" ] }

"label" = "sapphire" # used for lifetimes

"punctuation"         = "overlay2"
"punctuation.special" = "sky"

"keyword"                     = "mauve"
"keyword.control.conditional" = { fg = "mauve", modifiers = [ "italic" ] }

"operator" = "sky"

"function"       = "blue"
"function.macro" = "mauve"

"tag" = "blue"

"namespace" = { fg = "yellow", modifiers = [ "italic" ] }

"special" = "blue" # fuzzy highlight

"markup.bold"           = { fg = "red", modifiers = [ "bold" ] }
"markup.heading.1"      = "red"
"markup.heading.2"      = "peach"
"markup.heading.3"      = "yellow"
"markup.heading.4"      = "green"
"markup.heading.5"      = "sapphire"
"markup.heading.6"      = "lavender"
"markup.italic"         = { fg = "red", modifiers = [ "italic" ] }
"markup.link.label"     = "sapphire"
"markup.link.text"      = "lavender"
"markup.link.url"       = { fg = "blue", modifiers = [ "italic", "underlined" ] }
"markup.list"           = "teal"
"markup.list.checked"   = "green"
"markup.list.unchecked" = "overlay2"
"markup.quote"          = "pink"
"markup.raw"            = "green"

"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus"  = "green"

# User Interface
# --------------
"ui.background" = { bg = "base", fg = "text" }

"ui.linenr"          = { fg = "surface1" }
"ui.linenr.selected" = { fg = "lavender" }

"ui.statusline"          = { bg = "mantle", fg = "subtext1" }
"ui.statusline.inactive" = { bg = "mantle", fg = "surface2" }
"ui.statusline.insert"   = { bg = "green", fg = "base", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "rosewater", fg = "base", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "lavender", fg = "base", modifiers = [ "bold" ] }

"ui.help"   = { bg = "surface0", fg = "overlay2" }
"ui.popup"  = { bg = "surface0", fg = "text" }
"ui.window" = { fg = "crust" }

"ui.bufferline"            = { bg = "mantle", fg = "subtext0" }
"ui.bufferline.active"     = { bg = "base", fg = "mauve", underline = { color = "mauve", style = "line" } }
"ui.bufferline.background" = { bg = "crust" }

"ui.text"           = "text"
"ui.text.directory" = { fg = "blue" }
"ui.text.focus"     = { bg = "surface0", fg = "text", modifiers = [ "bold" ] }
"ui.text.inactive"  = { fg = "overlay1" }

"ui.virtual"              = "overlay0"
"ui.virtual.indent-guide" = "surface0"
"ui.virtual.inlay-hint"   = { bg = "mantle", fg = "surface1" }
"ui.virtual.jump-label"   = { fg = "rosewater", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "surface0" }

"ui.selection" = { bg = "surface1" }

"ui.cursor"         = { bg = "secondary_cursor", fg = "base" }
"ui.cursor.match"   = { fg = "peach", modifiers = [ "bold" ] }
"ui.cursor.primary" = { bg = "rosewater", fg = "base" }

"ui.cursor.primary.insert" = { bg = "green", fg = "base" }
"ui.cursor.primary.normal" = { bg = "rosewater", fg = "base" }
"ui.cursor.primary.select" = { bg = "lavender", fg = "base" }

"ui.cursor.insert" = { bg = "secondary_cursor_insert", fg = "base" }
"ui.cursor.normal" = { bg = "secondary_cursor_normal", fg = "base" }
"ui.cursor.select" = { bg = "secondary_cursor_select", fg = "base" }

"ui.cursorline.primary" = { bg = "cursorline" }

"ui.highlight" = { bg = "surface1", modifiers = [ "bold" ] }

"ui.menu"          = { bg = "surface0", fg = "overlay2" }
"ui.menu.selected" = { bg = "surface1", fg = "text", modifiers = [ "bold" ] }

"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "teal", style = "curl" } }
"diagnostic.info"        = { underline = { color = "sky", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }

error   = "red"
hint    = "teal"
info    = "sky"
warning = "yellow"

rainbow = [ "red", "peach", "yellow", "green", "sapphire", "lavender" ]

[palette]
base      = "#1e1e2e"
blue      = "#89b4fa"
crust     = "#11111b"
flamingo  = "#f2cdcd"
green     = "#a6e3a1"
lavender  = "#b4befe"
mantle    = "#181825"
maroon    = "#eba0ac"
mauve     = "#cba6f7"
overlay0  = "#6c7086"
overlay1  = "#7f849c"
overlay2  = "#9399b2"
peach     = "#fab387"
pink      = "#f5c2e7"
red       = "#f38ba8"
rosewater = "#f5e0dc"
sapphire  = "#74c7ec"
sky       = "#89dceb"
subtext0  = "#a6adc8"
subtext1  = "#bac2de"
surface0  = "#313244"
surface1  = "#45475a"
surface2  = "#585b70"
teal      = "#94e2d5"
text      = "#cdd6f4"
yellow    = "#f9e2af"

cursorline              = "#2a2b3c"
secondary_cursor        = "#b5a6a8"
secondary_cursor_insert = "#7ea87f"
secondary_cursor_normal = "#b5a6a8"
secondary_cursor_select = "#878ec0"
