inherits = "catppuccin_mocha"

[palette]
base      = "#303446"
blue      = "#8caaee"
crust     = "#232634"
flamingo  = "#eebebe"
green     = "#a6d189"
lavender  = "#babbf1"
mantle    = "#292c3c"
maroon    = "#ea999c"
mauve     = "#ca9ee6"
overlay0  = "#737994"
overlay1  = "#838ba7"
overlay2  = "#949cbb"
peach     = "#ef9f76"
pink      = "#f4b8e4"
red       = "#e78284"
rosewater = "#f2d5cf"
sapphire  = "#85c1dc"
sky       = "#99d1db"
subtext0  = "#a5adce"
subtext1  = "#b5bfe2"
surface0  = "#414559"
surface1  = "#51576d"
surface2  = "#626880"
teal      = "#81c8be"
text      = "#c6d0f5"
yellow    = "#e5c890"

cursorline              = "#3b3f52"
secondary_cursor        = "#b8a5a6"
secondary_cursor_insert = "#83a275"
secondary_cursor_normal = "#9192be"
