attribute_color             = "attribute_color"
comment                     = { fg = "comment_color", modifiers = [ "italic" ] }
constant                    = { fg = "white" }
"constant.builtin"          = "white"
"constant.character.escape" = "label"
"constant.numeric"          = "constant_numeric_foreground_color"
constructor                 = "light_blue"
function                    = "white"
"function.builtin"          = "white"
"function.macro"            = { fg = "light_blue" }
keyword                     = "keyword_foreground_color"
"keyword.directive"         = "light_blue"
namespace                   = "light_blue"
operator                    = "operator_color"
punctuation                 = "punctuation_color"
"punctuation.delimiter"     = "punctuation_color"
special                     = "label"
string                      = { fg = "string", modifiers = [ "italic" ] }
tag                         = "tag"
type                        = "white"
"type.builtin"              = "white"
variable                    = "variable"
"variable.builtin"          = { fg = "built_in", modifiers = [ "bold", "italic" ] }
"variable.other.member"     = "white"
"variable.parameter"        = { fg = "variable" }
# used for lifetimes
label = "label"

"markup.bold"          = { modifiers = [ "bold" ] }
"markup.heading"       = "light_blue"
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.link.text"     = "markup_link_foreground_color"
"markup.link.url"      = { fg = "link_url_foreground_color", modifiers = [ "underlined" ] }
"markup.raw"           = "markup_raw_foreground_color"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "info"
"diff.minus" = "#f22c86"
"diff.plus"  = "#35bf86"

"ui.background"           = { bg = "black" }
"ui.background.separator" = { fg = "window_color" }
"ui.linenr"               = { fg = "window_color" }
"ui.linenr.selected"      = { fg = "light_blue" }
"ui.statusline"           = { bg = "black", fg = "statusline_foreground_color" }
"ui.statusline.inactive"  = { bg = "black", fg = "statusline_inactive_foreground_color" }
"ui.virtual.ruler"        = { bg = "dark" }

"ui.help"   = { bg = "menu_background_color", fg = "menu_normal_text_color" }
"ui.popup"  = { bg = "menu_background_color", fg = "menu_normal_text_color" }
"ui.window" = { fg = "dark" }

"ui.text"          = { fg = "text" }
"ui.text.focus"    = { fg = "white" }
"ui.text.inactive" = "comment_color"
"ui.virtual"       = { fg = "#008DFF" }

"ui.virtual.indent-guide" = { fg = "window_color" }

"ui.cursor.match"          = { bg = "#6C6999", fg = "#212121" }
"ui.cursor.primary.insert" = { bg = "#f43f5e", fg = "white" }
"ui.cursor.select"         = { bg = "cursor_normal_bg_color" }
"ui.cursorline.primary"    = { bg = "dark" }
"ui.debug"                 = { fg = "#634450" }
"ui.debug.breakpoint"      = { fg = "debug_breakpoint" }
"ui.highlight"             = { bg = "dark" }
"ui.highlight.frameline"   = { bg = "#634450" }
"ui.menu"                  = { bg = "menu_background_color", fg = "menu_normal_text_color" }
"ui.menu.scroll"           = { bg = "window_color", fg = "menu_scroll" }
"ui.menu.selected"         = { bg = "white", fg = "menu_background_color" }
"ui.selection"             = { bg = "#4f46e5" }
"ui.selection.primary"     = { bg = "#4f46e5" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "error", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "hint", style = "curl" } }
"diagnostic.info"        = { underline = { color = "info", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "warning", style = "curl" } }

error   = "#f43f5e"
hint    = "#38bdf8"
info    = "info"
warning = "warning"

[palette]
attribute_color                      = "#dbbfef"
black                                = "#000000"
built_in                             = "#10b981"
comment_color                        = "#697C81"
constant_numeric_foreground_color    = "#E8DCA0"
cursor_normal_bg_color               = "#6366f1"
dark                                 = "#111111"
debug_breakpoint                     = "#f47868"
error                                = "#f43f5e"
hint                                 = "#38bdf8"
info                                 = "#6366f1"
keyword_foreground_color             = "#eccdba" # alternative color "#ecc1ba"
label                                = "#efba5d"
light_blue                           = "#bee0ec" #change name 
link_url_foreground_color            = "#b8b8b8"
markup_link_foreground_color         = "#eccdba"
markup_raw_foreground_color          = "#eccdba"
menu_background_color                = "#1e3a8a"
menu_normal_text_color               = "#93c5fd"
menu_scroll                          = "#93c5fd"
operator_color                       = "#bee0ec"
popup_background_color               = "#1e3a8a"
punctuation_color                    = "#a4a0e8"
statusline_active_background_color   = "#111111"
statusline_foreground_color          = "#6366f1"
statusline_inactive_background_color = "#0e0e0e"
statusline_inactive_foreground_color = "#b8b8b8"
string                               = "#6ee7b7"
tag                                  = "#eccdba"
text                                 = "#bfdbfe"
variable                             = "#c7d2fe"
warning                              = "#ffcd1c"
white                                = "#ffffff"
window_color                         = "#484a4d"
