# Cyan Light
# Adapted from JetBrains' Cyan Light Theme https://plugins.jetbrains.com/plugin/12102-cyan-light-theme 
# Author: Abderrahmane Tahri Jouti <tj.abderrahmane@gmail.com>

# Original Author : Olga Berdnikova
# LICENSE : MIT
# Source: https://github.com/OlyaB/CyanTheme

"attribute"         = "blue"
"constructor"       = "shade07"
"type"              = "shade07"
"type.enum.variant" = "purple"

"constant"                  = "darker_blue"
"constant.builtin.boolean"  = "blue"
"constant.character"        = "blue"
"constant.character.escape" = "dark_red"
"constant.numeric"          = "blue"

"string"         = "green"
"string.regexp"  = "blue"
"string.special" = { fg = "dark_red", modifiers = [ "underlined" ] }

"comment" = "comment_gray"

"variable"              = "green_blue"
"variable.builtin"      = { fg = "darker_blue" }
"variable.other.member" = "purple"
"variable.parameter"    = "purple"

"label"       = { fg = "darker_blue", modifiers = [ "underlined" ] }
"punctuation" = "shade06"

"keyword"                   = "darker_blue"
"keyword.control.exception" = "darker_blue"

"operator" = "shade06"

"function"         = "shade07"
"function.builtin" = { fg = "shade07", modifiers = [ "italic" ] }
"function.macro"   = "yellow"
"function.method"  = "dark_yellow"
"function.special" = "dark_red"

"namespace" = "darker_blue"
"special"   = "shade06"
"tag"       = "darker_blue"

"markup.bold"            = { fg = "shade06", modifiers = [ "bold" ] }
"markup.heading"         = { fg = "purple" }
"markup.italic"          = { fg = "shade06", modifiers = [ "italic" ] }
"markup.link.label"      = "dark_blue"
"markup.link.text"       = { fg = "dark_blue", modifiers = [ 'underlined' ] }
"markup.link.url"        = "shade06"
"markup.list"            = "darker_blue"
"markup.list.numbered"   = "darker_blue"
"markup.list.unnumbered" = "darker_blue"
"markup.quote"           = "green"
"markup.raw"             = "green"
"markup.raw.block"       = "green"
"markup.raw.inline"      = "green"
"markup.strikethrough"   = { fg = "shade06", modifiers = [ "crossed_out" ] }

"diff.delta"        = "blue"
"diff.delta.gutter" = "gutter_blue"
"diff.minus"        = "red"
"diff.minus.gutter" = "gutter_red"
"diff.plus"         = "green"
"diff.plus.gutter"  = "gutter_green"

# ui specific
"ui.background"            = { bg = "shade00" }
"ui.cursor"                = { bg = "shade02" }
"ui.cursor.match"          = { bg = "shade04", fg = "shade00" }
"ui.cursor.primary"        = { bg = "cursor_blue" }
"ui.cursor.primary.insert" = { bg = "light_green" }
"ui.cursor.primary.select" = { bg = "light_purple" }

"ui.selection"         = { bg = "lighter_blue" }
"ui.selection.primary" = { bg = "lighter_blue" }

"ui.cursorline.primary" = { bg = "faint_blue" }
"ui.highlight"          = { bg = "faint_blue" }

"ui.linenr"          = { fg = "shade03" }
"ui.linenr.selected" = { bg = "faint_blue", fg = "shade04", modifiers = [ "bold" ] }

"ui.statusline"          = { bg = "shade01", fg = "shade06" }
"ui.statusline.inactive" = { bg = "shade00", fg = "shade04" }
"ui.statusline.insert"   = { bg = "green", fg = "shade00" }
"ui.statusline.normal"   = { bg = "blue", fg = "shade00" }
"ui.statusline.select"   = { bg = "purple", fg = "shade00" }

"ui.help"           = { bg = "shade00", fg = "shade06" }
"ui.popup"          = { bg = "shade01_lighter", fg = "shade04" }
"ui.text"           = "shade05"
"ui.text.directory" = "blue"
"ui.text.focus"     = { bg = "light_blue", fg = "shade07" }
"ui.window"         = { bg = "shade00", fg = "shade04" }

"ui.virtual"            = "shade03"
"ui.virtual.inlay-hint" = { fg = "shade03_darker" }
"ui.virtual.jump-label" = { bg = "shade01", fg = "shade07", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "shade01" }

"ui.menu"          = { bg = "shade01_lighter", fg = "shade05" }
"ui.menu.selected" = { bg = "light_blue", fg = "shade07" }

"error"   = "red"
"hint"    = "shade04"
"info"    = "light_blue"
"warning" = "orange"

"diagnostic"             = { modifiers = [  ] }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "shade04", style = "line" } }
"diagnostic.info"        = { underline = { color = "light_blue", style = "line" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange", style = "curl" } }

[palette]
shade00 = "#f2f3f7"
shade01 = "#dadde8"
shade02 = "#c1c6d9"
shade03 = "#a9b0ca"
shade04 = "#525c85"
shade05 = "#434b6c"
shade06 = "#343a54"
shade07 = "#25293c"

shade01_lighter = "#e6e8f0"
shade03_darker  = "#9199bb"
shade04_lighter = "#616d9d"

background = "#f2f3f7"
foreground = "#25293c"

comment_gray = "#808080"

blue         = "#0073E6"
cursor_blue  = "#80bfff"
dark_blue    = "#185b93"
darker_blue  = "#000080"
faint_blue   = "#E8Eef1"
gutter_blue  = "#C3D6E8"
light_blue   = "#99ccff"
lighter_blue = "#d0eaff"

light_purple = "#ED9CFF"
purple       = "#660E7A"

green        = "#00733B"
green_blue   = "#458383"
gutter_green = "#C9DEC1"
light_green  = "#5DCE87"

dark_yellow = "#7A7A43"
yellow      = "#808000"

light_orange = "#f9c881"
orange       = "#F49810"

dark_red   = "#7F0000"
gutter_red = "#EBBCBC"
red        = "#d90016"
