# Original source and more info: https://github.com/jesusmgg/darcula-solid-helix

inherits = "darcula"

"ui.background.separator" = { bg = "grey01" }
"ui.cursorline.secondary" = { bg = "grey03" }
"ui.menu.scroll"          = { bg = "grey00", fg = "grey02" }
"ui.popup"                = { bg = "grey00", fg = "grey05" }
"ui.window"               = { bg = "grey00" }

[palette]
grey00 = "#101010"
grey01 = "#1f1f1f"
grey02 = "#323232"
grey03 = "#555555"
grey04 = "#a8a8a8"
