# Author : Nick Ogden <nick@nickogden.org>

"ui.background" = { bg = "grey01" }
"ui.bufferline" = { bg = "grey00", fg = "grey04" }
"ui.bufferline.active" = { bg = "grey02", fg = "grey07" }
"ui.cursor" = { fg = "grey04", modifiers = [ "reversed" ] }
"ui.cursor.match" = { fg = "white", modifiers = [ "underlined" ] }
"ui.cursor.primary" = { bg = "grey05", fg = "grey02" }
"ui.cursorline.primary" = { bg = "grey02" }
"ui.cursorline.secondary" = { bg = "grey02" }
"ui.gutter" = { bg = "grey01" }
"ui.help" = { bg = "grey01", fg = "grey04" }
"ui.linenr" = { bg = "grey01", fg = "grey03" }
"ui.linenr.selected" = { bg = "grey01", fg = "grey04", modifiers = [ "bold" ] }
"ui.menu" = { bg = "grey00", fg = "grey05" }
"ui.menu.selected" = { bg = "grey04", fg = "grey01" }
"ui.picker.header.column" = { fg = "grey05", modifiers = [ "italic", "bold" ] }
"ui.picker.header.column.active" = { bg = "grey03", fg = "grey05", modifiers = [
  "italic",
  "bold",
] }
"ui.popup" = { bg = "grey00", fg = "grey05" }
"ui.selection" = { bg = "grey02" }
"ui.selection.primary" = { bg = "blue" }
"ui.statusline" = { bg = "grey02", fg = "grey04" }
"ui.statusline.insert" = { bg = "white", fg = "grey01" }
"ui.statusline.select" = { bg = "orange", fg = "grey01" }
"ui.text" = "white"
"ui.text.focus" = "grey05"
"ui.virtual.indent-guide" = "grey02"
"ui.virtual.inlay-hint" = { fg = "grey03", modifiers = [ "italic" ] }
"ui.virtual.jump-label" = { fg = "lightblue", modifiers = [ "italic", "bold" ] }
"ui.virtual.ruler" = { bg = "grey02" }
"ui.virtual.whitespace" = "grey03"
"ui.window" = { bg = "grey01" }

"attribute"                 = "yellow"
"comment"                   = { fg = "grey", modifiers = [ "italic" ] }
"constant"                  = "lightblue"
"constant.character.escape" = "white"
"constant.numeric"          = "lightblue"
"constructor"               = "yellow"
"function"                  = "yellow"
"function.macro"            = "green"
"keyword"                   = "orange"
"label"                     = "purple"
"namespace"                 = { fg = "purple", modifiers = [ "italic" ] }
"operator"                  = "grey05"
"special"                   = "green"
"string"                    = "darkgreen"
"type"                      = "white"
"type.builtin"              = "orange"
"type.enum"                 = "white"
"type.enum.variant"         = "orange"
"type.parameter"            = { fg = "white", modifiers = [ "bold" ] }
"variable"                  = "white"
"variable.other.member"     = "yellow"

# HTML
"tag" = "orange"

"markup.bold"          = { fg = "white", modifiers = [ "bold" ] }
"markup.heading.1"     = "orange"
"markup.heading.2"     = "yellow"
"markup.heading.3"     = "darkred"
"markup.heading.4"     = "grey"
"markup.heading.5"     = "purple"
"markup.heading.6"     = "darkgreen"
"markup.italic"        = { fg = "white", modifiers = [ "italic" ] }
"markup.link.text"     = "white"
"markup.link.url"      = { fg = "lightblue", modifiers = [ "underlined" ] }
"markup.list"          = "white"
"markup.quote"         = "darkgreen"
"markup.raw"           = "purple"
"markup.strikethrough" = { fg = "white", modifiers = [ "crossed_out" ] }

"diff.delta" = "grey"
"diff.minus" = "red"
"diff.plus"  = "green"

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "grey05", style = "curl" } }
"diagnostic.info"        = { underline = { color = "grey05", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange", style = "curl" } }

"debug"   = "grey05"
"error"   = "red"
"hint"    = "grey05"
"info"    = "grey05"
"warning" = "orange"

[palette]
grey00 = "#181818" # Default Background
grey01 = "#282828" # Lighter Background (Used for status bars, line number and folding marks)
grey02 = "#383838" # Selection Background
grey03 = "#585858" # Comments, Invisibles, Line Highlighting
grey04 = "#b8b8b8" # Dark Foreground (Used for status bars)
grey05 = "#d8d8d8" # Default Foreground, Caret, Delimiters, Operators
grey06 = "#e8e8e8" # Light Foreground (Not often used)
grey07 = "#f8f8f8" # Light Background (Not often used)

blue      = "#104158"
darkgreen = "#629755"
darkred   = "#a34a27"
green     = "#32cd32"
grey      = "#808080"
lightblue = "#6897bb"
orange    = "#cc7832"
purple    = "#9876aa"
white     = "#d0d0d0"
yellow    = "#eedd82"
