# Author: David Else <12832280+David-Else@users.noreply.github.com>

# SYNTAX
"attribute"                 = "variable"
"comment"                   = "dark_green"
"constant"                  = "constant"
"constant.builtin"          = "blue2"
"constant.character"        = "orange"
"constant.character.escape" = "gold"
"constant.numeric"          = "pale_green"
"constructor"               = "type"
"diff.delta"                = "blue4"
"diff.minus"                = "orange_red"
"diff.plus"                 = "dark_green2"
"function"                  = "fn_declaration"
"function.builtin"          = "fn_declaration"
"function.macro"            = "blue2"
"keyword"                   = "blue2"
"keyword.control"           = "special"
"keyword.directive"         = "special"
"label"                     = "blue2"
"module"                    = "type"
"namespace"                 = "type"
"operator"                  = "text"
"punctuation"               = "text"
"punctuation.delimiter"     = "text"
"special"                   = "light_blue"
"string"                    = "orange"
"string.regexp"             = "gold"
"tag"                       = "blue2"
"type"                      = "type"
"type.builtin"              = "type"
"type.enum.variant"         = "constant"
"variable"                  = "variable"
"variable.builtin"          = "blue2"
"variable.other.member"     = "variable"
"variable.parameter"        = "variable"

# MARKUP
"markup.bold"          = { modifiers = [ "bold" ] }
"markup.heading"       = { fg = "blue2", modifiers = [ "bold" ] }
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.link.text"     = "orange"
"markup.link.url"      = { underline.style = "line" }
"markup.list"          = "blue3"
"markup.quote"         = "dark_green"
"markup.raw"           = "orange"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

# UI
"ui.background"    = { bg = "dark_gray2", fg = "light_gray" }
"ui.help"          = { bg = "widget", fg = "text" }
"ui.menu"          = { bg = "widget", fg = "text" }
"ui.menu.selected" = { bg = "dark_blue2" }
"ui.popup"         = { bg = "widget", fg = "text" }
"ui.window"        = { bg = "widget" }
# TODO: Alternate bg colour for `ui.cursor.match` and `ui.selection`.
"diagnostic.deprecated"          = { modifiers = [ "crossed_out" ] }
"diagnostic.error".underline     = { color = "red", style = "curl" }
"diagnostic".underline           = { color = "gold", style = "curl" }
"diagnostic.unnecessary"         = { modifiers = [ "dim" ] }
"error"                          = { fg = "red" }
"hint"                           = { fg = "light_gray3" }
"info"                           = { fg = "light_blue" }
"ui.bufferline"                  = { bg = "widget", fg = "text" }
"ui.bufferline.active"           = { bg = "blue", fg = "white" }
"ui.bufferline.background"       = { bg = "background" }
"ui.cursor"                      = { fg = "cursor", modifiers = [ "reversed" ] }
"ui.cursor.match"                = { bg = "#3a3d41", underline.style = "line" }
"ui.cursor.primary"              = { fg = "cursor", modifiers = [ "reversed" ] }
"ui.cursorline.primary"          = { bg = "dark_gray3" }
"ui.debug.active"                = { fg = "#ffcc00" }
"ui.debug.breakpoint"            = { fg = "#e51400" }
"ui.highlight.frameline"         = { bg = "#4b4b18" }
"ui.linenr"                      = { fg = "dark_gray" }
"ui.linenr.selected"             = { fg = "light_gray2" }
"ui.picker.header.column"        = { underline.style = "line" }
"ui.picker.header.column.active" = { fg = "white", underline.style = "line" }
"ui.selection"                   = { bg = "#3a3d41" }
"ui.selection.primary"           = { bg = "dark_blue" }
"ui.statusline"                  = { bg = "blue", fg = "white" }
"ui.statusline.inactive"         = { bg = "widget", fg = "white" }
"ui.statusline.insert"           = { bg = "yellow", fg = "white" }
"ui.statusline.select"           = { bg = "magenta", fg = "white" }
"ui.text"                        = { fg = "text" }
"ui.text.directory"              = { fg = "blue2" }
"ui.text.focus"                  = { fg = "white" }
"ui.text.inactive"               = { fg = "dark_gray" }
"ui.virtual.indent-guide"        = { fg = "dark_gray4" }
"ui.virtual.inlay-hint"          = { fg = "dark_gray5" }
"ui.virtual.jump-label"          = { fg = "yellow", modifiers = [ "bold" ] }
"ui.virtual.ruler"               = { bg = "borders" }
"ui.virtual.whitespace"          = { fg = "#3e3e3d" }
"ui.virtual.wrap"                = { fg = "#3e3e3d" }
"warning"                        = { fg = "gold2" }

rainbow = [ "#FFD700", "#DA70D6", "#179FFF" ]

[palette]
blue        = "#007acc"
blue2       = "#569CD6"
blue3       = "#6796E6"
blue4       = "#1b81a8"
dark_blue   = "#264f78"
dark_blue2  = "#094771"
dark_gray   = "#858585"
dark_gray2  = "#1e1e1e"
dark_gray3  = "#282828"
dark_gray4  = "#404040"
dark_gray5  = "#8b949e"
dark_green  = "#6A9955"
dark_green2 = "#487e02"
gold        = "#d7ba7d"
gold2       = "#cca700"
light_blue  = "#75beff"
light_gray  = "#d4d4d4"
light_gray2 = "#c6c6c6"
light_gray3 = "#eeeeee"
orange      = "#ce9178"
orange_red  = "#f14c4c"
pale_green  = "#b5cea8"
red         = "#ff1212"
white       = "#ffffff"

constant       = "#4FC1FF"
fn_declaration = "#DCDCAA"
special        = "#C586C0"
type           = "#4EC9B0"
variable       = "#9CDCFE"

background = "#1e1e1e"
borders    = "#323232"
cursor     = "#a6a6a6"
text       = "#d4d4d4"
widget     = "#252526"
