# Dark Synthwave
# Based on Dark SynthWave '84 for VS Code (https://github.com/brainomite/dark-synthwave-vscode/tree/main)
# 
# Author : Peter Retzlaff <pe.retzlaff@gmail.com>
# License: MIT License

# UI Colors
"ui.background"                  = { bg = "black", fg = "blood-red" }
"ui.background.separator"        = "synth-red"
"ui.cursor"                      = { fg = "white", modifiers = [ "reversed" ] }
"ui.cursor.match"                = { bg = "selection-blue" }
"ui.cursor.primary"              = { fg = "white", modifiers = [ "reversed" ] }
"ui.help"                        = { bg = "#1E1E1E", fg = "#f8f8f0" }
"ui.linenr"                      = "grey"
"ui.linenr.selected"             = "white"
"ui.menu"                        = { bg = "black", fg = "white" }
"ui.menu.selected"               = { bg = "synth-red", fg = "dark-grey" }
"ui.picker"                      = { fg = "neon-yellow" }
"ui.picker.header.column.active" = { modifiers = [ "bold" ] }
"ui.popup"                       = { bg = "#1E1E1E", fg = "#f8f8f0" }
"ui.popup.info"                  = { bg = "black", fg = "synth-red" }
"ui.selection"                   = { bg = "selection-blue" }
"ui.selection.primary"           = { bg = "selection-blue" }
"ui.statusline"                  = { bg = "black", fg = "white" }
"ui.statusline.inactive"         = { bg = "black", fg = "grey" }
"ui.statusline.separator"        = "synth-red"
"ui.text"                        = "white"
"ui.text.focus"                  = { bg = "synth-red", fg = "dark-grey" }
"ui.text.inactive"               = "grey"
"ui.virtual.jump-label"          = { fg = "synth-red", modifiers = [ "bold" ] }
"ui.window"                      = "synth-red"

# Diagnostic colors
"diagnostic.error"   = { underline = { color = "error", style = "curl" } }
"diagnostic.hint"    = { underline = { color = "info", style = "curl" } }
"diagnostic.info"    = { underline = { color = "info", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"error"              = "error"
"hint"               = "info"
"info"               = "info"
"warning"            = "warning"

# Syntax highlighting
"comment"                   = { fg = "mauve", modifiers = [ "italic" ] }
"constant"                  = "salmon"
"constant.builtin"          = "synthetic-green"
"constant.builtin.boolean"  = "synthetic-green"
"constant.character.escape" = "beaming-blue"
"constant.numeric"          = "salmon"
"constructor"               = "blood-red"
"function"                  = "beaming-blue"
"keyword"                   = "neon-yellow"
"keyword.control"           = "neon-yellow"
"keyword.control.import"    = "jade"
"keyword.directive"         = "jade"
"keyword.operator"          = "neon-yellow"
"keyword.storage.modifier"  = "neon-yellow"
"keyword.storage.type"      = "neon-yellow"
"string"                    = "orange"
"string.regexp"             = "salmon"
"type"                      = "blood-red"
"variable"                  = "pelati-red"
"variable.builtin"          = { fg = "blood-red", modifiers = [ "bold" ] }
"variable.parameter"        = { fg = "jess-green", modifiers = [ "italic" ] }

# "label" = "neon-yellow"
"namespace" = "blood-red"
"operator"  = "neon-yellow"
# "special" = "beaming-blue"

"attribute"           = { fg = "neon-yellow", modifiers = [ "italic" ] }
"punctuation.bracket" = "neon-yellow"
"tag"                 = "jade"

"markup.bold"       = { fg = "#2ee2fa", modifiers = [ "bold" ] }
"markup.heading"    = { fg = "#ff7edb", modifiers = [ "bold" ] }
"markup.italic"     = { fg = "#2ee2fa", modifiers = [ "italic" ] }
"markup.link.text"  = "neon-yellow"
"markup.link.url"   = { fg = "jade", modifiers = [ "italic" ] }
"markup.quote"      = { fg = "jade", modifiers = [ "italic" ] }
"markup.raw"        = "pelati-red"
"markup.raw.block"  = "pelati-red"
"markup.raw.inline" = "pelati-red"

# Git gutter
"diff.delta.gutter" = "info"
"diff.minus.gutter" = "error"
"diff.plus.gutter"  = "#47ffa0"

# bufferline
"ui.bufferline"        = { bg = "#000000", fg = "grey" }
"ui.bufferline.active" = { bg = "synth-red", fg = "dark-grey" }

[palette]
beaming-blue    = "#36f9f6"
black           = "#000000"
blood-red       = "#fe4450"
dark-grey       = "#141414"
error           = "#ff5252"
grey            = "#808080"
info            = "#40c4ff"
jade            = "#72f1b8"
jess-green      = "#28b881"
mauve           = "#848bbd"
neon-yellow     = "#fede5d"
orange          = "#ff8b39"
pelati-red      = "#f73232"
salmon          = "#f97e72"
selection-blue  = "#001069"
synth-red       = "#ff3366"
synthetic-green = "#1afc65"
warning         = "#ffab40"
white           = "#ffffff"
