# GreasySlug : dark high contrast <9619abgoni@gmail.com>

# Interface
"special"                 = "orange"                       # file picker fuzzy match
"ui.background"           = { bg = "black" }
"ui.background.separator" = { fg = "white" }
"ui.text"                 = "white"
"ui.text.focus"           = { modifiers = [ "reversed" ] } # file picker selected
"ui.window"               = { fg = "aqua" }

"ui.virtual" = "gray"
"ui.virtual.indent-guide" = "white"
"ui.virtual.inlay-hint" = { bg = "orange", fg = "black" }
"ui.virtual.inlay-hint.parameter" = { bg = "orange", fg = "black" }
"ui.virtual.inlay-hint.type" = { bg = "orange", fg = "black" }
"ui.virtual.jump-label" = { fg = "deep_red", modifiers = [
  "bold",
], underline = { color = "deep_red", style = "line" } }
"ui.virtual.ruler" = { bg = "gray", fg = "white" }
"ui.virtual.whitespace" = "gray"
"ui.virtual.wrap" = "gray"

"ui.statusline"           = { bg = "deep_blue", fg = "white" }
"ui.statusline.inactive"  = { bg = "deep_blue", fg = "gray" }
"ui.statusline.insert"    = { bg = "orange", fg = "black" }
"ui.statusline.normal"    = { bg = "aqua", fg = "black" }
"ui.statusline.select"    = { bg = "purple", fg = "black" }
"ui.statusline.separator" = { bg = "white", fg = "aqua" }

"ui.cursor"               = { bg = "white", fg = "black" }
"ui.cursor.insert"        = { bg = "white", fg = "black" }
"ui.cursor.match"         = { modifiers = [ "reversed" ] }
"ui.cursor.primary"       = { bg = "white", fg = "black", modifiers = [ "slow_blink" ] }
"ui.cursor.secondary"     = "white"
"ui.cursor.select"        = { bg = "white", fg = "black" }
"ui.cursorline.primary"   = { bg = "deep_blue", underline = { color = "orange", style = "double_line" } }
"ui.cursorline.secondary" = { bg = "dark_blue", underline = { color = "white", style = "line" } }
"ui.selection"            = { bg = "white", fg = "dark_blue" }
"ui.selection.primary"    = { bg = "white", fg = "deep_blue" }

"ui.help"          = { bg = "deep_blue", fg = "white" }
"ui.menu"          = { bg = "deep_blue", fg = "white" }
"ui.menu.scroll"   = { bg = "black", fg = "aqua" }
"ui.menu.selected" = { fg = "orange", underline = { style = "line" } }

"ui.popup"      = { bg = "deep_blue" }
"ui.popup.info" = { bg = "deep_blue", fg = "white" }

"ui.gutter"          = { bg = "black" }
"ui.gutter.selected" = { bg = "black" }
"ui.linenr"          = { bg = "black", fg = "white" }
"ui.linenr.selected" = { bg = "black", fg = "orange", modifiers = [ "bold" ] }

# Diagnostic
"debug"                  = "red"
"diagnostic"             = { fg = "white" }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "yellow", style = "dashed" } }
"diagnostic.info"        = { underline = { color = "white", style = "dotted" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange", style = "curl" } }
"error"                  = "red"
"hint"                   = "yellow"
"info"                   = "white"
"warning"                = "orange"

"diff.delta" = "blue"
"diff.minus" = "pink"
"diff.plus"  = "green"

# Syntax high light
"attribute"                 = "blue"
"attributes"                = "blue"
"comment"                   = "white"
"constant"                  = "aqua"
"constant.character.escape" = "yellow"
"constant.numeric"          = "emerald_green"
"constructor"               = "aqua"
"function"                  = "yellow"
"keyword"                   = "blue"
"keyword.control"           = "purple"
"label"                     = "blue"
"namespace"                 = "blue"
"operator"                  = "white"
"string"                    = "brown"
"string.special.url"        = "brown"
"tag"                       = "aqua"
"type"                      = "emerald_green"
"type.buildin"              = "emerald_green"
"variable"                  = "aqua"
"variable.other.member"     = "brown"

# Markup 
"markup.bold" = { fg = "emerald_green", modifiers = [ "bold" ] }
"markup.heading" = { fg = "yellow", modifiers = [
  "bold",
], underline = { color = "yellow", style = "double_line" } }
"markup.italic" = { fg = "blue", modifiers = [ "italic" ] }
"markup.link.text" = "pink"
"markup.link.url" = { fg = "blue", underline = { color = "blue", style = "line" } }
"markup.list" = "pink"
"markup.quote" = "yellow"
"markup.raw" = "brown"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

[palette]
aqua          = "#6fc3df"
black         = "#000000"
blue          = "#66a4ff"
brown         = "#ce9178"
dark_blue     = "#0d1a2d"
deep_blue     = "#142743"
deep_red      = "#fd0004"
emerald_green = "#4ec9b0"
gray          = "#585858"
green         = "#427a2d"
orange        = "#f38518"
pink          = "#ff5c8d"
purple        = "#c586c0"
red           = "#b65f5f"
white         = "#ffffff"
yellow        = "#cedc84"
