# Author: spentbliss <zyhkekrz.hatbox475@passinbox.com>
# License: MIT (originally by NTBBloodbath)

"ui.background"        = { bg = "bg", fg = "fg" }
"ui.cursor"            = { bg = "cyan", fg = "bg" }
"ui.linenr"            = "grey"
"ui.linenr.selected"   = "yellow"
"ui.selection"         = { bg = "bg_highlight" }
"ui.selection.primary" = { bg = "bg_highlight" }
"ui.statusline"        = { fg = "blue" }
"ui.text"              = "fg"
"ui.text.focus"        = { bg = "bg_highlight", fg = "cyan" }
"ui.virtual.ruler"     = { bg = "bg_highlight" }

# Markdown Highlighting
"markup.bold"          = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading.1"     = { bg = "#4F4258", fg = "#E99BEA" }
"markup.heading.2"     = { bg = "#2F4456", fg = "#51AFEF" }
"markup.heading.3"     = { bg = "#3F4153", fg = "#A9A1E1" }
"markup.heading.4"     = { bg = "#3C453D", fg = "#98BE65" }
"markup.heading.5"     = { bg = "#4B4641", fg = "#ECBE7B" }
"markup.heading.6"     = { bg = "#483C39", fg = "#DA8549" }
"markup.italic"        = { fg = "orange" }
"markup.link"          = { fg = "cyan" }
"markup.list"          = { fg = "magenta" }
"markup.quote"         = { fg = "fg" }
"markup.raw"           = { bg = "bg", fg = "blue" }
"markup.raw.inline"    = { fg = "orange" }
"markup.strikethrough" = { fg = "red", modifiers = [ "crossed_out" ] }

# Syntax Highlighting for Code
"comment"               = { fg = "grey" }
"comment.block"         = { fg = "grey" }
"comment.documentation" = { fg = "blue" }
"comment.line"          = { fg = "grey" }

"keyword"           = "blue"
"keyword.control"   = "blue"
"keyword.directive" = "green"
"keyword.function"  = "blue"
"keyword.operator"  = "fg"
"keyword.storage"   = "blue"

"type"              = "yellow"
"type.builtin"      = "yellow"
"type.enum.variant" = "purple"

"function"         = "magenta"
"function.builtin" = "fg"
"function.macro"   = "purple"
"function.method"  = "fg"

"variable"           = "fg"
"variable.builtin"   = "red"
"variable.parameter" = "fg"

"string"         = "green"
"string.special" = "green"

"constant"           = "orange"
"constant.boolean"   = "orange"
"constant.builtin"   = "orange"
"constant.character" = "orange"
"constant.numeric"   = "orange"

"attribute"   = "magenta"
"label"       = "red"
"macro"       = "orange"
"namespace"   = "blue"
"operator"    = "blue"
"tag"         = { fg = "magenta", modifiers = [ "bold" ] }
"tag.special" = { fg = "orange", modifiers = [ "bold" ] }

# Interface specific
"ui.cursorcolumn.primary"   = { bg = "bg_highlight" }
"ui.cursorcolumn.secondary" = { bg = "bg_alt" }
"ui.cursorline.primary"     = { bg = "bg_highlight" }
"ui.cursorline.secondary"   = { bg = "bg_alt" }
"ui.statusline.insert"      = { bg = "green", fg = "bg" }
"ui.statusline.normal"      = { bg = "blue", fg = "bg" }
"ui.statusline.select"      = { bg = "purple", fg = "bg" }

# Git changes indicator
"diff.delta"          = "green"
"diff.delta.conflict" = "purple"
"diff.delta.gutter"   = "green"
"diff.delta.moved"    = "orange"
"diff.minus"          = "red"
"diff.minus.gutter"   = "red"
"diff.plus"           = "green"
"diff.plus.gutter"    = "green"

# Diagnostic styles
"diagnostic.error"   = { fg = "red" }
"diagnostic.hint"    = { fg = "blue" }
"diagnostic.info"    = { fg = "cyan" }
"diagnostic.warning" = { fg = "yellow" }
"error"              = { fg = "red", modifiers = [ "bold" ] }
"hint"               = { fg = "blue", modifiers = [ "bold" ] }
"info"               = { fg = "cyan", modifiers = [ "bold" ] }
"warning"            = { fg = "yellow", modifiers = [ "bold" ] }

# Popups for documentation or file picker
"ui.menu"          = { bg = "bg", fg = "fg" }
"ui.menu.selected" = { bg = "bg_highlight", fg = "cyan" }
"ui.popup"         = { bg = "bg", fg = "fg" }
"ui.popup.info"    = { bg = "bg", fg = "fg" }

# Additional overrides
"ui.virtual.indent-guide" = { fg = "grey" }
"ui.virtual.whitespace"   = "grey"

[palette]
bg           = "#282C34"
bg_alt       = "#21242B"
bg_highlight = "#3C4048"
blue         = "#51AFEF"
cyan         = "#46D9FF"
fg           = "#BBC2CF"
green        = "#98BE65"
grey         = "#5B6268"
magenta      = "#C678DD"
orange       = "#DA8548"
purple       = "#A8A1E1"
red          = "#FF6C6B"
yellow       = "#ECBE7B"
