# Author : Luna <rinnray@gliroid.com>
#
# This was made based on
# https://github.com/doomemacs/themes/blob/master/themes/doom-acario-dark-theme.el
# I've done my best to make it look like the Emacs theme, there are still things that looks different from the original.
# But I've decided to keep it like that as I found it to be easier to read when there's a lot going on i.e lots of variables, strings and functions close to each other.

'attribute'                   = { fg = 'blue' }
'comment'                     = { fg = 'gray', modifiers = [ 'italic' ] }
'comment.block'               = { fg = 'green', modifiers = [ 'italic' ] }
'comment.block.documentation' = { fg = 'green', modifiers = [ 'italic' ] }
'comment.line.documentation'  = { fg = 'green', modifiers = [ 'italic' ] }
'constant'                    = { fg = 'magenta' }
'constant.numeric'            = { fg = 'orange' }
'constructor'                 = { fg = 'red' }
'function'                    = { fg = 'yellow' }
'function.builtin'            = { fg = 'blue' }
'function.method'             = { fg = 'white' }
'keyword'                     = { fg = 'red' }
'label'                       = { fg = 'green' }
'namespace'                   = { fg = 'white' }
'operator'                    = { fg = 'blue' }
'punctuation.bracket'         = { fg = 'blue' }
'punctuation.delimiter'       = { fg = 'white', modifiers = [ 'bold' ] }
'string'                      = { fg = 'green' }
'tag'                         = { fg = 'cyan' }
'type'                        = { fg = 'blue' }
'variable'                    = { fg = 'cyan' }
'variable.parameter'          = { fg = 'white' }

'markup.bold'          = { fg = 'orange', modifiers = [ 'bold' ] }
'markup.heading'       = { fg = 'red' }
'markup.italic'        = { fg = 'magenta', modifiers = [ 'italic' ] }
'markup.link'          = { fg = 'orange' }
'markup.link.label'    = { fg = 'green' }
'markup.link.text'     = { fg = 'orange' }
'markup.link.url'      = { fg = 'magenta' }
'markup.list'          = { fg = 'red' }
'markup.quote'         = { fg = 'green', modifiers = [ 'italic' ] }
'markup.raw.block'     = { bg = 'base4', fg = 'green' }
'markup.raw.inline'    = { bg = 'base4', fg = 'green' }
'markup.strikethrough' = { modifiers = [ 'crossed_out' ] }

'diff.delta' = { fg = 'blue' }
'diff.minus' = { fg = 'red' }
'diff.plus'  = { fg = 'green' }

'ui.background'            = { bg = 'bg' }
'ui.bufferline'            = { bg = 'base2', fg = 'gray' }
'ui.bufferline.active'     = { bg = 'base4', fg = 'white' }
'ui.bufferline.background' = { bg = 'bg' }
'ui.cursor'                = { bg = 'orange', fg = 'bg-alt' }
'ui.cursor.match'          = { fg = 'red', modifiers = [ 'bold' ] }
'ui.cursorline'            = { bg = 'bg-alt' }
'ui.help'                  = { bg = 'base2', fg = 'fg' }
'ui.linenr'                = { fg = 'base4' }
'ui.linenr.selected'       = { bg = 'bg-alt', fg = 'orange', modifiers = [ 'bold' ] }
'ui.menu'                  = { bg = 'bg-alt', fg = 'fg' }
'ui.menu.selected'         = { bg = 'base3', fg = 'fg' }
'ui.popup'                 = { bg = 'bg-alt' }
'ui.selection'             = { bg = 'base2' }
'ui.statusline'            = { bg = 'base3', fg = 'fg' }
'ui.statusline.insert'     = { bg = 'base3' }
'ui.statusline.normal'     = { bg = 'base3' }
'ui.statusline.select'     = { bg = 'base3' }
'ui.text'                  = { fg = 'fg' }
'ui.text.focus'            = { bg = 'bg-alt', fg = 'fg' }
'ui.text.info'             = { fg = 'fg' }
'ui.virtual.ruler'         = { bg = 'black' }
'ui.virtual.whitespace'    = { fg = 'base2' }
'ui.window'                = { fg = 'gray' }

'error'   = { fg = 'red', modifiers = [ 'bold' ] }
'hint'    = { fg = 'blue', modifiers = [ 'bold' ] }
'info'    = { fg = 'blue', modifiers = [ 'bold' ] }
'warning' = { fg = 'orange' }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
'diagnostic.error'       = { underline = { color = 'red', style = "curl" } }
'diagnostic.hint'        = { underline = { color = 'red', style = "curl" } }
'diagnostic.info'        = { underline = { color = 'blue', style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
'diagnostic.warning'     = { underline = { color = 'yellow', style = "curl" } }

'special' = { fg = 'orange' }

[palette]
black   = '#000000'
blue    = '#3679D8'
cyan    = '#36D8BD'
gray    = '#767676'
green   = '#79D836'
magenta = '#8041D8'
orange  = '#D85F00'
red     = '#D83441'
white   = '#ffffff'
yellow  = '#D8B941'

# Custom to doom
base2  = '#1E1E33'
base3  = '#464A56'
base4  = '#585C6C'
bg     = '#0D0E16'
bg-alt = '#040408'
fg     = '#C3DBE5'
