# Author : Sebastian Zivota <loewenheim@mailbox.org>
# Author : Chirikumbrah

"annotation" = { fg = "foreground" }

"attribute" = { fg = "green", modifiers = [ "italic" ] }

"comment"                     = { fg = "comment" }
"comment.block"               = { fg = "comment" }
"comment.block.documentation" = { fg = "comment" }
"comment.line"                = { fg = "comment" }
"comment.line.documentation"  = { fg = "comment" }

"constant"                  = { fg = "purple" }
"constant.builtin"          = { fg = "purple" }
"constant.builtin.boolean"  = { fg = "purple" }
"constant.character"        = { fg = "cyan" }
"constant.character.escape" = { fg = "pink" }
"constant.macro"            = { fg = "purple" }
"constant.numeric"          = { fg = "purple" }
"constructor"               = { fg = "purple" }

"definition" = { underline = { color = "cyan" } }

"diagnostic"             = { underline = { color = "orange", style = "curl" } }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "purple", style = "curl" } }
"diagnostic.info"        = { underline = { color = "cyan", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }

"error"   = { fg = "red" }
"hint"    = { fg = "purple" }
"info"    = { fg = "cyan" }
"warning" = { fg = "yellow" }

"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }
"diff.plus"  = { fg = "green" }

# d
"function"         = { fg = "green" }
"function.builtin" = { fg = "green" }
"function.call"    = { fg = "green" }
"function.macro"   = { fg = "purple" }
"function.method"  = { fg = "green" }

"keyword"                     = { fg = "pink" }
"keyword.control.conditional" = { fg = "pink" }
"keyword.control.exception"   = { fg = "purple" }
"keyword.control.import"      = { fg = "pink" }
"keyword.control.repeat"      = { fg = "pink" }
"keyword.directive"           = { fg = "green" }
"keyword.function"            = { fg = "pink" }
"keyword.operator"            = { fg = "pink" }
"keyword.return"              = { fg = "pink" }
"keyword.storage"             = { fg = "pink" }
"keyword.storage.modifier"    = { fg = "pink" }
"keyword.storage.type"        = { fg = "cyan", modifiers = [ "italic" ] }

"label" = { fg = "cyan" }

"markup.bold"          = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "purple", modifiers = [ "bold" ] }
"markup.italic"        = { fg = "yellow", modifiers = [ "italic" ] }
"markup.link.text"     = { fg = "pink" }
"markup.link.url"      = { fg = "cyan" }
"markup.list"          = { fg = "cyan" }
"markup.quote"         = { fg = "yellow", modifiers = [ "italic" ] }
"markup.raw"           = { fg = "foreground" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"punctuation"           = { fg = "foreground" }
"punctuation.bracket"   = { fg = "foreground" }
"punctuation.delimiter" = { fg = "foreground" }
"punctuation.special"   = { fg = "pink" }

"special" = { fg = "pink" }

"string"         = { fg = "yellow" }
"string.regexp"  = { fg = "red" }
"string.special" = { fg = "orange" }
"string.symbol"  = { fg = "yellow" }

"tag"           = { fg = "pink" }
"tag.attribute" = { fg = "purple" }
"tag.delimiter" = { fg = "foreground" }

"type"              = { fg = "cyan", modifiers = [ "italic" ] }
"type.builtin"      = { fg = "cyan" }
"type.enum.variant" = { fg = "foreground", modifiers = [ "italic" ] }

"ui.background"                   = { bg = "background", fg = "foreground" }
"ui.cursor"                       = { bg = "purple", fg = "background", modifiers = [ "dim" ] }
"ui.cursor.insert"                = { bg = "green", fg = "background", modifiers = [ "dim" ] }
"ui.cursor.match"                 = { bg = "grey", fg = "foreground" }
"ui.cursor.normal"                = { bg = "purple", fg = "background", modifiers = [ "dim" ] }
"ui.cursor.primary.insert"        = { bg = "green", fg = "background" }
"ui.cursor.primary.normal"        = { bg = "purple", fg = "background" }
"ui.cursor.primary.select"        = { bg = "cyan", fg = "background" }
"ui.cursor.select"                = { bg = "cyan", fg = "background", modifiers = [ "dim" ] }
"ui.cursorline.primary"           = { bg = "cursorline" }
"ui.debug"                        = { fg = "red" }
"ui.help"                         = { bg = "black", fg = "foreground" }
"ui.highlight.frameline"          = { bg = "red", fg = "background" }
"ui.linenr"                       = { fg = "comment" }
"ui.linenr.selected"              = { fg = "foreground" }
"ui.menu"                         = { bg = "current_line", fg = "foreground" }
"ui.menu.scroll"                  = { bg = "current_line", fg = "foreground" }
"ui.menu.selected"                = { bg = "purple", fg = "current_line", modifiers = [ "dim" ] }
"ui.popup"                        = { bg = "black", fg = "foreground" }
"ui.selection"                    = { bg = "selection" }
"ui.selection.primary"            = { bg = "current_line" }
"ui.statusline"                   = { bg = "darker", fg = "foreground" }
"ui.statusline.inactive"          = { bg = "darker", fg = "comment" }
"ui.statusline.insert"            = { bg = "green", fg = "black", modifiers = [ "bold" ] }
"ui.statusline.normal"            = { bg = "purple", fg = "black", modifiers = [ "bold" ] }
"ui.statusline.select"            = { bg = "cyan", fg = "black", modifiers = [ "bold" ] }
"ui.text"                         = { fg = "foreground" }
"ui.text.directory"               = { fg = "cyan" }
"ui.text.focus"                   = { fg = "cyan" }
"ui.virtual.indent-guide"         = { fg = "indent" }
"ui.virtual.inlay-hint"           = { fg = "cyan" }
"ui.virtual.inlay-hint.parameter" = { fg = "cyan", modifiers = [ "italic", "dim" ] }
"ui.virtual.inlay-hint.type"      = { fg = "cyan", modifiers = [ "italic", "dim" ] }
"ui.virtual.jump-label"           = { fg = "pink", modifiers = [ "bold" ] }
"ui.virtual.ruler"                = { bg = "black" }
"ui.virtual.whitespace"           = { fg = "whitespace" }
"ui.virtual.wrap"                 = { fg = "current_line" }
"ui.window"                       = { fg = "foreground" }

"variable"              = { fg = "foreground" }
"variable.builtin"      = { fg = "purple", modifiers = [ "italic" ] }
"variable.other"        = { fg = "foreground" }
"variable.other.member" = { fg = "foreground" }
"variable.parameter"    = { fg = "orange", modifiers = [ "italic" ] }


[palette]
background   = "#282A36"
black        = "#191A21"
comment      = "#6272A4"
current_line = "#44475a"
cursorline   = "#2d303e"
cyan         = "#8be9fd"
darker       = "#222430"
foreground   = "#f8f8f2"
green        = "#50fa7b"
grey         = "#666771"
indent       = "#56596a"
orange       = "#ffb86c"
pink         = "#ff79c6"
purple       = "#BD93F9"
red          = "#ff5555"
selection    = "#363848"
whitespace   = "#586693"
yellow       = "#f1fa8c"
