# Author : Sam Sartor <me@samsartor.com>
# A port of https://github.com/bceskavich/dracula-at-night
"comment"                   = { fg = "comment" }
"constant"                  = { fg = "purple" }
"constant.character.escape" = { fg = "pink" }
"function"                  = { fg = "green" }
"keyword"                   = { fg = "pink" }
"operator"                  = { fg = "pink" }
"punctuation"               = { fg = "foreground" }
"string"                    = { fg = "yellow" }
"string.regexp"             = { fg = "red" }
"tag"                       = { fg = "pink" }
"type"                      = { fg = "cyan", modifiers = [ "italic" ] }
"type.enum.variant"         = { fg = "foreground", modifiers = [ "italic" ] }
"variable"                  = { fg = "foreground" }
"variable.builtin"          = { fg = "cyan", modifiers = [ "italic" ] }
"variable.parameter"        = { fg = "orange", modifiers = [ "italic" ] }

"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }
"diff.plus"  = { fg = "green" }

"ui.background"          = { bg = "background", fg = "foreground" }
"ui.cursor"              = { bg = "orange", fg = "background", modifiers = [ "dim" ] }
"ui.cursor.match"        = { fg = "green", modifiers = [ "underlined" ] }
"ui.cursor.primary"      = { bg = "cyan", fg = "background", modifiers = [ "dim" ] }
"ui.cursorline"          = { bg = "background_dark" }
"ui.debug"               = { fg = "red" }
"ui.help"                = { bg = "background_dark", fg = "foreground" }
"ui.highlight.frameline" = { bg = "red", fg = "black" }
"ui.linenr"              = { fg = "comment" }
"ui.linenr.selected"     = { fg = "foreground" }
"ui.menu"                = { bg = "background_dark", fg = "foreground" }
"ui.menu.selected"       = { bg = "background_dark", fg = "cyan" }
"ui.popup"               = { bg = "background_dark", fg = "foreground" }
"ui.selection"           = { bg = "purple", fg = "background", modifiers = [ "dim" ] }
"ui.selection.primary"   = { bg = "pink", fg = "background" }
"ui.statusline"          = { bg = "background_dark", fg = "foreground" }
"ui.statusline.inactive" = { bg = "background_dark", fg = "comment" }
"ui.statusline.insert"   = { bg = "green", fg = "background_dark" }
"ui.statusline.normal"   = { bg = "cyan", fg = "background_dark" }
"ui.statusline.select"   = { bg = "purple", fg = "background_dark" }
"ui.text"                = { fg = "foreground" }
"ui.text.directory"      = { fg = "cyan" }
"ui.text.focus"          = { fg = "cyan" }
"ui.virtual.jump-label"  = { fg = "pink", modifiers = [ "bold" ] }
"ui.virtual.ruler"       = { bg = "background_dark" }
"ui.window"              = { fg = "foreground" }

"error"   = { fg = "red" }
"warning" = { fg = "cyan" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }

"markup.bold"          = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "purple", modifiers = [ "bold" ] }
"markup.italic"        = { fg = "yellow", modifiers = [ "italic" ] }
"markup.link.text"     = "pink"
"markup.link.url"      = "cyan"
"markup.list"          = "cyan"
"markup.quote"         = { fg = "yellow", modifiers = [ "italic" ] }
"markup.raw"           = { fg = "foreground" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

[palette]
background      = "#0e1419"
background_dark = "#21222c"
comment         = "#6272a4"
cyan            = "#8be9fd"
foreground      = "#f8f8f2"
green           = "#50fa7b"
orange          = "#ffb86c"
pink            = "#ff79c6"
purple          = "#bd93f9"
red             = "#ff5555"
yellow          = "#f1fa8c"
