# Author : Steven Vancoillie <steven.vancoillie@gmail.com>
#
# Migraine-friendly, minimal color scheme focused only on structural elements
# like types, functions, and keywords.

"comment"                 = { modifiers = [ "dim" ] }
"diagnostic.error"        = { underline = { color = "blush", style = "curl" } }
"diagnostic.hint"         = { underline = { color = "sky", style = "curl" } }
"diagnostic.info"         = { underline = { color = "grey", style = "curl" } }
"diagnostic.warning"      = { underline = { color = "maple", style = "curl" } }
"diff.delta"              = "silver"
"diff.minus"              = "blush"
"diff.plus"               = "jade"
"error"                   = "blush"
"function"                = { modifiers = [ "bold" ] }
"hint"                    = "sky"
"info"                    = "grey"
"keyword"                 = "earl"
"type"                    = "maple"
"ui.background"           = { bg = "chaotica" }
"ui.background.separator" = { fg = "snow" }
"ui.cursor"               = { bg = "earl", fg = "black" }
"ui.cursorline.primary"   = { bg = "deepspace" }
"ui.help"                 = { bg = "deepspace", fg = "snow" }
"ui.highlight"            = { bg = "space" }
"ui.linenr"               = { fg = "grey" }
"ui.linenr.selected"      = { fg = "earl" }
"ui.menu"                 = { bg = "deepspace", fg = "snow" }
"ui.menu.scroll"          = { bg = "deepspace", fg = "grey" }
"ui.menu.selected"        = { bg = "lacquer", fg = "snow" }
"ui.popup"                = { bg = "deepspace" }
"ui.selection"            = { bg = "lacquer" }
"ui.statusline"           = { bg = "deepspace", fg = "earl" }
"ui.statusline.inactive"  = { bg = "deepspace", fg = "snow", modifiers = [ "dim" ] }
"ui.statusline.insert"    = { bg = "earl", fg = "chaotica", modifiers = [ "bold" ] }
"ui.statusline.normal"    = { bg = "sky", fg = "chaotica", modifiers = [ "bold" ] }
"ui.statusline.select"    = { bg = "myrtle", fg = "chaotica", modifiers = [ "bold" ] }
"ui.text"                 = { fg = "silver" }
"ui.text.focus"           = { fg = "snow" }
"ui.virtual"              = { fg = "space" }
"ui.virtual.indent-guide" = { fg = "space" }
"ui.virtual.inlay-hint"   = { fg = "lacquer" }
"ui.virtual.jump-label"   = { fg = "myrtle" }
"ui.virtual.ruler"        = { bg = "space" }
"ui.window"               = { fg = "space" }
"warning"                 = "maple"

[palette]
black     = "#000000"
blush     = "#e78284"
chaotica  = "#101010"
darkgrey  = "#505050"
deepspace = "#1b1b1b"
earl      = "#b59efc"
grey      = "#808080"
jade      = "#90b99f"
lacquer   = "#3e3e3e"
maple     = "#e5c890"
myrtle    = "#e29eca"
silver    = "#a6a6a6"
sky       = "#99bbe0"
snow      = "#f0f0f0"
space     = "#2a2a2d"
white     = "#ffffff"
