# Everforest (Light Medium)
# Authors: CptPotato, WindSoilder, basbebe

# Original Author:
# URL: https://github.com/sainnhe/everforest
# Filename: colors/everforest.vim
# Author: sainnhe
# Email: sainnhe@gmail.com
# License: MIT License

"attribute"                 = { fg = "purple", modifiers = [ "italic" ] }
"comment"                   = { fg = "grey1", modifiers = [ "italic" ] }
"constant"                  = "fg"
"constant.builtin"          = { fg = "purple", modifiers = [ "italic" ] }
"constant.builtin.boolean"  = "purple"
"constant.character.escape" = "green"
"constant.numeric"          = "purple"
"constructor"               = "green"
"function"                  = "green"
"function.macro"            = "green"
"keyword"                   = "red"
"keyword.directive"         = "purple"
"keyword.operator"          = "orange"
"keyword.storage"           = "red"
"label"                     = "orange"
"module"                    = "yellow"
"namespace"                 = { fg = "yellow", modifiers = [ "italic" ] }
"operator"                  = "orange"
"punctuation"               = "grey2"
"punctuation.bracket"       = "fg"
"punctuation.delimiter"     = "grey1"
"punctuation.special"       = "blue"
"special"                   = "blue"
"string"                    = "aqua"
"string.regexp"             = "green"
"string.special"            = "yellow"
"tag"                       = "orange"
"type"                      = "yellow"
"variable"                  = "fg"
"variable.builtin"          = { fg = "purple", modifiers = [ "italic" ] }
"variable.other.member"     = "blue"
"variable.parameter"        = "fg"

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading.1"      = { fg = "red", modifiers = [ "bold" ] }
"markup.heading.2"      = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading.3"      = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading.4"      = { fg = "green", modifiers = [ "bold" ] }
"markup.heading.5"      = { fg = "blue", modifiers = [ "bold" ] }
"markup.heading.6"      = { fg = "purple", modifiers = [ "bold" ] }
"markup.heading.marker" = "grey1"
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.label"     = "orange"
"markup.link.text"      = "purple"
"markup.link.url"       = { fg = "blue", underline = { style = "line" } }
"markup.list"           = "red"
"markup.quote"          = "grey1"
"markup.raw.block"      = "aqua"
"markup.raw.inline"     = "green"
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus"  = "green"

"ui.background"           = { bg = "bg0" }
"ui.background.separator" = "grey0"
"ui.bufferline"           = { bg = "bg3", fg = "grey2" }
"ui.bufferline.active"    = { bg = "statusline1", fg = "bg0", modifiers = [ "bold" ] }
"ui.cursor"               = { bg = "grey2", fg = "bg1" }
"ui.cursor.insert"        = { bg = "grey1", fg = "bg0" }
"ui.cursor.match"         = { bg = "bg4", modifiers = [ "bold" ] }
"ui.cursor.primary"       = { bg = "fg", fg = "bg0" }
"ui.cursor.select"        = { bg = "blue", fg = "bg0" }
"ui.cursorline.primary"   = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg2" }
"ui.help"                 = { bg = "bg2", fg = "fg" }
"ui.linenr"               = "grey0"
"ui.linenr.selected"      = "grey2"
"ui.menu"                 = { bg = "bg3", fg = "fg" }
"ui.menu.selected"        = { bg = "green", fg = "bg0" }
"ui.picker.header"        = { modifiers = [ "bold", "underlined" ] }
"ui.popup"                = { bg = "bg2", fg = "grey2" }
"ui.selection"            = { bg = "bg3" }
"ui.statusline"           = { bg = "bg3", fg = "grey2" }
"ui.statusline.inactive"  = { bg = "bg1", fg = "grey0" }
"ui.statusline.insert"    = { bg = "statusline2", fg = "bg0", modifiers = [ "bold" ] }
"ui.statusline.normal"    = { bg = "statusline1", fg = "bg0", modifiers = [ "bold" ] }
"ui.statusline.select"    = { bg = "blue", fg = "bg0", modifiers = [ "bold" ] }
"ui.text"                 = "fg"
"ui.text.directory"       = { fg = "green" }
"ui.text.focus"           = "fg"
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.inlay-hint"   = { fg = "grey0" }
"ui.virtual.ruler"        = { bg = "bg3" }
"ui.virtual.whitespace"   = { fg = "bg4" }
"ui.virtual.wrap"         = { fg = "grey0" }
"ui.window"               = { bg = "bg_dim", fg = "bg4" }

"error"   = "red"
"hint"    = "green"
"info"    = "blue"
"warning" = "yellow"

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "green", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }

[palette]

bg0       = "#fdf6e3"
bg1       = "#f4f0d9"
bg2       = "#efebd4"
bg3       = "#e6e2cc"
bg4       = "#e0dcc7"
bg5       = "#bdc3af"
bg_blue   = "#e9f0e9"
bg_dim    = "#efebd4"
bg_green  = "#f0f1d2"
bg_red    = "#fbe3da"
bg_visual = "#eaedc8"
bg_yellow = "#faedcd"

aqua   = "#35a77c"
blue   = "#3a94c5"
fg     = "#5c6a72"
green  = "#8da101"
orange = "#f57d26"
purple = "#df69ba"
red    = "#f85552"
yellow = "#dfa000"

grey0       = "#a6b0a0"
grey1       = "#939f91"
grey2       = "#829181"
statusline1 = "#93b259"
statusline2 = "#708089"
statusline3 = "#e66868"
