# Author: Isotoxal <isotoxal@proton.me>

"attribute"                   = { fg = "blue" }
"comment"                     = { fg = "comment", modifiers = [ "italic" ] }
"constant"                    = { fg = "cyan" }
"constant.builtin"            = { fg = "blue" }
"constant.builtin.boolean"    = { fg = "cyan" }
"constant.character"          = { fg = "blue" }
"constant.numeric"            = { fg = "yellow" }
"constant.numeric.float"      = { fg = "black-light" }
"constructor"                 = { fg = "blue" }
"function"                    = { fg = "red" }
"function.builtin"            = { fg = "cyan-light" }
"function.macro"              = { fg = "green" }
"function.method"             = { fg = "blue-light" }
"keyword"                     = { fg = "blue" }
"keyword.control.conditional" = { fg = "red" }
"keyword.control.exception"   = { fg = "black-light" }
"keyword.control.import"      = { fg = "red-light" }
"keyword.control.repeat"      = { fg = "yellow-light" }
"keyword.control.return"      = { fg = "blue" }
"keyword.function"            = { fg = "blue" }
"keyword.operator"            = { fg = "blue-light" }
"label"                       = { fg = "blue" }
"namespace"                   = { fg = "red-light" }
"operator"                    = { fg = "white" }
#"parameter.reference" = { fg = "red-light" }
#"property" = { fg = "red" }
"punctuation.bracket"   = { fg = "white" }
"punctuation.delimiter" = { fg = "white" }
"punctuation.special"   = { fg = "white" }
"string"                = { fg = "green" }
"string.escape"         = { fg = "blue" }
"string.regex"          = { fg = "green" }
"string.special"        = { fg = "blue" }
"string.special.symbol" = { fg = "red" }
"tag"                   = { fg = "blue" }
"type"                  = { fg = "yellow" }
"type.builtin"          = { fg = "yellow" }
"variable"              = { fg = "white" }
"variable.builtin"      = { fg = "blue" }
"variable.other.member" = { fg = "red" }
"variable.parameter"    = { fg = "red" }

"diff.delta" = { fg = "magenta" }
"diff.minus" = { fg = "red" }
"diff.plus"  = { fg = "blue" }

"ui.background"           = { bg = "background", fg = "foreground" }
"ui.cursor"               = { modifiers = [ "reversed" ] }
"ui.cursorline.primary"   = { bg = "cursorline" }
"ui.help"                 = { bg = "contrast", fg = "foreground" }
"ui.linenr"               = { fg = "comment" }
"ui.linenr.selected"      = { fg = "foreground" }
"ui.menu"                 = { bg = "contrast", fg = "foreground" }
"ui.menu.selected"        = { bg = "black" }
"ui.popup"                = { bg = "contrast", fg = "foreground" }
"ui.selection"            = { bg = "black" }
"ui.selection.primary"    = { bg = "black" }
"ui.statusline"           = { bg = "background", fg = "foreground" }
"ui.statusline.inactive"  = { bg = "background", fg = "foreground" }
"ui.statusline.insert"    = { bg = "background", fg = "blue" }
"ui.statusline.normal"    = { bg = "background", fg = "white" }
"ui.statusline.select"    = { bg = "background", fg = "magenta" }
"ui.text"                 = { fg = "foreground" }
"ui.text.focus"           = { fg = "blue" }
"ui.virtual.indent-guide" = { fg = "comment" }
"ui.virtual.inlay-hint"   = { fg = "comment" }
"ui.virtual.ruler"        = { bg = "cursorline" }
"ui.virtual.whitespace"   = { fg = "comment" }
"ui.virtual.wrap"         = { fg = "comment" }
"ui.window"               = { fg = "black" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "green", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }
"error"                  = { fg = "red" }
"hint"                   = { fg = "green" }
"info"                   = { fg = "blue" }
"special"                = { fg = "red-light" }
"warning"                = { fg = "yellow" }

"markup.bold"          = { fg = "magenta", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "blue", modifiers = [ "bold" ] }
"markup.italic"        = { fg = "yellow", modifiers = [ "italic" ] }
"markup.link.text"     = { fg = "black-light" }
"markup.link.url"      = { fg = "green" }
"markup.list"          = { fg = "cyan" }
"markup.quote"         = { fg = "yellow", modifiers = [ "italic" ] }
"markup.raw"           = { fg = "cyan" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

[palette]
background    = "#141b1e"
black         = "#232a2d"
black-light   = "#2d3437"
blue          = "#67b0e8"
blue-light    = "#71baf2"
comment       = "#404749"
contrast      = "#161d1f"
cursorline    = "#2c3333"
cyan          = "#6cbfbf"
cyan-light    = "#67cbe7"
foreground    = "#dadada"
green         = "#8ccf7e"
green-light   = "#96d988"
magenta       = "#c47fd5"
magenta-light = "#ce89df"
red           = "#e57474"
red-light     = "#ef7e7e"
white         = "#b3b9b8"
white-light   = "#bdc3c2"
yellow        = "#e5c76b"
yellow-light  = "#f4d67a"
