# Author : Casper Rogild Storm <casper@asynkron.xyz>

"attribute"        = { fg = "ferra_blush" }
"comment"          = { fg = "ferra_bark", modifiers = [ "italic" ] }
"constant"         = { fg = "ferra_sage" }
"function"         = { fg = "ferra_coral" }
"function.macro"   = { fg = "ferra_mist" }
"keyword"          = { fg = "ferra_mist" }
"label"            = { fg = "ferra_sage" }
"module"           = { fg = "ferra_blush" }
"namespace"        = { fg = "ferra_blush" }
"operator"         = { fg = "ferra_mist" }
"punctuation"      = { fg = "ferra_blush" }
"string"           = { fg = "ferra_sage" }
"tag"              = { fg = "ferra_sage" }
"type"             = { fg = "ferra_rose" }
"variable"         = { fg = "ferra_blush" }
"variable.builtin" = { fg = "ferra_rose" }

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading"        = { fg = "ferra_sage", modifiers = [ "bold" ] }
"markup.heading.marker" = { fg = "ferra_bark" }
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = { fg = "ferra_rose" }
"markup.link.url"       = { fg = "ferra_rose", modifiers = [ "underlined" ] }
"markup.list"           = { fg = "ferra_mist" }
"markup.quote"          = { fg = "ferra_bark" }
"markup.raw"            = { fg = "ferra_coral" }
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"ui.background"           = { bg = "ferra_night" }
"ui.cursor"               = { bg = "ferra_blush", fg = "ferra_night" }
"ui.cursor.insert"        = { bg = "ferra_coral", fg = "ferra_night" }
"ui.cursor.match"         = { bg = "ferra_bark", fg = "ferra_night" }
"ui.cursor.select"        = { bg = "ferra_rose", fg = "ferra_night" }
"ui.cursorline"           = { bg = "ferra_ash", fg = "ferra_blush" }
"ui.help"                 = { bg = "ferra_ash", fg = "ferra_blush" }
"ui.linenr"               = { fg = "ferra_bark" }
"ui.linenr.selected"      = { fg = "ferra_blush" }
"ui.menu"                 = { bg = "ferra_ash", fg = "ferra_blush" }
"ui.menu.selected"        = { bg = "ferra_ash", fg = "ferra_coral" }
"ui.popup"                = { bg = "ferra_ash", fg = "ferra_blush" }
"ui.selection"            = { bg = "ferra_umber" }
"ui.statusline"           = { bg = "ferra_ash", fg = "ferra_blush" }
"ui.statusline.inactive"  = { bg = "ferra_ash", fg = "ferra_bark" }
"ui.statusline.insert"    = { bg = "ferra_coral", fg = "ferra_ash" }
"ui.statusline.normal"    = { bg = "ferra_blush", fg = "ferra_ash" }
"ui.statusline.select"    = { bg = "ferra_rose", fg = "ferra_ash" }
"ui.text"                 = { fg = "ferra_blush" }
"ui.text.focus"           = { fg = "ferra_coral" }
"ui.virtual"              = { fg = "ferra_bark" }
"ui.virtual.indent-guide" = { fg = "ferra_ash" }
"ui.virtual.inlay-hint"   = { fg = "ferra_bark" }
"ui.virtual.ruler"        = { bg = "ferra_ash" }
"ui.virtual.whitespace"   = { fg = "ferra_bark" }
"ui.window"               = { bg = "ferra_night", fg = "ferra_bark" }

"diff.delta" = { fg = "ferra_blush" }
"diff.minus" = { fg = "ferra_ember" }
"diff.plus"  = { fg = "ferra_sage" }

"error"   = { fg = "ferra_ember" }
"hint"    = { fg = "ferra_blush" }
"info"    = { fg = "ferra_blush" }
"warning" = { fg = "ferra_honey" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "ferra_ember", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "ferra_blush", style = "curl" } }
"diagnostic.info"        = { underline = { color = "ferra_blush", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "ferra_honey", style = "curl" } }

[palette]
ferra_ash   = "#383539"
ferra_bark  = "#6F5D63"
ferra_blush = "#fecdb2"
ferra_coral = "#ffa07a"
ferra_ember = "#e06b75"
ferra_honey = "#F5D76E"
ferra_mist  = "#D1D1E0"
ferra_night = "#2b292d"
ferra_rose  = "#F6B6C9"
ferra_sage  = "#B1B695"
ferra_umber = "#4d424b"
