# Author: Alexander Brevig <alexanderbrevig@gmail.com>, krfl <kr.fl@outlook.com>
# Adopted from https://github.com/biletskyy/flatwhite-syntax

"attribute"                   = { bg = "blue_bg", fg = "blue_text" }
"comment"                     = { fg = "base3", modifiers = [ "italic" ] }
"comment.block"               = {}
"comment.block.documentation" = { fg = "base2" }
"comment.line"                = {}
"comment.line.documentation"  = { fg = "base2" }
"constant"                    = { bg = "blue_bg", fg = "blue_text" }
"constructor"                 = { fg = "base1" }
"function"                    = { fg = "base1", modifiers = [ "bold" ] }
"keyword"                     = { bg = "purple_bg", fg = "purple_text" }
"label"                       = { modifiers = [ "bold" ] }
"namespace"                   = { bg = "teal_bg", fg = "teal_text" }
"operator"                    = { fg = "base1" }
"punctuation.bracket"         = { modifiers = [ "bold" ] }
"special"                     = { bg = "blue_bg", fg = "blue_text" }
"string"                      = { bg = "green_bg", fg = "green_text" }
"type"                        = { fg = "base1" }
"variable"                    = { fg = "base1" }
"variable.parameter"          = { bg = "blue_bg", fg = "blue_text" }

"diagnostic" = { modifiers = [ "underlined" ] }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "diff_delete", style = "curl" } }
"diagnostic.info"        = { underline = { color = "orange_text", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange_text", style = "curl" } }

"error"   = { fg = "diff_delete" }
"hint"    = { modifiers = [ "bold" ] }
"info"    = { bg = "orange_bg", fg = "orange_text" }
"warning" = { bg = "orange_bg", fg = "orange_text" }

"markup.bold"          = { modifiers = [ "bold" ] }
"markup.heading"       = { bg = "purple_bg", fg = "purple_text", modifiers = [ "bold" ] }
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.link.label"    = { bg = "blue_bg", fg = "blue_text" }
"markup.link.text"     = { bg = "blue_bg", fg = "blue_text" }
"markup.link.url"      = { bg = "blue_bg", fg = "blue_text", modifiers = [ "underlined" ] }
"markup.list"          = { bg = "purple_bg", fg = "purple_text" }
"markup.quote"         = { bg = "teal_bg", fg = "teal_text" }
"markup.raw"           = { bg = "orange_bg", fg = "orange_text" }
"markup.raw.block"     = { bg = "orange_bg", fg = "orange_text" }
"markup.raw.inline"    = { bg = "orange_bg", fg = "orange_text" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"ui.background"        = { bg = "base7", fg = "base1" }
"ui.cursor"            = { bg = "base7", fg = "base1", modifiers = [ "reversed" ] }
"ui.cursor.match"      = { bg = "base3", fg = "base5", modifiers = [ "reversed" ] }
"ui.cursor.primary"    = { bg = "base7", fg = "base1", modifiers = [ "reversed" ] }
"ui.cursorline"        = { bg = "base6" }
"ui.selection"         = { bg = "base4" }
"ui.selection.primary" = { bg = "base2", fg = "base6" }

"ui.virtual"            = { bg = "base6", fg = "base5" }
"ui.virtual.ruler"      = { bg = "base6" }
"ui.virtual.whitespace" = { fg = "base5" }
# Invalid modifier: "normal". See 'https://github.com/helix-editor/helix/issues/5709'
# "ui.virtual.inlay-hint" = { fg = "base4", modifiers = ["normal"] }
# "ui.virtual.inlay-hint.parameter" = { fg = "base3", modifiers = ["normal"] }
"ui.virtual.inlay-hint"           = "base4"
"ui.virtual.inlay-hint.parameter" = "base3"
"ui.virtual.inlay-hint.type"      = { fg = "base3", modifiers = [ "italic" ] }

"ui.linenr"          = { bg = "base6" }
"ui.linenr.selected" = { bg = "base6", modifiers = [ "reversed" ] }

"ui.statusline"          = { bg = "base1", fg = "base7", modifiers = [ "bold" ] }
"ui.statusline.inactive" = { bg = "base3", fg = "base7" }
"ui.statusline.insert"   = { bg = "purple_bg", fg = "purple_text", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "base1", fg = "base7", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "teal_bg", fg = "teal_text", modifiers = [ "bold" ] }

"ui.text"       = { fg = "base1" }
"ui.text.focus" = { fg = "base1", modifiers = [ "bold" ] }

"ui.help"          = { bg = "base6", fg = "base1" }
"ui.menu"          = { bg = "base6", fg = "base1" }
"ui.menu.scroll"   = { bg = "base6", fg = "base1" }
"ui.menu.selected" = { bg = "base6", fg = "base1", modifiers = [ "reversed" ] }
"ui.popup"         = { bg = "base6", fg = "base1" }
"ui.window"        = { bg = "base6", fg = "base1" }

"diff.delta" = { fg = "diff_change" }
"diff.minus" = { fg = "diff_delete" }
"diff.plus"  = { fg = "diff_add" }

[palette]
accent           = "#6a4cff"
base1            = "#605a52"
base2            = "#93836c"
base3            = "#b9a992"
base4            = "#dcd3c6"
base5            = "#e4ddd2"
base6            = "#f1ece4"
base7            = "#f7f3ee"
blue_bg          = "#dde4f2"
blue_text        = "#4c5361"
blue_text_sec    = "#7382a0"
diff_add         = "#2db448"
diff_change      = "#f2a60d"
diff_change_dark = "#795306"
diff_delete      = "#ff1414"
diff_renamed     = "#52aeff"
green_bg         = "#e2e9c1"
green_text       = "#525643"
green_text_sec   = "#81895d"
orange_bg        = "#f7e0c3"
orange_text      = "#5b5143"
orange_text_sec  = "#957f5f"
purple_bg        = "#f1ddf1"
purple_text      = "#614c61"
purple_text_sec  = "#9c739c"
teal_bg          = "#d2ebe3"
teal_text        = "#465953"
teal_text_sec    = "#5f8c7d"
white            = "#ffffff"
