# Fleet Dark
# A take on the JetBrains Fleet theme. Feel free to contribute

# Original author: @krfl
# Contributors:
# @matoous
# @kirawi

"attribute" = "Lime"

"constructor"    = "Yellow"
"type"           = "Blue"
"type.parameter" = "Blue Light"
"type.return"    = "Blue Light"

"constant" = "Violet"
# "constant.builtin" = {} # .boolean
"constant.builtin.boolean"  = "Cyan"
"constant.character"        = "Yellow"
"constant.character.escape" = "Cyan"
"constant.numeric"          = "Yellow"
"string"                    = "Pink"
"string.regexp"             = "Cyan"
"string.special"            = { fg = "Yellow", modifiers = [ "underlined" ] } #.path / .url / .symbol

"comment" = "Gray 90" # .line
# "comment.block" = {} # .documentation
"variable"         = "Gray 120"       # .builtin
"variable.builtin" = { fg = "Coral" }
# "variable.other" = {} # .member
"function"              = "Yellow"
"function.builtin"      = "Lime"
"function.declaration"  = "#EFEFEF"
"function.macro"        = "Lime"
"function.special"      = "Lime"
"keyword"               = "Cyan"    # .operator / .directive / .function
"label"                 = "Yellow"
"variable.other.member" = "Violet"
#"function.declaration.method" = { fg = "lightest", modifiers = ["bold"] } #depends on #4892
"namespace" = "Blue"
"special"   = "Lime"
"tag"       = "Blue"

# used in theming
# "markup" = {} # .normal / .quote / .raw
# "markup.normal" = {} # .completion / .hover
"markup.bold"            = { modifiers = [ "bold" ] }
"markup.heading"         = { fg = "Cyan", modifiers = [ "bold" ] } # .marker / .1 / .2 / .3 / .4 / .5 / .6
"markup.italic"          = { modifiers = [ "italic" ] }
"markup.list"            = "Pink"                                  # .unnumbered / .numbered
"markup.list.numbered"   = "Cyan"
"markup.list.unnumbered" = "Cyan"
"markup.strikethrough"   = { modifiers = [ "crossed_out" ] }
# "markup.link" = "green"
"markup.link.label" = "Purple 20"
"markup.link.text"  = "Cyan"
"markup.link.url"   = { fg = "Pink", modifiers = [ 'italic', 'underlined' ] }
"markup.quote"      = "Pink"
"markup.raw"        = "Pink"
"markup.raw.block"  = "#EB83E2"
"markup.raw.inline" = "Cyan"                                                  # .completion / .hover

"diff.delta" = "Blue 80"
"diff.minus" = "Red 50"
"diff.plus"  = "Green 50"

# ui specific
"ui.background"          = { bg = "Gray 10" }                   # .separator
"ui.statusline"          = { bg = "Gray 20", fg = "Gray 120" }  # .inactive / .normal / .insert / .select
"ui.statusline.inactive" = { fg = "Gray 90" }
"ui.statusline.insert"   = { bg = "Blue 90", fg = "Gray 20" }
"ui.statusline.normal"   = { bg = "Gray 20", fg = "Gray 120" }
"ui.statusline.select"   = { bg = "Yellow 60", fg = "Gray 20" }

"ui.cursor"            = { modifiers = [ "reversed" ] } # .insert / .select / .match / .primary
"ui.cursor.match"      = { bg = "Blue 30" }             # .insert / .select / .match / .primary
"ui.selection"         = { bg = "Gray 50" }             # .primary
"ui.selection.primary" = { bg = "Blue 40" }

"ui.cursorline"      = { bg = "Gray 15" }
"ui.linenr"          = "Gray 70"
"ui.linenr.selected" = "Gray 110"

"ui.help"          = { bg = "Gray 20", fg = "Gray 120" }
"ui.menu"          = { bg = "Gray 20", fg = "Gray 120" } # .selected
"ui.menu.selected" = { bg = "Blue 40", fg = "White" }    # .selected
"ui.popup"         = { bg = "Gray 20", fg = "Gray 120" } # .info
"ui.window"        = { fg = "Gray 50" }
# Calculated as #ffffff with 30% opacity
"ui.menu.scroll" = { fg = "#dfdfdf" }

"ui.text"       = "Gray 120"                       # .focus / .info
"ui.text.focus" = { bg = "Blue 40", fg = "White" }

"ui.virtual"            = "Gray 90"          # .whitespace
"ui.virtual.inlay-hint" = { fg = "Gray 70" }
"ui.virtual.ruler"      = { bg = "Gray 20" }

"error"   = "#FF5269"
"hint"    = "Gray 80"
"info"    = "#A366C4"
"warning" = "#FACb66"

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "#FF5269", style = "line" } }
"diagnostic.hint"        = { underline = { color = "Gray 80", style = "line" } }
"diagnostic.info"        = { underline = { color = "#A366C4", style = "line" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "#FACB66", style = "line" } }

[palette]
"Black"     = "#000000"
"Blue 10"   = "#0b1b32"
"Blue 100"  = "#4d9bf8"
"Blue 110"  = "#6daaf7"
"Blue 20"   = "#132c4f"
"Blue 30"   = "#163764"
"Blue 40"   = "#194176"
"Blue 50"   = "#195eb5"
"Blue 60"   = "#0c6ddd"
"Blue 70"   = "#0273eb"
"Blue 80"   = "#1a85f6"
"Blue 90"   = "#3691f9"
"Gray 10"   = "#181818"
"Gray 100"  = "#a0a0a0"
"Gray 110"  = "#c2c2c2"
"Gray 120"  = "#d1d1d1"
"Gray 15"   = "#1F1F1F"
"Gray 20"   = "#292929"
"Gray 30"   = "#2d2d2d"
"Gray 40"   = "#333333"
"Gray 50"   = "#383838"
"Gray 60"   = "#484848"
"Gray 70"   = "#5d5d5d"
"Gray 80"   = "#767676"
"Gray 90"   = "#898989"
"Green 10"  = "#081f19"
"Green 20"  = "#134939"
"Green 30"  = "#028764"
"Green 40"  = "#3ea17f"
"Green 50"  = "#4ca988"
"Purple 10" = "#b35def"
"Purple 20" = "#c07bf3"
"Red 10"    = "#390813"
"Red 20"    = "#761b2d"
"Red 30"    = "#a72a3f"
"Red 40"    = "#c03248"
"Red 50"    = "#ce364d"
"Red 60"    = "#d93953"
"Red 70"    = "#ea4b67"
"Red 80"    = "#ec7388"
"White"     = "#ffffff"
"Yellow 10" = "#281806"
"Yellow 20" = "#5a3a14"
"Yellow 30" = "#7c511a"
"Yellow 40" = "#b5791f"
"Yellow 50" = "#e1971b"
"Yellow 60" = "#f8ab17"

"Blue"       = "#87C3FF"
"Blue Light" = "#ADD1DE"
"Coral"      = "#CC7C8A"
"Cyan"       = "#82D2CE"
"Cyan Dark"  = "#779E9E"
"Lime"       = "#A8CC7C"
"Orange"     = "#E09B70"
"Pink"       = "#E394DC"
"Violet"     = "#AF9CFF"
"Yellow"     = "#EBC88D"
