inherits = "flexoki_light"

[palette]
bg   = "#100F0F"
bg-2 = "#1C1B1A"
tx   = "#CECDC3"
tx-2 = "#878580"
tx-3 = "#575653"
ui   = "#282726"
ui-2 = "#343331"
ui-3 = "#403E3C"

bl = "#4385BE"
cy = "#3AA99F"
gr = "#879A39"
ma = "#CE5D97"
or = "#DA702C"
pu = "#8B7EC8"
re = "#D14D41"
ye = "#D0A215"
