# Based on Flexoki: https://stephango.com/flexoki

"attribute"                   = "ye"
"comment"                     = "tx-3"
"constant"                    = "pu"
"constant.builtin"            = "ye"
"constructor"                 = "gr"
"diagnostic.deprecated"       = { modifiers = [ "crossed_out" ] }
"diagnostic.error"            = { underline = { color = "re", style = "curl" } }
"diagnostic.hint"             = { underline = { color = "bl", style = "curl" } }
"diagnostic.info"             = { underline = { color = "bl", style = "curl" } }
"diagnostic.unnecessary"      = { modifiers = [ "dim" ] }
"diagnostic.warning"          = { underline = { color = "ye", style = "curl" } }
"diff.delta"                  = "ye"
"diff.minus"                  = "re"
"diff.plus"                   = "gr"
"error"                       = { fg = "re", modifiers = [ "bold" ] }
"function"                    = "or"
"hint"                        = { fg = "bl", modifiers = [ "bold" ] }
"info"                        = { fg = "ye", modifiers = [ "bold" ] }
"keyword"                     = "gr"
"keyword.control"             = "re"
"keyword.control.conditional" = "gr"
"keyword.control.import"      = "ye"
"keyword.control.return"      = "gr"
"keyword.function"            = "gr"
"keyword.storage.modifier"    = "bl"
"keyword.storage.type"        = "bl"
"markup.bold"                 = { fg = "or", modifiers = [ "bold" ] }
"markup.heading"              = "or"
"markup.italic"               = { fg = "or", modifiers = [ "italic" ] }
"markup.link.label"           = "gr"
"markup.link.text"            = "ye"
"markup.link.url"             = "bl"
"markup.list"                 = "ye"
"markup.quote"                = "ye"
"markup.raw"                  = "bl"
"markup.raw.block"            = "or"
"markup.strikethrough"        = { modifiers = [ "crossed_out" ] }
"namespace"                   = "re"
"operator"                    = "tx-2"
"punctuation"                 = "tx-2"
"string"                      = "cy"
"string.regexp"               = "or"
"string.special"              = "ye"
"tag"                         = "bl"
"type"                        = "ye"
"ui.background"               = { bg = "bg" }
"ui.bufferline"               = { bg = "bg-2", fg = "tx-2" }
"ui.bufferline.active"        = { bg = "bg-2", fg = "ye" }
"ui.cursor"                   = { bg = "tx-3", fg = "tx" }
"ui.cursor.match"             = { modifiers = [ "bold" ] }
"ui.cursor.primary"           = { bg = "tx", fg = "bg" }
"ui.cursorline"               = { bg = "bg-2" }
"ui.debug"                    = { bg = "bg", fg = "or" }
"ui.help"                     = { bg = "bg", fg = "tx" }
"ui.highlight.frameline"      = { bg = "ye" }
"ui.linenr"                   = "tx-3"
"ui.linenr.selected"          = "tx"
"ui.menu"                     = { bg = "bg", fg = "tx" }
"ui.menu.selected"            = { bg = "ui", fg = "tx" }
"ui.popup"                    = { bg = "bg-2", fg = "tx" }
"ui.selection"                = { bg = "ui-2" }
"ui.statusline"               = { bg = "bg-2", fg = "tx" }
"ui.statusline.insert"        = { bg = "or", fg = "bg" }
"ui.statusline.normal"        = { bg = "bl", fg = "bg" }
"ui.statusline.select"        = { bg = "ma", fg = "bg" }
"ui.text"                     = "tx"
"ui.text.focus"               = { bg = "bg-2", fg = "tx" }
"ui.text.info"                = "tx"
"ui.virtual.inlay-hint"       = { bg = "bg", fg = "tx-3" }
"ui.virtual.jump-label"       = { bg = "bg-2", modifiers = [ "bold" ] }
"ui.virtual.ruler"            = { bg = "bg-2" }
"ui.virtual.whitespace"       = "bg-2"
"ui.window"                   = "tx"
"variable"                    = "tx"
"variable.builtin"            = "ma"
"variable.other"              = "bl"
"warning"                     = { fg = "or", modifiers = [ "bold" ] }

[palette]
bg   = "#FFFCF0"
bg-2 = "#F2F0E5"
tx   = "#100F0F"
tx-2 = "#6F6E69"
tx-3 = "#B7B5AC"
ui   = "#E6E4D9"
ui-2 = "#DAD8CE"
ui-3 = "#CECDC3"


bl = "#205EA6"
cy = "#24837B"
gr = "#66800B"
ma = "#A02F6F"
or = "#BC5215"
pu = "#5E409D"
re = "#AF3029"
ye = "#AD8301"
