# Author : Mehedi Hasan <mehedi.r137@gmail.com>
# Based on : https://github.com/rexim/gruber-darker-theme

"attribute"                 = "fg0"
"comment"                   = { fg = "brown0" }
"constant.builtin"          = { fg = "yellow0", modifiers = [ "bold" ] }
"constant.character"        = { fg = "green0" }
"constant.character.escape" = { fg = "yellow0" }
"constant.numeric"          = "wisteria"
"constructor"               = { fg = "quartz" }
"function"                  = "niagara0"
"function.builtin"          = "yellow0"
"keyword"                   = { fg = "yellow0", modifiers = [ "bold" ] }
"keyword.directive"         = "quartz"
"label"                     = "fg0"
"module"                    = "aqua1"
"namespace"                 = "quartz"
"operator"                  = "fg0"
"punctuation"               = "fg0"
"punctuation.delimiter"     = "fg0"
"special"                   = { fg = "yellow0", modifiers = [ "bold" ] }
"string"                    = "green0"
"tag"                       = "niagara0"
"type"                      = "quartz"
"type.builtin"              = "yellow0"
"variable"                  = "fg0"
"variable.builtin"          = { fg = "yellow0", modifiers = [ "bold" ] }
"variable.parameter"        = "fg0"

"diff.delta" = "orange1"
"diff.minus" = "red0"
"diff.plus"  = "green1"

"error"   = { fg = "red0", modifiers = [ "bold" ] }
"hint"    = { fg = "blue0", modifiers = [ "bold" ] }
"info"    = { fg = "aqua1", modifiers = [ "bold" ] }
"warning" = { fg = "orange1", modifiers = [ "bold" ] }

"ui.background"      = { bg = "bg0" }
"ui.cursorline"      = { bg = "bg1" }
"ui.linenr"          = { fg = "bg4" }
"ui.linenr.selected" = { fg = "yellow0" }

"ui.statusline"          = { bg = "bg1", fg = "fg0" }
"ui.statusline.inactive" = { bg = "bg1", fg = "fg3" }
"ui.statusline.insert"   = { bg = "blue0", fg = "bg1", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "yellow0", fg = "bg1", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "wisteria", fg = "bg1", modifiers = [ "bold" ] }

"ui.bufferline"        = { bg = "bg6", fg = "fg3" }
"ui.bufferline.active" = { bg = "bg7", fg = "fg0" }

"ui.cursor.match"      = { bg = "yellow1" }
"ui.cursor.primary"    = { bg = "fg0", fg = "niagara1" }
"ui.help"              = { bg = "bg1", fg = "fg0" }
"ui.menu"              = { bg = "bg6", fg = "fg0" }
"ui.menu.selected"     = { bg = "bg5", fg = "fg0", modifiers = [ "bold" ] }
"ui.popup"             = { bg = "bg6" }
"ui.selection"         = { bg = "bg2" }
"ui.selection.primary" = { bg = "bg5" }
"ui.text"              = { fg = "fg0" }
"ui.text.directory"    = { fg = "niagara0", modifiers = [ "bold" ] }
"ui.text.focus"        = { bg = "bg5", modifiers = [ "bold" ] }
"ui.window"            = { fg = "bg1" }

"ui.virtual.indent-guide" = "bg8"
"ui.virtual.inlay-hint"   = { fg = "bg7" }
"ui.virtual.jump-label"   = { fg = "red3", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "bg1" }
"ui.virtual.whitespace"   = "bg8"
"ui.virtual.wrap"         = { fg = "bg2" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red3", style = "dashed" } }
"diagnostic.hint"        = { underline = { color = "blue0", style = "dashed" } }
"diagnostic.info"        = { underline = { color = "aqua1", style = "dashed" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange1", style = "dashed" } }

"markup.bold"          = { modifiers = [ "bold" ] }
"markup.heading"       = { fg = "aqua1", modifiers = [ "bold" ] }
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.link.text"     = "red3"
"markup.link.url"      = { fg = "green1", modifiers = [ "underlined" ] }
"markup.raw"           = { bg = "bg8", fg = "fg0", modifiers = [ "bold" ] }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

[palette]
aqua1    = "#8ec07c"
bg0      = "#181818"
bg1      = "#282828"
bg2      = "#453d41"
bg4      = "#52494e"
bg5      = "#404040"
bg6      = "#232323"
bg7      = "#3f3f3f"
bg8      = "#2c2c2c"
blue0    = "#5292c8"
brown0   = "#cc8c3c"
fg0      = "#e4e4ef"
fg1      = "#f4f4ff"
fg2      = "#f5f5f5"
fg3      = "#a89984"
green0   = "#73c936"
green1   = "#b8bb26"
niagara0 = "#96a6c8"
niagara1 = "#303540"
orange0  = "#d65d0e"
orange1  = "#fe8019"
quartz   = "#95a99f"
red0     = "#f43841"
red1     = "#ff4f58"
red2     = "#2B0A0B"
red3     = "#fb4934"
wisteria = "#9e95c7"
yellow0  = "#ffdd33"
yellow1  = "#655814"
