# Author : Sven-Hendrik Haase <svenstaro@gmail.com>
# Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# The theme uses the gruvbox dark palette with hard contrast: github.com/morhetz/gruvbox

inherits = "gruvbox"

"ui.cursor.match"   = { bg = "bg2" }
"ui.cursor.primary" = { modifiers = [ "reversed" ] }

"diagnostic.error" = { underline = { color = "red0", style = "curl" } }

[palette]
bg0 = "#1d2021" # main background
