# Gruvbox Material Dark Medium for Helix
# Original Author: @sainnhe (https://github.com/sainnhe/gruvbox-material)
# Ported by: @satoqz
# License: MIT

"attribute"                 = "green"
"comment"                   = { fg = "grey1", modifiers = [ "italic" ] }
"constant"                  = "fg0"
"constant.builtin"          = "purple"
"constant.character.escape" = "green"
"constant.numeric"          = "purple"
"constructor"               = "green"
"function"                  = "green"
"keyword"                   = "red"
"keyword.directive"         = "purple"
"keyword.operator"          = "orange"
"label"                     = "red"
"namespace"                 = "yellow"
"operator"                  = "orange"
"punctuation"               = "grey1"
"punctuation.bracket"       = "fg0"
"punctuation.delimiter"     = "grey1"
"punctuation.special"       = "blue"
"special"                   = "green"
"string"                    = "aqua"
"string.regexp"             = "green"
"string.special.path"       = "yellow"
"string.special.symbol"     = "fg0"
"string.special.url"        = { fg = "fg0", modifiers = [ "underlined" ] }
"tag"                       = "orange"
"type"                      = "yellow"
"type.enum.variant"         = "purple"
"variable"                  = "fg0"
"variable.builtin"          = "purple"
"variable.other.member"     = "blue"
"variable.parameter"        = "fg0"

"markup.heading.1" = "red"
"markup.heading.2" = "orange"
"markup.heading.3" = "yellow"
"markup.heading.4" = "green"
"markup.heading.5" = "blue"
"markup.heading.6" = "purple"

"markup.bold"          = { fg = "fg0", modifiers = [ "bold" ] }
"markup.italic"        = { fg = "fg0", modifiers = [ "italic" ] }
"markup.strikethrough" = { fg = "fg0", modifiers = [ "crossed_out" ] }

"markup.link.label"     = "blue"
"markup.link.text"      = "yellow"
"markup.link.url"       = { fg = "blue", modifiers = [ "underlined" ] }
"markup.list"           = "blue"
"markup.list.checked"   = "green"
"markup.list.unchecked" = "grey1"
"markup.quote"          = "grey1"
"markup.raw"            = "green"

"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus"  = "green"

"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "green", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }

error   = "red"
hint    = "green"
info    = "blue"
warning = "yellow"

"ui.background"            = { bg = "bg0", fg = "fg0" }
"ui.bufferline"            = { bg = "bg4", fg = "fg1" }
"ui.bufferline.active"     = { bg = "grey2", fg = "bg0" }
"ui.bufferline.background" = { bg = "bg1" }
"ui.cursor"                = { bg = "grey1", fg = "bg0" }
"ui.cursor.match"          = { bg = "bg2" }
"ui.cursor.primary"        = { bg = "fg0", fg = "bg0" }
"ui.cursorline.primary"    = { bg = "bg1" }
"ui.help"                  = { bg = "bg0", fg = "grey1" }
"ui.highlight"             = { bg = "bg2" }
"ui.linenr"                = "bg3"
"ui.linenr.selected"       = "grey1"
"ui.menu"                  = { bg = "bg2", fg = "fg1" }
"ui.menu.scroll"           = { bg = "bg1", fg = "grey0" }
"ui.menu.selected"         = { bg = "grey2", fg = "bg2" }
"ui.popup"                 = { bg = "bg2", fg = "fg1" }
"ui.popup.info"            = { "fg" = "grey1", bg = "bg0" }
"ui.selection"             = { bg = "bg2" }
"ui.statusline"            = { bg = "bg1", fg = "fg1" }
"ui.statusline.inactive"   = { bg = "bg1", fg = "grey1" }
"ui.statusline.insert"     = { bg = "green", fg = "bg0" }
"ui.statusline.normal"     = { bg = "grey2", fg = "bg0" }
"ui.statusline.select"     = { bg = "red", fg = "bg0" }
"ui.text"                  = "fg0"
"ui.text.directory"        = { fg = "blue" }
"ui.text.focus"            = { bg = "bg2" }
"ui.text.inactive"         = { fg = "grey1" }
"ui.text.info"             = "grey1"
"ui.virtual"               = "grey0"
"ui.virtual.indent-guide"  = "bg3"
"ui.virtual.inlay-hint"    = "grey0"
"ui.virtual.jump-label"    = "grey2"
"ui.virtual.ruler"         = { bg = "bg1" }
"ui.window"                = { fg = "bg3" }

[palette]
fg0 = "#d4be98"
fg1 = "#ddc7a1"

bg0 = "#282828"
bg1 = "#32302f"
bg2 = "#45403d"
bg3 = "#5a524c"
bg4 = "#504945"

grey0 = "#7c6f64"
grey1 = "#928374"
grey2 = "#a89984"

aqua   = "#89b482"
blue   = "#7daea3"
green  = "#a9b665"
orange = "#e78a4e"
purple = "#d3869b"
red    = "#ea6962"
yellow = "#d8a657"
