# Author: IrishMaestro <github.com/irishmaestro>

# Syntax highlighting
"comment"            = { fg = "teddy_bear_pink", modifiers = [ "slow_blink", "italic" ] }
"constant"           = { fg = "hazmat_yellow" }
"constructor"        = { fg = "barium_green" }
"diff.delta"         = { fg = "orange" }
"diff.minus"         = { fg = "chili_powder_red" }
"diff.plus"          = { fg = "cash_green" }
"function"           = { fg = "cash_green", modifiers = [ "bold" ] }
"keyword"            = { fg = "barium_green" }
"keyword.control"    = { fg = "barium_green" }
"keyword.directive"  = { fg = "teddy_bear_pink" }
"label"              = { fg = "vapor_yellow" }
"markup.heading"     = { fg = "hazmat_yellow" }
"markup.link.label"  = { fg = "barium_green" }
"markup.link.text"   = { fg = "vapor_yellow" }
"markup.link.url"    = { fg = "crystal_blue" }
"markup.list"        = { fg = "vapor_yellow" }
"markup.quote"       = { fg = "vapor_yellow" }
"markup.raw.block"   = { bg = "background", fg = "orange" }
"namespace"          = { fg = "hazmat_yellow" }
"operator"           = { fg = "hazmat_yellow" }
"punctuation"        = { fg = "barium_green" }
"string"             = { fg = "crystal_blue" }
"string.regexp"      = { fg = "orange" }
"string.special"     = { fg = "vapor_yellow" }
"tag"                = { fg = "crystal_blue" }
"type"               = { fg = "crystal_blue" }
"type.builtin"       = { fg = "crystal_blue" }
"variable"           = { fg = "element_green" }
"variable.parameter" = { fg = "hazmat_yellow" }

# Interface
"diagnostic.deprecated"   = { modifiers = [ "crossed_out" ] }
"diagnostic.error"        = { underline = { color = "chili_powder_red", style = "curl" } }
"diagnostic.hint"         = { underline = { color = "chili_powder_red", style = "curl" } }
"diagnostic.info"         = { underline = { color = "crystal_blue", style = "curl" } }
"diagnostic.unnecessary"  = { modifiers = [ "dim" ] }
"diagnostic.warning"      = { underline = { color = "vapor_yellow", style = "curl" } }
"error"                   = { fg = "chili_powder_red", modifiers = [ "bold" ] }
"hint"                    = { fg = "crystal_blue", modifiers = [ "bold" ] }
"info"                    = { fg = "crystal_blue", modifiers = [ "bold" ] }
"ui.background"           = { bg = "background" }
"ui.bufferline"           = { bg = "background", fg = "gray" }
"ui.bufferline.active"    = { bg = "dark_gray", fg = "foreground" }
"ui.cursor"               = { bg = "crystal_blue", fg = "background" }
"ui.cursor.match"         = { fg = "hazmat_yellow" }
"ui.cursorline.primary"   = { bg = "#041B0E" }
"ui.help"                 = { bg = "background", fg = "crystal_blue" }
"ui.linenr"               = { fg = "crystal_blue" }
"ui.linenr.selected"      = { fg = "barium_green" }
"ui.menu"                 = { bg = "background", fg = "crystal_blue" }
"ui.menu.selected"        = { bg = "hazmat_yellow", fg = "background" }
"ui.popup"                = { bg = "background", fg = "crystal_blue" }
"ui.selection"            = { bg = "#1B0334" }
"ui.selection.primary"    = { bg = "desert_maroon" }
"ui.statusline"           = { bg = "black", fg = "crystal_blue" }
"ui.statusline.insert"    = { bg = "black", fg = "barium_green" }
"ui.statusline.normal"    = { bg = "black", fg = "crystal_blue" }
"ui.statusline.select"    = { bg = "black", fg = "hazmat_yellow" }
"ui.text"                 = { fg = "crystal_blue" }
"ui.text.focus"           = { bg = "background", fg = "barium_green" }
"ui.text.info"            = { fg = "crystal_blue" }
"ui.virtual.indent-guide" = { fg = "#08341B" }
"ui.virtual.ruler"        = { bg = "#041B0E" }
"ui.virtual.whitespace"   = { fg = "#08341B" }
"ui.window"               = { fg = "barium_green" }
"warning"                 = { fg = "vapor_yellow" }

"special" = { fg = "cash_green" }

[palette]
background       = "#000000"
barium_green     = "#009669"
black            = "#121212"
cash_green       = "#00ff80"
chili_powder_red = "#c32101"
crystal_blue     = "#32c9fa"
dark_gray        = "#2d3640"
desert_maroon    = "#2B0C02"
element_green    = "#186800"
foreground       = "#cccccc"
gray             = "#5c6773"
hazmat_yellow    = "#f7b90c"
orange           = "#ff8f40"
teddy_bear_pink  = "#bd5173"
vapor_yellow     = "#cecd19"
