# Author : portalsurfer <https://github.com/PORTALSURFER>

"comment"                     = { fg = "comment" }
"comment.block.documentation" = { bg = "comment_doc", modifiers = [ "italic" ] }
"comment.line.documentation"  = { bg = "comment_doc", modifiers = [ "italic" ] }

"constant"                 = { fg = "t11" }
"function"                 = { fg = "t10" }
"function.macro"           = { fg = "t7" }
"function.method"          = { fg = "t7" }
"keyword"                  = { fg = "t6" }
"keyword.control"          = { fg = "t8" }
"keyword.control.import"   = { fg = "t8" }
"keyword.function"         = { fg = "t11" }
"keyword.storage.modifier" = { fg = "t7" }
"label"                    = { fg = "t4" }
"namespace"                = { fg = "t6", modifiers = [ "bold" ] }
"operator"                 = { fg = "t8" }
"punctuation"              = { fg = "t9" }
"string"                   = { fg = "t6", modifiers = [ "italic" ] }
"string.regexp"            = { fg = "t6" }
"tag"                      = { fg = "t4" }
"type"                     = { fg = "t8", modifiers = [ "bold" ] }
"variable"                 = { fg = "t4" }
"variable.other.member"    = { fg = "t3" }
"variable.parameter"       = { fg = "t6" }

"diff.delta"       = { fg = "diff_delta" }
"diff.delta.moved" = { fg = "diff_delta_moved" }
"diff.minus"       = { fg = "diff_minus" }
"diff.plus"        = { fg = "diff_plus" }

"ui.cursor.match"          = { bg = "t1", fg = "highlight", modifiers = [ "bold" ] }
"ui.cursor.primary"        = { bg = "highlight_three", fg = "t1" }
"ui.cursor.primary.insert" = { bg = "highlight", fg = "t2" }
"ui.cursor.primary.select" = { bg = "highlight_two", fg = "t2" }
"ui.cursorline.primary"    = { bg = "ruler" }
"ui.cursorline.secondary"  = { bg = "ruler" }

"ui.gutter"          = { bg = "t2" }
"ui.linenr"          = { bg = "t2", fg = "t3" }
"ui.linenr.selected" = { bg = "t2", fg = "highlight_three" }

"ui.background"           = { bg = "t2", fg = "t4" }
"ui.background.separator" = { fg = "t3" }
"ui.help"                 = { bg = "t1", fg = "t4" }
"ui.menu"                 = { bg = "t1", fg = "t4" }
"ui.menu.selected"        = { bg = "t1", fg = "highlight_three" }
"ui.popup"                = { bg = "t1", fg = "t4" }
"ui.window"               = { fg = "t4" }

"ui.selection" = { bg = "selection", fg = "selection_fg" }

"ui.statusline"          = { bg = "t1", fg = "t4" }
"ui.statusline.inactive" = { bg = "t1", fg = "t4" }
"ui.statusline.insert"   = { bg = "t1", fg = "t3" }
"ui.statusline.normal"   = { bg = "t1", fg = "t3" }
"ui.statusline.select"   = { bg = "t4", fg = "highlight" }

"ui.text"       = { fg = "t4" }
"ui.text.focus" = { fg = "highlight_three", modifiers = [ "bold" ] }

"ui.virtual.indent-guide" = { fg = "t3" }
"ui.virtual.inlay-hint"   = { fg = "hints", modifiers = [ "bold" ] }
"ui.virtual.jump-label"   = { fg = "t11", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "ruler" }
"ui.virtual.whitespace"   = { fg = "t3" }

"ui.bufferline"        = { bg = "t1", fg = "t3" }
"ui.bufferline.active" = { bg = "t2", fg = "t7" }

"diagnostic.error"   = { underline = { color = "error", style = "curl" } }
"diagnostic.hint"    = { underline = { color = "display", style = "curl" } }
"diagnostic.info"    = { underline = { color = "info", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }

"error"   = { fg = "error", modifiers = [ "bold" ] }
"hint"    = { fg = "display", modifiers = [ "bold" ] }
"info"    = { fg = "info", modifiers = [ "bold" ] }
"special" = { fg = "t7", modifiers = [ "bold" ] }
"warning" = { fg = "warning", modifiers = [ "bold" ] }

"markup.bold"          = { fg = "t4" }
"markup.heading"       = { fg = "t7" }
"markup.italic"        = { fg = "t4" }
"markup.link.text"     = { fg = "t11" }
"markup.link.url"      = { fg = "t11", modifiers = [ "underlined" ] }
"markup.list"          = { fg = "t7" }
"markup.quote"         = { fg = "t5" }
"markup.raw"           = { fg = "t4" }
"markup.strikethrough" = { fg = "t4", modifiers = [ "crossed_out" ] }

[palette]
t1  = "#0e0e0d"
t10 = "#c3c3bd"
t11 = "#f78c5e"
t2  = "#1d1e1b"
t3  = "#5b5555"
t4  = "#656869"
t5  = "#727b7c"
t6  = "#6e8789"
t7  = "#d85c60"
t8  = "#9bc1bb"
t9  = "#b5c5c5"

highlight       = "#f23672"
highlight_three = "#d4d987"
highlight_two   = "#f69c3c"

selection    = "#4a9aa6"
selection_fg = "#080a0b"

black       = "#000000"
comment     = "#654642"
comment_doc = "#234048"
hints       = "#31353c"
ruler       = "#222320"

display = "#42baff"
error   = "#ff4000"
info    = "#dad7d5"
warning = "#ffbf00"

diff_delta       = "#0078bd"
diff_delta_moved = "#0048bd"
diff_minus       = "#ff4000"
diff_plus        = "#c9d400"
