# Author : portalsurfer <https://github.com/PORTALSURFER>

inherits = "hex_steel"

[palette]
t1  = "#121211"
t10 = "#6fa197"
t11 = "#6fd7a8"
t2  = "#1e1f1b"
t3  = "#4c513a"
t4  = "#5a6052"
t5  = "#6f6d6f"
t6  = "#98acaa"
t7  = "#b1b354"
t8  = "#7e808a"
t9  = "#3f4a4e"

highlight       = "#ff2e5f"
highlight_three = "#d7ff52"
highlight_two   = "#0affa9"

black = "#000000"

selection    = "#290019"
selection_fg = "#c8e732"

comment     = "#396884"
comment_doc = "#234048"

display = "#57ff89"
error   = "#c73500"
info    = "#dad7d5"
warning = "#dcbb00"

hints = "#313d3c"
ruler = "#21221e"

diff_delta       = "#16a7c7"
diff_delta_moved = "#0048bd"
diff_minus       = "#ff4000"
diff_plus        = "#c9d400"
