# Author : portalsurfer <https://github.com/PORTALSURFER>

inherits = "hex_steel"

[palette]
t1  = "#101719"
t10 = "#b0d4d8"
t11 = "#ffbf52"
t2  = "#1b2a32"
t3  = "#4b5968"
t4  = "#8792ab"
t5  = "#6f91bc"
t6  = "#8bb2b9"
t7  = "#eeac90"
t8  = "#b0bd9f"
t9  = "#b3ccd0"

highlight       = "#ff0a50"
highlight_three = "#f8ed8b"
highlight_two   = "#0affa9"

black = "#000000"

selection    = "#b10656"
selection_fg = "#101719"

comment     = "#417e8c"
comment_doc = "#234048"

display = "#57ff89"
error   = "#ff0900"
info    = "#dad7d5"
warning = "#ffbf00"

hints = "#39515c"
ruler = "#1e3039"

diff_delta       = "#0078bd"
diff_delta_moved = "#0048bd"
diff_minus       = "#ff4000"
diff_plus        = "#c9d400"
