# Syntax
attribute               = "brown"
comment                 = "light-gray"
constant                = "purple"
"constant.builtin"      = "orange"
"constant.numeric"      = "orange"
constructor             = "orange"
function                = "blue"
keyword                 = "purple"
label                   = "orange"
namespace               = "orange"
"punctuation"           = "red"
"punctuation.bracket"   = "purple"
"punctuation.delimiter" = "white"
special                 = "purple"
string                  = "orange"
tag                     = "red"
type                    = "orange"
variable                = "red"

# User Interface
"ui.background" = { bg = "bg", fg = "gray" }
"ui.background.separator" = "light-gray"
"ui.bufferline" = { bg = "dark-bg", fg = "light-gray" }
"ui.bufferline.active" = { bg = "dark-bg", fg = "orange" }
"ui.cursor" = { modifiers = [ "reversed" ] }
"ui.cursor.match" = { bg = "selection" }
"ui.cursor.primary" = { modifiers = [ "reversed" ] }
"ui.gutter" = "gray"
"ui.gutter.selected" = "light-gray"
"ui.help" = { bg = "dark-bg", fg = "orange" }
"ui.menu" = { bg = "dark-bg", fg = "light-gray" }
"ui.menu.selected" = { bg = "selection", fg = "orange" }
"ui.picker.header.column" = { fg = "orange", underline.style = "line" }
"ui.picker.header.column.active" = { fg = "purple", modifiers = [
  "bold",
], underline.style = "line" }
"ui.popup" = { bg = "dark-bg", fg = "orange" }
"ui.selection" = { bg = "selection" }
"ui.statusline" = { bg = "dark-bg", fg = "light-gray" }
"ui.text" = "white"
"ui.text.focus" = "green"
"ui.text.inactive" = "selection"
"ui.text.info" = "orange"
"ui.virtual.indent-guide" = { fg = "gray" }
"ui.virtual.jump-label" = { fg = "pink", modifiers = [ "bold" ] }
"ui.virtual.ruler" = { bg = "dark-bg" }
"ui.virtual.whitespace" = { fg = "light-gray" }
"ui.window" = "selection"

# Diagnostics
"diagnostic"             = { underline = { style = "curl" } }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.hint"        = { underline = { color = "green", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostics.error"      = { underline = { color = "red", style = "curl" } }
"diagnostics.warning"    = { underline = { color = "orange", style = "curl" } }

error   = { fg = "red", modifiers = [ "bold" ] }
hint    = { fg = "green", modifiers = [ "bold" ] }
info    = { fg = "blue", modifiers = [ "bold" ] }
warning = { fg = "orange", modifiers = [ "bold" ] }

# Markup
"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading"        = "pink"
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link"           = "blue"
"markup.list"           = "light-gray"
"markup.list.checked"   = "green"
"markup.list.unchecked" = "light-gray"
"markup.quote"          = "orange"
"markup.raw"            = "orange"
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"diff.delta" = "orange"
"diff.minus" = "red"
"diff.plus"  = "green"

[palette]
bg         = "#1C1E26"
blue       = "#25B2BC"
brown      = "#F09383"
dark-bg    = "#16161C"
gray       = "#2E303E"
green      = "#27D796"
light-gray = "#6C6F93"
orange     = "#FAB795"
pink       = "#EE64AE"
purple     = "#B877DB"
red        = "#E95678"
selection  = "#353747"
white      = "#D5D8DA"
