# Author : Chromo-residuum-opec <development.0extl@simplelogin.com>

inherits           = "iceberg-dark"
"ui.menu.selected" = { bg = "menusel_bg", fg = "background_fg" }

[palette]

orange = "#c67439"
pale   = "#505695"
purple = "#785ab5"

black         = "#dcdfe7"
blue          = "#2e539e"
cyan          = "#3f84a6"
gray          = "#8389a3"
green         = "#668f3d"
light-blue    = "#22478e"
light-cyan    = "#327698"
light-gray    = "#262a3f"
light-green   = "#598030"
light-magenta = "#6845ad"
light-red     = "#cc3768"
light-yellow  = "#b6662d"
magenta       = "#7759b4"
red           = "#cd517a"
white         = "#33374c"
yellow        = "#c57339"

background_bg   = "#e9e9ed"
background_fg   = "#33374d"
comment_fg      = "#8489a4"
cursorlinenr_bg = "#cccfe0"
linenr_bg       = "#dddfe9"
linenr_fg       = "#a0a5c0"
matchparen_bg   = "#bec0ca"
menusel_bg      = "#a9afd1"
sel_bg          = "#cacdd8"
statusline_bg   = "#cad0de"
statusline_fg   = "#757da3"
