# Author : Ingrid Rebecca Abraham <git@ingrids.email>

"attribute"                 = "#839A53"
"comment"                   = "#A6B6CE"
"constant"                  = "#D4A520"
"constant.builtin"          = "#D4A520"
"constant.character.escape" = { fg = "#D74E50", modifiers = [ "bold" ] }
"constant.numeric"          = "#D74E50"
"constructor"               = { fg = "#839A53", modifiers = [ "bold" ] }
"function"                  = { fg = "#89BEB7", modifiers = [ "bold" ] }
"function.builtin"          = "#89BEB7"
"function.macro"            = { fg = "#D4A520", modifiers = [ "bold" ] }
"keyword"                   = { fg = "#D74E50", modifiers = [ "bold" ] }
"keyword.directive"         = "#6F873E"
"label"                     = "#D68482"
"namespace"                 = "#839A53"
"operator"                  = { fg = "#D74E50", modifiers = [ "bold" ] }
"punctuation"               = "#C97270"
"punctuation.delimiter"     = "#C97270"
"special"                   = "#D68482"
"string"                    = "#D74E50"
"type"                      = { fg = "#A6B6CE", modifiers = [ "bold" ] }
"type.builtin"              = "#839A53"
"variable"                  = "#A6B6CE"
"variable.builtin"          = "#D4A520"
"variable.other.member"     = "#89BEB7"
"variable.parameter"        = "#89BEB7"

"module" = "#839A53"

# TODO
"markup.bold"          = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading"       = "blue"
"markup.italic"        = { fg = "magenta", modifiers = [ "italic" ] }
"markup.link.text"     = "red"
"markup.link.url"      = { fg = "yellow", modifiers = [ "underlined" ] }
"markup.list"          = "red"
"markup.quote"         = "cyan"
"markup.raw"           = "green"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "#D4A520"
"diff.minus" = "#D74E50"
"diff.plus"  = "#839A53"

"ui.background"          = { bg = "#FFFCFD" }
"ui.cursorline"          = { bg = "#F3EAE9" }
"ui.help"                = { bg = "#D8B8B3", fg = "#250E07" }
"ui.linenr"              = { fg = "#bbbbbb" }
"ui.linenr.selected"     = { fg = "#ED5466", modifiers = [ "bold" ] }
"ui.popup"               = { bg = "#F3E8E9", fg = "#7B91b3" }
"ui.statusline"          = { bg = "#F3EAE9", fg = "#250E07" }
"ui.statusline.inactive" = { bg = "#F3EAE9", fg = "#7b91b3" }
"ui.window"              = { bg = "#D8B8B3" }

"ui.text"               = { fg = "#7B91B3" }
"ui.text.focus"         = { fg = "#250E07", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "#F3EAE9" }
"ui.virtual.whitespace" = "#A6B6CE"

"ui.cursor.match"   = { bg = "#F3EAE9", fg = "#ED5466", modifiers = [ "bold" ] }
"ui.cursor.primary" = { bg = "#ED5466", fg = "#FFFCFD", modifiers = [ "bold" ] }
"ui.menu"           = { bg = "#F3EAE9", fg = "#7B91B3" }
"ui.menu.selected"  = { bg = "#F3EAE9", fg = "#D74E50" }
"ui.selection"      = { bg = "#F3EAE9" }

"error"   = "#D74E50"
"hint"    = "#A6B6CE"
"info"    = "#839A53"
"warning" = "#D4A520"

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "#D74E50", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "#A6B6CE", style = "curl" } }
"diagnostic.info"        = { underline = { color = "#839A53", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "#D4A520", style = "curl" } }
