# Theme: Iroaseta
# Author: YardQuit

# SYNTAX HIGHLIGHTING
"attribute"                 = { fg = "yellow" }
"comment"                   = { fg = "gray" }
"constant"                  = { fg = "blue" }
"constant.character.escape" = { fg = "yellow" }
"constructor"               = { fg = "orange" }
"diff"                      = { fg = "white" }
"diff.delta"                = { fg = "brown" }
"diff.minus"                = { fg = "red" }
"function"                  = { fg = "purple" }
"function.macro"            = { fg = "green" }
"function.method"           = { fg = "green" }
"function.special"          = { fg = "yellow" }
"keyword"                   = { fg = "red" }
"keyword.directive"         = { fg = "white" }
"keyword.function"          = { fg = "red" }
"keyword.operator"          = { fg = "blue" }
"keyword.storage"           = { fg = "red" }
"keyword.storage.modifier"  = { fg = "green" }
"label"                     = { fg = "blue" }
"namespace"                 = { fg = "white" }
"operator"                  = { fg = "white" }
"punctuation"               = { fg = "white" }
"punctuation.bracket"       = { fg = "orange" }
"punctuation.special"       = { fg = "yellow" }
"string"                    = { fg = "blue" }
"string.regexp"             = { fg = "yellow" }
"tag"                       = { fg = "green" }
"type"                      = { fg = "white" }
"type.builtin"              = { fg = "white" }
"type.enum"                 = { fg = "white" }
"type.enum.variant"         = { fg = "white" }
"type.parameter"            = { fg = "white" }
"variable"                  = { fg = "orange" }
"variable.other"            = { fg = "green" }
"variable.other.member"     = { fg = "green" }
"variable.parameter"        = { fg = "yellow" }

# MARKUP, SYNTAX HIGHLIGHTING AND INTERFACE HYBRID
"markup.bold"          = { fg = "crystal_blue", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "blaze_orange" }
"markup.heading.1"     = { fg = "crystal_blue", modifiers = [ "bold" ] }
"markup.heading.2"     = { fg = "sky_blue", modifiers = [ "bold" ] }
"markup.heading.3"     = { fg = "dreamy_blue", modifiers = [ "bold" ] }
"markup.heading.4"     = { fg = "crystal_blue" }
"markup.heading.5"     = { fg = "sky_blue" }
"markup.heading.6"     = { fg = "dreamy_blue" }
"markup.italic"        = { fg = "crystal_blue", modifiers = [ "italic" ] }
"markup.link"          = { fg = "crystal_blue", underline = { color = "light_purple", style = "line" } }
"markup.link.label"    = { fg = "crystal_blue" }
"markup.link.text"     = { fg = "crystal_blue", modifiers = [ "bold" ] }
"markup.link.url"      = { fg = "slate_purple", underline = { color = "slate_purple", style = "line" } }
"markup.list"          = { fg = "blaze_orange" }
"markup.quote"         = { fg = "misty_white", modifiers = [ "italic" ] }
"markup.raw"           = { fg = "misty_white" }
"markup.raw.block"     = { fg = "white" }
"markup.strikethrough" = { fg = "crystal_blue", modifiers = [ "crossed_out" ] }

# USER INTERFACE 
"ui.background" = { bg = "amber_shadow" } # workspace background
"ui.background.separator" = { fg = "misty_white" } # picker separator below input line (space + j)
"ui.bufferline" = { fg = "slate_gray", modifiers = [ "bold" ] } # bufferline inactive tab
"ui.bufferline.active" = { bg = "rustic_red", fg = "misty_white" } # bufferline active tab
"ui.bufferline.background" = { bg = "pitch_black" } # bufferline background
"ui.cursor" = { modifiers = [ "reversed" ] } # only if "ui.cursor.primary.normal" isn't set
"ui.cursor.insert" = { bg = "rustic_red" } # slave cursor block in insert mode
"ui.cursor.match" = { bg = "blaze_orange", fg = "amber_shadow", modifiers = [
  "bold",
] } # matching bracket etc
"ui.cursor.normal" = { modifiers = [ "reversed" ] } # slave cursor block in normal mode
"ui.cursor.primary" = { modifiers = [
  "reversed",
] } # cursor with primary selection (has no effect due to "ui.cursor.primary.normal" is set)
"ui.cursor.primary.insert" = { bg = "ruby_glow", fg = "amber_shadow" } # cursor block in insert mode    
"ui.cursor.primary.normal" = { modifiers = [ "reversed" ] } # cursor block in normal mode
"ui.cursor.primary.select" = { bg = "deep_purple", fg = "misty_white" } # cursor block in select mode (not the selected color)
"ui.cursor.select" = { bg = "deep_purple" } # slave cursor block in select mode
"ui.cursorcolumn.primary" = { bg = "dark_steel" } # column of the primary cursor
"ui.cursorcolumn.secondary" = { bg = "midnight_black" } # columns of secondary cursors
"ui.cursorline.primary" = { bg = "dark_steel" } # line of the primary cursor
"ui.cursorline.secondary" = { bg = "midnight_black" } # lines of secondary cursors
"ui.gutter" = { bg = "amber_shadow" } # gutter
"ui.gutter.selected" = { bg = "pitch_black" } # gutter for the line the cursor is on
"ui.linenr" = { fg = "slate_gray" } # line numbers
"ui.linenr.selected" = { fg = "blaze_orange", modifiers = [
  "bold",
] } # line number for the line the cursor is on
"ui.selection" = { bg = "deep_purple" } # slave selections in the editing area
"ui.selection.primary" = { bg = "light_purple" } # primary selection in the editing area
"ui.statusline" = { bg = "pitch_black", fg = "misty_white" } # statusline, fucused
"ui.statusline.inactive" = { bg = "dark_steel", fg = "slate_gray" } # statusline, unfocused
"ui.statusline.insert" = { bg = "blaze_orange", fg = "amber_shadow", modifiers = [
  "bold",
] } # statusline insert mode (if editor.color-modes is enabled)
"ui.statusline.normal" = { bg = "leafy_green", fg = "amber_shadow", modifiers = [
  "bold",
] } # statusline normal mode (if editor.color-modes is enabled)
"ui.statusline.select" = { bg = "sky_blue", fg = "amber_shadow", modifiers = [
  "bold",
] } # statusline select mode (if editor.color-modes is enabled)
"ui.statusline.separator" = { fg = "misty_white" } # separator character is statusline
"ui.virtual.indent-guide" = { fg = "brown" } # vertical indent width guides
"ui.virtual.inlay-hint" = { fg = "slate_gray" } # inlay hints of all kinds
"ui.virtual.inlay-hint.parameter" = { fg = "slate_gray" } # inlay hints of kind parameter (lsps are not required to set a kind)
"ui.virtual.inlay-hint.type" = { fg = "slate_gray" } # inlay hints of kind type (lsps are not required to set a kind)
"ui.virtual.jump-label" = { modifiers = [ "reversed" ] } # virtual jump labels (g + w)
"ui.virtual.ruler" = { bg = "rustic_red" } # ruler columns
"ui.virtual.whitespace" = { fg = "brown" } # whitespace characters
"ui.virtual.wrap" = { fg = "slate_gray" } # soft-wrap indicator

# USER INTERFACE - MENUS AND POPUP
"ui.help"          = { bg = "midnight_black", fg = "misty_white" }              # description box for commands
"ui.highlight"     = { underline = { color = "blaze_orange", style = "line" } } # highlighted lines in the picker preview
"ui.menu"          = { bg = "pitch_black", fg = "ethereal_gray" }               # code and command completion menus ":"
"ui.menu.scroll"   = { bg = "midnight_black", fg = "slate_gray" }               # scrollbar
"ui.menu.selected" = { bg = "dark_steel", fg = "misty_white" }                  # selected autocomplete item
"ui.popup"         = { bg = "midnight_black", fg = "misty_white" }              # documentation popups (space + k)
"ui.popup.info"    = { bg = "midnight_black", fg = "misty_white" }              # prompt for multiple key options, menu border (space, g, z, m, etc)
"ui.text"          = { fg = "white" }                                           # default text style, command prompts, popup text, etc
"ui.text.focus"    = { fg = "leafy_green" }                                     # the currently selected line in the picker (space j, space f, space s, etc)
"ui.text.inactive" = { fg = "slate_gray" }                                      # same as ui.text but when the text is inactive e.g. suggestions
"ui.text.info"     = { bg = "midnight_black", fg = "misty_white" }              # the key: command in ui.popup.info boxes (space, g, z, m, etc)
"ui.window"        = { fg = "pitch_black" }                                     # borderlines separating splits

# User Interface - Diagnostics
"diagnostic"         = { modifiers = [ "reversed" ] }                # diagnostics fallback style (editing area)
"diagnostic.error"   = { bg = "rustic_red", fg = "misty_white" }     # diagnostics error (editing area)
"diagnostic.hint"    = { bg = "walnut_brown", fg = "amber_shadow" }  # diagnostics hint (editing area)
"diagnostic.info"    = { bg = "twilight_slate", fg = "misty_white" } # diagnostics info (editing area)
"diagnostic.warning" = { bg = "rustic_amber", fg = "misty_white" }   # diagnostics warning (editing area)
"error"              = { fg = "ruby_glow" }                          # diagnostics error (gutter)
"hint"               = { fg = "walnut_brown" }                       # diagnostics hint (gutter)
"info"               = { fg = "sky_blue" }                           # diagnostics info (gutter)
"warning"            = { fg = "lemon_zest" }                         # diagnostics warning (gutter)

# COLOR NAMES
[palette]
# PALETTE USER INTERFACE
amber_shadow   = "#0d1117"
blaze_orange   = "#ff9000"
crystal_blue   = "#99c7ff"
dark_steel     = "#161b22"
deep_purple    = "#4c1785"
dreamy_blue    = "#6eb0ff"
ethereal_gray  = "#91a3b0"
leafy_green    = "#81be83"
lemon_zest     = "#ffba00"
light_purple   = "#7533bd"
midnight_black = "#010409"
misty_white    = "#f2f0eb"
pitch_black    = "#000000"
ruby_glow      = "#fa7970"
rustic_amber   = "#9d5800"
rustic_red     = "#540b0c"
sky_blue       = "#45b1e8"
slate_gray     = "#838a97"
slate_purple   = "#d2a8ff"
twilight_slate = "#263c57"
walnut_brown   = "#987654"

# PALETTE SYNTAX HIGHLIGHTING
black  = "#0d1117"
blue   = "#45b1e8"
brown  = "#987654"
gray   = "#838a97"
green  = "#81be83"
orange = "#ff9000"
purple = "#d2a8ff"
red    = "#fa7970"
white  = "#dadada"
yellow = "#ffba00"
