#
#    __       _ _       _                           
#    \ \  ___| | |_   _| |__   ___  __ _ _ __  ___  
#     \ \/ _ \ | | | | |  _ \ / _ \/ _  |  _ \/ __| 
#  /\_/ /  __/ | | |_| | |_| |  __/ |_| | | | \__ \ 
#  \___/ \___|_|_|\__  |____/ \___|\____|_| |_|___/ 
#                 \___/                             
#
# Jellybeans
# A take on the Jellybeans theme, please feel free to contribute! 
#
# Original author: @nanotech
# Original repository: nanotech/jellybeans.vim
# Contributors:
# @cemalokten

"attribute"         = "green"
"constant"          = "dark_orange"
"constructor"       = "yellow"
"type"              = "light_blue"
"type.enum.variant" = "purple"

"comment"                   = "light_gray"
"constant.builtin.boolean"  = "yellow"
"constant.character"        = "yellow"
"constant.character.escape" = "red_error"
"constant.numeric"          = "dark_orange"
"string"                    = "dark_green"
"string.regexp"             = "light_purple"
"string.special"            = { fg = "yellow", modifiers = [ "underlined" ] }

"function"                  = "yellow"
"function.builtin"          = "green"
"function.macro"            = "green"
"function.method"           = "yellow"
"function.special"          = "green"
"keyword"                   = "mid_blue"
"keyword.control.exception" = "purple"
"label"                     = "yellow"
"namespace"                 = "light_purple"
"operator"                  = "light_purple"
"punctuation"               = "mid_blue"
"special"                   = "green"
"tag"                       = "light_blue"
"variable"                  = "light_yellow"
"variable.builtin"          = { fg = "dark_green", modifiers = [ "underlined" ] }
"variable.other.member"     = "light_purple"
"variable.parameter"        = "yellow"

"markup.bold"            = { fg = "white", modifiers = [ "bold" ] }
"markup.heading"         = { fg = "mid_blue", modifiers = [ "bold" ] }
"markup.italic"          = { modifiers = [ "italic" ] }
"markup.link.label"      = "purple"
"markup.link.text"       = "mid_blue"
"markup.link.url"        = { fg = "dark_green", modifiers = [ 'italic', 'underlined' ] }
"markup.list"            = "dark_green"
"markup.list.numbered"   = "mid_blue"
"markup.list.unnumbered" = "mid_blue"
"markup.quote"           = "dark_green"
"markup.raw"             = "dark_green"
"markup.raw.block"       = "dark_green"
"markup.raw.inline"      = "mid_blue"
"markup.strikethrough"   = { modifiers = [ "crossed_out" ] }

"diff.delta" = "blue_accent"
"diff.minus" = "red_accent"
"diff.plus"  = "diff_plus"

# ui specific
"diagnostic"             = { modifiers = [  ] }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red_error", style = "line" } }
"diagnostic.hint"        = { underline = { color = "light_purple", style = "line" } }
"diagnostic.info"        = { underline = { color = "blue_accent", style = "line" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow_accent", style = "line" } }
"error"                  = "red_error"
"hint"                   = "blue"
"info"                   = "yellow_accent"
"ui.background"          = { bg = "background" }                                       # .separator
"ui.cursor"              = { bg = "background", modifiers = [ "reversed" ] }
"ui.cursor.insert"       = { bg = "light_yellow", fg = "background" }
"ui.cursor.match"        = { bg = "dark_orange", fg = "background" }
"ui.cursorline"          = { bg = "darker" }
"ui.help"                = { bg = "darkest", fg = "light_yellow" }
"ui.linenr"              = "dark_gray"
"ui.linenr.selected"     = { bg = "darker", fg = "light_yellow" }
"ui.menu"                = { bg = "darkest", fg = "light_purple" }
"ui.menu.selected"       = { bg = "dark_blue", fg = "white" }
"ui.popup"               = { bg = "darkest", fg = "light_yellow" }
"ui.selection"           = { bg = "darker" }
"ui.selection.primary"   = { bg = "selection", fg = "selectionFG" }
"ui.statusline"          = { bg = "darker", fg = "light_yellow" }
"ui.statusline.inactive" = { bg = "darker", fg = "dark" }
"ui.statusline.insert"   = { bg = "purple", fg = "darker" }
"ui.statusline.normal"   = { bg = "darker", fg = "light_yellow" }
"ui.statusline.select"   = { bg = "selection", fg = "selectionFG" }
"ui.text"                = "light_yellow"
"ui.text.focus"          = { bg = "dark_blue", fg = "white" }
"ui.virtual"             = "dark"
"ui.virtual.ruler"       = { bg = "darker" }
"ui.window"              = { bg = "darkest", fg = "dark" }
"warning"                = "orange_accent"

[palette]
background = "#151515"
dark       = "#898989"
dark_gray  = "#535353"
darker     = "#292929"
darkest    = "#1e1e1e"
light_gray = "#6d6d6d"
white      = "#ffffff"

light_purple = "#CDBEF0"
purple       = "#a390f0"

blue        = "#52a7f6"
blue_accent = "#2197F3"
dark_blue   = "#204474"
light_blue  = "#8fbfdc"
mid_blue    = "#8197bf"

dark_green = "#84A775"
green      = "#99ad6a"

red        = "#CC7C8A"
red_accent = "#F44747"
red_error  = "#902020"

dark_orange   = "#cf6a4c"
orange        = "#efb080"
orange_accent = "#EE7F25"

light_yellow  = "#EBEBD8"
yellow        = "#fad07a"
yellow_accent = "#DEA407"

diff_plus   = "#5A9F81"
selection   = "#37232D"
selectionFG = "#F2AAC7"
