comment                       = "blue133"
"comment.block.documentation" = "green130"
"comment.line.documentation"  = "green130"
"constant.builtin"            = "red207"
"constant.numeric"            = "blue184"
function                      = "blue245"
"function.macro"              = "red179"
keyword                       = "red207"
label                         = "red199"
string                        = "green171"
tag                           = "red213"
"type.builtin"                = "red207"
"type.enum"                   = "red199"
"variable.builtin"            = "red207"
"variable.other.member"       = "red199"

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading"        = { fg = "red199", modifiers = [ "italic" ] }
"markup.heading.marker" = "red207"
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link"           = { fg = "blue247", underline = { style = "line" } }
"markup.list"           = "red207"
"markup.raw"            = { bg = "blue64" }
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"diff.delta" = "blue173"
"diff.minus" = "blue145"
"diff.plus"  = "green145"

"ui.background"             = { bg = "blue34", fg = "blue196" }
"ui.cursorcolumn.primary"   = { bg = "blue46" }
"ui.cursorcolumn.secondary" = { bg = "blue46" }
"ui.cursorline.primary"     = { bg = "blue46" }
"ui.cursorline.secondary"   = { bg = "blue46" }
"ui.gutter"                 = "blue56"
"ui.gutter.selected"        = { bg = "blue46", fg = "blue56" }
"ui.linenr"                 = "blue89"
"ui.linenr.selected"        = "blue171"
"ui.menu"                   = { bg = "blue48" }
"ui.menu.scroll"            = { bg = "blue48", fg = "blue81" }
"ui.menu.selected"          = { bg = "blue110" }
"ui.popup"                  = { bg = "blue48" }
"ui.selection"              = { bg = "blue214", fg = "black" }
"ui.selection.primary"      = { bg = "blue131" }
"ui.statusline"             = { bg = "blue48" }
"ui.statusline.inactive"    = "blue89"
"ui.statusline.insert"      = { bg = "blue247", fg = "blue48", modifiers = [ "bold" ] }
"ui.statusline.normal"      = { bg = "green156", fg = "blue48", modifiers = [ "bold" ] }
"ui.statusline.select"      = { bg = "red194", fg = "blue48", modifiers = [ "bold" ] }
"ui.text.focus"             = "blue247"
"ui.virtual"                = "blue122"
"ui.virtual.indent-guide"   = "blue56"
"ui.virtual.inlay-hint"     = { bg = "blue50", fg = "blue145" }
"ui.virtual.ruler"          = { bg = "blue64" }
"ui.virtual.whitespace"     = "blue122"

error   = "red214"
hint    = "green156"
info    = "blue247"
warning = "red194"

"diagnostic"             = { underline = { style = "curl" } }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red214", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "green156", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue247", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "red194", style = "curl" } }

[palette]
red179 = "#b3ae60"
red194 = "#c29e4a"
red199 = "#c77dbb"
red207 = "#cf8e6d"
red213 = "#d5b778"
red214 = "#d64d5b"

green130 = "#5f826b"
green145 = "#549159"
green156 = "#499c54"
green171 = "#6aab73"

blue110 = "#2e436e"
blue122 = "#6f737a"
blue131 = "#214283"
blue133 = "#7a7e85"
blue145 = "#868a91"
blue171 = "#A1A3AB"
blue173 = "#375fad"
blue184 = "#2aacb8"
blue196 = "#bcbec4"
blue214 = "#ced0d6"
blue245 = "#56a8f5"
blue247 = "#57aaf7"
blue34  = "#1e1f22"
blue46  = "#26282e"
blue48  = "#2b2d30"
blue50  = "#2d2e32"
blue56  = "#313438"
blue64  = "#293c40"
blue81  = "#4d4e51"
blue89  = "#4b5059"
