# Kanagawa Dragon
# Author: EricHenry

# Adaptation of https://github.com/rebelot/kanagawa.nvim
# Original author: rebelot
# All credits to the original author, the palette is taken from the README
# because of some theming differences, it's not an exact copy of the original.

inherits = "kanagawa"

## User interface
"ui.background"        = { bg = "dragonBlack3", fg = "dragonWhite" }
"ui.gutter"            = { bg = "dragonBlack4", fg = "dragonBlack6" }
"ui.selection"         = { bg = "waveBlue2" }
"ui.selection.primary" = { bg = "waveBlue1" }

"ui.linenr"          = { bg = "dragonBlack4", fg = "dragonBlack6" }
"ui.linenr.selected" = { fg = "roninYellow", modifiers = [ "bold" ] }

"ui.virtual"                      = "dragonBlack4"
"ui.virtual.inlay-hint"           = "dragonGray2"
"ui.virtual.inlay-hint.parameter" = { fg = "dragonYellow", modifiers = [ "dim" ] }
"ui.virtual.inlay-hint.type"      = { fg = "dragonAqua", modifiers = [ "dim" ] }
"ui.virtual.jump-label"           = { fg = "dragonRed", modifiers = [ "bold" ] }
"ui.virtual.ruler"                = { bg = "dragonBlack5" }

"ui.statusline" = { bg = "dragonBlack0", fg = "oldWhite" }

"ui.bufferline"            = { bg = "dragonBlack0", fg = "oldWhite" }
"ui.bufferline.active"     = { bg = "dragonBlack0", fg = "oldWhite" }
"ui.bufferline.background" = { bg = "sumiInk0" }

"ui.help"       = { bg = "sumiInk0", fg = "fujiWhite" }
"ui.popup"      = { bg = "dragonBlack0", fg = "oldWhite" }
"ui.text"       = "dragonWhite"
"ui.text.focus" = { bg = "waveBlue1", fg = "dragonWhite", modifiers = [ "bold" ] }
"ui.window"     = { fg = "sumiInk0" }

"ui.cursor"         = { bg = "waveAqua2", fg = "waveBlue1" }
"ui.cursor.match"   = { fg = "roninYellow", modifiers = [ "bold" ] }
"ui.cursor.primary" = { bg = "fujiWhite", fg = "waveBlue1" }
"ui.highlight"      = { bg = "waveBlue2", fg = "fujiWhite" }

"ui.cursorcolumn.primary" = { bg = "dragonBlack5" }
"ui.cursorline.primary"   = { bg = "dragonBlack5" }

"diagnostic.deprecated" = { fg = "katanaGray", modifiers = [ "crossed_out" ] }
"diagnostic.hint"       = { underline = { color = "waveAqua1", style = "curl" } }
"diagnostic.info"       = { underline = { color = "dragonBlue", style = "curl" } }

## Syntax highlighting
"attribute"                 = "waveRed"
"comment"                   = "dragonAsh"
"constant"                  = "dragonOrange"
"constant.character.escape" = "dragonBlue2"
"constant.numeric"          = "dragonPink"
"constructor"               = "dragonTeal"
"function"                  = "dragonBlue2"
"function.builtin"          = "dragonBlue2"
"function.macro"            = "dragonRed"
"keyword"                   = "dragonViolet"
"keyword.control.exception" = "dragonRed"
"keyword.control.return"    = "dragonRed"
"keyword.directive"         = "dragonRed"
"label"                     = "dragonRed"
"namespace"                 = "dragonWhite"
"operator"                  = "dragonRed"
"punctuation"               = "dragonWhite"
"special"                   = "dragonYellow"
"string"                    = "dragonGreen2"
"string.regexp"             = "dragonRed"
"string.special.symbol"     = "dragonTeal"
"string.special.url"        = "dragonTeal"
"tag"                       = "dragonYellow"
"type"                      = "dragonAqua"
"type.enum.variant"         = "dragonOrange"
"variable"                  = "dragonWhite"
"variable.builtin"          = "dragonRed"
"variable.other.member"     = "dragonYellow"
"variable.parameter"        = "dragonGray"

## Markup modifiers
"markup.bold"            = { modifiers = [ "bold" ] }
"markup.heading.1"       = { fg = "dragonOrange", modifiers = [ "bold" ] }
"markup.heading.2"       = { fg = "dragonYellow", modifiers = [ "bold" ] }
"markup.heading.3"       = { fg = "dragonBlue2", modifiers = [ "bold" ] }
"markup.heading.4"       = { fg = "dragonWhite", modifiers = [ "bold" ] }
"markup.heading.5"       = { fg = "dragonRed", modifiers = [ "bold" ] }
"markup.heading.6"       = { fg = "dragonPink", modifiers = [ "bold" ] }
"markup.heading.marker"  = "dragonViolet"
"markup.italic"          = { modifiers = [ "italic" ] }
"markup.link.label"      = "dragonBlue2"
"markup.link.text"       = "dragonTeal"
"markup.link.url"        = { fg = "dragonPink", underline.style = "line" }
"markup.list.numbered"   = "dragonPink"
"markup.list.unnumbered" = "dragonRed"
"markup.quote"           = "springViolet1"
"markup.raw"             = "dragonGreen2"
"markup.strikethrough"   = { modifiers = [ "crossed_out" ] }

[palette]
dragonBlack0 = "#0d0c0c"
dragonBlack1 = "#12120f"
dragonBlack2 = "#1D1C19"
dragonBlack3 = "#181616"
dragonBlack4 = "#282727"
dragonBlack5 = "#393836"
dragonBlack6 = "#625e5a"

dragonAqua    = "#8ea4a2"
dragonAsh     = "#737c73"
dragonBlue2   = "#8ba4b0"
dragonGray    = "#a6a69c"
dragonGray2   = "#9e9b93"
dragonGray3   = "#7a8382"
dragonGreen   = "#87a987"
dragonGreen2  = "#8a9a7b"
dragonOrange  = "#b6927b"
dragonOrange2 = "#b98d7b"
dragonPink    = "#a292a3"
dragonRed     = "#c4746e"
dragonTeal    = "#949fb5"
dragonViolet  = "#8992a7"
dragonWhite   = "#c5c9c5"
dragonYellow  = "#c4b28a"
