# Kanagawa
# Author: zetashift

# Adaptation of https://github.com/rebelot/kanagawa.nvim
# Original author: rebelot
# All credits to the original author, the palette is taken from the README
# because of some theming differences, it's not an exact copy of the original.

## User interface
"ui.background"        = { bg = "sumiInk3", fg = "fujiWhite" }
"ui.selection"         = { bg = "waveBlue2" }
"ui.selection.primary" = { bg = "waveBlue2" }

"ui.gutter"          = { bg = "sumiInk4", fg = "sumiInk6" }
"ui.linenr"          = { fg = "sumiInk6" }
"ui.linenr.selected" = { fg = "roninYellow", modifiers = [ "bold" ] }

"ui.virtual"            = "sumiInk6"
"ui.virtual.inlay-hint" = "sumiInk6"
"ui.virtual.jump-label" = { fg = "peachRed", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "sumiInk4" }

"ui.statusline"          = { bg = "sumiInk0", fg = "oldWhite" }
"ui.statusline.inactive" = { bg = "sumiInk0", fg = "fujiGray" }
"ui.statusline.insert"   = { bg = "autumnGreen", fg = "sumiInk0", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "crystalBlue", fg = "sumiInk0", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "oniViolet", fg = "sumiInk0", modifiers = [ "bold" ] }

"ui.bufferline"            = { bg = "sumiInk0", fg = "fujiGray" }
"ui.bufferline.active"     = { bg = "sumiInk0", fg = "oldWhite" }
"ui.bufferline.background" = { bg = "sumiInk0" }

"ui.help"       = { bg = "sumiInk0", fg = "fujiWhite" }
"ui.popup"      = { bg = "sumiInk0", fg = "fujiWhite" }
"ui.text"       = "fujiWhite"
"ui.text.focus" = { bg = "waveBlue2", fg = "fujiWhite", modifiers = [ "bold" ] }
"ui.window"     = { fg = "sumiInk0" }

"ui.cursor"         = { bg = "waveAqua2", fg = "waveBlue1" }
"ui.cursor.match"   = { fg = "waveRed", modifiers = [ "bold" ] }
"ui.cursor.primary" = { bg = "fujiWhite", fg = "waveBlue1" }
"ui.highlight"      = { bg = "waveBlue2", fg = "fujiWhite" }
"ui.menu"           = { bg = "waveBlue1", fg = "fujiWhite" }
"ui.menu.scroll"    = { bg = "waveBlue1", fg = "oldWhite" }
"ui.menu.selected"  = { bg = "waveBlue2", fg = "fujiWhite", modifiers = [ "bold" ] }

"ui.cursorcolumn.primary" = { bg = "sumiInk5" }
"ui.cursorline.primary"   = { bg = "sumiInk5" }

"ui.debug.active"     = "winterRed"
"ui.debug.breakpoint" = "springBlue"

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "samuraiRed", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "waveAqua1", style = "curl" } }
"diagnostic.info"        = { underline = { color = "dragonBlue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "roninYellow", style = "curl" } }

error   = "samuraiRed"
hint    = "waveAqua1"
info    = "dragonBlue"
warning = "roninYellow"

## Diff
"diff.delta" = "autumnYellow"
"diff.minus" = "autumnRed"
"diff.plus"  = "autumnGreen"

## Syntax highlighting
"attribute"                 = "waveRed"
"comment"                   = "fujiGray"
"constant"                  = "surimiOrange"
"constant.character.escape" = { fg = "boatYellow2", modifiers = [ "bold" ] }
"constant.numeric"          = "sakuraPink"
"constructor"               = "springBlue"
"function"                  = "crystalBlue"
"function.builtin"          = "springBlue"
"function.macro"            = "waveRed"
"keyword"                   = { fg = "oniViolet", modifiers = [ "italic" ] }
"keyword.control.exception" = "peachRed"
"keyword.control.return"    = "peachRed"
"keyword.directive"         = "waveRed"
"label"                     = "springBlue"
"namespace"                 = "surimiOrange"
"operator"                  = "boatYellow2"
"punctuation"               = "springViolet2"
"special"                   = "peachRed"
"string"                    = "springGreen"
"string.regexp"             = "boatYellow2"
"string.special.symbol"     = "oniViolet"
"string.special.url"        = "springBlue"
"tag"                       = "waveAqua2"
"type"                      = "waveAqua2"
"type.builtin"              = "springBlue"
"variable"                  = "fujiWhite"
"variable.builtin"          = "waveRed"
"variable.other.member"     = "carpYellow"
"variable.parameter"        = "oniViolet2"

## Markup modifiers
"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading"        = { fg = "springViolet2", modifiers = [ "bold" ] }
"markup.heading.1"      = { fg = "carpYellow", modifiers = [ "bold" ] }
"markup.heading.2"      = { fg = "crystalBlue", modifiers = [ "bold" ] }
"markup.heading.3"      = { fg = "waveAqua2", modifiers = [ "bold" ] }
"markup.heading.marker" = "springViolet2"
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.label"     = "surimiOrange"
"markup.link.text"      = { fg = "springBlue" }
"markup.link.url"       = { fg = "lightBlue" }
"markup.list"           = "sakuraPink"
"markup.quote"          = "oniViolet2"
"markup.raw"            = "springGreen"
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

[palette]
autumnGreen   = "#76946A" # git add
autumnRed     = "#C34043" # git delete
autumnYellow  = "#DCA561" # git change
boatYellow1   = "#938056" # unused
boatYellow2   = "#C0A36E" # operators, regex
carpYellow    = "#E6C384" # identifiers
crystalBlue   = "#7E9CD8" # functions and titles
dragonBlue    = "#658594" # diagnostic hint
fujiGray      = "#727169" # comments
fujiWhite     = "#DCD7BA" # default foreground
katanaGray    = "#717C7C" # unused
lightBlue     = "#A3D4D5" # URLs
oldWhite      = "#C8C093" # dark foreground, e.g. statuslines
oniViolet     = "#957FB8" # statements and keywords
oniViolet2    = "#B8B4D0" # parameters
peachRed      = "#FF5D62" # standout specials 2, e.g. exception handling, returns
roninYellow   = "#FF9E3B" # diagnostic warning
sakuraPink    = "#D27E99" # numbers
samuraiRed    = "#E82424" # diagnostic error
springBlue    = "#7FB4CA" # specials and builtins
springGreen   = "#98BB6C" # strings
springViolet1 = "#938AA9" # unused
springViolet2 = "#9CABCA" # brackets and punctuation
sumiInk0      = "#16161D" # dark background, e.g. statuslines, floating windows
sumiInk1      = "#181820" # unused
sumiInk2      = "#1A1A22" # unused
sumiInk3      = "#1F1F28" # default background
sumiInk4      = "#2A2A37" # lighter background, e.g. colorcolumns, folds
sumiInk5      = "#363646" # lighter background, e.g. cursorline
sumiInk6      = "#54546D" # inlay hints
surimiOrange  = "#FFA066" # constants, imports, booleans
waveAqua1     = "#6A9589" # diagnostic info
waveAqua2     = "#7AA89F" # types
waveAqua3     = "#68AD99" # unused
waveAqua4     = "#7AA880" # unused
waveAqua5     = "#6CAF95" # unused
waveBlue1     = "#223249" # popup background, visual selection background
waveBlue2     = "#2D4F67" # popup selection background, search background
waveRed       = "#E46876" # standout specials 1, e.g. builtin variables
winterBlue    = "#252535" # diff line background
winterGreen   = "#2B3328" # diff add background
winterRed     = "#43242B" # diff delete background
winterYellow  = "#49443C" # diff change background
