# Author : thlsrms <thlsrmsdev@gmail.com>

# Original author: kaolin-valley-dark by Ogden Webb: github.com/ogdenwebb/emacs-kaolin-themes
# Kaolin Valley Dark Theme - Colorful Kaolin theme with brown background

inherits = "kaolin-dark"

"attribute"                 = "fg1"
"constant.builtin"          = { fg = "aquamarine3" }
"constant.character.escape" = "fg1"
"constant.numeric"          = "aquamarine3"
"function"                  = { fg = "valley-dark-fn" }
"function.builtin"          = "aquamarine3"
"function.macro"            = "valley-dark-fn"
"keyword"                   = { fg = "teal3" }
"keyword.directive"         = "green0"
"label"                     = "ultramarine3"
"module"                    = "green0"
"operator"                  = "teal3"
"special"                   = "ultramarine3"
"string"                    = "fg1"
"tag"                       = "green0"
"type.builtin"              = "aquamarine3"
"variable"                  = "constant"
"variable.builtin"          = "teal3"
"variable.other.member"     = { fg = "selection0", modifiers = [ "italic" ] }
"variable.parameter"        = "constant"

"diff.delta" = "type"

"ui.cursor.match"                 = { bg = "selection0", fg = "bg0" }
"ui.linenr.selected"              = { fg = "warn", modifiers = [ "bold" ] }
"ui.menu"                         = { bg = "bg1", fg = "fg1" }
"ui.menu.selected"                = { bg = "bg1", fg = "selection0", modifiers = [ "bold" ] }
"ui.statusline"                   = { bg = "bg1", fg = "fg0" }
"ui.statusline.insert"            = { bg = "bg1", fg = "hint", modifiers = [ "bold" ] }
"ui.statusline.normal"            = { bg = "bg1", fg = "warn", modifiers = [ "bold" ] }
"ui.statusline.select"            = { bg = "bg1", fg = "constant", modifiers = [ "bold" ] }
"ui.text.focus"                   = { bg = "bg1", fg = "selection0" }
"ui.virtual.indent-guide"         = "gray1"
"ui.virtual.inlay-hint"           = "gray0"
"ui.virtual.inlay-hint.parameter" = { fg = "gray0", modifiers = [ "italic" ] }
"ui.virtual.inlay-hint.type"      = { fg = "gray0", modifiers = [ "italic" ] }
"ui.virtual.ruler"                = { bg = "bg2" }
"ui.virtual.whitespace"           = "gray1"
"ui.virtual.wrap"                 = "gray1"

"markup.heading"   = "type"
"markup.link.text" = "valley-dark-fn"
"markup.link.url"  = { fg = "constant", modifiers = [ "underlined" ] }

[palette]
# kaolin-valley-dark palette
aquamarine3    = "#53e6b5"
bg0            = "#262221" # valley-dark-bg1
bg1            = "#2e2a29" # valley-dark-bg2
bg2            = "#383030" # valley-dark-bg4
constant       = "#ef6787" # crimson3
error          = "#e84c58" # red3
fg0            = "#eee6d3" # amber9
fg1            = "#cea2ca" # magenta3
gray0          = "#635c4a" # valley-dark-comment
gray1          = "#52413f" # brown2
green0         = "#91f368" # harlequin3
hint           = "#6bd9db" # cyan3
info           = "#41b0f3" # capri3
selection0     = "#ee7042" # vermilion3
selection1     = "#402e2e" # red6
teal3          = "#49bdb0"
type           = "#eed891" # amber3
ultramarine3   = "#9587dd"
valley-dark-fn = "#7ed7e6"
warn           = "#cfb05f" # amber1
