# Author : thlsrms <thlsrmsdev@gmail.com>

# Original author: kaolin-dark by Ogden Webb: github.com/ogdenwebb/emacs-kaolin-themes
# Kaolin Dark Theme - A dark jade theme inspired by Sierra.vim : github.com/AlessandroYorba/Sierra

"attribute"                 = "constant"
"comment"                   = { fg = "gray0", modifiers = [ "italic" ] }
"constant"                  = { fg = "constant" }
"constant.builtin"          = { fg = "info" }
"constant.character.escape" = { fg = "hint", modifiers = [ "bold" ] }
"constant.numeric"          = "info"
"constructor"               = { fg = "type" }
"function"                  = { fg = "info" }
"function.builtin"          = "selection0"
"function.macro"            = "constant"
"keyword"                   = { fg = "hint" }
"keyword.directive"         = "info"
"label"                     = "constant"
"module"                    = "info"
"namespace"                 = "constant"
"operator"                  = "fg0"
"punctuation"               = "fg0"
"punctuation.delimiter"     = "fg0"
"special"                   = "constant"
"string"                    = "hint"
"tag"                       = "#7aaaa5"
"type"                      = "type"
"type.builtin"              = "info"
"variable"                  = "ultramarine4_dark"
"variable.builtin"          = "hint"
"variable.other.member"     = { fg = "violet7", modifiers = [ "italic" ] }
"variable.parameter"        = "ultramarine4_dark"

"diff.delta" = "warn"
"diff.minus" = "error"
"diff.plus"  = "green0"

"error"   = "error"
"hint"    = "hint"
"info"    = "info"
"warning" = "warn"

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "error", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "hint", style = "curl" } }
"diagnostic.info"        = { underline = { color = "info", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "warn", style = "curl" } }

"ui.background" = { bg = "bg0" }
"ui.cursor.match" = { bg = "ultramarine4_dark", fg = "bg1" }
"ui.cursor.primary" = { modifiers = [ "reversed" ] }
"ui.cursorcolumn.primary" = { bg = "bg1" }
"ui.cursorcolumn.secondary" = { bg = "bg2" }
"ui.cursorline" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg2" }
"ui.debug.active" = "warn"
"ui.debug.breakpoint" = "error"
"ui.help" = { bg = "bg1", fg = "fg0" }
"ui.linenr" = { fg = "gray0" }
"ui.linenr.selected" = { fg = "gray1", modifiers = [ "bold" ] }
"ui.menu" = { bg = "bg1", fg = "fg0" }
"ui.menu.selected" = { bg = "bg2", fg = "selection0", modifiers = [ "bold" ] }
"ui.popup" = { bg = "bg1" }
"ui.selection" = { bg = "selection1" }
"ui.selection.primary" = { bg = "selection1" }
"ui.statusline" = { bg = "bg1", fg = "info" }
"ui.statusline.inactive" = { bg = "bg1", fg = "gray0" }
"ui.statusline.insert" = { bg = "bg1", fg = "green0", modifiers = [ "reversed", "bold" ] }
"ui.statusline.normal" = { bg = "bg1", fg = "hint", modifiers = [ "reversed", "bold" ] }
"ui.statusline.select" = { bg = "bg1", fg = "ultramarine4_dark", modifiers = [
  "reversed",
  "bold",
] }
"ui.text" = { fg = "fg1" }
"ui.text.focus" = { fg = "selection0" }
"ui.virtual.indent-guide" = "bg2"
"ui.virtual.inlay-hint" = "gray1"
"ui.virtual.inlay-hint.parameter" = { fg = "gray1", modifiers = [ "dim" ] }
"ui.virtual.inlay-hint.type" = { fg = "gray1", modifiers = [ "dim" ] }
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.whitespace" = "fg1"
"ui.virtual.wrap" = "bg2"
"ui.window" = { bg = "bg0", fg = "bg1" }

"markup.bold"          = { modifiers = [ "bold" ] }
"markup.heading"       = "info"
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.link.text"     = "selection0"
"markup.link.url"      = { fg = "warn", underline = { style = "line" } }
"markup.raw"           = "selection0"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

[palette]
# kaolin-dark palette
bg0               = "#18181b" # black1
bg1               = "#222225" # black2
bg2               = "#303035" # black4
constant          = "#ab98b5" # purple4
error             = "#cd5c60" # red1
fg0               = "#e6e6e8" # white1
fg1               = "#adadb9" # whiet4
gray0             = "#545c5e" # gray3
gray1             = "#919a9c" # gray9
green0            = "#6fb593" # spring-green3
hint              = "#4d9391" # teal1
info              = "#80bcb6" # teal4
selection0        = "#68f3ca" # aquamarine3
selection1        = "#2e403b" # aquamarine6
type              = "#cd9575" # vermilion4
ultramarine4_dark = "#968cc7"
violet7           = "#766884"
warn              = "#dbac66" # orange1
