# Author: spentbliss <zyhkekrz.hatbox475@passinbox.com>
# License: MIT (originally by Alex Barnett)

"ui.background"        = { bg = "bg", fg = "fg" }   # file picker border color
"ui.cursor"            = { bg = "blue", fg = "bg" }
"ui.linenr"            = "grey"
"ui.selection"         = "green"
"ui.selection.primary" = { bg = "bg_highlight" }
"ui.statusline"        = { fg = "fg" }
"ui.text"              = "fg"
"ui.text.focus"        = { bg = "fg", fg = "bg" }   # file picker selection
"ui.virtual.ruler"     = { bg = "bg_highlight" }

# Syntax Highlighting for Markdown 
"markup.bold"          = { fg = "fg", modifiers = [ "bold" ] }
"markup.heading.1"     = { bg = "#11313B", fg = "#46D9FF" }            # cyan
"markup.heading.2"     = { bg = "#2D2233", fg = "#C678DD" }            # magenta
"markup.heading.3"     = { bg = "#253027", fg = "#98BE65" }            # green
"markup.heading.4"     = { bg = "#2A2738", fg = "#A8A1E1" }            # purple
"markup.heading.5"     = { bg = "#3A3223", fg = "#ECBE7B" }            # yellow
"markup.heading.6"     = { bg = "#1E2A30", fg = "#46D9FF" }            # cyan again
"markup.italic"        = { fg = "fg" }
"markup.link"          = { fg = "cyan" }
"markup.list"          = { fg = "purple" }
"markup.quote"         = { fg = "fg" }
"markup.raw"           = { bg = "bg", fg = "purple" }
"markup.raw.inline"    = { fg = "fg" }
"markup.strikethrough" = { fg = "red", modifiers = [ "crossed_out" ] }

# Syntax Highlighting for Code
"comment"               = { fg = "grey", modifiers = [ "italic" ] }
"comment.block"         = { fg = "grey", modifiers = [ "italic" ] }
"comment.documentation" = { fg = "blue", modifiers = [ "italic" ] }
"comment.line"          = { fg = "grey", modifiers = [ "italic" ] }

"keyword"                     = "blue"
"keyword.control.conditional" = "blue" # if, else
"keyword.control.export"      = "blue"
"keyword.control.import"      = "blue" # use keyword in rust
"keyword.control.repeat"      = "blue" # for, while, loop
"keyword.directive"           = "blue"
"keyword.function"            = "blue" # function keyword color
"keyword.operator"            = "blue" # or, in keywords
"keyword.storage"             = "blue" # let keyword in rust 
"keyword.storage.modifier"    = "fg"   # mut keyword
"keyword.storage.type"        = "blue" # keywords describing how things are stored, class, var, let, etc

"type"           = "green"
"type.builtin"   = "green" # primitive types int, usize
"type.enum"      = "cyan"
"type.parameter" = "green"

"function"         = "purple" # color for function NAME not the keyword fn or func
"function.builtin" = "purple"
"function.method"  = "blue"

"variable"           = "fg"
"variable.builtin"   = "fg"
"variable.parameter" = "cyan"

"string"         = "green"
"string.special" = "green"

"constant"           = "cyan"
"constant.builtin"   = "blue"   # true, false, nil
"constant.character" = "yellow" # escape character
"constant.numeric"   = "cyan"   # int & float

"operator" = "fg"

# html tags
"attribute" = "blue"
"tag"       = { fg = "purple", modifiers = [ "bold" ] }

"label"     = "red"
"macro"     = "orange"
"namespace" = "fg"

# Interface specific
"ui.cursorcolumn.primary"   = { bg = "bg_highlight" }
"ui.cursorcolumn.secondary" = { bg = "bg_alt" }
"ui.cursorline.primary"     = { bg = "bg_highlight" }
"ui.cursorline.secondary"   = { bg = "bg_alt" }
"ui.statusline.insert"      = { bg = "green", fg = "bg" }
"ui.statusline.normal"      = { bg = "cyan", fg = "bg" }
"ui.statusline.select"      = { bg = "purple", fg = "bg" }

# Diagnostic styles
"diagnostic.error"   = { fg = "grey" }
"diagnostic.hint"    = { fg = "grey" }
"diagnostic.info"    = { fg = "grey" }
"diagnostic.warning" = { fg = "grey" }
"error"              = { fg = "red", modifiers = [ "bold" ] }
"hint"               = { fg = "blue", modifiers = [ "bold" ] }
"info"               = { fg = "cyan", modifiers = [ "bold" ] }
"warning"            = { fg = "yellow", modifiers = [ "bold" ] }

# Git changes indicator
"diff.delta"          = "fg"
"diff.delta.conflict" = "purple"
"diff.delta.gutter"   = "fg"
"diff.delta.moved"    = "orange"
"diff.minus"          = "red"
"diff.minus.gutter"   = "red"
"diff.plus"           = "green"
"diff.plus.gutter"    = "green"

# Popups and Menus
"ui.menu"          = { bg = "bg", fg = "fg" }
"ui.menu.selected" = { bg = "fg", fg = "bg" }
"ui.popup"         = { bg = "bg", fg = "fg" }
"ui.popup.info"    = { bg = "bg", fg = "fg" }

# Additional overrides
"ui.virtual.indent-guide" = { fg = "indent_color", underline.style = "dotted" }
"ui.virtual.whitespace"   = "grey"

[palette]
bg           = "#1B1F27"
bg_alt       = "#14181D"
bg_highlight = "#43537A"
blue         = "#83ABFC"
cyan         = "#84FCD4"
fg           = "#D6E2FF"
green        = "#ABFC83"
grey         = "#7183A9"
indent_color = "#2E3953"
orange       = "#FCAB83"
pink         = "#FC83D6"
purple       = "#D483FC"
red          = "#FC83AB"
yellow       = "#FCD583"
