# Material Theme <https://material-theme.com/> for Helix Editor

# Syntax Highlighting

"type" = "purple"

"constructor" = "blue"

"constant" = "yellow"

"string"         = "green"
"string.regexp"  = "yellow"
"string.special" = "blue"

"comment" = { fg = "comment" }

"variable"           = "text"
"variable.builtin"   = "yellow"
"variable.parameter" = { fg = "orange" }

"label" = "orange"

"punctuation" = "cyan"

"keyword"         = "purple"
"keyword.storage" = "cyan"

"operator" = "cyan"

"function"       = "blue"
"function.macro" = "cyan"

"attribute" = "purple"
"tag"       = "red"

"namespace" = { fg = "yellow" }

"special" = "cyan"

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading.1"      = "cyan"
"markup.heading.2"      = "red"
"markup.heading.3"      = "green"
"markup.heading.4"      = "yellow"
"markup.heading.5"      = "blue"
"markup.heading.6"      = "orange"
"markup.heading.marker" = { fg = "cyan", modifiers = [ "bold" ] }
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = "blue"
"markup.link.url"       = { fg = "green", modifiers = [ "underlined" ] }
"markup.list"           = "purple"
"markup.raw"            = "text"
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus"  = "green"

# User Interface

"ui.background"     = { bg = "bg", fg = "text" }
"ui.text"           = { fg = "text" }
"ui.text.directory" = { fg = "blue" }

"ui.statusline"          = { bg = "bg", fg = "text" }
"ui.statusline.inactive" = { bg = "bg", fg = "disabled" }
"ui.statusline.insert"   = { bg = "green", fg = "bg" }
"ui.statusline.normal"   = { bg = "blue", fg = "bg" }
"ui.statusline.select"   = { bg = "purple", fg = "bg" }


"ui.selection" = { bg = "selection" }

"ui.linenr"          = { fg = "line-number" }
"ui.linenr.selected" = { fg = "accent" }

"ui.cursor" = { bg = "highlight", fg = "white" }

"ui.cursor.primary"     = { bg = "white", fg = "gray" }
"ui.cursorline.primary" = { bg = "active" }

"ui.virtual"              = { fg = "gray" }
"ui.virtual.indent-guide" = { fg = "gray" }
"ui.virtual.ruler"        = { bg = "highlight" }

"ui.highlight" = { bg = "highlight" }

"ui.menu"          = { bg = "highlight", fg = "text" }
"ui.menu.selected" = { bg = "blue", fg = "bg" }

"ui.help" = { bg = "highlight", fg = "text" }

"ui.popup" = { bg = "highlight", fg = "text" }

"ui.virtual.jump-label" = { fg = "purple", modifiers = [ "bold" ] }

error   = "error"
hint    = "purple"
info    = "blue"
warning = "yellow"

"diagnostic"             = { underline = { color = "error", style = "curl" } }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "error", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "purple", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }


[palette]
bg   = "#0f111a"
text = "#a6accd"

blue   = "#82aaff"
cyan   = "#89ddff"
error  = "#ff5370"
gray   = "#717cb4"
green  = "#c3e88d"
orange = "#f78c6c"
purple = "#c792ea"
red    = "#f07178"
white  = "#eeffff"
yellow = "#ffcb6b"

disabled = "#464b5d"

accent = "#84ffff"

active    = "#1a1c25"
highlight = "#1f2233"

comment = "#464b5d"

selection = "#1f2233"

line-number = "#3b3f51"
