# Author: Ramojus Lapinskas <ramojus.lap@gmail.com>

"comment"                = { fg = "comment" }
"constant"               = { fg = "magenta" }
"function"               = { fg = "blue" }
"keyword"                = { fg = "orange" }
"keyword.control"        = { fg = "red" }
"keyword.control.import" = { fg = "orange" }
"keyword.function"       = { fg = "red" }
"label"                  = { fg = "orange" }
"namespace"              = { fg = "blue" }
"operator"               = { fg = "secondary_white" }
"punctuation"            = { fg = "secondary_white" }
"string"                 = { fg = "yellow" }
"string.regexp"          = { fg = "orange" }
"tag"                    = { fg = "red" }
"type"                   = { fg = "secondary_white" }
"variable"               = { fg = "white" }

"diff.delta" = { fg = "magenta" }
"diff.minus" = { fg = "red" }
"diff.plus"  = { fg = "blue" }

"ui.cursor"         = { bg = "light_grey", fg = "black" }
"ui.cursor.match"   = { bg = "dark_grey" }
"ui.cursor.primary" = { bg = "secondary_white", fg = "black" }

"ui.gutter"          = { bg = "dark_black" }
"ui.linenr"          = { bg = "dark_black", fg = "grey" }
"ui.linenr.selected" = { bg = "dark_light_black", fg = "dark_white" }

"ui.background"           = { bg = "black", fg = "light_grey" }
"ui.background.separator" = { fg = "dark_grey" }
"ui.help"                 = { bg = "light_black3", fg = "white" }
"ui.menu"                 = { bg = "light_black", fg = "dark_white" }
"ui.menu.selected"        = { bg = "orange", fg = "black" }
"ui.popup"                = { bg = "light_black", fg = "dark_white" }
"ui.window"               = { fg = "light_black3" }

"ui.cursorline.primary" = { bg = "light_black" }
"ui.selection"          = { bg = "light_black3" }
"ui.selection.primary"  = { bg = "light_black3", modifiers = [ "bold" ] }

"ui.statusline"          = { bg = "light_black3", fg = "dark_white" }
"ui.statusline.inactive" = { bg = "light_black", fg = "dark_white2" }
"ui.statusline.insert"   = { bg = "blue", fg = "black" }
"ui.statusline.normal"   = { bg = "dark_white2", fg = "black" }
"ui.statusline.select"   = { bg = "orange", fg = "black" }

"ui.text"       = { fg = "white" }
"ui.text.focus" = { fg = "orange" }

"ui.virtual.indent-guide" = { fg = "dark_grey2" }
"ui.virtual.ruler"        = { bg = "light_black2" }
"ui.virtual.whitespace"   = { fg = "grey" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "magenta", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange", style = "curl" } }

"error"   = { fg = "red" }
"hint"    = { fg = "magenta" }
"info"    = { fg = "blue" }
"special" = { fg = "yellow" }
"warning" = { fg = "orange" }

"markup.bold"          = { fg = "magenta", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "orange" }
"markup.italic"        = { fg = "blue", modifiers = [ "italic" ] }
"markup.link.text"     = { fg = "comment" }
"markup.link.url"      = { fg = "comment", modifiers = [ "underlined" ] }
"markup.list"          = { fg = "blue" }
"markup.quote"         = { fg = "yellow" }
"markup.raw"           = { fg = "blue" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

[palette]
blue    = "#a49db9"
magenta = "#b494af"
orange  = "#cbab8a"
red     = "#d29595"
yellow  = "#c9b58e"

comment = "#707035"

black            = "#1c1917"
dark_black       = "#191514"
dark_light_black = "#211d1c"
light_black      = "#252220"
light_black2     = "#292725"
light_black3     = "#302D2B"

dark_grey       = "#4c4b49"
dark_grey2      = "#383735"
dark_white      = "#aaa7a6"
dark_white2     = "#949290"
grey            = "#605e5d"
light_grey      = "#6a6867"
secondary_white = "#c2b4a8"
white           = "#dad7d5"
