# Author : Rohit K Viswanath <kvrohit@gmail.com>
# Theme: Mellow

"attribute" = { fg = "blue", modifiers = [ "italic" ] }

"keyword"                     = "blue"
"keyword.control.conditional" = { fg = "blue", modifiers = [ "italic" ] }
"keyword.directive"           = "magenta"                                 # -- preprocessor comments (#if in C)

"namespace" = { fg = "cyan", modifiers = [ "italic" ] }

"punctuation"           = "gray06"
"punctuation.delimiter" = "gray06"

"operator" = "yellow"
"special"  = "yellow"

"variable"              = "fg"
"variable.builtin"      = "bright_blue"
"variable.other.member" = "white"
"variable.parameter"    = "cyan"

"type"              = "bright_blue"
"type.builtin"      = "magenta"
"type.enum.variant" = "magenta"

"constructor" = "yellow"

"function"         = "white"
"function.builtin" = "bright_blue"
"function.macro"   = "bright_cyan"

"comment" = { fg = "gray05", modifiers = [ "italic" ] }
"tag"     = "cyan"

"string"         = "green"
"string.regexp"  = "green"
"string.special" = "yellow"

"constant"                  = "cyan"
"constant.builtin"          = "yellow"
"constant.character.escape" = "cyan"
"constant.numeric"          = "magenta"

# used for lifetimes
"label" = "yellow"

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading"        = { fg = "bright_blue", modifiers = [ "bold" ] }
"markup.heading.marker" = { fg = "gray06" }
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = { fg = "blue", modifiers = [ "italic" ] }
"markup.link.url"       = { fg = "green", modifiers = [ "underlined" ] }
"markup.list"           = "gray06"
"markup.raw"            = "yellow"
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"diff.delta" = "bright_blue"
"diff.minus" = "bright_red"
"diff.plus"  = "bright_green"

"ui.background"           = { bg = "bg" }
"ui.background.separator" = { fg = "fg" }

"ui.linenr"          = { fg = "gray04" }
"ui.linenr.selected" = { fg = "fg" }

"ui.statusline"          = { bg = "gray01", fg = "fg" }
"ui.statusline.inactive" = { bg = "gray01", fg = "fg", modifiers = [ "dim" ] }
"ui.statusline.insert"   = { bg = "blue", fg = "bg", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "cyan", fg = "bg", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "magenta", fg = "bg", modifiers = [ "bold" ] }

"ui.help"   = { bg = "gray01", fg = "white" }
"ui.popup"  = { bg = "gray01" }
"ui.window" = { fg = "gray02" }

"ui.text"       = { fg = "fg" }
"ui.text.focus" = { fg = "fg" }

"ui.virtual"              = { fg = "gray02" }
"ui.virtual.indent-guide" = { fg = "gray02" }
"ui.virtual.inlay-hint"   = { fg = "gray04" }
"ui.virtual.ruler"        = { bg = "gray02" }

"ui.selection"         = { bg = "gray03" }
"ui.selection.primary" = { bg = "gray03" }

"ui.cursor"             = { bg = "gray04" }
"ui.cursor.match"       = { fg = "yellow", modifiers = [ "bold", "underlined" ] }
"ui.cursorline.primary" = { bg = "gray01" }

"ui.highlight" = { bg = "gray02" }

"ui.menu"          = { bg = "gray01", fg = "white" }
"ui.menu.scroll"   = { bg = "gray01", fg = "gray04" }
"ui.menu.selected" = { bg = "gray03", fg = "bright_white" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "bright_red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "bright_cyan", style = "curl" } }
"diagnostic.info"        = { underline = { color = "bright_blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "bright_yellow", style = "curl" } }

error   = "bright_red"
hint    = "bright_cyan"
info    = "bright_blue"
warning = "bright_yellow"

[palette]
bg      = "#161617"
bg_dark = "#131314"
fg      = "#c9c7cd"

black        = "#27272a"
bright_black = "#353539"

bright_red = "#ffae9f"
red        = "#f5a191"

bright_green = "#9dc6ac"
green        = "#90b99f"

bright_yellow = "#f0c5a9"
yellow        = "#e6b99d"

blue        = "#aca1cf"
bright_blue = "#b9aeda"

bright_magenta = "#ecaad6"
magenta        = "#e29eca"

bright_cyan = "#f591b2"
cyan        = "#ea83a5"

bright_white = "#cac9dd"
white        = "#c1c0d4"

gray01 = "#1b1b1d"
gray02 = "#2a2a2d"
gray03 = "#3e3e43"
gray04 = "#57575f"
gray05 = "#757581"
gray06 = "#9998a8"
gray07 = "#c1c0d4"
