# Author: Alexis Mousset <contact@amousset.me>
# modus_operandi.toml variant
#
# This variant is optimized for users with red-green color deficiency (deuteranopia)
# Version 4.6.0

inherits = "modus_operandi"

"comment"                   = "yellow-cooler"
"constant.character.escape" = "magenta"
"function"                  = "magenta"
"tag"                       = "magenta"

"ui.cursor"                = { bg = "blue-intense", fg = "bg-main" }
"ui.cursor.primary.normal" = { bg = "blue-intense", fg = "bg-main" }

"diagnostic.error"   = { underline = { color = "yellow-intense", style = "curl" } }
"diagnostic.hint"    = { underline = { color = "blue", style = "curl" } }
"diagnostic.info"    = { underline = { color = "cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "magenta-faint", style = "curl" } }

error   = "yellow-intense"
hint    = "blue"
info    = "cyan"
warning = "magenta-faint"

[palette]

yellow        = "#695500"
yellow-cooler = "#77492f"
yellow-warmer = "#973300"

bg-mode-line-active     = "#d0d6ff"
border-mode-line-active = "#4f4f74"
fg-mode-line-active     = "#0f0f0f"

modeline-err     = "#603a00"
modeline-info    = "#023d92"
modeline-warning = "#454500"

# Diffs
bg-added   = "#d5d7ff"
bg-changed = "#eecfdf"
bg-removed = "#f4f099"
fg-added   = "#303099"
fg-changed = "#6f1343"
fg-removed = "#553d00"
