# Author: Matous Dzivjak <matousdzivjak@gmail.com>
# Adapted from https://protesilaos.com/emacs/modus-themes, by Protesilaos Stavrou
# Source: https://github.com/protesilaos/modus-themes/blob/main/modus-vivendi-tritanopia-theme.el
# Version 4.6.0

inherits = "modus_vivendi"

"comment"                   = "red-faint"
"constant"                  = "green-cooler"
"constant.character.escape" = "red-cooler"
"constructor"               = "blue-warmer"
"function"                  = "cyan-warmer"
"function.macro"            = "magenta"
"keyword"                   = "red-cooler"
"keyword.directive"         = "red-warmer"
"string"                    = "cyan"
"tag"                       = "red-cooler"
"type"                      = "blue-warmer"
"variable.parameter"        = "cyan-cooler"

"markup.heading.2" = { fg = "red-faint", modifiers = [ "bold" ] }
"markup.heading.3" = { fg = "cyan-faint", modifiers = [ "bold" ] }
"markup.heading.6" = { fg = "magenta-faint", modifiers = [ "bold" ] }
"markup.link.text" = { fg = "cyan", modifiers = [ "underlined" ] }
"markup.link.url"  = { fg = "cyan-cooler" }

"ui.cursor"                = { bg = "red-intense", fg = "bg-main" }
"ui.cursor.primary.normal" = { bg = "red-intense", fg = "bg-main" }

"diagnostic.error"   = { underline = { color = "red-warmer", style = "curl" } }
"diagnostic.hint"    = { underline = { color = "blue", style = "curl" } }
"diagnostic.info"    = { underline = { color = "cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "magenta", style = "curl" } }

error   = "red-warmer"
hint    = "blue"
info    = "cyan"
warning = "magenta"

rainbow = [ "red", "magenta", "green-intense", "cyan", "blue", "magenta-intense" ]

[palette]
# Basic values
bg-active   = "#535353"
bg-dim      = "#1e1e1e"
bg-inactive = "#303030"
bg-main     = "#000000"
border      = "#646464"
fg-alt      = "#c6daff"
fg-dim      = "#989898"
fg-main     = "#ffffff"

# Common accent foregrounds
blue            = "#2fafff"
blue-cooler     = "#00bcff"
blue-faint      = "#82b0ec"
blue-intense    = "#338fff"
blue-warmer     = "#79a8ff"
cyan            = "#00d3d0"
cyan-cooler     = "#6ae4b9"
cyan-faint      = "#7fdbdf"
cyan-intense    = "#00eff0"
cyan-warmer     = "#4ae2ff"
green           = "#44bc44"
green-cooler    = "#00c06f"
green-faint     = "#88ca9f"
green-intense   = "#44df44"
green-warmer    = "#70b900"
magenta         = "#feacd0"
magenta-cooler  = "#b6a0ff"
magenta-faint   = "#caa6df"
magenta-intense = "#ef7fff"
magenta-warmer  = "#f78fe7"
red             = "#ff5f59"
red-cooler      = "#ff7f86"
red-faint       = "#ff9070"
red-intense     = "#ff5f5f"
red-warmer      = "#ff6740"
yellow          = "#cabf00"
yellow-cooler   = "#d8af7a"
yellow-faint    = "#d2b580"
yellow-intense  = "#efef00"
yellow-warmer   = "#ffa00f"

# Uncommon accent foregrounds
gold   = "#c0965b"
indigo = "#9099d9"
maroon = "#cf7fa7"
olive  = "#9cbd6f"
pink   = "#d09dc0"
rust   = "#db7b5f"
slate  = "#76afbf"

# Common accent backgrounds
bg-blue-intense    = "#1640b0"
bg-cyan-intense    = "#2266ae"
bg-green-intense   = "#2f822f"
bg-magenta-intense = "#7030af"
bg-red-intense     = "#9d1f1f"
bg-yellow-intense  = "#7a6100"

bg-blue-subtle    = "#242679"
bg-cyan-subtle    = "#004065"
bg-green-subtle   = "#00422a"
bg-magenta-subtle = "#552f5f"
bg-red-subtle     = "#620f2a"
bg-yellow-subtle  = "#4a4000"

bg-blue-nuanced    = "#12154a"
bg-cyan-nuanced    = "#042837"
bg-green-nuanced   = "#092f1f"
bg-magenta-nuanced = "#2f0c3f"
bg-red-nuanced     = "#3a0c14"
bg-yellow-nuanced  = "#381d0f"

# Uncommon accent backgrounds
bg-lavender = "#38325c"
bg-ochre    = "#442c2f"
bg-sage     = "#0f3d30"

# Graphs
bg-graph-blue-0    = "#4f9fdf"
bg-graph-blue-1    = "#004559"
bg-graph-cyan-0    = "#57dfea"
bg-graph-cyan-1    = "#00808f"
bg-graph-green-0   = "#afd1c0"
bg-graph-green-1   = "#607a8f"
bg-graph-magenta-0 = "#b6427f"
bg-graph-magenta-1 = "#7f506f"
bg-graph-red-0     = "#b52c2c"
bg-graph-red-1     = "#702020"
bg-graph-yellow-0  = "#facfd6"
bg-graph-yellow-1  = "#b57b85"

# Special purpose
bg-completion      = "#004253"
bg-hl-line         = "#2f3849"
bg-hover           = "#8e3e3b"
bg-hover-secondary = "#00405f"
bg-region          = "#5a5a5a"
fg-region          = "#ffffff"

bg-char-0 = "#922a00"
bg-char-1 = "#00709f"
bg-char-2 = "#5f3faf"

bg-mode-line-active       = "#003c52"
bg-mode-line-inactive     = "#2d2d2d"
border-mode-line-active   = "#5f8fb4"
border-mode-line-inactive = "#606060"
fg-mode-line-active       = "#f0f0f0"
fg-mode-line-inactive     = "#969696"

modeline-err     = "#ff7fbf"
modeline-info    = "#4fcfef"
modeline-warning = "#df9f93"

bg-tab-bar     = "#313131"
bg-tab-current = "#000000"
bg-tab-other   = "#545454"

# Diffs
bg-added         = "#004254"
bg-added-faint   = "#003042"
bg-added-fringe  = "#008fcf"
bg-added-refine  = "#004f7f"
fg-added         = "#9fdfdf"
fg-added-intense = "#50c0ef"

bg-changed         = "#2f123f"
bg-changed-faint   = "#1f022f"
bg-changed-fringe  = "#7f55a0"
bg-changed-refine  = "#3f325f"
fg-changed         = "#e3cfff"
fg-changed-intense = "#cf9fe2"

bg-removed         = "#4f1119"
bg-removed-faint   = "#380a0f"
bg-removed-fringe  = "#b81a1f"
bg-removed-refine  = "#781a1f"
fg-removed         = "#ffbfbf"
fg-removed-intense = "#ff9095"

bg-diff-context = "#1a1a1a"

# Paren match
bg-paren-expression = "#453040"
bg-paren-match      = "#2f7f9f"
