# Author: Alexis Mousset <contact@amousset.me>
# Adapted from https://protesilaos.com/emacs/modus-themes, by Protesilaos Stavrou
# Version 4.6.0
#

# Syntax highlighting
# -------------------
"constructor" = "cyan-cooler"
"type"        = "cyan-cooler"

"constant"                  = "blue-cooler"
"constant.character.escape" = "magenta"

"string"         = "blue-warmer"
"string.regexp"  = "magenta-faint"
"string.special" = "blue-faint"    # used for colors in CSS

"comment" = "fg-dim"

"function"           = "magenta"
"function.macro"     = "magenta-warmer"
"keyword"            = "magenta-cooler"
"keyword.directive"  = "red-cooler"
"label"              = "fg-dim"         # used for language in markdown code blocks
"variable.builtin"   = "magenta-cooler"
"variable.parameter" = "cyan"

"attribute" = "cyan-cooler"
"namespace" = "blue-cooler"
punctuation = "fg-dim"
"special"   = "red-cooler"
"tag"       = "magenta"

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading.1"      = { fg = "fg-main", modifiers = [ "bold" ] }
"markup.heading.2"      = { fg = "yellow-faint", modifiers = [ "bold" ] }
"markup.heading.3"      = { fg = "fg-alt", modifiers = [ "bold" ] }
"markup.heading.4"      = { fg = "magenta", modifiers = [ "bold" ] }
"markup.heading.5"      = { fg = "green-faint", modifiers = [ "bold" ] }
"markup.heading.6"      = { fg = "red-faint", modifiers = [ "bold" ] }
"markup.heading.marker" = "fg-dim"
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = { fg = "blue-warmer", modifiers = [ "underlined" ] }
"markup.link.url"       = { fg = "cyan" }
"markup.list"           = "fg-dim"
"markup.list.checked"   = { fg = "yellow-warmer" }
"markup.list.unchecked" = { fg = "yellow-warmer" }
"markup.raw.block"      = { bg = "bg-dim" }
"markup.raw.inline"     = { fg = "green-cooler" }
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"diff.delta"        = { bg = "bg-changed", fg = "fg-changed" }
"diff.delta.gutter" = "yellow-intense"
"diff.minus"        = { bg = "bg-removed", fg = "fg-removed" }
"diff.minus.gutter" = "red-intense"
"diff.plus"         = { bg = "bg-added", fg = "fg-added" }
"diff.plus.gutter"  = "green-intense"

# User Interface
# --------------

"ui.background" = { bg = "bg-main" }

"ui.linenr"          = { bg = "bg-dim", fg = "fg-dim" }
"ui.linenr.selected" = { bg = "bg-active", fg = "fg-main" }

"ui.statusline"          = { bg = "bg-mode-line-active", fg = "fg-mode-line-active" }
"ui.statusline.inactive" = { bg = "bg-mode-line-inactive", fg = "fg-mode-line-inactive" }
"ui.statusline.insert"   = { fg = "green-warmer" }
"ui.statusline.normal"   = { fg = "blue-warmer" }
"ui.statusline.select"   = { fg = "magenta-warmer" }

"ui.gutter"             = { bg = "bg-dim" }
"ui.help"               = { bg = "bg-active", fg = "fg-main" }
"ui.popup"              = { bg = "bg-dim", fg = "fg-main" }
"ui.text"               = "fg-main"
"ui.text.directory"     = "blue"
"ui.text.focus"         = { bg = "bg-completion", fg = "fg-main", modifiers = [ "bold" ] }
"ui.text.inactive"      = { fg = "fg-dim" }
"ui.virtual"            = "bg-active"
"ui.virtual.inlay-hint" = { fg = "fg-dim", modifiers = [ "italic" ] }
"ui.virtual.jump-label" = { fg = "yellow-cooler", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "bg-dim" }
"ui.window"             = { fg = "fg-dim" }

"ui.selection"         = { bg = "bg-inactive" }
"ui.selection.primary" = { bg = "bg-active" }

"ui.cursor"             = { bg = "fg-main", fg = "bg-main" }
"ui.cursor.match"       = { bg = "bg-paren-match", fg = "fg-main" }
"ui.cursor.primary"     = { bg = "fg-dim", fg = "bg-main" }
"ui.cursorline.primary" = { bg = "bg-hl-line" }

"ui.highlight" = { bg = "bg-hl-line" }

"ui.menu"          = { bg = "bg-dim", fg = "fg-main" }
"ui.menu.scroll"   = { bg = "bg-cyan-intense", fg = "fg-dim" }
"ui.menu.selected" = { bg = "bg-completion", fg = "fg-main", modifiers = [ "bold" ] }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red-intense", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "blue-intense", style = "curl" } }
"diagnostic.info"        = { underline = { color = "cyan-intense", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow-intense", style = "curl" } }

error   = "red"
hint    = "blue-cooler"
info    = "cyan-cooler"
warning = "yellow-warmer"

[palette]
# Basic values
bg-active   = "#c4c4c4"
bg-dim      = "#f2f2f2"
bg-inactive = "#e0e0e0"
bg-main     = "#ffffff"
fg-alt      = "#193668"
fg-dim      = "#595959"
fg-main     = "#000000"

# Common accent foregrounds
blue            = "#0031a9"
blue-cooler     = "#0000b0"
blue-faint      = "#003497"
blue-intense    = "#0000ff"
blue-warmer     = "#354fcf"
cyan            = "#005e8b"
cyan-cooler     = "#005f5f"
cyan-faint      = "#005077"
cyan-intense    = "#008899"
cyan-warmer     = "#3f578f"
green           = "#006800"
green-cooler    = "#00663f"
green-faint     = "#2a5045"
green-intense   = "#008900"
green-warmer    = "#316500"
magenta         = "#721045"
magenta-cooler  = "#531ab6"
magenta-faint   = "#7c318f"
magenta-intense = "#dd22dd"
magenta-warmer  = "#8f0075"
red             = "#a60000"
red-cooler      = "#a0132f"
red-faint       = "#7f0000"
red-intense     = "#d00000"
red-warmer      = "#972500"
yellow          = "#6f5500"
yellow-cooler   = "#7a4f2f"
yellow-faint    = "#624416"
yellow-intense  = "#808000"
yellow-warmer   = "#884900"

# Common accent backgrounds
bg-blue-intense    = "#bfc9ff"
bg-cyan-intense    = "#a4d5f9"
bg-green-intense   = "#8adf80"
bg-magenta-intense = "#dfa0f0"
bg-red-intense     = "#ff8f88"
bg-yellow-intense  = "#f3d000"

bg-blue-subtle    = "#ccdfff"
bg-cyan-subtle    = "#bfefff"
bg-green-subtle   = "#b3fabf"
bg-magenta-subtle = "#ffddff"
bg-red-subtle     = "#ffcfbf"
bg-yellow-subtle  = "#fff576"

bg-blue-nuanced    = "#ecedff"
bg-cyan-nuanced    = "#e0f2fa"
bg-green-nuanced   = "#e0f6e0"
bg-magenta-nuanced = "#f8e6f5"
bg-red-nuanced     = "#ffe8e8"
bg-yellow-nuanced  = "#f8f0d0"

# Special purpose
bg-completion = "#c0deff"
bg-hl-line    = "#dae5ec"

bg-mode-line-active   = "#c8c8c8"
bg-mode-line-inactive = "#e6e6e6"
fg-mode-line-active   = "#000000"
fg-mode-line-inactive = "#585858"

modeline-err     = "#7f0000"
modeline-info    = "#002580"
modeline-warning = "#5f0070"

# Diffs
bg-added   = "#c1f2d1"
bg-changed = "#ffdfa9"
bg-removed = "#ffd8d5"
fg-added   = "#005000"
fg-changed = "#553d00"
fg-removed = "#8f1313"

# Paren match
bg-paren-match = "#5fcfff"
