# Author: Matous Dzivjak <matousdzivjak@gmail.com>
# Adapted from: https://protesilaos.com/emacs/modus-themes, by Protesilaos Stavrou
# Source: https://github.com/protesilaos/modus-themes/blob/main/modus-vivendi-tinted-theme.el
# Version 4.6.0

inherits = "modus_vivendi"

"comment" = "red-faint"

"ui.cursor.primary" = { bg = "magenta-intense", fg = "bg-main" }

[palette]
# Basic values
bg-active   = "#4a4f69"
bg-dim      = "#1d2235"
bg-inactive = "#2b3045"
bg-main     = "#0d0e1c"
border      = "#61647a"
fg-alt      = "#c6daff"
fg-dim      = "#989898"
fg-main     = "#ffffff"

# Common accent foregrounds
blue            = "#2fafff"
blue-cooler     = "#00bcff"
blue-faint      = "#82b0ec"
blue-intense    = "#338fff"
blue-warmer     = "#79a8ff"
cyan            = "#00d3d0"
cyan-cooler     = "#6ae4b9"
cyan-faint      = "#9ac8e0"
cyan-intense    = "#00eff0"
cyan-warmer     = "#4ae2f0"
green           = "#44bc44"
green-cooler    = "#00c06f"
green-faint     = "#88ca9f"
green-intense   = "#44df44"
green-warmer    = "#70b900"
magenta         = "#feacd0"
magenta-cooler  = "#b6a0ff"
magenta-faint   = "#caa6df"
magenta-intense = "#ff66ff"
magenta-warmer  = "#f78fe7"
red             = "#ff5f59"
red-cooler      = "#ff7f86"
red-faint       = "#ff9f80"
red-intense     = "#ff5f5f"
red-warmer      = "#ff6b55"
yellow          = "#d0bc00"
yellow-cooler   = "#dfaf7a"
yellow-faint    = "#d2b580"
yellow-intense  = "#efef00"
yellow-warmer   = "#fec43f"

# Uncommon accent foregrounds
gold   = "#c0965b"
indigo = "#9099d9"
maroon = "#cf7fa7"
olive  = "#9cbd6f"
pink   = "#d09dc0"
rust   = "#db7b5f"
slate  = "#76afbf"

# Common accent backgrounds
bg-blue-intense    = "#1640b0"
bg-cyan-intense    = "#2266ae"
bg-green-intense   = "#2f822f"
bg-magenta-intense = "#7030af"
bg-red-intense     = "#9d1f1f"
bg-yellow-intense  = "#7a6100"

bg-blue-subtle    = "#242679"
bg-cyan-subtle    = "#004065"
bg-green-subtle   = "#00422a"
bg-magenta-subtle = "#552f5f"
bg-red-subtle     = "#620f2a"
bg-yellow-subtle  = "#4a4000"

bg-blue-nuanced    = "#12154a"
bg-cyan-nuanced    = "#042837"
bg-green-nuanced   = "#092f1f"
bg-magenta-nuanced = "#2f0c3f"
bg-red-nuanced     = "#3a0c14"
bg-yellow-nuanced  = "#381d0f"

# Special purpose
bg-completion      = "#483d8a"
bg-hl-line         = "#303a6f"
bg-hover           = "#45605e"
bg-hover-secondary = "#654a39"
bg-region          = "#555a66"
fg-region          = "#ffffff"

bg-char-0 = "#0050af"
bg-char-1 = "#7f1f7f"
bg-char-2 = "#625a00"

bg-mode-line-active       = "#484d67"
bg-mode-line-inactive     = "#292d48"
border-mode-line-active   = "#979797"
border-mode-line-inactive = "#606270"
fg-mode-line-active       = "#ffffff"
fg-mode-line-inactive     = "#969696"

modeline-err     = "#ffa9bf"
modeline-info    = "#9fefff"
modeline-warning = "#dfcf43"

bg-tab-bar     = "#2c3045"
bg-tab-current = "#0d0e1c"
bg-tab-other   = "#4a4f6a"

# Diffs
bg-added         = "#003a2f"
bg-added-faint   = "#002922"
bg-added-fringe  = "#23884f"
bg-added-refine  = "#035542"
fg-added         = "#a0e0a0"
fg-added-intense = "#80e080"

bg-changed         = "#363300"
bg-changed-faint   = "#2a1f00"
bg-changed-fringe  = "#8f7a30"
bg-changed-refine  = "#4a4a00"
fg-changed         = "#efef80"
fg-changed-intense = "#c0b05f"

bg-removed         = "#4f1127"
bg-removed-faint   = "#380a19"
bg-removed-fringe  = "#b81a26"
bg-removed-refine  = "#781a3a"
fg-removed         = "#ffbfbf"
fg-removed-intense = "#ff9095"

bg-diff-context = "#1a1f30"

# Uncommon accent backgrounds
bg-lavender = "#38325c"
bg-ochre    = "#442c2f"
bg-sage     = "#0f3d30"

# Paren match
bg-paren-expression = "#453040"
bg-paren-match      = "#5f789f"
