# Author: Alexis Mousset <contact@amousset.me>
# modus_operandi.toml variant
# Version 4.6.0

inherits = "modus_operandi"

"comment" = "red-faint"

"ui.cursor.primary" = { bg = "red-intense", fg = "bg-main" }

[palette]
# Basic values
bg-active   = "#c9b9b0"
bg-dim      = "#efe9dd"
bg-inactive = "#dfd5cf"
bg-main     = "#fbf7f0"
border      = "#9f9690"

# Common accent backgrounds
bg-blue-nuanced    = "#ebebff"
bg-cyan-nuanced    = "#e1f3fc"
bg-green-nuanced   = "#e0f5e0"
bg-magenta-nuanced = "#f6e7ff"
bg-red-nuanced     = "#ffe8f0"
bg-yellow-nuanced  = "#f9ead0"

# Special purpose
bg-completion = "#f0c1cf"
bg-hl-line    = "#f1d5d0"
bg-region     = "#c2bcb5"

bg-mode-line-active       = "#cab9b2"
bg-mode-line-inactive     = "#dfd9cf"
border-mode-line-active   = "#545454"
border-mode-line-inactive = "#a59a94"

bg-tab-bar     = "#e0d4ce"
bg-tab-current = "#fbf7f0"
bg-tab-other   = "#c8b8b2"

# Diffs
bg-added   = "#c3ebc1"
bg-removed = "#f4d0cf"

# Paren match
bg-paren-match = "#7fdfcf"
