# Author: Matous Dzivjak <matousdzivjak@gmail.com>
# Adapted from https://protesilaos.com/emacs/modus-themes, by Protesilaos Stavrou
# Source: https://github.com/protesilaos/modus-themes/blob/main/modus-vivendi-deuteranopia-theme.el
# Version 4.6.0

inherits = "modus_vivendi"

"comment"                   = "yellow-cooler"
"constant.character.escape" = "magenta"
"function"                  = "magenta"
"tag"                       = "magenta"

"ui.cursor"                = { bg = "blue-intense", fg = "bg-main" }
"ui.cursor.primary.normal" = { bg = "blue-intense", fg = "bg-main" }

"diagnostic.error"   = { underline = { color = "yellow-intense", style = "curl" } }
"diagnostic.hint"    = { underline = { color = "blue", style = "curl" } }
"diagnostic.info"    = { underline = { color = "cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "magenta-faint", style = "curl" } }

error   = "yellow-intense"
hint    = "blue"
info    = "cyan"
warning = "magenta-faint"

rainbow = [ "red", "yellow-intense", "green-intense", "cyan", "blue", "magenta-intense" ]

[palette]
# Basic values
bg-active   = "#535353"
bg-dim      = "#1e1e1e"
bg-inactive = "#303030"
bg-main     = "#000000"
border      = "#646464"
fg-alt      = "#c6daff"
fg-dim      = "#989898"
fg-main     = "#ffffff"

# Common accent foregrounds
blue            = "#2fafff"
blue-cooler     = "#00bcff"
blue-faint      = "#82b0ec"
blue-intense    = "#338fff"
blue-warmer     = "#79a8ff"
cyan            = "#00d3d0"
cyan-cooler     = "#6ae4b9"
cyan-faint      = "#9ac8e0"
cyan-intense    = "#00eff0"
cyan-warmer     = "#4ae2f0"
green           = "#44bc44"
green-cooler    = "#00c06f"
green-faint     = "#88ca9f"
green-intense   = "#44df44"
green-warmer    = "#70b900"
magenta         = "#feacd0"
magenta-cooler  = "#b6a0ff"
magenta-faint   = "#caa6df"
magenta-intense = "#ff66ff"
magenta-warmer  = "#f78fe7"
red             = "#ff5f59"
red-cooler      = "#ff7f86"
red-faint       = "#ff9580"
red-intense     = "#ff5f5f"
red-warmer      = "#ff6b55"
yellow          = "#cabf00"
yellow-cooler   = "#d8af7a"
yellow-faint    = "#d2b580"
yellow-intense  = "#efef00"
yellow-warmer   = "#ffa00f"

# Uncommon accent foregrounds
gold   = "#c0965b"
indigo = "#9099d9"
maroon = "#cf7fa7"
olive  = "#9cbd6f"
pink   = "#d09dc0"
rust   = "#db7b5f"
slate  = "#76afbf"

# Common accent backgrounds
bg-blue-intense    = "#1640b0"
bg-cyan-intense    = "#2266ae"
bg-green-intense   = "#2f822f"
bg-magenta-intense = "#7030af"
bg-red-intense     = "#9d1f1f"
bg-yellow-intense  = "#7a6100"

bg-blue-subtle    = "#242679"
bg-cyan-subtle    = "#004065"
bg-green-subtle   = "#00422a"
bg-magenta-subtle = "#552f5f"
bg-red-subtle     = "#620f2a"
bg-yellow-subtle  = "#4a4000"

bg-blue-nuanced    = "#12154a"
bg-cyan-nuanced    = "#042837"
bg-green-nuanced   = "#092f1f"
bg-magenta-nuanced = "#2f0c3f"
bg-red-nuanced     = "#3a0c14"
bg-yellow-nuanced  = "#381d0f"

# Uncommon accent backgrounds
bg-lavender = "#38325c"
bg-ochre    = "#442c2f"
bg-sage     = "#0f3d30"

# Special purpose
bg-completion      = "#2f447f"
bg-hl-line         = "#2f3849"
bg-hover           = "#45605e"
bg-hover-secondary = "#654a39"
bg-region          = "#5a5a5a"
fg-region          = "#ffffff"

bg-char-0 = "#0050af"
bg-char-1 = "#7f1f7f"
bg-char-2 = "#625a00"

bg-mode-line-active       = "#2a2a6a"
bg-mode-line-inactive     = "#2d2d2d"
border-mode-line-active   = "#8080a7"
border-mode-line-inactive = "#606060"
fg-mode-line-active       = "#f0f0f0"
fg-mode-line-inactive     = "#969696"

modeline-err     = "#e5bf00"
modeline-info    = "#abeadf"
modeline-warning = "#c0cf35"

bg-tab-bar     = "#313131"
bg-tab-current = "#000000"
bg-tab-other   = "#545454"

# Diffs
bg-added         = "#003066"
bg-added-faint   = "#001a4f"
bg-added-fringe  = "#006fff"
bg-added-refine  = "#0f4a77"
fg-added         = "#c4d5ff"
fg-added-intense = "#8080ff"

bg-changed         = "#2f123f"
bg-changed-faint   = "#1f022f"
bg-changed-fringe  = "#7f55a0"
bg-changed-refine  = "#3f325f"
fg-changed         = "#e3cfff"
fg-changed-intense = "#cf9fe2"

bg-removed         = "#3d3d00"
bg-removed-faint   = "#281f00"
bg-removed-fringe  = "#d0c03f"
bg-removed-refine  = "#555500"
fg-removed         = "#d4d48f"
fg-removed-intense = "#d0b05f"

bg-diff-context = "#1a1a1a"

# Paren match
bg-paren-expression = "#453040"
bg-paren-match      = "#2f7f9f"
