# Author : Maxwell Anderson <zaechus@pm.me>

inherits = "monokai"

"comment"                     = "comment"
"comment.block.documentation" = { fg = "comment", modifiers = [ "bold" ] }
"comment.line.documentation"  = { fg = "comment", modifiers = [ "bold" ] }
"constant.character.escape"   = { fg = "light-blue", modifiers = [ "italic" ] }
"function.macro"              = { fg = "#c4be89", modifiers = [ "italic" ] }
"keyword"                     = { fg = "keyword", modifiers = [ "bold" ] }
"keyword.control"             = { fg = "keyword", modifiers = [ "bold" ] }
"keyword.control.exception"   = { fg = "fn_declaration", modifiers = [ "bold" ] }
"keyword.directive"           = { fg = "fn_declaration", modifiers = [ "bold" ] }
"keyword.storage.modifier"    = { fg = "#fd971f", modifiers = [ "italic" ] }
"label"                       = "#e6db74"
"operator"                    = "keyword"
"punctuation.delimiter"       = "#8f8f8f"
"tag.builtin"                 = { fg = "#ae81ff", modifiers = [ "bold" ] }
"type"                        = "light-blue"
"variable.builtin"            = { fg = "#ae81ff", modifiers = [ "bold" ] }
"variable.parameter"          = "variable"

"diff.delta" = "#89807d"
"diff.minus" = "#960050"
"diff.plus"  = "text"

"ui.cursor.match"    = { bg = "#fd971f", fg = "#000000", modifiers = [ "bold" ] }
"ui.cursor.primary"  = { bg = "#f8f8f0", fg = "#000000" }
"ui.linenr"          = "#465457"
"ui.linenr.selected" = "#fd971f"
"ui.selection"       = { bg = "#403d3d" }

"ui.help"       = { bg = "#000000", fg = "light-blue" }
"ui.menu"       = { bg = "#000000", fg = "light-blue" }
"ui.popup"      = { bg = "#000000", fg = "light-blue" }
"ui.popup.info" = { bg = "#000000", fg = "light-blue" }
"ui.text.info"  = { bg = "#000000", fg = "light-blue" }

"error"   = { fg = "#ffffff", modifiers = [ "bold" ] }
"hint"    = { fg = "#ffffff", modifiers = [ "bold" ] }
"info"    = { fg = "#ffffff", modifiers = [ "bold" ] }
"warning" = { fg = "#ffffff", modifiers = [ "bold" ] }

[palette]
light-blue = "#66d9ef"

background = "#1b1d1e"

comment = "#7e8e91"
