# Monokai Soda port for Helix (https://helix-editor.com)
# Author : Jimmy Zelinskie <jimmy@zelinskie.com>

# Syntax

## Constants
"constant"                  = "white"
"constant.builtin"          = "pink"
"constant.character.escape" = "blue"
"constant.numeric"          = "purple"

## Diagnostics
"diagnostic"             = { modifiers = [ "underlined" ] }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "pink", style = "curl" } }
"diagnostic.info"        = { underline = { color = "white", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange", style = "curl" } }

## Diffs
"diff.delta"       = "orange"
"diff.delta.moved" = "orange"
"diff.minus"       = "pink"
"diff.plus"        = "green"

## Functions
"constructor"      = "blue"
"function"         = "green"
"function.builtin" = "pink"
"function.macro"   = "blue"

## Keywords
"keyword"           = "pink"
"keyword.directive" = "blue"

## Punctuation
"punctuation" = "gray"

## Strings
"string" = "yellow"

## Types
"type"         = "blue"
"type.builtin" = "pink"

## Variables
"variable"              = "white"
"variable.builtin"      = "pink"
"variable.other.member" = "white"
"variable.parameter"    = "softorange"

## Markup
"markup.bold"      = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading"   = "green"
"markup.italic"    = { fg = "orange", modifiers = [ "italic" ] }
"markup.link.text" = "yellow"
"markup.link.url"  = { fg = "orange", modifiers = [ "underlined" ] }
"markup.quote"     = "green"

## Misc
"attribute" = "blue"
"comment"   = { fg = "gray", modifiers = [ "italic" ] }
"error"     = "pink"
"hint"      = "white"
"info"      = "white"
"label"     = "yellow"
"module"    = "softorange"
"namespace" = "pink"
"operator"  = "pink"
"special"   = "softorange"
"warning"   = "orange"

# Editor UI

## Main
"ui.background" = { bg = "background" }
"ui.text"       = "white"
"ui.window"     = { bg = "darkgray" }

## Debug (TODO)

## Menus
"ui.help"          = { bg = "darkgray", fg = "white" }
"ui.menu"          = { bg = "darkgray", fg = "white" }
"ui.menu.selected" = { modifiers = [ "reversed" ] }
"ui.popup"         = { bg = "darkgray" }

## Gutter
"ui.linenr"          = "darkgray"
"ui.linenr.selected" = "orange"

## Cursor
"ui.cursor.match"   = { fg = "white", modifiers = [ "reversed" ] }
"ui.cursor.primary" = { fg = "white", modifiers = [ "reversed" ] }
"ui.selection"      = { bg = "darkgray" }

## Statusline
"ui.statusline"          = { bg = "darkgray" }
"ui.statusline.inactive" = { bg = "darkgray", fg = "white" }
"ui.statusline.insert"   = { bg = "green", fg = "white" }
"ui.statusline.normal"   = { bg = "blue", fg = "white" }
"ui.statusline.select"   = { bg = "purple", fg = "white" }

"ui.text.focus"         = { fg = "yellow", modifiers = [ "bold" ] }
"ui.virtual"            = "darkgray"
"ui.virtual.jump-label" = { fg = "softorange", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "darkgray" }

# Palette

[palette]
"background" = "#191919"
"black"      = "#222222"
"blue"       = "#66d9ef"
"darkgray"   = "#444444"
"gray"       = "#75715e"
"green"      = "#a6e22e"
"orange"     = "#fd971f"
"pink"       = "#f92a72"
"purple"     = "#AE81FF"
"softorange" = "#f59762"
"white"      = "#cfcfc2"
"yellow"     = "#E6DB74"
