# Author : WindSoilder<WindSoilder@outlook.com>
# The unofficial Monokai Pro theme, simply migrate from jetbrains monokai pro theme: https://github.com/subtheme-dev/monokai-pro
# Credit goes to the original creator: https://monokai.pro

"ui.linenr.selected"    = { bg = "base3" }
"ui.menu"               = { bg = "base3", fg = "base8" }
"ui.menu.selected"      = { bg = "yellow", fg = "base2" }
"ui.text.focus"         = { fg = "yellow", modifiers = [ "bold" ] }
"ui.virtual.jump-label" = { fg = "red", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "base1" }
"ui.virtual.whitespace" = "base5"

"hint" = "base8"
"info" = "base8"

# background color
"ui.background"          = { bg = "base2" }
"ui.statusline.inactive" = { bg = "base8x0c", fg = "base8" }

# status bars, panels, modals, autocompletion
"ui.help"       = { bg = "base3", fg = "base8" }
"ui.popup"      = { bg = "base3" }
"ui.statusline" = { bg = "base4", fg = "base8" }
"ui.window"     = { bg = "base3" }

# active line, highlighting
"ui.cursor.match" = { bg = "base4" }
"ui.cursorline"   = { bg = "base1" }
"ui.selection"    = { bg = "base4" }

# bufferline, inlay hints
"ui.bufferline"         = { bg = "base8x0c", fg = "base6" }
"ui.bufferline.active"  = { bg = "base4", fg = "base8" }
"ui.virtual.inlay-hint" = { fg = "base6" }

# comments, nord3 based lighter color
"comment"   = { fg = "base5", modifiers = [ "italic" ] }
"ui.linenr" = { fg = "base5" }

# cursor, variables, constants, attributes, fields
"attribute"         = "blue"
"constant"          = "orange"
"constant.builtin"  = "red"
"namespace"         = "base8"
"ui.cursor.primary" = { fg = "base7", modifiers = [ "reversed" ] }
"variable"          = "base8"
"variable.builtin"  = "red"

# base text, punctuation
"punctuation" = "base6"
"ui.text"     = { fg = "base8" }

# classes, types, primitives
"label"        = "base8"
"type"         = "green"
"type.builtin" = { fg = "red" }

# declaration, methods, routines
"constructor"      = "blue"
"function"         = "green"
"function.builtin" = { fg = "cyan" }
"function.macro"   = { fg = "blue" }

# operator, tags, units, punctuations
"operator"              = "red"
"variable.other.member" = "base8"

# keywords, special
"keyword"            = { fg = "red" }
"keyword.directive"  = "blue"
"variable.parameter" = "#f59762"

# error
"error" = "red"

# annotations, decorators
"module"  = "#f59762"
"special" = "#f59762"

# warnings, escape characters, regex
"constant.character.escape" = { fg = "base8" }
"warning"                   = "orange"

# strings
"string" = "yellow"

# integer, floating point
"constant.numeric" = "purple"

# vcs
"diff.delta" = "orange"
"diff.minus" = "red"
"diff.plus"  = "green"

# make diagnostic underlined, to distinguish with selection text.
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "base8", style = "curl" } }
"diagnostic.info"        = { underline = { color = "base8", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange", style = "curl" } }

# markup highlight, no need for `markup.raw` and `markup.list`, make them to be default
"markup.bold"          = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading"       = "green"
"markup.italic"        = { fg = "orange", modifiers = [ "italic" ] }
"markup.link.text"     = "yellow"
"markup.link.url"      = { fg = "orange", modifiers = [ "underlined" ] }
"markup.quote"         = "green"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

[palette]
# primary colors
"blue"   = "#7cd5f1"
"green"  = "#a2e57b"
"orange" = "#ffb270"
"purple" = "#baa0f8"
"red"    = "#ff6d7e"
"yellow" = "#ffed72"
# base colors
"base0" = "#161b1e"
"base1" = "#1d2528"
"base2" = "#273136"
"base3" = "#3a4449"
"base4" = "#545f62"
"base5" = "#6b7678"
"base6" = "#798384"
"base7" = "#b8c4c3"
"base8" = "#f2fffc"
# variants
"base8x0c" = "#303a3e"
