# Author: Shafkath Shuhan <shafkathshuhannyc@gmail.com>

"tag" = { fg = "tag" }

"module"    = { fg = "type" }
"namespace" = { fg = "type" }

"constructor"           = { fg = "fn_declaration" }
"type"                  = { fg = "type" }
"type.builtin"          = { fg = "#66D9EF" }
"type.enum.variant"     = { fg = "text" }
"variable.other.member" = { fg = "variable" }

"keyword"           = { fg = "keyword" }
"keyword.control"   = { fg = "keyword" }
"keyword.directive" = { fg = "keyword" }
"label"             = { fg = "keyword" }

"operator" = { fg = "text" }
"special"  = { fg = "keyword" }

"punctuation"           = { fg = "text" }
"punctuation.delimiter" = { fg = "text" }

"constant"           = { fg = "variable" }
"constant.builtin"   = { fg = "#ae81ff" }
"variable"           = { fg = "variable" }
"variable.builtin"   = { fg = "keyword" }
"variable.parameter" = { fg = "#fd971f" }

"attribute"        = { fg = "fn_declaration" }
"function"         = { fg = "fn_declaration" }
"function.builtin" = { fg = "fn_declaration" }
"function.macro"   = { fg = "keyword" }

"comment"               = { fg = "#88846F" }
"ui.virtual.jump-label" = { fg = "special", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "#24241e" }
"ui.virtual.whitespace" = "#88846F"

"constant.character"        = { fg = "#e6db74" }
"constant.character.escape" = { fg = "#ae81ff" }
"constant.numeric"          = { fg = "#ae81ff" }
"string"                    = { fg = "#e6db74" }
"string.regexp"             = { fg = "regex" }

# TODO
"markup.bold"          = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading"       = "blue"
"markup.italic"        = { fg = "magenta", modifiers = [ "italic" ] }
"markup.link.text"     = "red"
"markup.link.url"      = { fg = "yellow", modifiers = [ "underlined" ] }
"markup.list"          = "red"
"markup.quote"         = "cyan"
"markup.raw"           = "green"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = { fg = "#fd971f" }
"diff.minus" = { fg = "#f92672" }
"diff.plus"  = { fg = "#a6e22e" }

"ui.background" = { bg = "background", fg = "text" }

"ui.help"          = { bg = "widget", fg = "text" }
"ui.menu"          = { bg = "widget", fg = "text" }
"ui.menu.selected" = { bg = "#414339" }
"ui.popup"         = { bg = "widget", fg = "text" }
"ui.window"        = { bg = "widget" }

"ui.cursor"         = { fg = "cursor", modifiers = [ "reversed" ] }
"ui.cursor.match"   = { fg = "#888888", modifiers = [ "reversed" ] }
"ui.cursor.primary" = { fg = "cursor", modifiers = [ "reversed" ] }

"ui.selection"         = { bg = "#878b91" }
"ui.selection.primary" = { bg = "#575b61" }

"ui.linenr"          = { fg = "#90908a" }
"ui.linenr.selected" = { fg = "#c2c2bf" }

"ui.cursorline"          = { bg = "#24241e" }
"ui.statusline"          = { bg = "#414339", fg = "active_text" }
"ui.statusline.inactive" = { bg = "#75715e", fg = "active_text" }

# Malformed ANSI: grey2, bg3. See 'https://github.com/helix-editor/helix/issues/5709'
# "ui.bufferline" = { fg = "grey2", bg = "bg3" }
"ui.bufferline.active"  = { bg = "selection", fg = "active_text", modifiers = [ "bold" ] }
"ui.virtual.inlay-hint" = { fg = "#88846F" }

"ui.text"       = { fg = "text" }
"ui.text.focus" = { fg = "active_text" }

"error"   = { fg = "#f48771" }
"hint"    = { fg = "#eeeeb3" }
"info"    = { fg = "#75beff" }
"warning" = { fg = "#cca700" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "#f48771", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "#eeeeb3", style = "curl" } }
"diagnostic.info"        = { underline = { color = "#75beff", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "#cca700", style = "curl" } }

[palette]
fn_declaration = "#A6E22E"
keyword        = "#F92672"
regex          = "#CE9178"
special        = "#C586C0"
type           = "#A6E22E"
variable       = "#F8F8F2"

active_text     = "#ffffff"
background      = "#272822"
cursor          = "#a6a6a6"
inactive_cursor = "#878b91"
selection       = "#414339"
tag             = "#F92672"
text            = "#f8f8f2"
widget          = "#1e1f1c"
