# Author: Nick Saika <n@nesv.ca>
#
# This theme is a port of naysayer-theme.el:
#    https://github.com/nickav/naysayer-theme.el

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { bg = "error", fg = "text", modifiers = [ "bold" ] }
"diagnostic.hint"        = { bg = "cyan", modifiers = [ "bold" ] }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { bg = "warning", fg = "text", modifiers = [ "bold" ] }
"ui.background"          = { bg = "bg" }
"ui.bufferline"          = { bg = "bg", fg = "text" }
"ui.bufferline.active"   = { bg = "bg", fg = "text", modifiers = [ 'underlined' ] }
"ui.cursor"              = { bg = "#777777" }
"ui.cursor.match"        = { bg = "cyan" }
"ui.cursor.primary"      = { bg = "white" }
"ui.cursorline"          = { bg = "highlight-line" }
"ui.debug"               = { fg = "orange" }
"ui.gutter.selected"     = { bg = "highlight-line", modifiers = [ "bold" ] }
"ui.help"                = { bg = "bg", fg = "text" }
"ui.highlight"           = { bg = "highlight-line" }
"ui.highlight.frameline" = { bg = "#da8581" }
"ui.linenr"              = { bg = "bg", fg = "line-fg" }
"ui.linenr.selected"     = { bg = "highlight-line", fg = "line-fg" }
"ui.menu"                = { bg = "bg", fg = "text" }
"ui.menu.selected"       = { bg = "bg", fg = "text", modifiers = [ 'underlined' ] }
"ui.popup"               = { bg = "bg", fg = "text" }
"ui.selection"           = { bg = "selection" }
"ui.statusline"          = { bg = "text", fg = "bg" }
"ui.statusline.inactive" = { bg = "bg", fg = "text" }
"ui.text"                = "text"
"ui.virtual"             = "indent"
"ui.virtual.ruler"       = { bg = "line-fg" }
"ui.window"              = { bg = "bg" }

# Scopes: Syntax Highlighting.
"attribute"                = "text"
"comment"                  = "comments"
"constant"                 = "constants"
"constant.builtin"         = "builtin"
"constant.builtin.boolean" = "builtin"
"constant.character"       = "text"
"constant.numeric"         = "numbers"
"constructor"              = "functions"
"diff.delta"               = { fg = "blue" }
"diff.minus"               = { fg = "red" }
"diff.plus"                = { fg = "green" }
"function"                 = "functions"
"function.builtin"         = "builtin"
"function.macro"           = "macros"
"function.method"          = "methods"
"function.special"         = "macros"
"keyword"                  = "keywords"
"markup.bold"              = { modifiers = [ "bold" ] }
"markup.italic"            = { modifiers = [ "italic" ] }
"markup.strikethrough"     = { modifiers = [ "crossed_out" ] }
"punctuation"              = "punctuation"
"string"                   = "strings"
"tag.builtin"              = "builtin"
"type"                     = "text"
"type.builtin"             = "builtin"
"variable"                 = "variables"
"variable.builtin"         = "builtin"

[palette]
bg             = "#062329"
builtin        = "#ffffff"
comments       = "#44b340"
constants      = "#7ad0c6"
error          = "#ff0000"
functions      = "#ffffff"
highlight-line = "#0b3335"
indent         = "#aaaaaa"
keywords       = "#ffffff"
line-fg        = "#126367"
macros         = "#8cde94"
methods        = "#c1d1e3"
numbers        = "#7ad0c6"
punctuation    = "#8cde94"
selection      = "#0000ff"
strings        = "#2ec90c"
text           = "#d1b897"
variables      = "#c1d1e3"
warning        = "#ffaa00"
white          = "#ffffff"

blue    = "#66d9ef"
cyan    = "#a1efe4"
green   = "#a6e22e"
magenta = "#fd5ff0"
orange  = "#fd971f"
red     = "#f92672"
violet  = "#a381ff"
yellow  = "#e6db74"
