# Author : Joe Mckay joemckay3006@gmail.com
# Palette from https://github.com/haishanh/night-owl.vim

'error'   = { fg = 'red', modifiers = [ 'dim' ] }
'hint'    = { fg = 'paleblue', modifiers = [ 'dim' ] }
'info'    = { fg = 'blue', modifiers = [ 'dim' ] }
'warning' = { fg = 'peach', modifiers = [ 'dim' ] }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "paleblue", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "peach", style = "curl" } }

# UI
'ui.background'          = { bg = 'background', fg = 'foreground' }
'ui.cursor'              = { bg = 'blue', fg = 'background' }
'ui.cursor.match'        = { bg = 'selection', modifiers = [ 'underlined' ] }
'ui.cursor.primary'      = { bg = 'gold', fg = 'background' }
'ui.cursorline.primary'  = { bg = 'background2' }
'ui.gutter'              = { bg = 'grey2' }
'ui.help'                = { bg = 'background2', fg = 'gold' }
'ui.linenr'              = { bg = 'background2', fg = 'grey4' }
'ui.linenr.selected'     = { bg = 'background2', fg = 'greyE' }
'ui.menu'                = { bg = 'selection', fg = 'foreground' }
'ui.menu.selected'       = { bg = 'pink', fg = 'foreground' }
'ui.popup'               = { bg = 'background2', fg = 'foreground' }
'ui.popup.info'          = { bg = 'background2', fg = 'gold' }
'ui.selection'           = { bg = 'selection', modifiers = [ 'dim' ] }
'ui.statusline'          = { bg = 'background2', fg = 'greyE' }
'ui.statusline.inactive' = { bg = 'background2', fg = 'grey7' }
'ui.statusline.insert'   = { bg = 'peach' }
'ui.statusline.normal'   = { bg = 'slate' }
'ui.statusline.select'   = { bg = 'green' }
'ui.text'                = { fg = 'foreground' }
'ui.text.focus'          = { fg = 'foreground' }
'ui.text.info'           = { fg = 'foreground' }
'ui.virtual.ruler'       = { bg = 'grey4' }
'ui.virtual.whitespace'  = { fg = 'grey4' }
'ui.window'              = { fg = 'grey7' }

# SYNTAX
'attribute'                   = { fg = 'paleblue' }
'comment'                     = { fg = 'slate', modifiers = [ 'italic' ] }
'comment.block.documentation' = { fg = 'slate' }
'comment.line.documentation'  = { fg = 'slate' }
'constant'                    = { fg = 'foreground' }
'constant.builtin'            = { fg = 'paleblue' }
'constant.character.escape'   = { fg = 'peach' }
'constructor'                 = { fg = 'blue' }
'function'                    = { fg = 'blue' }
'function.macro'              = { fg = 'peach' }
'function.special'            = { fg = 'pink' }
'keyword'                     = { fg = 'pink' }
'keyword.control.exception'   = { fg = 'red' }
'keyword.control.import'      = { fg = 'green', modifiers = [ 'italic' ] }
'keyword.control.return'      = { fg = 'pink', modifiers = [ 'italic' ] }
'label'                       = { fg = 'foreground' }
'module'                      = { fg = 'greyE' }
'namespace'                   = { fg = 'peach' }
'operator'                    = { fg = 'pink' }
'punctuation'                 = { fg = 'foreground' }
'punctuation.special'         = { fg = 'pink' }
'special'                     = { fg = 'greyE' }
'string'                      = { fg = 'gold' }
'string.regexp'               = { fg = 'green' }
'string.special.url'          = { fg = 'gold', modifiers = [ 'underlined' ] }
'tag'                         = { fg = 'blue' }
'type'                        = { fg = 'green' }
'variable'                    = { fg = 'green' }
'variable.builtin'            = { fg = 'green', modifiers = [ 'italic' ] }

# MARKUP
'markup.bold'           = { fg = 'foreground', modifiers = [ 'bold' ] }
'markup.heading'        = { fg = 'blue', modifiers = [ 'bold' ] }
'markup.heading.1'      = { fg = 'blue', modifiers = [ 'bold' ] }
'markup.heading.2'      = { fg = 'paleblue', modifiers = [ 'bold' ] }
'markup.heading.3'      = { fg = 'green', modifiers = [ 'bold' ] }
'markup.heading.4'      = { fg = 'pink', modifiers = [ 'bold' ] }
'markup.heading.5'      = { fg = 'peach', modifiers = [ 'bold' ] }
'markup.heading.6'      = { fg = 'slate', modifiers = [ 'bold' ] }
'markup.heading.marker' = { fg = 'grey4', modifiers = [ 'dim' ] }
'markup.italic'         = { fg = 'foreground', modifiers = [ 'italic' ] }
'markup.link'           = { fg = 'pink', modifiers = [ 'underlined' ] }
'markup.link.url'       = { fg = 'slate', modifiers = [ 'underlined' ] }
'markup.list'           = { fg = 'pink' }
'markup.quote'          = { fg = 'green', modifiers = [ 'italic' ] }
'markup.raw'            = { bg = 'background2', fg = 'gold' }
'markup.strikethrough'  = { fg = 'foreground', modifiers = [ 'crossed_out' ] }

# DIFF
'diff.delta'       = { fg = 'blue' }
'diff.delta.moved' = { fg = 'blue', modifiers = [ 'italic' ] }
'diff.minus'       = { fg = 'red' }
'diff.plus'        = { fg = 'green' }

[palette]
background  = '#011627'
background2 = '#112630'
foreground  = '#d6deeb'
selection   = '#2d2c5d'

blue     = '#82aaff'
gold     = '#ecc48d'
green    = '#addb67'
paleblue = '#7fdbca'
peach    = '#f78c6c'
pink     = '#c792ea'
red      = '#ff5874'
slate    = '#637777'

# Greys are named after their value.
grey2 = '#222222'
grey4 = '#444444'
grey7 = '#777777'
greyE = '#eeeeee'
