# Author: Joseph Harrison-Lim <josephharrisonlim@gmail.com>

"attribute"                   = { fg = "#7060eb", modifiers = [ "bold" ] }
"comment"                     = { fg = "base03", modifiers = [ "italic" ] }
"comment.block.documentation" = { fg = "base06", modifiers = [ "italic" ] }
"comment.line.documentation"  = { fg = "base06", modifiers = [ "italic" ] }
"constant"                    = "base09"
"constant.character.escape"   = "base0C"
"constant.numeric"            = "#7060eb"
"constructor"                 = "base0D"
"function"                    = "base0D"
"keyword"                     = "base0E"
"keyword.control"             = { fg = "base0E", modifiers = [ "bold" ] }
"keyword.directive"           = "white"
"keyword.import"              = { fg = "#df769b" }
"keyword.operator"            = { fg = "base0E", modifiers = [ "italic" ] }
"label"                       = "base0E"
"namespace"                   = "base0E"
"operator"                    = "base05"
"special"                     = "base0D"
"string"                      = "base0B"
"type"                        = "base10"
"variable"                    = "base08"
"variable.other.member"       = "base08"

"ui.background"      = { bg = "base00" }
"ui.cursor"          = { fg = "base04", modifiers = [ "reversed" ] }
"ui.cursor.match"    = { fg = "base0A", modifiers = [ "underlined" ] }
"ui.cursor.primary"  = { fg = "base05", modifiers = [ "reversed" ] }
"ui.cursorline"      = { bg = "base01" }
"ui.help"            = { bg = "base01", fg = "base06" }
"ui.linenr"          = { bg = "base01", fg = "#715b63" }
"ui.linenr.selected" = { bg = "base01", fg = "base02", modifiers = [ "bold" ] }
"ui.menu"            = { bg = "base01", fg = "base05" }
"ui.menu.selected"   = { bg = "base01", fg = "base0B" }
"ui.popup"           = { bg = "base01" }
"ui.selection"       = { bg = "base02", fg = "base05" }
"ui.statusline"      = { bg = "base01", fg = "base02" }
"ui.text"            = "base05"
"ui.text.focus"      = "base05"
"ui.virtual"         = "base03"
"ui.virtual.ruler"   = { bg = "base01" }
"ui.window"          = { bg = "base01" }

"markup.bold"          = { fg = "base0A", modifiers = [ "bold" ] }
"markup.heading"       = "base0D"
"markup.italic"        = { fg = "base0E", modifiers = [ "italic" ] }
"markup.link.text"     = "base08"
"markup.link.url"      = { fg = "base09", modifiers = [ "underlined" ] }
"markup.list"          = "base08"
"markup.quote"         = "base0C"
"markup.raw"           = "base0B"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus"  = "base0B"

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "base08", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "base03", style = "curl" } }
"diagnostic.info"        = { underline = { color = "base0D", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "base09", style = "curl" } }

"debug"     = "base03"
"error"     = "base08"
"hint"      = "base03"
"info"      = "base0D"
"ui.gutter" = { bg = "base01" }
"warning"   = "base09"

[palette]
base00 = "#322a2d" # Default Background
base01 = "#2c2528" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#997582" # Selection Background
base03 = "#585858" # Comments, Invisibles, Line Highlighting
base04 = "#322a2d" # Dark Foreground (Used for status bars)
base05 = "#cbbec2" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)
base08 = "#e4b781" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#d5971a" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#df769b" # Classes, Markup Bold, Search Text Background
base0B = "#49e9a6" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#16b673" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#16a3b6" # Functions, Methods, Attribute IDs, Headings
base0E = "#ba8baf" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#d67e5c" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
base10 = "#b0b0ff" # Types
