# nyxvamp - obsidian variant
# author: zoedsoupe <zoey.spessanha@zeetech.io>

inherits = "nyxvamp-radiance"

# Override specific styles for obsidian variant
"function"         = { fg = "function_fg", modifiers = [ "bold" ] }
"function.builtin" = { fg = "function_builtin_fg", modifiers = [ "bold" ] }
"ui.match_paren"   = { bg = "match_paren_bg", fg = "match_paren_fg", modifiers = [ "bold" ] }

# Palette overrides
[palette]
# Very dark theme colors
background       = "#000A0F" # Very dark background
cursor_bg        = "#F28FAD" # Pink cursor
cursor_fg        = "#0E0E10"
cursorline       = "#1E1E20" # Slightly lighter background
foreground       = "#C0C0CE" # Slightly muted foreground
line_nr          = "#5E5A76" # Dark gray line numbers
line_nr_selected = "#C0C0CE" # Foreground color for selected line number
selection        = "#2E2E30" # Dark gray selection

# Status line colors
status_bg          = "#1E1E20"
status_fg          = "#C0C0CE"
status_inactive_bg = "#0E0E10"
status_inactive_fg = "#5E5A76"

# Menu colors
menu_bg        = "#0E0E10"
menu_fg        = "#C0C0CE"
menu_scroll_bg = "#0E0E10"
menu_scroll_fg = "#5E5A76"
menu_sel_bg    = "#F28FAD"
menu_sel_fg    = "#0E0E10"
popup_bg       = "#0E0E10"
popup_fg       = "#C0C0CE"

# UI virtual
virtual_ruler_bg = "#191921" # Slightly lighter than background, close to comment color

# Syntax highlighting
attribute_fg        = "#F5C2E7"
boolean_fg          = "#F28FAD"
comment_fg          = "#5E5A76" # Dark gray comments
constant_builtin_fg = "#F28FAD"
constant_fg         = "#F28FAD" # Pink constants
function_builtin_fg = "#7FAFD7"
function_fg         = "#7FAFD7" # Muted blue functions
keyword_control_fg  = "#F5C2E7"
keyword_fg          = "#F5C2E7" # Pink keywords
match_paren_bg      = "#0E0E10"
match_paren_fg      = "#F28FAD"
namespace_fg        = "#A090C0" # Muted purple namespaces
number_fg           = "#D8A080" # Muted peach numbers
operator_fg         = "#C0C0CE" # Foreground color for operators
punctuation_fg      = "#C0C0CE"
string_fg           = "#8FBF8F" # Muted green strings
string_special_fg   = "#F28FAD" # Pink special strings
symbol_fg           = "#F28FAD"
type_builtin_fg     = "#A0A0D0"
type_fg             = "#A0A0D0" # Muted lavender types
variable_builtin_fg = "#F28FAD"
variable_fg         = "#C0C0CE"

# Diagnostics
error_fg   = "#D78284" # Muted red errors
hint_fg    = "#7BB5A8" # Muted cyan hints
info_fg    = "#7A9CCC" # Muted blue info
warning_fg = "#D5B880" # Muted yellow warnings

# Diff colors
diff_add_fg    = "#86BA75" # Muted green additions
diff_change_fg = "#D5B880" # Muted yellow changes
diff_delete_fg = "#D78284" # Muted red deletions

# Markup colors
markup_bold_fg      = "#F5C2E7"
markup_heading_fg   = "#F5C2E7"
markup_italic_fg    = "#F5C2E7"
markup_link_text_fg = "#F5C2E7"
markup_link_url_fg  = "#7FAFD7"
markup_quote_fg     = "#5E5A76"
