# nyxvamp - radiance variant
# author: <zoey.spessanha@zeetech.io>

# UI Elements
"ui.background"                  = { bg = "background", fg = "foreground" }
"ui.cursor"                      = { bg = "cursor_bg", fg = "cursor_fg" }
"ui.cursorline.primary"          = { bg = "cursorline" }
"ui.help"                        = { bg = "menu_bg", fg = "menu_fg" }
"ui.highlight"                   = { bg = "menu_sel_bg", fg = "menu_sel_fg" }
"ui.linenr"                      = { fg = "line_nr" }
"ui.linenr.selected"             = { fg = "line_nr_selected", modifiers = [ "bold" ] }
"ui.match_paren"                 = { bg = "match_paren_bg", fg = "match_paren_fg", modifiers = [ "bold" ] }
"ui.menu"                        = { bg = "menu_bg", fg = "menu_fg" }
"ui.menu.scroll"                 = { bg = "menu_scroll_bg", fg = "menu_scroll_fg" }
"ui.menu.selected"               = { bg = "menu_sel_bg", fg = "menu_sel_fg" }
"ui.picker.header"               = { bg = "menu_bg", fg = "menu_fg" }
"ui.picker.header.column"        = { bg = "menu_bg", fg = "menu_fg" }
"ui.picker.header.column.active" = { bg = "menu_sel_bg", fg = "menu_sel_fg" }
"ui.popup"                       = { bg = "popup_bg", fg = "popup_fg" }
"ui.popup.info"                  = { bg = "menu_bg", fg = "menu_fg" }
"ui.selection"                   = { bg = "selection" }
"ui.selection.primary"           = { bg = "selection" }
"ui.statusline"                  = { bg = "status_bg", fg = "status_fg" }
"ui.statusline.inactive"         = { bg = "status_inactive_bg", fg = "status_inactive_fg" }
"ui.text"                        = { fg = "foreground" }
"ui.text.directory"              = { fg = "function_fg", modifiers = [ "bold" ] }
"ui.text.focus"                  = { bg = "menu_sel_bg", fg = "menu_sel_fg" }
"ui.text.inactive"               = { fg = "comment_fg" }
"ui.text.info"                   = { bg = "menu_bg", fg = "menu_fg" }
"ui.virtual"                     = { fg = "comment_fg" }
"ui.virtual.ruler"               = { bg = "virtual_ruler_bg" }
"ui.window"                      = { fg = "foreground" }

# Syntax Highlighting
"attribute"        = { fg = "attribute_fg" }
"boolean"          = { fg = "boolean_fg" }
"comment"          = { fg = "comment_fg", modifiers = [ "italic" ] }
"constant"         = { fg = "constant_fg" }
"constant.builtin" = { fg = "constant_builtin_fg", modifiers = [ "bold" ] }
"function"         = { fg = "function_fg", modifiers = [ "bold" ] }           # Added bold for better distinction
"function.builtin" = { fg = "function_builtin_fg", modifiers = [ "bold" ] }
"keyword"          = { fg = "keyword_fg", modifiers = [ "bold" ] }
"keyword.control"  = { fg = "keyword_control_fg", modifiers = [ "bold" ] }
"namespace"        = { fg = "namespace_fg" }
"number"           = { fg = "number_fg" }
"operator"         = { fg = "operator_fg" }
"punctuation"      = { fg = "punctuation_fg" }
"string"           = { fg = "string_fg" }
"string.special"   = { fg = "string_special_fg" }
"symbol"           = { fg = "symbol_fg", modifiers = [ "italic" ] }
"type"             = { fg = "type_fg", modifiers = [ "italic" ] }
"type.builtin"     = { fg = "type_builtin_fg", modifiers = [ "italic" ] }
"variable"         = { fg = "variable_fg" }
"variable.builtin" = { fg = "variable_builtin_fg", modifiers = [ "italic" ] }

# Diagnostics
"diagnostic"         = { fg = "error_fg" }
"diagnostic.error"   = { fg = "error_fg", modifiers = [ "bold" ] }
"diagnostic.hint"    = { fg = "hint_fg", modifiers = [ "bold" ] }
"diagnostic.info"    = { fg = "info_fg", modifiers = [ "bold" ] }
"diagnostic.warning" = { fg = "warning_fg", modifiers = [ "bold" ] }
"error"              = { fg = "error_fg" }
"hint"               = { fg = "hint_fg" }
"info"               = { fg = "info_fg" }
"warning"            = { fg = "warning_fg" }

# Diff
"diff.delta" = { fg = "diff_change_fg" }
"diff.minus" = { fg = "diff_delete_fg" }
"diff.plus"  = { fg = "diff_add_fg" }

# Markup
"markup.bold"      = { fg = "markup_bold_fg", modifiers = [ "bold" ] }
"markup.heading"   = { fg = "markup_heading_fg", modifiers = [ "bold" ] }
"markup.italic"    = { fg = "markup_italic_fg", modifiers = [ "italic" ] }
"markup.link.text" = { fg = "markup_link_text_fg" }
"markup.link.url"  = { fg = "markup_link_url_fg", modifiers = [ "underlined" ] }
"markup.quote"     = { fg = "markup_quote_fg", modifiers = [ "italic" ] }

# Palette
[palette]
background         = "#F7F7FF" # Off-white background (from your visual identity)
cursor_bg          = "#9655FF" # Deep purple cursor (from your visual identity)
cursor_fg          = "#F7F7FF" # Off-white cursor text
cursorline         = "#E8E8F0" # Slightly darker than background
foreground         = "#1E1E2E" # Deep navy foreground (from your visual identity)
line_nr            = "#5A5570" # Darker gray for line numbers
line_nr_selected   = "#1E1E2E" # Deep navy for selected line number
match_paren_bg     = "#E8D5FF" # Light purple matching selection
match_paren_fg     = "#1E1E2E" # Deep navy
menu_bg            = "#E8E8F0" # Light gray
menu_fg            = "#1E1E2E" # Deep navy
menu_scroll_bg     = "#E8E8F0" # Light gray
menu_scroll_fg     = "#5A5570" # Darker gray
menu_sel_bg        = "#E8D5FF" # Light purple selection
menu_sel_fg        = "#1E1E2E" # Dark navy text for better contrast
popup_bg           = "#E8E8F0" # Light gray
popup_fg           = "#1E1E2E" # Deep navy
selection          = "#E8D5FF" # Light purple selection that matches theme palette
status_bg          = "#E8E8F0" # Light gray
status_fg          = "#1E1E2E" # Deep navy
status_inactive_bg = "#F7F7FF" # Off-white
status_inactive_fg = "#5A5570" # Darker gray
virtual_ruler_bg   = "#EAEAF0" # Slightly lighter than comment color background

attribute_fg        = "#9655FF" # Deep purple attributes
boolean_fg          = "#9F1239" # Even darker pink booleans
comment_fg          = "#5A5570" # Darker gray comments for better contrast
constant_builtin_fg = "#9F1239" # Even darker pink built-in constants
constant_fg         = "#9F1239" # Even darker pink constants for maximum contrast
function_builtin_fg = "#005F87" # Dark blue built-in functions
function_fg         = "#005F87" # Dark blue functions (more distinguishable)
keyword_control_fg  = "#9655FF" # Deep purple control keywords
keyword_fg          = "#9655FF" # Deep purple keywords
namespace_fg        = "#9655FF" # Deep purple namespaces
number_fg           = "#C2410C" # Darker orange numbers for better contrast
operator_fg         = "#4A4560" # Darker purple-gray operators for better contrast
punctuation_fg      = "#1E1E2E" # Deep navy punctuation
string_fg           = "#B8860B" # Dark golden rod - much better contrast on light background
string_special_fg   = "#9F1239" # Even darker pink special strings
symbol_fg           = "#9F1239" # Even darker pink symbols (atoms) for maximum contrast
type_builtin_fg     = "#6B46C1" # Darker purple built-in types for better contrast
type_fg             = "#6B46C1" # Darker purple types for better contrast
variable_builtin_fg = "#9F1239" # Even darker pink built-in variables
variable_fg         = "#1E1E2E" # Deep navy variables

error_fg   = "#E78284" # Soft red errors
hint_fg    = "#8BD5CA" # Soft cyan hints
info_fg    = "#8CAAEE" # Soft blue info
warning_fg = "#E5C890" # Soft yellow warnings

diff_add_fg    = "#A6DA95" # Soft green additions
diff_change_fg = "#E5C890" # Soft yellow changes
diff_delete_fg = "#E78284" # Soft red deletions

markup_bold_fg      = "#1E1E2E" # Deep navy bold text
markup_heading_fg   = "#9655FF" # Deep purple headings
markup_italic_fg    = "#1E1E2E" # Deep navy italic text
markup_link_text_fg = "#9655FF" # Deep purple link text
markup_link_url_fg  = "#005F87" # Dark blue links
markup_quote_fg     = "#5A5570" # Darker gray quotes
