# nyxvamp: veil variant
# author: zoedsoupe <zoey.spessanha@zeetech.io>

inherits = "nyxvamp-radiance"

# Override specific styles for veil variant
"function"         = { fg = "function_fg", modifiers = [ "bold" ] }
"function.builtin" = { fg = "function_builtin_fg", modifiers = [ "bold" ] }
"ui.match_paren"   = { bg = "match_paren_bg", fg = "match_paren_fg", modifiers = [ "bold" ] }

# Palette overrides
[palette]
# Dark theme colors - only override what's different from the base theme
background       = "#1E1E2E" # Dark purple background
cursor_bg        = "#F5C2E7" # Soft pink cursor
cursor_fg        = "#1E1E2E"
cursorline       = "#2E2E3E" # Slightly lighter background
foreground       = "#D9E0EE" # Light lavender foreground
line_nr          = "#6E6A86" # Medium gray for line numbers
line_nr_selected = "#D9E0EE" # Foreground color for selected line number
selection        = "#494D64" # Grayish selection

# Status line colors
status_bg          = "#302D41"
status_fg          = "#D9E0EE"
status_inactive_bg = "#1E1E2E"
status_inactive_fg = "#6E6A86"

# Menu colors
menu_bg        = "#1E1E2E"
menu_fg        = "#D9E0EE"
menu_scroll_bg = "#1E1E2E"
menu_scroll_fg = "#6E6A86"
menu_sel_bg    = "#F5C2E7"
menu_sel_fg    = "#1E1E2E"
popup_bg       = "#1E1E2E"
popup_fg       = "#D9E0EE"

# UI virtual
virtual_ruler_bg = "#2A2A3C" # Slightly lighter than background, close to comment color

# Syntax highlighting
attribute_fg        = "#F5C2E7" # Pink attributes
boolean_fg          = "#F28FAD" # Pink booleans
comment_fg          = "#6E6A86" # Gray comments
constant_builtin_fg = "#F28FAD" # Pink built-in constants
constant_fg         = "#F28FAD" # Pink constants
function_builtin_fg = "#96CDFB" # Blue built-in functions
function_fg         = "#96CDFB" # Blue functions
keyword_control_fg  = "#F5C2E7" # Pink control keywords
keyword_fg          = "#F5C2E7" # Pink keywords
match_paren_bg      = "#1E1E2E"
match_paren_fg      = "#F28FAD"
namespace_fg        = "#DDB6F2" # Purple namespaces
number_fg           = "#F8BD96" # Peach numbers
operator_fg         = "#D9E0EE" # Foreground color for operators
punctuation_fg      = "#D9E0EE" # Foreground color for punctuation
string_fg           = "#ABE9B3" # Green strings
string_special_fg   = "#F28FAD" # Pink special strings
symbol_fg           = "#F28FAD" # Pink symbols (e.g., Elixir atoms)
type_builtin_fg     = "#C9CBFF" # Lavender built-in types
type_fg             = "#C9CBFF" # Lavender types
variable_builtin_fg = "#F28FAD" # Pink built-in variables
variable_fg         = "#D9E0EE" # Foreground color for variables

# Diagnostics
error_fg   = "#E78284" # Red errors
hint_fg    = "#8BD5CA" # Cyan hints
info_fg    = "#8CAAEE" # Blue info
warning_fg = "#E5C890" # Yellow warnings

# Diff colors
diff_add_fg    = "#A6DA95" # Green additions
diff_change_fg = "#E5C890" # Yellow changes
diff_delete_fg = "#E78284" # Red deletions

# Markup colors
markup_bold_fg      = "#F5C2E7" # Pink bold text
markup_heading_fg   = "#F5C2E7" # Pink headings
markup_italic_fg    = "#F5C2E7" # Pink italic text
markup_link_text_fg = "#F5C2E7" # Pink link text
markup_link_url_fg  = "#96CDFB" # Blue links
markup_quote_fg     = "#6E6A86" # Gray quotes
