# Author : Gokul Soumya <gokulps15@gmail.com>

"attribute"                 = { fg = "yellow" }
"comment"                   = { fg = "light-gray", modifiers = [ "italic" ] }
"constant"                  = { fg = "cyan" }
"constant.builtin"          = { fg = "gold" }
"constant.character.escape" = { fg = "gold" }
"constant.numeric"          = { fg = "gold" }
"constructor"               = { fg = "blue" }
"function"                  = { fg = "blue" }
"function.builtin"          = { fg = "blue" }
"function.macro"            = { fg = "purple" }
"keyword"                   = { fg = "red" }
"keyword.control"           = { fg = "purple" }
"keyword.control.import"    = { fg = "red" }
"keyword.directive"         = { fg = "purple" }
"keyword.operator"          = { fg = "purple" }
"keyword.storage"           = { fg = "purple" }
"label"                     = { fg = "purple" }
"namespace"                 = { fg = "blue" }
"operator"                  = { fg = "purple" }
"special"                   = { fg = "blue" }
"string"                    = { fg = "green" }
"tag"                       = { fg = "red" }
"type"                      = { fg = "yellow" }
# "variable" = { fg = "blue" }
"variable.builtin"      = { fg = "blue" }
"variable.other.member" = { fg = "red" }
"variable.parameter"    = { fg = "red" }

"markup.bold"          = { fg = "gold", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "red" }
"markup.italic"        = { fg = "purple", modifiers = [ "italic" ] }
"markup.link.text"     = { fg = "purple" }
"markup.link.url"      = { fg = "cyan", modifiers = [ "underlined" ] }
"markup.list"          = { fg = "red" }
"markup.quote"         = { fg = "yellow" }
"markup.raw.inline"    = { fg = "green" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "gold"
"diff.minus" = "red"
"diff.plus"  = "green"

"diagnostic.deprecated"        = { modifiers = [ "crossed_out" ] }
"diagnostic.error".underline   = { color = "red", style = "curl" }
"diagnostic.hint".underline    = { color = "green", style = "curl" }
"diagnostic.info".underline    = { color = "blue", style = "curl" }
"diagnostic.unnecessary"       = { modifiers = [ "dim" ] }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }
"error"                        = { fg = "red", modifiers = [ "bold" ] }
"hint"                         = { fg = "green", modifiers = [ "bold" ] }
"info"                         = { fg = "blue", modifiers = [ "bold" ] }
"warning"                      = { fg = "yellow", modifiers = [ "bold" ] }

"ui.background"           = { bg = "black" }
"ui.virtual"              = { fg = "faint-gray" }
"ui.virtual.indent-guide" = { fg = "faint-gray" }
"ui.virtual.inlay-hint"   = { fg = "light-gray" }
"ui.virtual.jump-label"   = { fg = "light-gray", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "gray" }
"ui.virtual.whitespace"   = { fg = "light-gray" }

"ui.cursor"         = { fg = "white", modifiers = [ "reversed" ] }
"ui.cursor.match"   = { fg = "blue", modifiers = [ "underlined" ] }
"ui.cursor.primary" = { fg = "white", modifiers = [ "reversed" ] }

"ui.cursorline.primary" = { bg = "light-black" }
"ui.selection"          = { bg = "faint-gray" }
"ui.selection.primary"  = { bg = "gray" }

"ui.highlight"           = { bg = "gray" }
"ui.highlight.frameline" = { bg = "#97202a" }

"ui.linenr"          = { fg = "linenr" }
"ui.linenr.selected" = { fg = "white" }

"ui.statusline"          = { bg = "light-black", fg = "white" }
"ui.statusline.inactive" = { bg = "light-black", fg = "light-gray" }
"ui.statusline.insert"   = { bg = "green", fg = "light-black", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "blue", fg = "light-black", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "purple", fg = "light-black", modifiers = [ "bold" ] }

"ui.bufferline"            = { bg = "light-black", fg = "light-gray" }
"ui.bufferline.active"     = { bg = "blue", fg = "light-black", underline = { color = "light-black", style = "line" } }
"ui.bufferline.background" = { bg = "light-black" }

"ui.text"           = { fg = "white" }
"ui.text.directory" = { fg = "blue" }
"ui.text.focus"     = { bg = "light-black", fg = "white", modifiers = [ "bold" ] }

"ui.help"          = { bg = "gray", fg = "white" }
"ui.menu"          = { bg = "gray", fg = "white" }
"ui.menu.scroll"   = { bg = "light-gray", fg = "white" }
"ui.menu.selected" = { bg = "blue", fg = "black" }
"ui.popup"         = { bg = "gray" }
"ui.window"        = { fg = "gray" }

"ui.debug" = { fg = "red" }

[palette]

black       = "#282C34"
blue        = "#61AFEF"
cyan        = "#56B6C2"
faint-gray  = "#3B4048"
gold        = "#D19A66"
gray        = "#3E4452"
green       = "#98C379"
light-black = "#2C323C"
light-gray  = "#5C6370"
linenr      = "#4B5263"
purple      = "#C678DD"
red         = "#E06C75"
white       = "#ABB2BF"
yellow      = "#E5C07B"
