# Author : nuid32 <lvkuzvesov@proton.me>

"attribute"                 = { fg = "yellow" }
"comment"                   = { fg = "light-gray", modifiers = [ "italic" ] }
"constant"                  = { fg = "gold" }
"constant.builtin"          = { fg = "gold" }
"constant.character.escape" = { fg = "gold" }
"constant.numeric"          = { fg = "gold" }
"constructor"               = { fg = "blue" }
"function"                  = { fg = "white" }
"function.builtin"          = { fg = "blue" }
"function.macro"            = { fg = "purple" }
"keyword"                   = { fg = "purple" }
"keyword.control"           = { fg = "purple" }
"keyword.control.import"    = { fg = "purple" }
"keyword.directive"         = { fg = "purple" }
"keyword.operator"          = { fg = "white" }
"label"                     = { fg = "purple" }
"namespace"                 = { fg = "purple" }
"operator"                  = { fg = "white" }
"special"                   = { fg = "blue" }
"string"                    = { fg = "green" }
"tag"                       = { fg = "purple" }
"type"                      = { fg = "yellow" }
"variable"                  = { fg = "white" }
"variable.builtin"          = { fg = "red" }
"variable.other.member"     = { fg = "blue" }
"variable.parameter"        = { fg = "red" }

"markup.bold"          = { fg = "gold", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "red" }
"markup.italic"        = { fg = "purple", modifiers = [ "italic" ] }
"markup.link.label"    = { fg = "white" }
"markup.link.text"     = { fg = "white" }
"markup.link.url"      = { fg = "blue", modifiers = [ "underlined" ] }
"markup.list"          = { fg = "red" }
"markup.quote"         = { fg = "yellow" }
"markup.raw.block"     = { fg = "white" }
"markup.raw.inline"    = { fg = "green" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "gold"
"diff.minus" = "red"
"diff.plus"  = "green"

"diagnostic.deprecated"        = { modifiers = [ "crossed_out" ] }
"diagnostic.error".underline   = { color = "red", style = "curl" }
"diagnostic.hint".underline    = { color = "green", style = "curl" }
"diagnostic.info".underline    = { color = "blue", style = "curl" }
"diagnostic.unnecessary"       = { modifiers = [ "dim" ] }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }

"error"   = { fg = "red", modifiers = [ "bold" ] }
"hint"    = { fg = "green", modifiers = [ "bold" ] }
"info"    = { fg = "blue", modifiers = [ "bold" ] }
"warning" = { fg = "yellow", modifiers = [ "bold" ] }

"ui.background"           = { bg = "black" }
"ui.virtual"              = { fg = "faint-gray" }
"ui.virtual.indent-guide" = { fg = "faint-gray" }
"ui.virtual.inlay-hint"   = { fg = "light-gray" }
"ui.virtual.jump-label"   = { fg = "gold", modifiers = [ "bold", "underlined" ] }
"ui.virtual.ruler"        = { bg = "gray" }
"ui.virtual.whitespace"   = { fg = "light-gray" }

"ui.cursor"         = { fg = "white", modifiers = [ "reversed" ] }
"ui.cursor.match"   = { fg = "blue", modifiers = [ "underlined" ] }
"ui.cursor.primary" = { fg = "white", modifiers = [ "reversed" ] }

"ui.cursorline.primary" = { bg = "dark-black" }
"ui.selection"          = { bg = "black", modifiers = [ "reversed" ] }
"ui.selection.primary"  = { bg = "gray" }

"ui.linenr"          = { fg = "linenr" }
"ui.linenr.selected" = { fg = "white" }

"ui.statusline"          = { bg = "light-black", fg = "white" }
"ui.statusline.inactive" = { bg = "light-black", fg = "light-gray" }
"ui.statusline.insert"   = { bg = "green", fg = "light-black", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "purple", fg = "light-black", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "cyan", fg = "light-black", modifiers = [ "bold" ] }

"ui.bufferline"            = { bg = "light-black", fg = "light-gray" }
"ui.bufferline.active"     = { bg = "blue", fg = "light-black", underline = { color = "light-black", style = "line" } }
"ui.bufferline.background" = { bg = "light-black" }

"ui.text"           = { fg = "white" }
"ui.text.directory" = { fg = "blue" }
"ui.text.focus"     = { bg = "light-black", fg = "white", modifiers = [ "bold" ] }

"ui.debug"               = { fg = "red" }
"ui.help"                = { bg = "gray", fg = "white" }
"ui.highlight.frameline" = { bg = "#97202a" }
"ui.menu"                = { bg = "gray", fg = "white" }
"ui.menu.scroll"         = { bg = "light-gray", fg = "white" }
"ui.menu.selected"       = { bg = "blue", fg = "black" }
"ui.popup"               = { bg = "gray" }
"ui.window"              = { fg = "gray" }

[palette]

black       = "#16181A"
blue        = "#519FDF"
cyan        = "#46A6B2"
dark-black  = "#12100E"
faint-gray  = "#ABB2BF"
gold        = "#D19A66"
gray        = "#252D30"
green       = "#7DA869"
light-black = "#2C323C"
light-gray  = "#636C6E"
linenr      = "#282C34"
purple      = "#B668CD"
red         = "#D05C65"
white       = "#ABB2BF"
yellow      = "#D5B06B"
