# Author : erasin<erasinoo@gmail.com>

"attribute"   = { fg = "yellow" }
"constructor" = { fg = "blue" }
"label"       = { fg = "cyan" }
"module"      = { fg = "blue" }
"namespace"   = { fg = "blue" }
"operator"    = { fg = "red" }
"property"    = { fg = "purple" }
"special"     = { fg = "deep-purple" }
"tag"         = { fg = "cyan" }

"type"              = { fg = "gold" }
"type.builtin"      = { fg = "yellow" }
"type.enum"         = { fg = "cyan" }
"type.enum.variant" = { fg = "cyan" }

"constant"                  = { fg = "cyan", modifiers = [ "bold" ] }
"constant.builtin"          = { fg = "deep-purple" }
"constant.builtin.boolean"  = { fg = "purple", modifiers = [ "bold" ] }
"constant.character"        = { fg = "green" }
"constant.character.escape" = { fg = "brown", modifiers = [ "bold" ] }
"constant.numeric"          = { fg = "brown", modifiers = [ "bold" ] }
"constant.numeric.float"    = { fg = "brown", modifiers = [ "bold" ] }
"constant.numeric.integer"  = { fg = "brown", modifiers = [ "bold" ] }

"string"                = { fg = "green" }
"string.regexp"         = { fg = "purple" }
"string.special"        = { fg = "green" }
"string.special.path"   = { fg = "blue" }
"string.special.symbol" = { fg = "pink" }
"string.special.url"    = { fg = "light-blue" }

"comment"                     = { fg = "grey", modifiers = [ "italic" ] }
"comment.block"               = { fg = "grey", modifiers = [ "italic" ] }
"comment.block.documentation" = { fg = "grey", modifiers = [ "italic" ] }
"comment.line"                = { fg = "grey", modifiers = [ "italic" ] }
"comment.line.documentation"  = { fg = "grey", modifiers = [ "italic" ] }

# "variable" = { fg = "black" }
"variable.builtin"      = { fg = "light-blue" }
"variable.other"        = { fg = "pink" }
"variable.other.member" = { fg = "pink" }
"variable.parameter"    = { fg = "red" }

"punctuation"           = { fg = "black" }
"punctuation.bracket"   = { fg = "brown" }
"punctuation.delimiter" = { fg = "purple" }
"punctuation.special"   = { fg = "brown" }

"keyword"                     = { fg = "purple" }
"keyword.control"             = { fg = "purple" }
"keyword.control.conditional" = { fg = "red", modifiers = [ "bold" ] }
"keyword.control.exception"   = { fg = "purple" }
"keyword.control.import"      = { fg = "red" }
"keyword.control.repeat"      = { fg = "pink", modifiers = [ "bold" ] }
"keyword.control.return"      = { fg = "deep-purple", modifiers = [ "bold" ] }
"keyword.directive"           = { fg = "deep-purple" }
"keyword.function"            = { fg = "purple" }
"keyword.operator"            = { fg = "red" }
"keyword.storage"             = { fg = "purple" }
"keyword.storage.modifier"    = { fg = "purple", modifiers = [ "bold" ] }
"keyword.storage.type"        = { fg = "purple" }

"function"         = { fg = "blue" }
"function.builtin" = { fg = "cyan" }
"function.macro"   = { fg = "pink", modifiers = [ "bold" ] }
"function.method"  = { fg = "light-blue" }
"function.special" = { fg = "cyan" }

"markup.bold"            = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading"         = { fg = "red" }
"markup.heading.1"       = { fg = "red", modifiers = [ "bold" ] }
"markup.heading.2"       = { fg = "gold", modifiers = [ "bold" ], underline = { style = "line" } }
"markup.heading.3"       = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading.4"       = { fg = "green", modifiers = [ "bold" ] }
"markup.heading.5"       = { fg = "blue", modifiers = [ "bold" ] }
"markup.heading.6"       = { fg = "purple", modifiers = [ "bold" ] }
"markup.heading.marker"  = { fg = "red" }
"markup.italic"          = { fg = "purple", modifiers = [ "italic" ] }
"markup.link"            = { fg = "light-blue" }
"markup.link.text"       = { fg = "light-blue" }
"markup.link.url"        = { fg = "cyan", modifiers = [ "underlined" ] }
"markup.list"            = { fg = "light-blue" }
"markup.list.checked"    = { fg = "green" }
"markup.list.numbered"   = { fg = "light-blue" }
"markup.list.unchecked"  = { fg = "blue" }
"markup.list.unnumbered" = { fg = "light-blue" }
"markup.quote"           = { fg = "grey" }
"markup.raw"             = { fg = "brown" }
"markup.raw.block"       = { fg = "brown" }
"markup.raw.inline"      = { fg = "green" }
"markup.strikethrough"   = { fg = "red", modifiers = [ "crossed_out" ] }

"diff"                = { fg = "red" }
"diff.delta"          = { fg = "cyan" }
"diff.delta.conflict" = { fg = "blue" }
"diff.delta.moved"    = { fg = "cyan" }
"diff.minus"          = { fg = "red" }
"diff.plus"           = { fg = "green" }

"ui.background"           = { bg = "white" }
"ui.background.separator" = { bg = "white" }

"ui.cursor"                = { bg = "grey", fg = "white" }
"ui.cursor.insert"         = { bg = "grey", fg = "white" }
"ui.cursor.match"          = { bg = "grey-300", modifiers = [ "bold" ] }
"ui.cursor.normal"         = { bg = "grey", fg = "white" }
"ui.cursor.primary"        = { bg = "black", fg = "white" }
"ui.cursor.primary.insert" = { bg = "black", fg = "red" }
"ui.cursor.primary.normal" = { bg = "black", fg = "white" }
"ui.cursor.primary.select" = { bg = "black", fg = "white" }
"ui.cursor.select"         = { bg = "grey", fg = "white" }

"ui.gutter"          = { fg = "grey-500" }
"ui.gutter.selected" = { fg = "black" }

"ui.linenr"          = { fg = "grey-500" }
"ui.linenr.selected" = { fg = "black", modifiers = [ "bold" ] }

"ui.statusline"          = { bg = "grey-300", fg = "black" }
"ui.statusline.inactive" = { bg = "grey-200", fg = "grey" }
"ui.statusline.insert"   = { bg = "green", fg = "grey-300" }
"ui.statusline.normal"   = { bg = "light-blue", fg = "grey-300" }
"ui.statusline.select"   = { bg = "purple", fg = "grey-300" }

"ui.help"       = { bg = "grey-200", fg = "black" }
"ui.popup"      = { bg = "grey-200", fg = "black" }
"ui.popup.info" = { bg = "grey-200", fg = "black" }
"ui.window"     = { bg = "grey-100", fg = "grey-500" }

"ui.text"           = { fg = "black" }
"ui.text.directory" = { fg = "blue", underline = { style = "line" } }
"ui.text.focus"     = { bg = "grey-300", fg = "red", modifiers = [ "bold" ] }
"ui.text.inactive"  = { fg = "grey" }
"ui.text.info"      = { fg = "black" }

"ui.virtual"                      = { fg = "grey-500" }
"ui.virtual.indent-guide"         = { fg = "grey-500" }
"ui.virtual.inlay-hint"           = { fg = "grey-500" }
"ui.virtual.inlay-hint.parameter" = { fg = "grey-500", modifiers = [ "italic" ] }
"ui.virtual.inlay-hint.type"      = { fg = "grey-500" }
"ui.virtual.jump-label"           = { bg = "grey-200", fg = "black", modifiers = [ "bold" ] }
"ui.virtual.ruler"                = { bg = "grey-200" }
"ui.virtual.whitespace"           = { fg = "grey-400" }
"ui.virtual.wrap"                 = { fg = "grey-500" }

"ui.menu"          = { bg = "grey-300", fg = "black" }
"ui.menu.scroll"   = { bg = "white", fg = "light-blue" }
"ui.menu.selected" = { bg = "light-blue", fg = "white" }

"ui.selection"         = { bg = "grey-300", modifiers = [ "dim" ] }
"ui.selection.primary" = { bg = "grey-300" }

"ui.cursorline.primary"   = { bg = "grey-100", fg = "white" }
"ui.cursorline.secondary" = { bg = "grey-200", fg = "white" }

"ui.cursorcolumn.primary"   = { bg = "grey-100", fg = "white" }
"ui.cursorcolumn.secondary" = { bg = "grey-200", fg = "white" }

"ui.highlight" = { bg = "grey-300" }

"ui.picker.header"               = { fg = "purple" }
"ui.picker.header.column.active" = { fg = "blue" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "green", style = "dashed" } }
"diagnostic.info"        = { underline = { color = "blue", style = "dotted" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }

"error"   = { fg = "red", modifiers = [ "bold" ] }
"hint"    = { fg = "green", modifiers = [ "bold" ] }
"info"    = { fg = "blue", modifiers = [ "bold" ] }
"warning" = { fg = "yellow", modifiers = [ "bold" ] }

"tabstop" = { bg = "grey-300", modifiers = [ "italic" ] }

[palette]
black       = "#282C34"
blue        = "#0061FF"
brown       = "#795548"
cyan        = "#0086C1"
deep-purple = "#651FFF"
gold        = "#D35400"
green       = "#24A443"
grey        = "#5C6370"
grey-100    = "#F2F2F2"
grey-200    = "#EEEEEE"
grey-300    = "#E0E0E0"
grey-400    = "#BDBDBD"
grey-500    = "#9E9E9E"
light-blue  = "#0091EA"
pink        = "#C2185B"
purple      = "#B500A9"
red         = "#D50000"
white       = "#FAFAFA"
yellow      = "#FF6F00"
