# Palette based on https://github.com/NLKNguyen/papercolor-theme
# Author: Soc Virnyl Estela <socvirnyl.estela@gmail.com>

inherits = "papercolor-light"

[palette]
background = "#1c1c1c"
foreground = "#d0d0d0"

bright0  = "#585858" # color08 "Nontext"
bright1  = "#5faf5f" # color09 "Red"
bright2  = "#afd700" # color10 "Pink"
bright3  = "#af87d7" # color11 "Purple"
bright4  = "#ffaf00" # color12 "Accent"
bright5  = "#ff5faf" # color13 "Orange"
bright6  = "#00afaf" # color14 "Blue"
bright7  = "#5f8787" # color15 "Highlight"
regular0 = "#1c1c1c" # color00 "Background"
regular1 = "#af005f" # color01 "Negative"
regular2 = "#5faf00" # color02 "Positive"
regular3 = "#d7af5f" # color03 "Olive"
regular4 = "#5fafd7" # color04 "Neutral" / Aqua
regular5 = "#808080" # color05 "Comment"
regular6 = "#d7875f" # color06 "Navy"
regular7 = "#d0d0d0" # color07 "Foreground"

selection_bg           = "#8787af"
selection_fg           = "#000000"
selection_secondary_bg = "#707097"
selection_secondary_fg = "#333333"
special                = "#3e999f"

cursorcolumn_bg           = "#303030"
cursorcolumn_secondary_bg = "#2a2a2a"
cursorline_bg             = "#303030"
cursorline_secondary_bg   = "#2a2a2a"
cursorlinenr_fg           = "#ffff00"
diffadd_bg                = "#005f00"
diffadd_fg                = "#87d700"
diffchange_bg             = "#005f5f"
diffdelete_bg             = "#5f0000"
diffdelete_fg             = "#af005f"
error_bg                  = "#5f0000"
error_fg                  = "#af005f"
linenumber_fg             = "#585858"
matchparen_bg             = "#4e4e4e"
matchparen_fg             = "#c6c6c6"
popupmenu_bg              = "#303030"
popupmenu_fg              = "#c6c6c6"
statusline_active_bg      = "#5f8787"
statusline_active_fg      = "#1c1c1c"
statusline_inactive_bg    = "#3a3a3a"
statusline_inactive_fg    = "#bcbcbc"
todo_fg                   = "#ff8700"
vertsplit_fg              = "#5f8787"
wildmenu_bg               = "#afd700"
wildmenu_fg               = "#1c1c1c"

# 16 bit ANSI color names
black         = "#1c1c1c"
blue          = "#5fafd7"
cyan          = "#d7875f"
green         = "#5faf00"
light-black   = "#585858"
light-blue    = "#ffaf00"
light-cyan    = "#00afaf"
light-green   = "#afd700"
light-magenta = "#ff5faf"
light-red     = "#5faf5f"
light-white   = "#5f8787"
light-yellow  = "#af87d7"
magenta       = "#808080"
red           = "#af005f"
white         = "#d0d0d0"
yellow        = "#d7af5f"
