# Author : geonove <andre.novellini@gmail.com>
# License : Vim License

"attribute"                   = "yellow"
"comment"                     = "light-green"
"comment.block"               = "red"
"comment.block.documentation" = "red"
"comment.line"                = "light-green"
"comment.line.documentation"  = "light-green"
"constant"                    = "white"
"constant.builtin"            = "red"
"constant.character.escape"   = "light-cyan"
"constant.numeric"            = "red"
"string"                      = "red"
"type"                        = "green"
"type.builtin"                = "cyan"
"ui.cursor"                   = { fg = "light-gray", modifiers = [ "reversed" ] }
"ui.cursor.match"             = { fg = "light-gray", modifiers = [ "reversed" ] }
"ui.cursor.primary"           = { fg = "light-gray", modifiers = [ "reversed" ] }
"ui.help"                     = { bg = "black", fg = "white" }
"ui.linenr"                   = "yellow"
"ui.linenr.selected"          = "light-yellow"
"ui.menu"                     = { bg = "gray", fg = "light-gray" }
"ui.menu.selected"            = { modifiers = [ "reversed" ] }
"ui.popup"                    = { bg = "black" }
"ui.selection"                = { fg = "gray", modifiers = [ "reversed" ] }
"ui.statusline"               = { bg = "light-cyan", fg = "black" }
"ui.statusline.inactive"      = { bg = "black", fg = "gray" }
"ui.text.focus"               = { bg = "white", fg = "black" }
"ui.virtual.jump-label"       = { fg = "blue", modifiers = [ "bold", "underlined" ] }
"ui.virtual.ruler"            = { bg = "black" }
"ui.virtual.whitespace"       = "light-gray"
"ui.window"                   = { bg = "black" }
"variable"                    = "white"
"variable.other.member"       = "white"
#"function.builtin" = "cyan"
#"function.method" = "cyan"
#"function.method.private" = "cyan"
"constructor"            = "cyan"
"function"               = "cyan"
"keyword"                = "yellow"
"keyword.control.import" = "magenta"
"label"                  = "white"
"namespace"              = "white"
"special"                = "light-blue"

"markup.bold"          = { fg = "light-yellow", modifiers = [ "bold" ] }
"markup.heading"       = "light-magenta"
"markup.italic"        = { fg = "light-magenta", modifiers = [ "italic" ] }
"markup.link.text"     = "light-red"
"markup.link.url"      = { fg = "yellow", modifiers = [ "underlined" ] }
"markup.list"          = "light-red"
"markup.quote"         = "light-cyan"
"markup.raw"           = "light-green"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "yellow"
"diff.minus" = "light-red"
"diff.plus"  = "light-green"

"debug"      = "gray"
"diagnostic" = { modifiers = [ "underlined" ] }
"error"      = "light-red"
"hint"       = "gray"
"info"       = "light-blue"
"warning"    = "yellow"
