##########
# SYNTAX #
##########

comment = "sky-"

label               = "blue"
tag                 = "blue"
type                = "green"
"type.enum.variant" = "green"

constant             = "purple"
"constant.character" = "purple"
"constant.numeric"   = "cyan"

string                  = "yellow"
"string.special.path"   = "cyan"
"string.special.symbol" = "cyan"

variable           = "sky"
"variable.builtin" = "red"

keyword = "magenta"

function         = "blue"
"function.macro" = "purple"

namespace   = "sky"
operator    = "magenta"
punctuation = "sky"

"diff.delta" = "cyan"
"diff.minus" = "red"
"diff.plus"  = "green"


##########
#   UI   #
##########

error   = "red"
hint    = "sky-"
info    = "sky"
warning = "yellow"

"diagnostic.deprecated"        = { modifiers = [ "crossed_out" ] }
"diagnostic.error".underline   = { color = "red", style = "curl" }
"diagnostic.hint".underline    = { color = "sky-", style = "curl" }
"diagnostic.info".underline    = { color = "sky", style = "curl" }
"diagnostic.unnecessary"       = { modifiers = [ "dim" ] }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }

"ui.background"           = { bg = "shade" }
"ui.background.separator" = "sky"

"ui.cursor"       = { modifiers = [ "reversed" ] }
"ui.cursor.match" = { bg = "shade+" }

"ui.cursorline.primary" = { bg = "shade-" }
# "ui.cursorline.secondary" = { bg = "shade+" }

"ui.linenr"          = "sky-"
"ui.linenr.selected" = "sky"

# Using themed status line:
"ui.statusline"          = { bg = "sky", fg = "shade" }
"ui.statusline.inactive" = { bg = "shade+", fg = "sky" }
"ui.statusline.insert"   = { bg = "green", fg = "shade" }
"ui.statusline.normal"   = { bg = "blue", fg = "shade" }
"ui.statusline.select"   = { bg = "purple", fg = "shade" }

# Without themed status line:
# "ui.statusline" = { fg = "shade-", bg = "blue" }
# "ui.statusline.inactive" = { fg = "sky", bg = "shade+" }

"ui.popup"      = { bg = "shade-" }
"ui.popup.info" = { bg = "shade" }

"ui.help"   = { bg = "shade-", fg = "sky" }
"ui.window" = "sky"

"ui.text"       = "sky"
"ui.text.focus" = "blue"
"ui.text.info"  = "sky"

"ui.virtual.indent-guide" = "shade+"
"ui.virtual.ruler"        = { bg = "shade-" }
"ui.virtual.whitespace"   = "sky-"

"ui.menu"          = { bg = "shade-", fg = "sky" }
"ui.menu.scroll"   = { bg = "shade+", fg = "sky" }
"ui.menu.selected" = { fg = "blue", modifiers = [ "bold" ] }

"ui.selection" = { bg = "shade+" }

"markup.bold"          = { modifiers = [ "bold" ] }
"markup.heading"       = { fg = "sky+", modifiers = [ "bold" ] }
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.link.text"     = "magenta"
"markup.link.url"      = { modifiers = [ "underlined" ] }
"markup.list"          = "sky"
"markup.quote"         = "green"
"markup.raw"           = "orange"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }


[palette]

# contrast+ accents
blue    = "#61A3E6"
cyan    = "#00B3C2"
green   = "#50B584"
magenta = "#D080B6"
orange  = "#CE9042"
purple  = "#A48FE1"
red     = "#DF7F78"
yellow  = "#9CA748"

# contrast+ base
"shade"  = "#24272B"
"shade+" = "#3E4044"
"shade-" = "#181B1F"
"sky"    = "#9E9E9E"
"sky+"   = "#CECECE"
"sky-"   = "#636363"
"sun"    = "#FFF7ED"
"sun+"   = "#FFFDFB"
"sun-"   = "#F2E6D4"
