# Author: Ambuj Kumar <ambujs89@gmail.com>
# Ported from: https://github.com/drcmda/poimandres-theme

attribute                   = { fg = "desaturatedBlue", modifiers = [ "italic" ] }
comment                     = { fg = "darkerGray.b0", modifiers = [ "italic" ] }
constant                    = "brightMint"
"constant.builtin"          = { fg = "hotRed" }
"constant.character.escape" = { fg = "offWhite" }
"constant.numeric"          = { fg = "brightMint" }
constructor                 = "lightBlue"
function                    = "lightBlue"
"function.method"           = { fg = "lightBlue" }
keyword                     = "brightMint"
"keyword.directive"         = "gray"
"keyword.operator"          = "desaturatedBlue"
"keyword.other"             = "brightMint"
"keyword.storage.modifier"  = "lowerMint"
"keyword.storage.type"      = "desaturatedBlue"
label                       = { fg = "gray.c0" }
namespace                   = "lightBlue"
operator                    = "desaturatedBlue"
punctuation                 = "gray"
"punctuation.bracket"       = "desaturatedBlue"
special                     = "desaturatedBlue"
string                      = { fg = "brightMint" }
tag                         = "brightMint"
type                        = { fg = "gray.c0" }
"type.builtin"              = { fg = "desaturatedBlue" }
variable                    = "offWhite"
"variable.builtin"          = { fg = "lightBlue", modifiers = [ "italic" ] }
"variable.other"            = "offWhite"
"variable.parameter"        = { fg = "offWhite" }

# Markup
"markup.bold"          = { fg = "bluishGrayBrighter", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "brightMint" }
"markup.italic"        = { fg = "bluishGrayBrighter", modifiers = [ "italic" ] }
"markup.strikethrough" = { modifiers = [ "italic", "crossed_out" ] }

# UI
"markup.link.text" = { fg = "lightBlue", modifiers = [ "underlined" ] }
"markup.link.url"  = { fg = "lightBlue", modifiers = [ "underlined" ] }
"markup.raw"       = { fg = "lightBlue" }

"ui.background"           = { bg = "bg" }
"ui.background.separator" = { fg = "darkerGray" }
"ui.cursor"               = { bg = "gray", fg = "bg" }
"ui.cursor.match"         = { bg = "focus" }
"ui.cursorline"           = { bg = "#242837" }
"ui.linenr"               = "darkerGray.50"
"ui.linenr.selected"      = "offWhite"

"ui.popup"  = { bg = "#20232d" }
"ui.window" = "gray"

"ui.text"                 = "gray"
"ui.text.focus"           = { bg = "focus", fg = "offWhite", modifiers = [ "bold" ] }
"ui.text.inactive"        = "darkerGray"
"ui.virtual"              = { fg = "darkerGray.b0" }
"ui.virtual.indent-guide" = "#303442"
"ui.virtual.ruler"        = { bg = "selection" }

"ui.selection"         = { bg = "focus" }
"ui.selection.primary" = { bg = "selection" }

"ui.menu"          = { bg = "bg", fg = "offWhite" }
"ui.menu.scroll"   = { bg = "bg", fg = "gray" }
"ui.menu.selected" = { bg = "gray", fg = "bg" }

"ui.statusline"          = { bg = "selection", fg = "offWhite" }
"ui.statusline.inactive" = { bg = "bg", fg = "lightBlue" }
"ui.statusline.insert"   = { bg = "brightMint", fg = "bg", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "lightBlue", fg = "bg", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "hotRed", fg = "bg", modifiers = [ "bold" ] }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "hotRed", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "lowerMint", style = "curl" } }
"diagnostic.info"        = { underline = { color = "lightBlue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "brightYellow", style = "curl" } }

error   = "hotRed"
hint    = "lowerMint"
info    = "lightBlue"
warning = "brightYellow"

# Version Control
"diff.delta" = "lightBlue"
"diff.minus" = "hotRed"
"diff.plus"  = "lowerMint"

[palette]
bg                 = "#1b1e28"
black              = "#000000"
blueishGreen       = "#42675A"
bluishGray         = "#506477"
bluishGrayBrighter = "#7390AA"
brightMint         = "#5DE4c7"
brightYellow       = "#fffac2"
darkerGray         = "#767c9d"
"darkerGray.50"    = "#404559"
"darkerGray.b0"    = "#6c7494"
desaturatedBlue    = "#91B4D5"
focus              = "#303340"
gray               = "#a6accd"
"gray.c0"          = "#98a0c2"
hotRed             = "#d0679d"
lightBlue          = "#ADD7FF"
lowerBlue          = "#89ddff"
lowerMint          = "#5fb3a1"
offWhite           = "#e4f0fb"
pink               = "#f087bd"
selection          = "#30354a"
transparent        = "#00000000"
white              = "#ffffff"
