# Author: Ambuj Kumar <ambujs89@gmail.com>
# Ported from: https://github.com/drcmda/poimandres-theme

inherits = "poimandres"

"ui.cursorline"           = { bg = "#303747" }
"ui.popup"                = { bg = "#2a303c" }
"ui.virtual.indent-guide" = "#3a4151"

[palette]
bg              = "#252b37"
black           = "#101010"
bluishGray      = "#607487"
darkerGray      = "#868cad"
"darkerGray.50" = "#4f576d"
"darkerGray.b0" = "#818cae"
focus           = "#404350"
"gray.c0"       = "#98a2c4"
selection       = "#3d455c"
