# Author : Rohit K Viswanath <kvrohit@gmail.com>
# Ported from : [rsms/sublime-theme](https://github.com/rsms/sublime-theme)

"attribute" = "cyan"

"keyword"                     = "blue"
"keyword.control.conditional" = { fg = "blue", modifiers = [ "italic" ] }
"keyword.directive"           = "magenta"                                 # -- preprocessor comments (#if in C)

"namespace" = { fg = "blue", modifiers = [ "italic" ] }

"punctuation"           = "gray06"
"punctuation.delimiter" = "gray06"

"operator" = "yellow"
"special"  = "yellow"

"variable"              = "white"
"variable.builtin"      = "bright_blue"
"variable.other.member" = "white"
"variable.parameter"    = "bright_white"

"type"              = "bright_white"
"type.builtin"      = "magenta"
"type.enum.variant" = "magenta"

"constructor" = "yellow"

"function"         = "white"
"function.builtin" = "blue"
"function.macro"   = "blue"

"comment" = { fg = "gray05", modifiers = [ "italic" ] }
"tag"     = "yellow"

"string"         = "cyan"
"string.regexp"  = "green"
"string.special" = "blue"

"constant"                  = "white"
"constant.builtin"          = "white"
"constant.character.escape" = "magenta"
"constant.numeric"          = "magenta"

# used for lifetimes
"label" = "yellow"

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading.1"      = { fg = "white", modifiers = [ "bold" ] }
"markup.heading.2"      = { fg = "gray07", modifiers = [ "bold" ] }
"markup.heading.3"      = { fg = "gray07", modifiers = [ "bold" ] }
"markup.heading.4"      = { fg = "gray07", modifiers = [ "bold" ] }
"markup.heading.5"      = { fg = "gray06", modifiers = [ "bold" ] }
"markup.heading.6"      = { fg = "gray06", modifiers = [ "bold" ] }
"markup.heading.marker" = { fg = "gray07" }
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = "blue"
"markup.link.url"       = { fg = "cyan", modifiers = [ "underlined" ] }
"markup.list"           = "gray07"
"markup.raw"            = "yellow"
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"diff.delta" = "bright_cyan"
"diff.minus" = "bright_red"
"diff.plus"  = "bright_green"

"ui.background"           = { bg = "bg" }
"ui.background.separator" = { fg = "fg" }

"ui.linenr"          = { fg = "gray04" }
"ui.linenr.selected" = { fg = "gray07" }

"ui.statusline"          = { bg = "gray02", fg = "gray07" }
"ui.statusline.inactive" = { bg = "gray01", fg = "gray05" }
"ui.statusline.insert"   = { bg = "blue", fg = "black", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "cyan", fg = "black", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "magenta", fg = "black", modifiers = [ "bold" ] }

"ui.help"   = { bg = "gray01", fg = "fg" }
"ui.popup"  = { bg = "gray01" }
"ui.window" = { fg = "gray02" }

"ui.text"       = { fg = "fg" }
"ui.text.focus" = { fg = "white" }

"ui.virtual"              = { fg = "gray03" }
"ui.virtual.indent-guide" = { fg = "gray04" }
"ui.virtual.inlay-hint"   = { fg = "gray05" }
"ui.virtual.ruler"        = { bg = "gray03" }

"ui.selection"         = { bg = "gray03" }
"ui.selection.primary" = { bg = "gray03" }

"ui.cursor"             = { bg = "gray04" }
"ui.cursor.insert"      = { bg = "white" }
"ui.cursor.match"       = { fg = "bright_yellow" }
"ui.cursor.select"      = { bg = "gray03" }
"ui.cursorline.primary" = { bg = "gray01" }

"ui.highlight" = { bg = "gray03" }

"ui.menu"          = { bg = "gray01", fg = "white" }
"ui.menu.scroll"   = { bg = "gray01", fg = "white" }
"ui.menu.selected" = { bg = "gray03", fg = "fg" }

"diagnostic.deprecated"        = { modifiers = [ "crossed_out" ] }
"diagnostic.error".underline   = { color = "bright_red", style = "curl" }
"diagnostic.hint".underline    = { color = "bright_cyan", style = "curl" }
"diagnostic.info".underline    = { color = "bright_blue", style = "curl" }
"diagnostic.unnecessary"       = { modifiers = [ "dim" ] }
"diagnostic.warning".underline = { color = "bright_yellow", style = "curl" }

error   = "bright_red"
hint    = "bright_cyan"
info    = "bright_blue"
warning = "bright_yellow"

[palette]
bg             = "#1a1a19"
black          = "#333332"
blue           = "#8db4d4"
bright_black   = "#4c4c4b"
bright_blue    = "#a6cded"
bright_cyan    = "#94c9b2"
bright_green   = "#7aae98"
bright_magenta = "#f7b4e1"
bright_red     = "#ffafa5"
bright_white   = "#eaeaea"
bright_yellow  = "#ffdeaa"
cyan           = "#7bb099"
fg             = "#d1d1d1"
gray01         = "#222221"
gray02         = "#2a2a29"
gray03         = "#323231"
gray04         = "#3a3a39"
gray05         = "#6a6a69"
gray06         = "#767675"
gray07         = "#b6b6b5"
green          = "#61957f"
magenta        = "#de9bc8"
red            = "#ff968c"
white          = "#d1d1d1"
yellow         = "#ffc591"
