# Author: Rosé Pine <hi@rosepinetheme.com>
# Upstream: https://github.com/rose-pine/helix
# Contributing:
#   Please submit changes to https://github.com/rose-pine/helix.
#   The Rosé Pine team will update Helix, including you as a co-author.

"ui.background"           = { bg = "base" }
"ui.background.separator" = { bg = "base" }

"ui.cursor" = { bg = "highlight_high", fg = "text" }
# "ui.cursor.select" = {}
"ui.cursor.match"   = { bg = "highlight_med", fg = "text" }
"ui.cursor.primary" = { bg = "muted", fg = "text" }

# "ui.gutter" = {}
# "ui.gutter.selected" = {}

"ui.linenr"          = { fg = "muted" }
"ui.linenr.selected" = { fg = "text" }

"ui.bufferline"          = { bg = "base", fg = "muted" }
"ui.bufferline.active"   = { bg = "overlay", fg = "text" }
"ui.statusline"          = { bg = "surface", fg = "subtle" }
"ui.statusline.inactive" = { bg = "surface", fg = "muted" }
"ui.statusline.insert"   = { bg = "foam_10", fg = "foam" }
"ui.statusline.normal"   = { bg = "rose_10", fg = "rose" }
"ui.statusline.select"   = { bg = "iris_10", fg = "iris" }
# "ui.statusline.separator" = {}

"ui.popup"      = { bg = "surface" }
"ui.popup.info" = { bg = "surface" }

"ui.help"   = { bg = "overlay", fg = "subtle" }
"ui.window" = { bg = "base", fg = "overlay" }

"ui.text"           = { fg = "text" }
"ui.text.directory" = { fg = "iris" }
"ui.text.focus"     = { bg = "overlay" }
"ui.text.info"      = { fg = "subtle" }

"ui.virtual.indent-guide" = { fg = "muted" }
"ui.virtual.inlay-hint"   = { fg = "subtle" }
"ui.virtual.jump-label"   = { fg = "love", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "overlay" }
"ui.virtual.whitespace"   = { fg = "highlight_high" }

"ui.menu"          = { bg = "surface", fg = "subtle" }
"ui.menu.scroll"   = { bg = "highlight_med", fg = "muted" }
"ui.menu.selected" = { bg = "overlay", fg = "text" }

"ui.selection"         = { bg = "overlay" }
"ui.selection.primary" = { bg = "highlight_med" }

"ui.cursorline.primary"   = { bg = "highlight_low" }
"ui.cursorline.secondary" = { bg = "surface" }

"debug"   = "rose"
"error"   = "love"
"hint"    = "iris"
"info"    = "foam"
"warning" = "gold"

"diagnostic"             = { underline = { color = "subtle", style = "curl" } }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "love", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "iris", style = "curl" } }
"diagnostic.info"        = { underline = { color = "foam", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "gold", style = "curl" } }
"special"                = "rose"

"attribute" = "iris"

"type" = "foam"
# "type.builtin" = ""

"constructor" = "foam"

"constant"                  = "foam"
"constant.builtin"          = "love"
"constant.builtin.boolean"  = "rose"
"constant.character"        = "gold"
"constant.character.escape" = "pine"
"constant.numeric"          = "gold"
# "constant.numeric.integer" = ""
# "constant.numeric.float" = ""

"string" = "gold"
# "string.regexp" = ""
# "string.special" = ""
# "string.special.path" = ""
# "string.special.url" = ""
# "string.special.symbol" = ""

"comment" = { fg = "muted", modifiers = [ "italic" ] }
# "comment.line" = ""
# "comment.line.documentation" = ""
# "comment.block" = ""
# "comment.block.documentation" = ""

"variable"           = "text"
"variable.builtin"   = "love"
"variable.parameter" = "iris"
# "variable.other" = ""
"variable.other.member" = "foam"

"label" = "foam"

"punctuation" = "subtle"
# "punctuation.delimiter" = ""
# "punctuation.bracket" = ""
# "punctuation.special" = ""

"keyword" = "pine"
# "keyword.control" = ""
# "keyword.control.conditional" = ""
# "keyword.control.repeat" = ""
# "keyword.control.import" = ""
# "keyword.control.return" = ""
# "keyword.control.exception" = ""
"keyword.operator" = "subtle"
# "keyword.directive" = ""
# "keyword.function" = ""
# "keyword.storage" = ""
# "keyword.storage.type" = ""
# "keyword.storage.modifier" = ""

"operator" = "subtle"

"function"         = "rose" # maybe pine
"function.builtin" = "love"
# "function.method" = ""
# "function.macro" = ""
# "function.special" = ""

"tag" = "foam"

"namespace" = "text"

"markup.heading"        = { fg = "iris", modifiers = [ "bold" ] }
"markup.heading.1"      = { fg = "iris", modifiers = [ "bold" ] }
"markup.heading.2"      = { fg = "foam", modifiers = [ "bold" ] }
"markup.heading.3"      = { fg = "rose", modifiers = [ "bold" ] }
"markup.heading.4"      = { fg = "gold", modifiers = [ "bold" ] }
"markup.heading.5"      = { fg = "pine", modifiers = [ "bold" ] }
"markup.heading.6"      = { fg = "foam", modifiers = [ "bold" ] }
"markup.heading.marker" = "muted"
# "markup.heading.completion" = ""
# "markup.heading.hover" = ""
"markup.list" = "muted"
# "markup.list.unnumbered" = ""
# "markup.list.numbered" = ""
"markup.bold"          = { modifiers = [ "bold" ] }
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.link"          = "iris"
"markup.link.label"    = "subtle"
"markup.link.text"     = "text"
"markup.link.url"      = { fg = "iris", underline = { color = "iris", style = "line" } }
"markup.quote"         = "subtle"
"markup.raw"           = "subtle"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }
# "markup.raw.inline" = {}
# "markup.raw.inline.completion" = {}
# "markup.raw.inline.hover" = {}
# "markup.raw.block" = {}
# "markup.normal" = ""
# "markup.normal.completion" = ""
# "markup.normal.hover" = ""

"diff"       = "overlay"
"diff.delta" = "highlight_high"
"diff.minus" = "love"
"diff.plus"  = "foam"
# "diff.delta.moved" = ""

[palette]
base           = "#191724"
foam           = "#9ccfd8"
foam_10        = "#252937"
gold           = "#f6c177"
gold_10        = "#30282c"
highlight_high = "#524f67"
highlight_low  = "#21202e"
highlight_med  = "#403d52"
iris           = "#c4a7e7"
iris_10        = "#2b2539"
love           = "#eb6f92"
love_10        = "#311f30"
muted          = "#6e6a86"
overlay        = "#26233a"
pine           = "#31748f"
pine_10        = "#1a2030"
rose           = "#ebbcba"
rose_10        = "#2f2834"
subtle         = "#908caa"
surface        = "#1f1d2e"
text           = "#e0def4"
