# Seoul256 Light Hard
# Author : EricHenry
# Original Creator: https://github.com/junegunn/seoul256.vim

inherits = "seoul256-light"

"ui.background"         = { bg = "gray11" }
"ui.cursor.match"       = { bg = "gray10", modifiers = [ "underlined" ] }
"ui.cursorline.primary" = { bg = "gray12" }
"ui.gutter"             = { bg = "white1" }
"ui.gutter.selected"    = { bg = "gray12" }
"ui.linenr.selected"    = { bg = "gray12", fg = "magenta", modifiers = [ "bold" ] }

"ui.help"  = { bg = "gray12", fg = "black1" }
"ui.menu"  = { bg = "gray12", fg = "black1" }
"ui.popup" = { bg = "gray12", fg = "black1" }
