# Seoul256 Light Soft
# Author : EricHenry
# Original Creator: https://github.com/junegunn/seoul256.vim

inherits = "seoul256-light"

"ui.background"         = { bg = "white" }
"ui.cursor.match"       = { bg = "gray13", modifiers = [ "underlined" ] }
"ui.cursorline.primary" = { bg = "gray10" }
"ui.gutter"             = { bg = "gray13" }
"ui.gutter.selected"    = { bg = "gray10" }
"ui.linenr.selected"    = { bg = "gray10", fg = "magenta", modifiers = [ "bold" ] }

"ui.help"  = { bg = "gray10", fg = "black1" }
"ui.menu"  = { bg = "gray10", fg = "black1" }
"ui.popup" = { bg = "gray10", fg = "black1" }
