# Seoul256 Dark
# Author : EricHenry
# Original Creator: https://github.com/junegunn/seoul256.vim

# Syntax highlighting configuration
"attribute"                 = { fg = "yellow" }
"comment"                   = { fg = "green1" }
"constant"                  = { fg = "blue5" }
"constant.builtin.boolean"  = { fg = "purple" }
"constant.character.escape" = { fg = "salmon" }
"constant.numeric"          = { fg = "yellow1" }
"constructor"               = { fg = "yellow" }
"function"                  = { fg = "yellow2" }
"function.builtin"          = { fg = "blue1" }
"function.macro"            = { fg = "yellow2" }
"function.method"           = { fg = "salmon" }
"keyword"                   = { fg = "mauve" }
"label"                     = { fg = "magenta" }
"namespace"                 = { fg = "cyan" }
"operator"                  = { fg = "yellow3" }
"punctuation"               = { fg = "brown" }
"special"                   = { fg = "yellow2" }
"string"                    = { fg = "blue" }
"type"                      = { fg = "yellow" }
"type.builtin"              = { fg = "salmon" }
"variable"                  = { fg = "white" }
"variable.builtin"          = { fg = "salmon" }
"variable.other.member"     = { fg = "white" }
"variable.parameter"        = { fg = "white" }

"markup.bold"          = { fg = "yellow1", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "salmon2", modifiers = [ "bold" ] }
"markup.italic"        = { fg = "magenta1", modifiers = [ "italic" ] }
"markup.link.text"     = { fg = "salmon2" }
"markup.link.url"      = { fg = "cyan", modifiers = [ "underlined" ] }
"markup.list"          = { fg = "salmon" }
"markup.quote"         = { fg = "yellow" }
"markup.raw.inline"    = { fg = "green" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = { fg = "blue1" }
"diff.minus" = { fg = "magenta3" }
"diff.plus"  = { fg = "green3" }

"diagnostic.deprecated"        = { modifiers = [ "crossed_out" ] }
"diagnostic.error".underline   = { color = "red", style = "curl" }
"diagnostic.hint".underline    = { color = "green1", style = "curl" }
"diagnostic.info".underline    = { color = "cyan", style = "curl" }
"diagnostic.unnecessary"       = { modifiers = [ "dim" ] }
"diagnostic.warning".underline = { color = "yellow1", style = "curl" }
"error"                        = { fg = "red", modifiers = [ "bold" ] }
"hint"                         = { fg = "blue3", modifiers = [ "bold" ] }
"info"                         = { fg = "blue2", modifiers = [ "bold" ] }
"warning"                      = { fg = "yellow", modifiers = [ "bold" ] }

"ui.background"           = { bg = "gray4" }
"ui.gutter"               = { bg = "gray5" }
"ui.gutter.selected"      = { bg = "gray3" }
"ui.virtual"              = { fg = "gray6" }
"ui.virtual.indent-guide" = { fg = "gray6" }
"ui.virtual.inlay-hint"   = { fg = "gray9", modifiers = [ "bold" ] }
"ui.virtual.jump-label"   = { fg = "red", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "gray5" }
"ui.virtual.whitespace"   = { fg = "gray6" }

"ui.cursor"         = { fg = "white", modifiers = [ "reversed" ] }
"ui.cursor.insert"  = { fg = "blue1" }
"ui.cursor.match"   = { bg = "gray4", modifiers = [ "underlined" ] }
"ui.cursor.primary" = { fg = "white", modifiers = [ "reversed" ] }

"ui.cursorline.primary" = { bg = "gray3" }
"ui.selection"          = { bg = "magenta2" }
"ui.selection.primary"  = { bg = "blue4" }

"ui.highlight"           = { bg = "gray5" }
"ui.highlight.frameline" = { bg = "red" }

"ui.linenr"          = { fg = "yellow4" }
"ui.linenr.selected" = { bg = "gray3", fg = "magenta", modifiers = [ "bold" ] }

"ui.statusline"          = { bg = "yellow2", fg = "magenta2" }
"ui.statusline.inactive" = { bg = "black", fg = "gray6" }
"ui.statusline.insert"   = { bg = "green2", fg = "black" }
"ui.statusline.normal"   = { bg = "blue2", fg = "black" }
"ui.statusline.select"   = { bg = "magenta", fg = "black" }

"ui.text"       = { fg = "white" }
"ui.text.focus" = { bg = "magenta2", fg = "white", modifiers = [ "bold" ] }

"ui.help"          = { bg = "gray3", fg = "white" }
"ui.menu"          = { bg = "gray3", fg = "white" }
"ui.menu.scroll"   = { bg = "gray6", fg = "gray7" }
"ui.menu.selected" = { bg = "magenta2", fg = "white" }
"ui.popup"         = { bg = "gray3", fg = "white" }
"ui.window"        = { fg = "white" }

"ui.debug" = { fg = "red" }

# Colors (Seoul256)
[palette]
black    = '#000000' # Black
black1   = '#14161B'
blue     = '#87afaf' # Light Blue
blue1    = '#5f87d7' # Bright Blue
blue2    = '#5f5f87' # Blue
blue3    = '#a6dbff' # Lightest Blue
blue4    = '#005f5f' # Blue Green
blue5    = '#5fafaf' # Dark Blue
blue6    = '#008787'
brown    = '#af875f' # Brownish
brown1   = '#875f00' # Brownish
cyan     = '#87d7d7' # Bright Cyan
cyan1    = '#afd7d7'
green    = '#afd75f' # Greenish Yellow
green1   = '#5f875f' # Greenish Gray
green2   = '#5f8700' # Green
green3   = '#87af87'
green4   = '#5f5f00'
magenta  = '#af5f5f' # Magenta
magenta1 = '#af5f87' # Soft Magenta
magenta2 = '#875f5f' # Dark Magenta
magenta3 = '#d7005f' # Darker Magenta
mauve    = '#d75f87' # Mauve
orange   = '#ff5f00' # Orange
purple   = '#8787af' # Purple
red      = '#d70000' # Red
salmon   = '#ffaf87' # Salmon
salmon1  = '#d78787' # Salmon Bright
salmon2  = '#d7afaf' # Salmon Light
salmon3  = '#d7875f' # Yellowish
white    = '#d0d0d0' # White
white1   = '#dadada' # White
yellow   = '#d8af5f' # Yellow
yellow1  = '#ffd787' # Bright Yellow
yellow2  = '#d7d7af' # Yellowish
yellow3  = '#d7d787' # Yellow Dim
yellow4  = '#87875f' # Olive
yellow5  = '#6B5300'

gray   = '#121212' # Very Dark Gray
gray1  = '#1c1c1c' # Darker Gray
gray10 = '#c6c6c6'
gray11 = '#eeeeee'
gray12 = '#e4e4e4'
gray13 = '#bcbcbc'
gray2  = '#262626' # Dark Gray
gray3  = '#303030' # Dark Medium Gray
gray4  = '#3a3a3a' # Medium Gray
gray5  = '#444444' # Lighter Medium Gray
gray6  = '#585858' # Light Gray
gray7  = '#626262' # Lighter Gray
gray8  = '#4e4e4e' # Even Lighter Gray
gray9  = '#5f5f5f'

# 233 = '#121212' 
# 234 = '#1c1c1c'
# 235 = '#262626'
# 236 = '#303030'
# 237 = '#3a3a3a' # Default
# 238 = '#444444'
# 239 = '#4e4e4e'
