# Serika (Dark)
# Author: VuiMuich

# Original Author:
# URL: https://github.com/arturoalviar/serika-syntax
# Author: arturoalviar
# License: MIT License

"attribute"             = "aqua"
"comment"               = { fg = "grey2", modifiers = [ "italic" ] }
"constant"              = "purple"
"constructor"           = "yellow"
"escape"                = "orange"
"function"              = "green"
"function.builtin"      = "blue"
"function.macro"        = "aqua"
"keyword"               = "red"
"label"                 = "aqua"
"module"                = "blue"
"namespace"             = "fg"
"number"                = "purple"
"operator"              = "grey0"
"punctuation"           = "grey0"
"punctuation.bracket"   = "fg"
"punctuation.delimiter" = "bg4"
"special"               = "orange"
"string"                = "fg"
"tag"                   = "yellow"
"type"                  = "yellow"
"variable"              = "yellow"
"variable.builtin"      = "blue"
"variable.parameter"    = "yellow"
"variable.property"     = "yellow"

"ui.background"            = { bg = "bg0" }
"ui.background.separator"  = { fg = "bg2" }
"ui.bufferline"            = { fg = "grey1" }
"ui.bufferline.active"     = { fg = "yellow" }
"ui.bufferline.background" = { bg = "bg2" }
"ui.cursor"                = { bg = "dark-red", fg = "fg" }
"ui.cursor.insert"         = { bg = "pale-yellow", fg = "bg0" }
"ui.cursor.match"          = { bg = "pale-yellow", fg = "grey2" }
"ui.cursor.primary"        = { bg = "fg", fg = "dark-red" }
"ui.cursor.primary.insert" = { bg = "bg-yellow", fg = "dark-red" }
"ui.cursor.primary.match"  = { bg = "grey2", fg = "pale-yellow" }
"ui.cursor.primary.select" = { bg = "nasty-red", fg = "yellow" }
"ui.cursor.select"         = { bg = "bg-yellow", fg = "bg0" }
"ui.cursorline"            = { bg = "bg2", fg = "grey1" }
"ui.help"                  = { bg = "bg1", fg = "fg" }
"ui.linenr"                = { fg = "yellow", modifiers = [ "dim" ] }
"ui.linenr.selected"       = { fg = "fg", modifiers = [ "dim" ], underline.style = "line" }
"ui.menu"                  = { bg = "bg2", fg = "fg" }
"ui.menu.selected"         = { bg = "bg-yellow", fg = "bg0" }
"ui.picker.header"         = { fg = "bg2", underline.style = "dashed" }
"ui.popup"                 = { bg = "bg1", fg = "grey2" }
"ui.selection"             = { bg = "yellow", modifiers = [ "dim" ] }
"ui.selection.prime"       = { underline.style = "line" }
"ui.statusline"            = { bg = "bg2", fg = "grey1" }
"ui.statusline.inactive"   = { bg = "bg1", fg = "bg5" }
"ui.statusline.insert"     = { fg = "blue" }
"ui.statusline.select"     = { fg = "pale-yellow" }
"ui.text"                  = "fg"
"ui.text.directory"        = "grey0"
"ui.text.focus"            = "yellow"
"ui.text.inactive"         = { fg = "fg", modifiers = [ "dim" ] }
"ui.virtual.inlay-hint"    = { fg = "grey2", modifiers = [ "italic" ] }
"ui.virtual.jump-label"    = { fg = "nasty-red", modifiers = [ "bold" ] }
"ui.virtual.ruler"         = { bg = "bg1" }
"ui.virtual.whitespace"    = { fg = "grey2", modifiers = [ "italic" ] }
"ui.virtual.wrap"          = { fg = "grey2", modifiers = [ "italic" ] }
"ui.window"                = { bg = "bg1", fg = "bg1" }

"error"   = "nasty-red"
"hint"    = "blue"
"info"    = "aqua"
"warning" = "yellow"

"diagnostic"             = { underline = { color = "purple", style = "curl" } }
"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "nasty-red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.info"        = { underline = { color = "aqua", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }

"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "nasty-red" }
"diff.plus"  = { fg = "green" }

"markup.bold"          = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "purple", modifiers = [ "bold" ] }
"markup.italic"        = { fg = "yellow", modifiers = [ "italic" ] }
"markup.link.text"     = "pink"
"markup.link.url"      = "cyan"
"markup.list"          = "cyan"
"markup.quote"         = { fg = "yellow", modifiers = [ "italic" ] }
"markup.raw"           = { fg = "fg" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

[palette]

bg-blue   = "#6a89af"
bg-green  = "#86b365"
bg-red    = "#7e2a33"
bg-visual = "#646669"
bg-yellow = "#e2b714"
bg0       = "#323437"
bg1       = "#494c50"
bg2       = "#55585e"
bg3       = "#61656b"
bg4       = "#6d7278"
bg5       = "#797e86"

aqua        = "#b9c2c6"
blue        = "#adc9db"
dark-red    = "#7e2a33"
fg          = "#d1d0c5"
green       = "#bcd5a8"
grey0       = "#aaaeb3"
grey1       = "#e1e1e3"
grey2       = "#646669"
nasty-red   = "#ca4754"
orange      = "#dd8a3c"
pale-yellow = "#f3e0a1"
pink        = "#e06c75"
purple      = "#be9ec9"
red         = "#e29da7"
yellow      = "#e2b714"
