"attribute"                 = { fg = "violet" }
"comment"                   = { fg = "base01" }
"constant"                  = { fg = "cyan" }
"constant.builtin"          = { fg = "cyan", modifiers = [ "bold" ] }
"constant.character.escape" = { fg = "red", modifiers = [ "bold" ] }
"constructor"               = { fg = "blue" }
"function"                  = { fg = "blue" }
"function.builtin"          = { fg = "blue", modifiers = [ "bold" ] }
"function.macro"            = { fg = "magenta" }
"function.special"          = { fg = "magenta" }
"keyword"                   = { fg = "green" }
"keyword.directive"         = { fg = "orange" }
"label"                     = { fg = "green" }
"module"                    = { fg = "violet" }
"namespace"                 = { fg = "violet" }
"operator"                  = { fg = "green" }
"special"                   = { fg = "orange" }
"string"                    = { fg = "cyan" }
"tag"                       = { fg = "magenta" }
"type"                      = { fg = "yellow" }
"type.builtin"              = { fg = "yellow", modifiers = [ "bold" ] }
"variable.builtin"          = { fg = "cyan", modifiers = [ "bold" ] }
"variable.function"         = { fg = "blue" }

# TODO
"markup.bold"          = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading"       = "blue"
"markup.italic"        = { fg = "magenta", modifiers = [ "italic" ] }
"markup.link.text"     = "red"
"markup.link.url"      = { fg = "yellow", modifiers = [ "underlined" ] }
"markup.list"          = "red"
"markup.quote"         = "cyan"
"markup.raw"           = "green"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = { fg = "yellow" }
"diff.minus" = { fg = "red" }
"diff.plus"  = { fg = "green" }

# 背景
# background
"ui.background" = { bg = "base03" }

"ui.virtual.inlay-hint" = { fg = "base01", modifiers = [ "italic" ] }
"ui.virtual.jump-label" = { fg = "red", modifiers = [ "bold" ] }
"ui.virtual.whitespace" = { fg = "base01" }

# 行号栏
# line number column
"ui.linenr" = { bg = "base02", fg = "base0" }
# 当前行号栏
# current line number column
"ui.linenr.selected" = { fg = "blue", modifiers = [ "bold" ] }
# cursorline
"ui.cursorline" = { bg = "base0" }

# 状态栏
# status bar
"ui.statusline"        = { bg = "base0", fg = "base03" }
"ui.statusline.insert" = { bg = "green" }
"ui.statusline.normal" = { bg = "blue" }
"ui.statusline.select" = { bg = "yellow" }

# 非活动状态栏
# inactive status bar
"ui.statusline.inactive" = { bg = "base01", fg = "base1" }

# 补全窗口, preview窗口
# Completion window, preview window
"ui.popup" = { bg = "base02" }
# 影响 补全选中 cmd弹出信息选中
# Affect completion selection, cmd pop-up information selection
"ui.menu"          = { bg = "base02", fg = "base0" }
"ui.menu.selected" = { bg = "base2", fg = "base02" }
# ??
"ui.window" = { fg = "base3" }
# 命令行 补全的帮助信息
# Command line completion help information
"ui.help" = { modifiers = [ "reversed" ] }

# 快捷键窗口 
# Shortcut window
"ui.popup.info" = { bg = "base1" }
# 快捷键字体
# Shortcut font
"ui.text.info" = { fg = "base02", modifiers = [ "bold" ] }

# 普通ui的字体样式
# Normal ui font style
"ui.text" = { fg = "base1" }
# 影响 picker列表选中, 快捷键帮助窗口文本
# Affects picker list selection, shortcut key help window text
"ui.text.focus" = { fg = "blue", modifiers = [ "bold" ] }

# 主光标/selection
# main cursor/selection
"ui.cursor.primary" = { bg = "base1", fg = "base03" }
"ui.cursor.select"  = { bg = "cyan", fg = "base02" }

"ui.cursorline.primary"   = { bg = "base02" }
"ui.cursorline.secondary" = { bg = "base025" }

"ui.selection"         = { bg = "base0175" }
"ui.selection.primary" = { bg = "base015" }

"ui.virtual.indent-guide" = { fg = "base02" }
"ui.virtual.ruler"        = { bg = "base02" }

# normal模式的光标
# normal mode cursor
"ui.cursor"        = { bg = "cyan", fg = "base02" }
"ui.cursor.insert" = { bg = "base3", fg = "base03" }
# 当前光标匹配的标点符号
# The punctuation character matched by the current cursor
"ui.cursor.match" = { bg = "base015", fg = "base02" }

"error"   = { fg = "red", modifiers = [ "bold", "underlined" ] }
"hint"    = { fg = "base01", modifiers = [ "bold", "underlined" ] }
"info"    = { fg = "blue", modifiers = [ "bold", "underlined" ] }
"warning" = { fg = "orange", modifiers = [ "bold", "underlined" ] }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "base01", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "orange", style = "curl" } }


[palette]
blue    = '#268bd2'
cyan    = '#2aa198'
green   = '#859900'
magenta = '#d33682'
orange  = '#cb4b16'
red     = '#dc322f'
violet  = '#6c71c4'
yellow  = '#b58900'

# 深色 越来越深
# dark getting darker
base0 = '#657b83'
base1 = '#586e75'
base2 = '#073642'
base3 = '#002b36'

# 浅色 越來越浅
# Lighter and lighter
base00   = '#839496'
base01   = '#93a1a1'
base015  = '#c5c8bd'
base0175 = '#dddbcc'
base02   = '#eee8d5'
base025  = '#f5eedb'
base03   = '#fdf6e3'
