### Sublime Text Sonokai Theme
## Original Author: sainnhe
# URL: https://github.com/sainnhe/sonokai
## Modified by p4ymak
# URL: https://github.com/p4ymak
# License: MIT License

"attribute"                 = "purple"
"comment"                   = "grey"
"constant"                  = "fg"
"constant.builtin"          = "purple"
"constant.character.escape" = "orange"
"constant.numeric"          = "purple"
"constructor"               = "blue"
"function"                  = "green"
"function.builtin"          = "green"
"function.macro"            = "green"
"keyword"                   = "red"
"label"                     = "red"
"module"                    = "blue"
"namespace"                 = "blue"
"operator"                  = "red"
"punctuation"               = "grey"
"punctuation.special"       = "yellow"
"special"                   = "orange"
"string"                    = "yellow"
"tag"                       = "yellow"
"type"                      = "blue"
"variable"                  = "fg"
"variable.builtin"          = "purple"
"variable.other.member"     = "orange"
"variable.parameter"        = "fg"

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading.1"      = { fg = "red", modifiers = [ "bold" ] }
"markup.heading.2"      = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading.3"      = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading.4"      = { fg = "green", modifiers = [ "bold" ] }
"markup.heading.5"      = { fg = "blue", modifiers = [ "bold" ] }
"markup.heading.6"      = { fg = "fg", modifiers = [ "bold" ] }
"markup.heading.marker" = "grey"
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = "purple"
"markup.link.url"       = { fg = "blue", modifiers = [ "underlined" ] }
"markup.list"           = "red"
"markup.quote"          = "grey"
"markup.raw"            = "green"
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }

"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus"  = "green"

"ui.background"          = { bg = "bg0" }
"ui.cursor"              = { modifiers = [ 'reversed' ] }
"ui.cursor.insert"       = { bg = "grey", fg = "black" }
"ui.cursor.match"        = { bg = "bg4" }
"ui.cursor.select"       = { bg = "blue", fg = "bg0" }
"ui.cursorline.primary"  = { bg = "bg1" }
"ui.help"                = { bg = "bg1", fg = "fg" }
"ui.linenr"              = "grey"
"ui.linenr.selected"     = "fg"
"ui.menu"                = { bg = "bg2", fg = "fg" }
"ui.menu.selected"       = { bg = "green", fg = "bg0" }
"ui.popup"               = { bg = "bg2", fg = "grey" }
"ui.selection"           = { bg = "bg5" }
"ui.selection.primary"   = { bg = "bg4" }
"ui.statusline"          = { bg = "bg3", fg = "fg" }
"ui.statusline.inactive" = { bg = "bg1", fg = "grey" }
"ui.statusline.insert"   = { bg = "green", fg = "bg0", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "blue", fg = "bg0", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "purple", fg = "bg0", modifiers = [ "bold" ] }
"ui.text"                = "fg"
"ui.text.focus"          = "green"
"ui.virtual.inlay-hint"  = { fg = "grey_dim" }
"ui.virtual.ruler"       = { bg = "bg3" }
"ui.virtual.whitespace"  = "bg4"
"ui.window"              = { bg = "bg0", fg = "grey" }

error   = { bg = 'bg2', fg = 'red', modifiers = [ 'bold' ] }
hint    = { bg = 'bg2', fg = 'blue', modifiers = [ 'bold' ] }
info    = { bg = 'bg2', fg = 'green' }
warning = { bg = 'bg2', fg = 'yellow', modifiers = [ 'bold' ] }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.info"        = { underline = { color = "green", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }


[palette]

bg0         = "#2c2e34"
bg1         = "#33353f"
bg2         = "#363944"
bg3         = "#3b3e48"
bg4         = "#414550"
bg5         = "#444852"
bg_blue     = "#85d3f2"
bg_dim      = "#222327"
bg_green    = "#a7df78"
bg_red      = "#ff6077"
black       = "#181819"
blue        = "#76cce0"
cyan        = "#8dd0b6" # added for compatibility with `edge` scheme
diff_blue   = "#354157"
diff_green  = "#394634"
diff_red    = "#55393d"
diff_yellow = "#4e432f"
fg          = "#e2e2e3"
green       = "#9ed072"
grey        = "#7f8490"
grey_dim    = "#595f6f"
orange      = "#f39660"
purple      = "#b39df3"
red         = "#fc5d7c"
yellow      = "#e7c664"
