# Author : Koen Van der Auwera <atog@hey.com>
# Based on SpaceBones Light https://github.com/chipotle/spacebones
# https://github.com/chipotle/spacebones/blob/main/SpaceBones%20Light.bbColorScheme

"attribute"             = "#b1951d"
"comment"               = { fg = "#a49da5", modifiers = [ "italic" ] }
"constant"              = { fg = "#6c3163" }
"constant.builtin"      = { fg = "#6c3163", modifiers = [ "bold" ] }
"constructor"           = { fg = "#4e3163", modifiers = [ "bold" ] }
"escape"                = { fg = "fg2", modifiers = [ "bold" ] }
"function"              = { fg = "#715ab1", modifiers = [ "bold" ] }
"function.builtin"      = "#b1951d"
"function.macro"        = "#b1951d"
"keyword"               = { fg = "#3a81c3" }
"keyword.directive"     = "#3a81c3"
"label"                 = "#b1951d"
"module"                = "#b1951d"
"namespace"             = "#b1951d"
"number"                = "#6c3163"
"operator"              = "#ba2f59"
"punctuation"           = "#6c3163"
"punctuation.delimiter" = "#6c3163"
"special"               = "#ba2f59"
"string"                = "theme_aqua"
"type"                  = "#6c3163"
"type.builtin"          = "#6c3163"
"variable"              = "#715ab1"
"variable.builtin"      = "#715ab1"
"variable.other.member" = "#002db3"
"variable.parameter"    = "#7590db"
"variable.property"     = "#7590db"

# TODO
"markup.bold"          = { fg = "theme_yellow", modifiers = [ "bold" ] }
"markup.heading"       = "theme_blue"
"markup.italic"        = { fg = "theme_magenta", modifiers = [ "italic" ] }
"markup.link.text"     = "theme_red"
"markup.link.url"      = { fg = "theme_yellow", modifiers = [ "underlined" ] }
"markup.list"          = "theme_red"
"markup.quote"         = "theme_cyan"
"markup.raw"           = "theme_green"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "#715ab1"
"diff.minus" = "#ba2f59"
"diff.plus"  = "theme_aqua"

"error"   = { fg = "#e0211d" }
"hint"    = { fg = "bg2" }
"info"    = { fg = "theme_yellow" }
"warning" = { fg = "meta" }

"ui.background"          = { bg = "bg0" }
"ui.cursor.match"        = { bg = "bg3" }
"ui.cursor.primary"      = { modifiers = [ "reversed" ] }
"ui.cursorline"          = { bg = "bg2" }
"ui.cursorline.primary"  = { bg = "bg1" }
"ui.help"                = { bg = "bg1", fg = "fg1" }
"ui.linenr"              = { fg = "bg3" }
"ui.linenr.selected"     = { fg = "theme_yellow" }
"ui.menu"                = { bg = "bg2", fg = "fg1" }
"ui.menu.selected"       = { bg = "bg2", fg = "base", modifiers = [ "bold" ] }
"ui.popup"               = { bg = "bg1" }
"ui.selection"           = { bg = "hl2" }
"ui.selection.primary"   = { bg = "hl1" }
"ui.statusline"          = { bg = "bg2", fg = "fg1" }
"ui.statusline.inactive" = { bg = "bg1", fg = "fg4" }
"ui.statusline.insert"   = { bg = "theme_green", fg = "bg1" }
"ui.statusline.normal"   = { bg = "theme_cyan", fg = "bg1" }
"ui.statusline.select"   = { bg = "theme_magenta", fg = "bg1" }
"ui.text"                = { fg = "fg1" }
"ui.text.directory"      = { fg = "theme_blue" }
"ui.text.focus"          = { fg = "fg1", modifiers = [ "bold" ] }
"ui.virtual"             = "base-dim"
"ui.virtual.ruler"       = { bg = "bg1" }
"ui.window"              = { bg = "bg1" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "#e0211d", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "bg2", style = "curl" } }
"diagnostic.info"        = { underline = { color = "theme_yellow", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "meta", style = "curl" } }

[palette]
base     = "#655370"
base-dim = "#a094a2"
meta     = "#da8b55"

bg0 = "#fbf8ef"
bg1 = "#efeae9"
bg2 = "#d1dcdf"
bg3 = "#b4c6cb"

hl1 = "#d3d3e7"
hl2 = "#e7e7fc"

fg1 = "#655370"
fg2 = "#5f3bc4"
fg3 = "#bdae93"
fg4 = "#a89984"

theme_aqua    = "#2d9574"
theme_blue    = "#3a81c3"
theme_cyan    = "#21b8c7"
theme_green   = "#67b11d"
theme_magenta = "#a31db1"
theme_red     = "#c10e0b"
theme_yellow  = "#b1951d"
