# Author : eemilhaa <eemil.haapanen@gmail.com> 
# Palette from : https://github.com/CosmicToast/starlight

# Syntax
"constructor" = "green"
"function"    = "green"

"constant"            = "cyan"
"punctuation.special" = "cyan"
"string.regexp"       = "cyan"
"string.special"      = "cyan"
"type"                = "cyan"

"module"    = "white"
"namespace" = "white"
"variable"  = "white"

"attribute"             = "magenta"
"type.parameter"        = "magenta"
"variable.other.member" = "magenta"
"variable.parameter"    = "magenta"

"keyword"          = "blue"
"label"            = "blue"
"operator"         = "blue"
"special"          = "blue"
"tag"              = "blue"
"variable.builtin" = "blue"

"string" = "yellow"

"punctuation" = "punct"

"comment" = "dark-fg"

# Markup
"markup.bold"           = { fg = "magenta", modifiers = [ "bold" ] }
"markup.heading"        = { fg = "white", modifiers = [ "bold" ] }
"markup.heading.marker" = { fg = "blue", modifiers = [ "bold" ] }
"markup.italic"         = { fg = "magenta", modifiers = [ "italic" ] }
"markup.link"           = "cyan"
"markup.link.text"      = "yellow"
"markup.list"           = "blue"
"markup.quote"          = "magenta"
"markup.raw"            = "green"
"markup.strikethrough"  = "red"

# UI
"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus"  = "green"

"ui.background"            = { bg = "dark-bg", fg = "dark-fg" }
"ui.bufferline"            = { bg = "light-bg", fg = "light-fg" }
"ui.bufferline.active"     = { bg = "dark-fg", fg = "white" }
"ui.bufferline.background" = { bg = "dark-bg" }
"ui.cursor"                = { bg = "light-fg", fg = "black" }
"ui.cursor.match"          = { bg = "dark-blue", fg = "black", modifiers = [ "bold" ] }
"ui.cursor.primary"        = { bg = "yellow", fg = "black" }
"ui.cursorcolumn.primary"  = { bg = "black" }
"ui.cursorline.primary"    = { bg = "black" }
"ui.help"                  = { bg = "light-bg", fg = "light-fg" }
"ui.highlight"             = { bg = "light-bg" }
"ui.linenr"                = "dark-fg"
"ui.linenr.selected"       = "yellow"
"ui.menu"                  = { bg = "light-bg", fg = "light-fg" }
"ui.menu.selected"         = { bg = "dark-fg", fg = "white", modifiers = [ "bold" ] }
"ui.popup"                 = { bg = "light-bg", fg = "dark-fg" }
"ui.selection"             = { bg = "dark-fg", fg = "light-fg" }
"ui.selection.primary"     = { bg = "dark-blue", fg = "white" }
"ui.statusline"            = { bg = "light-bg", fg = "light-fg" }
"ui.statusline.inactive"   = { bg = "light-bg", fg = "dark-fg" }
"ui.statusline.insert"     = { bg = "green", fg = "black" }
"ui.statusline.normal"     = { bg = "blue", fg = "black" }
"ui.statusline.select"     = { bg = "magenta", fg = "black" }
"ui.text"                  = "light-fg"
"ui.text.focus"            = { bg = "light-bg", fg = "white", modifiers = [ "bold" ] }
"ui.virtual"               = "dark-fg"
"ui.virtual.indent-guide"  = "indent"
"ui.virtual.ruler"         = { bg = "medium-bg" }
"ui.virtual.whitespace"    = "indent"
"ui.window"                = { bg = "dark-bg", fg = "light-bg" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.info"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }

"error"   = "red"
"hint"    = "blue"
"info"    = "blue"
"warning" = "yellow"

[palette]
# Colors
blue      = "#5DC5F8"
cyan      = "#24DFC4"
dark-blue = "#24ACD4"
green     = "#35D450"
magenta   = "#FEABF2"
punct     = "#C9C9C9"
red       = "#FF4D51"
white     = "#ffffff"
yellow    = "#E9E836"

# Grays
black     = "#1e1e1e"
dark-bg   = "#242424"
dark-fg   = "#929292"
indent    = "#616161"
light-bg  = "#353535"
light-fg  = "#E6E6E6"
medium-bg = "#2D2D2D"
