# Sunset
# Author : Egor Afanasin <afanasin.egor@gmail.com>
# Repo: https://github.com/pithecantrope/sunset

# Syntax highlighting
# ----------------------------------------------------------------
attribute = "mud"

type           = "mud"
"type.builtin" = { fg = "mud", modifiers = [ "italic" ] }

constructor = "wood"

constant             = "fire"
"constant.builtin"   = { fg = "fire", modifiers = [ "italic" ] }
"constant.character" = "wood"
"constant.numeric"   = "wood"

string                  = "grass"
"string.regexp"         = "mud"
"string.special"        = "rose"
"string.special.symbol" = "fire"

comment                       = { fg = "cmnt", modifiers = [ "italic" ] }
"comment.block.documentation" = "grass"
"comment.line.documentation"  = "grass"

variable                = "text"
"variable.builtin"      = { fg = "sky", modifiers = [ "italic" ] }
"variable.other.member" = "pink"
"variable.parameter"    = "rose"

label = "sky"

punctuation           = "cmnt"
"punctuation.special" = "wine"

keyword                     = "sun"
"keyword.control.exception" = { fg = "sun", modifiers = [ "italic" ] }
"keyword.control.return"    = { fg = "sun", modifiers = [ "italic" ] }
"keyword.directive"         = "sky"

operator = "wine"

function           = "peach"
"function.builtin" = { fg = "peach", modifiers = [ "italic" ] }
"function.macro"   = "sky"

tag = "peach"

namespace = { fg = "text", modifiers = [ "italic" ] }

special = "wine"

# Editor interface
# ----------------------------------------------------------------
"markup.heading.1"      = "fire"
"markup.heading.2"      = "wine"
"markup.heading.3"      = "rose"
"markup.heading.4"      = "peach"
"markup.heading.5"      = "grass"
"markup.heading.6"      = "wood"
"markup.heading.marker" = "sun"

"markup.list" = "wood"

"markup.bold"          = { modifiers = [ "bold" ] }
"markup.italic"        = { modifiers = [ "italic" ] }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"markup.link.label" = "sky"
"markup.link.text"  = "mud"
"markup.link.url"   = { fg = "sky", underline.style = "line" }

"markup.quote" = "mud"

"markup.raw" = "pink"

"diff.delta" = "sky"
"diff.minus" = "attn"
"diff.plus"  = "grass"

# User interface
# ----------------------------------------------------------------
"ui.background" = { bg = "base", fg = "text" }

"ui.cursor"                = { bg = "cmnt", fg = "base" }
"ui.cursor.match"          = { fg = "attn", modifiers = [ "bold" ] }
"ui.cursor.primary.insert" = { bg = "grass", fg = "base" }
"ui.cursor.primary.normal" = { bg = "text", fg = "base" }
"ui.cursor.primary.select" = { bg = "sky", fg = "base" }

# TODO: ui.debug

"ui.linenr"          = "block"
"ui.linenr.selected" = "cmnt"

"ui.statusline"          = { bg = "block" }
"ui.statusline.inactive" = { fg = "cmnt" }
"ui.statusline.insert"   = { bg = "grass", fg = "block", modifiers = [ "bold" ] }
"ui.statusline.normal"   = { bg = "text", fg = "block", modifiers = [ "bold" ] }
"ui.statusline.select"   = { bg = "sky", fg = "block", modifiers = [ "bold" ] }

"ui.bufferline"        = { bg = "block", fg = "cmnt" }
"ui.bufferline.active" = "fire"

"ui.popup"      = { bg = "base", fg = "text" }
"ui.popup.info" = { bg = "block", fg = "text" }

"ui.picker.header" = { underline.style = "line" }

"ui.window" = { fg = "block", modifiers = [ "bold" ] }

"ui.help" = { bg = "block", fg = "text" }

"ui.text"           = "text"
"ui.text.directory" = "sky"
"ui.text.focus"     = "sun"
"ui.text.inactive"  = { fg = "cmnt", modifiers = [ "italic" ] }
"ui.text.info"      = { bg = "block" }

"ui.virtual"            = { fg = "block" }
"ui.virtual.jump-label" = { fg = "attn", modifiers = [ "bold" ] }
"ui.virtual.ruler"      = { bg = "block" }

"ui.menu"          = { bg = "base", fg = "text" }
"ui.menu.scroll"   = "block"
"ui.menu.selected" = { bg = "sel" }

"ui.selection" = { bg = "sel" }

"ui.highlight" = { bg = "sel" }

error   = "attn"
hint    = "mud"
info    = "sky"
warning = "fire"

diagnostic = { underline.style = "line" }

[palette]
# Reddish
fire  = "#EE7711"
peach = "#EEBB77"
pink  = "#EEAAAA"
rose  = "#EE7777"
wood  = "#997755"

# Greenish
grass = "#66CC33"
mud   = "#AACC77"
sun   = "#EEEE11"

# Bluish
sky  = "#77AAAA"
wine = "#775599"

# Ui
attn  = "#EE1111"
base  = "#111111"
block = "#222222"
cmnt  = "#777777"
sel   = "#333333"
text  = "#EEEEEE"
