# Author: dgkf
# Modified from base16_terminal, Author: NNB <nnbnh@protonmail.com>

inherits = "term16_dark"

"ui.background.separator"   = "light-gray"
"ui.cursor"                 = { fg = "gray", modifiers = [ "reversed" ] }
"ui.cursor.match"           = { fg = "yellow", modifiers = [ "reversed" ] }
"ui.cursor.primary"         = { fg = "black", modifiers = [ "reversed" ] }
"ui.cursor.secondary"       = { fg = "gray", modifiers = [ "reversed" ] }
"ui.cursorcolumn.primary"   = { bg = "white" }
"ui.cursorcolumn.secondary" = { bg = "white" }
"ui.cursorline.primary"     = { bg = "white" }
"ui.cursorline.secondary"   = { bg = "white" }
"ui.gutter"                 = {}
"ui.gutter.selected"        = { bg = "white" }
"ui.help"                   = {}
"ui.linenr"                 = { fg = "gray", modifiers = [ "dim" ] }
"ui.linenr.selected"        = { fg = "black", modifiers = [ "bold" ] }
"ui.menu"                   = { bg = "light-gray" }
"ui.menu.scroll"            = { fg = "light-blue" }
"ui.menu.selected"          = { bg = "gray", fg = "white", modifiers = [ "bold" ] }
"ui.popup"                  = { bg = "white" }
"ui.selection"              = { bg = "light-gray" }
"ui.statusline"             = { bg = "white" }
"ui.statusline.inactive"    = { fg = "gray", modifiers = [ "underlined" ] }
"ui.statusline.insert"      = { bg = "blue", fg = "white" }
"ui.statusline.select"      = { bg = "magenta", fg = "white" }
"ui.text"                   = {}
"ui.text.focus"             = {}
"ui.virtual"                = { fg = "light-gray" }
"ui.virtual.indent-guide"   = { fg = "light-gray", modifiers = [ "dim" ] }
"ui.virtual.ruler"          = { bg = "white" }
"ui.virtual.wrap"           = { fg = "light-gray" }
"ui.window"                 = { fg = "gray", modifiers = [ "dim" ] }

"comment" = { fg = "gray", modifiers = [ "italic", "dim" ] }

"attribute"                 = "yellow"
"constant"                  = { fg = "yellow", modifiers = [ "bold" ] }
"constant.character.escape" = "blue"
"constant.numeric"          = { fg = "yellow", modifiers = [ "bold" ] }
"constructor"               = "blue"
"function"                  = "blue"
"function.builtin"          = { fg = "blue", modifiers = [ "bold" ] }
"keyword"                   = "magenta"
"keyword.control.exception" = "red"
"keyword.directive"         = { fg = "yellow", modifiers = [ "bold" ] }
"keyword.operator"          = { fg = "blue", modifiers = [ "bold" ] }
"label"                     = "red"
"namespace"                 = { fg = "blue", modifiers = [ "dim" ] }
"special"                   = "red"
"string"                    = "green"
"tag"                       = { fg = "magenta", modifiers = [ "dim" ] }
"type"                      = "blue"
"type.builtin"              = { fg = "blue", modifiers = [ "bold" ] }
"type.enum.variant"         = { fg = "magenta", modifiers = [ "dim" ] }
"variable"                  = { fg = "black", modifiers = [ "dim" ] }
"variable.other.member"     = "green"
"variable.parameter"        = { fg = "red", modifiers = [ "italic", "dim" ] }

"markup.bold"          = { fg = "cyan", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "blue", modifiers = [ "bold" ] }
"markup.italic"        = { fg = "blue", modifiers = [ "italic" ] }
"markup.link.text"     = { fg = "magenta", modifiers = [ "bold" ] }
"markup.link.url"      = { fg = "magenta", modifiers = [ "dim" ] }
"markup.list"          = "red"
"markup.quote"         = "cyan"
"markup.raw"           = "blue"
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "yellow"
"diff.minus" = "red"
"diff.plus"  = "green"

"diagnostic.error"   = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"    = { underline = { color = "cyan", style = "curl" } }
"diagnostic.info"    = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }

"debug"   = "light-yellow"
"error"   = "red"
"hint"    = "cyan"
"info"    = "blue"
"warning" = "yellow"
