# Author: Paul Graydon <untimely.creation97@proton.me>

inherits = "tokyonight"

[palette]
aqua        = "#65bcff"
black       = "#444a73"
blue        = "#82aaff"
comment     = "#636da6"
cyan        = "#86e1fc"
green       = "#4fd6be"
light-cyan  = "#b4f9f8"
light-green = "#c3e88d"
magenta     = "#c099ff"
orange      = "#ff966c"
purple      = "#fca7ea"
red         = "#ff757f"
teal        = "#4fd6be"
turquoise   = "#89ddff"
yellow      = "#ffc777"

add    = "#b8db87"
change = "#7ca1f2"
delete = "#e26a75"

error = "#c53b53"
hint  = "#4fd6be"
info  = "#0db9d7"

bg               = "#222436"
bg-focus         = "#2d3f76"
bg-inlay         = "#273644"
bg-menu          = "#1e2030"
bg-selection     = "#2f334d"
border           = "#1b1d2b"
border-highlight = "#589ed7"
fg               = "#c8d3f5"
fg-dark          = "#828bb8"
fg-gutter        = "#3b4261"
fg-linenr        = "#737aa2"
fg-selected      = "#363c58"
