# Author: Paul Graydon <untimely.creation97@proton.me>

inherits = "tokyonight"

[palette]
bg               = "#24283b"
bg-focus         = "#2e3c64"
bg-inlay         = "#233745"
bg-menu          = "#1f2335"
bg-selection     = "#373d5a"
border           = "#1d202f"
border-highlight = "#29a4bd"
