# Author: Paul Graydon <untimely.creation97@proton.me>

inherits = "tokyonight"

[palette]
aqua        = "#188092"
black       = "#a1a6c5"
blue        = "#2e7de9"
comment     = "#848cb5"
cyan        = "#007197"
green       = "#387068"
light-cyan  = "#2e5857"
light-green = "#587539"
magenta     = "#9854f1"
orange      = "#b15c00"
purple      = "#7847bd"
red         = "#f52a65"
teal        = "#118c74"
turquoise   = "#006a83"
yellow      = "#8c6c3e"

add    = "#aecde6"
change = "#d6d8e3"
delete = "#dfccd4"

error = "#c64343"
hint  = "#118c74"
info  = "#07879d"

bg               = "#e1e2e7"
bg-focus         = "#b6bfe2"
bg-inlay         = "#acd7eb"
bg-menu          = "#e9e9ec"
bg-selection     = "#c4c8da"
border           = "#e9e9ed"
border-highlight = "#2496ac"
fg               = "#3760bf"
fg-dark          = "#6172b0"
fg-gutter        = "#a8aecb"
fg-linenr        = "#68709a"
fg-selected      = "#b3b8d1"
