# Author : Tomas Ruud <git@me.2ms.no>

"ui.background.separator" = "gray"
"ui.cursor"               = { bg = "light-gray", fg = "black" }
"ui.cursor.match"         = { modifiers = [ "underlined" ] }
"ui.cursor.primary"       = { bg = "light-gray", fg = "black" }
"ui.help"                 = { bg = "black", fg = "white" }
"ui.linenr"               = "gray"
"ui.linenr.selected"      = { bg = "gray", fg = "white" }
"ui.menu"                 = { bg = "black", fg = "white" }
"ui.menu.selected"        = { bg = "light-gray", fg = "black" }
"ui.popup"                = { bg = "black", fg = "white" }
"ui.selection"            = { bg = "gray", fg = "white" }
"ui.statusline"           = { bg = "black", fg = "white" }
"ui.virtual.ruler"        = { underline = { style = "line" } }

"comment"  = { bg = "light-magenta", fg = "black" }
"constant" = { bg = "light-cyan", fg = "black" }
"string"   = { bg = "light-green", fg = "black" }

"diff.delta" = "gray"
"diff.minus" = "red"
"diff.plus"  = "green"

"error"   = { bg = "light-red", fg = "black" }
"hint"    = { bg = "light-blue", fg = "black" }
"warning" = { bg = "light-yellow", fg = "black" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { bg = "light-red", fg = "black" }
"diagnostic.hint"        = { bg = "light-blue", fg = "black" }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { bg = "light-yellow", fg = "black" }
