# Varua: an easy on the eyes color palette based on Gruvbox Material and Everforest by sainnhe.
# Author : Kamek <b.kamek@gmail.com>

"attribute"                 = "aqua"
"comment"                   = "grey0"
"constant"                  = "purple"
"constant.character.escape" = "orange"
"constant.numeric"          = "purple"
"constructor"               = "aqua"
"function"                  = "green"
"function.builtin"          = "blue"
"function.macro"            = "aqua"
"keyword"                   = "purple"
"label"                     = "aqua"
"module"                    = "blue"
"namespace"                 = "aqua"
"operator"                  = "orange"
"punctuation"               = "grey2"
"punctuation.bracket"       = "fg"
"punctuation.delimiter"     = "grey2"
"special"                   = "orange"
"string"                    = "green"
"tag"                       = "yellow"
"type"                      = "blue"
"variable"                  = "fg"
"variable.builtin"          = "blue"
"variable.other.member"     = "fg"
"variable.parameter"        = "fg"

"markup.heading.1"      = { fg = "red", modifiers = [ "bold" ] }
"markup.heading.2"      = { fg = "orange", modifiers = [ "bold" ] }
"markup.heading.3"      = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading.4"      = { fg = "green", modifiers = [ "bold" ] }
"markup.heading.5"      = { fg = "blue", modifiers = [ "bold" ] }
"markup.heading.6"      = { fg = "fg", modifiers = [ "bold" ] }
"markup.heading.marker" = "grey2"
"markup.link.text"      = "purple"
"markup.link.url"       = { fg = "blue", modifiers = [ "underlined" ] }
"markup.list"           = "red"
"markup.quote"          = "grey2"
"markup.raw"            = "green"

"diff.delta" = "orange"
"diff.minus" = "red"
"diff.plus"  = "green"

"ui.background"          = { bg = "bg0" }
"ui.cursor"              = { bg = "fg", fg = "bg0" }
"ui.cursor.insert"       = { bg = "grey1", fg = "bg0" }
"ui.cursor.match"        = { bg = "bg_yellow", fg = "orange" }
"ui.cursor.select"       = { bg = "blue", fg = "bg0" }
"ui.cursorline.primary"  = { bg = "bg6" }
"ui.help"                = { bg = "bg1", fg = "fg" }
"ui.linenr"              = "grey0"
"ui.linenr.selected"     = "fg"
"ui.menu"                = { bg = "bg2", fg = "fg" }
"ui.menu.selected"       = { bg = "bg1", fg = "fg" }
"ui.popup"               = { bg = "bg2", fg = "grey0" }
"ui.selection"           = { bg = "bg3" }
"ui.statusline"          = { bg = "bg2", fg = "fg" }
"ui.statusline.inactive" = { bg = "bg1", fg = "grey0" }
"ui.statusline.insert"   = { bg = "green", fg = "bg2" }
"ui.statusline.select"   = { bg = "blue", fg = "bg2" }
"ui.text"                = "fg"
"ui.text.focus"          = "fg"
"ui.virtual.inlay-hint"  = { fg = "grey1" }
"ui.virtual.ruler"       = { bg = "bg2" }
"ui.virtual.whitespace"  = "grey0"
"ui.virtual.wrap"        = { fg = "grey0" }
"ui.window"              = { bg = "bg1", fg = "grey0" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "blue", style = "curl" } }
"diagnostic.info"        = { underline = { color = "aqua", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }
"error"                  = "red"
"hint"                   = "blue"
"info"                   = "aqua"
"ui.virtual.jump-label"  = { fg = "red", modifiers = [ "bold" ] }
"warning"                = "yellow"

[palette]
bg0       = "#282828"
bg1       = "#45403d"
bg2       = "#32302f"
bg3       = "#3c3836"
bg4       = "#4c555b"
bg5       = "#53605c"
bg6       = "#2c2c2c"
bg_blue   = "#394f5a"
bg_green  = "#404d44"
bg_red    = "#4e3e43"
bg_visual = "#503946"
bg_yellow = "#4a4940"

aqua   = "#83c092"
blue   = "#7fbbb3"
fg     = "#dfbf8e"
green  = "#a7c080"
grey0  = "#928374"
grey1  = "#859289"
grey2  = "#9da9a0"
orange = "#e69875"
purple = "#d699b6"
red    = "#e67e80"
yellow = "#dbbc7f"
