"ui.background"           = { bg = "black" }
"ui.bufferline"           = { bg = "black" }
"ui.bufferline.active"    = { bg = "dark-magenta", fg = "light-magenta" }
"ui.cursor"               = { fg = "green", modifiers = [ "reversed" ] }
"ui.cursor.match"         = { bg = "dark-cyan", fg = "light-cyan" }
"ui.cursor.primary"       = { fg = "light-green", modifiers = [ "reversed" ] }
"ui.cursorline.primary"   = { bg = "gray" }
"ui.menu"                 = { bg = "dark-white" }
"ui.menu.selected"        = { fg = "yellow" }
"ui.popup"                = { bg = "dark-white" }
"ui.selection"            = { bg = "dark-white" }
"ui.statusline"           = { bg = "dark-magenta", fg = "light-magenta" }
"ui.statusline.insert"    = { bg = "light-cyan", fg = "black" }
"ui.statusline.normal"    = { bg = "light-yellow", fg = "black" }
"ui.statusline.select"    = { bg = "yellow", fg = "black" }
"ui.text"                 = { fg = "default" }
"ui.text.focus"           = { fg = "yellow" }
"ui.text.info"            = { bg = "dark-white" }
"ui.virtual.indent-guide" = { fg = "dark-blue" }
"ui.virtual.ruler"        = { bg = "dark-white" }
"ui.virtual.wrap"         = { fg = "dark-blue" }
"ui.window"               = { bg = "dark-white" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { bg = "dark-red" }
"diagnostic.hint"        = { bg = "dark-cyan" }
"diagnostic.info"        = { bg = "dark-white" }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { bg = "dark-yellow" }
"error"                  = { bg = "dark-red", fg = "red" }
"hint"                   = { bg = "dark-cyan", fg = "cyan" }
"info"                   = { bg = "dark-white", fg = "default" }
"warning"                = { bg = "dark-yellow", fg = "yellow" }

"comment"                   = "light-black"
"comment.documentation"     = "magenta"
"constant"                  = "red"
"constant.character.escape" = "magenta"
"constructor"               = "light-cyan"
"function"                  = "light-cyan"
"function.macro"            = "magenta"
"keyword"                   = "yellow"
"keyword.directive"         = "magenta"
"label"                     = "green"
"special"                   = "cyan"
"string"                    = "red"
"type"                      = "green"

"diff.delta" = "yellow"
"diff.minus" = "red"
"diff.plus"  = "green"

[palette]
black         = "#000000"
blue          = "#688ef1"
cyan          = "#3a97d4"
dark-black    = "#000000"
dark-blue     = "#2c4074"
dark-cyan     = "#144c71"
dark-green    = "#00643c"
dark-magenta  = "#602864"
dark-red      = "#742833"
dark-white    = "#3e4043"
dark-yellow   = "#6e3500"
default       = "#c1c9d2"
gray          = "#111111"
green         = "#1ea672"
light-black   = "#697386"
light-blue    = "#9fcdff"
light-cyan    = "#7fd3ed"
light-green   = "#85d996"
light-magenta = "#f0b4e4"
light-red     = "#fbb5b2"
light-white   = "#ffffff"
light-yellow  = "#efc078"
magenta       = "#c96ed0"
red           = "#ed5f74"
white         = "#e3e8ee"
yellow        = "#d97917"
