# Vintage Theme for the Helix Editor
# Author: rojebd<roniellberrios@gmail.com>
# Repo: https://github.com/rojebd/vintage
# This theme is vintage inspired
# Info: I made this theme one afternoon because my bus was late and I stayed home :)

attribute                   = "#a7bf67"
comment                     = "light-gray"
constant                    = "#A5C4D4"
"constant.builtin"          = "bright-yellow"
"constant.character.escape" = "#c95c56"
"constant.numeric"          = "#b577b0"
constructor                 = "#c19ef7"
function                    = "muddy"
"function.builtin"          = "#db985e"
"function.macro"            = "muddy"
keyword                     = "#A4A2B4"
"keyword.directive"         = "light-gray"
label                       = "#abcc8a"
namespace                   = "#7095bf"
operator                    = "muddy"
punctuation                 = "white"
"punctuation.delimiter"     = "white"
special                     = "pink"
string                      = "#d6a560"
tag                         = "#d37a78"
type                        = "#efbe4c"
"type.builtin"              = "#efbe4c"
variable                    = "green"
"variable.builtin"          = "light-green"
"variable.other.member"     = "green"
"variable.parameter"        = "light-green"

"markup.bold"          = { fg = "markdown-bold", modifiers = [ "bold" ] }
"markup.heading"       = "bright-pink"
"markup.italic"        = { fg = "markdown-italic", modifiers = [ "italic" ] }
"markup.link.text"     = "orange"
"markup.link.url"      = { fg = "blueish", modifiers = [ "underlined" ] }
"markup.raw"           = "gray"
"markup.strikethrough" = { fg = "bright-pink", modifiers = [ "crossed_out", "bold" ] }

"diff.delta" = { fg = "blueish", modifiers = [ "bold" ] }
"diff.minus" = { fg = "redish", modifiers = [ "bold" ] }
"diff.plus"  = { fg = "bright-green", modifiers = [ "bold" ] }

"ui.background"           = { bg = "background" }
"ui.background.separator" = { fg = "white" }
"ui.help"                 = { bg = "#35353a", fg = "light-gray" }
"ui.linenr"               = { fg = "#747575" }
"ui.linenr.selected"      = { fg = "#c7dddd" }
"ui.popup"                = { bg = "#3b3b3d" }
"ui.statusline"           = { bg = "gray", fg = "black" }
"ui.statusline.inactive"  = { bg = "#3c3836", fg = "gray" }
"ui.window"               = { fg = "yellow" }

"ui.text"                 = { fg = "light-gray" }
"ui.text.focus"           = { fg = "#83c679" }
"ui.text.inactive"        = "#93a56f"
"ui.virtual"              = { fg = "yellow" }
"ui.virtual.indent-guide" = { fg = "#5b5b5a" }
"ui.virtual.ruler"        = { bg = "#363638" }

"ui.cursor"             = { modifiers = [ "reversed" ] }
"ui.cursor.match"       = { bg = "gray", fg = "white" }
"ui.cursorline.primary" = { bg = "#3b3b3f" }
"ui.selection"          = { bg = "gray", fg = "white" }
"ui.selection.primary"  = { bg = "gray", fg = "white" }

"ui.debug"            = { fg = "#634450" }
"ui.debug.active"     = { fg = "blueish" }
"ui.debug.breakpoint" = { fg = "redish" }
"ui.menu"             = { bg = "black", fg = "gray" }
"ui.menu.selected"    = { bg = "gray", fg = "black" }

"diagnostic.error"   = { underline = { color = "bright-pink", style = "curl" } }
"diagnostic.hint"    = { underline = { color = "bright-yellow", style = "curl" } }
"diagnostic.info"    = { underline = { color = "bright-yellow", style = "curl" } }
"diagnostic.warning" = { underline = { color = "bright-yellow", style = "curl" } }

error   = "bright-pink"
hint    = "bright-yellow"
info    = "bright-yellow"
warning = "bright-yellow"

[palette]
background      = "#1f1f21"
blueish         = "#3876BF"
bright-green    = "#4F6F52"
bright-pink     = "#DE6468"
bright-yellow   = "#FFCB69"
brown           = "#BAA587"
dark-brown      = "#B58463"
green           = "#778e61"
light-green     = "#9B9B7A"
markdown-bold   = "#6faa75"
markdown-italic = "#80a552"
muddy           = "#D08C60"
orange          = "#E8AC65"
pink            = "#D9AE94"
purple-ish      = "#997B66"
redish          = "#B80000"
yellow          = "#F1DCA7"
