# author: Gael Lopes Da Silva
# project: Yellowed
# github: https://github.com/Gael-Lopes-Da-Silva/YellowedHelix

"attribute"                 = { fg = "text" }
"comment"                   = { fg = "comment" }
"constant"                  = { fg = "text", modifiers = [ "bold" ] }
"constant.builtin"          = { fg = "constants", modifiers = [ "bold" ] }
"constant.character"        = { fg = "string" }
"constant.character.escape" = { fg = "constants", modifiers = [ "bold" ] }
"constant.numeric"          = { fg = "keywords" }
"constructor"               = { fg = "text", modifiers = [ "bold" ] }
"function"                  = { fg = "text", modifiers = [ "bold" ] }
"keyword"                   = { fg = "keywords", modifiers = [ "bold" ] }
"keyword.control"           = { fg = "keywords" }
"keyword.control.return"    = { fg = "keywords", modifiers = [ "bold" ] }
"keyword.directive"         = { fg = "keywords" }
"keyword.operator"          = { fg = "keywords" }
"label"                     = { fg = "text" }
"namespace"                 = { fg = "text" }
"operator"                  = { fg = "keywords" }
"punctuation"               = { fg = "text" }
"punctuation.special"       = { fg = "constants", modifiers = [ "bold" ] }
"special"                   = { fg = "yellow" }
"string"                    = { fg = "string" }
"string.regexp"             = { fg = "constants" }
"tag"                       = { fg = "keywords", modifiers = [ "bold" ] }
"type"                      = { fg = "text" }
"type.builtin"              = { fg = "keywords" }
"type.enum"                 = { fg = "keywords" }
"variable"                  = { fg = "text" }
"variable.builtin"          = { fg = "keywords" }
"variable.parameter"        = { fg = "text", modifiers = [ "italic" ] }

"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading.1"      = { fg = "text", modifiers = [ "bold" ] }
"markup.heading.2"      = { fg = "text", modifiers = [ "bold" ] }
"markup.heading.3"      = { fg = "text", modifiers = [ "bold" ] }
"markup.heading.4"      = { fg = "text", modifiers = [ "bold" ] }
"markup.heading.5"      = { fg = "text", modifiers = [ "bold" ] }
"markup.heading.6"      = { fg = "text", modifiers = [ "bold" ] }
"markup.heading.marker" = { fg = "keywords", modifiers = [ "bold" ] }
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.text"      = { fg = "string" }
"markup.link.url"       = { fg = "text", modifiers = [ "underlined" ] }
"markup.list"           = { fg = "keywords", modifiers = [ "bold" ] }
"markup.quote"          = { fg = "text" }
"markup.raw"            = { fg = "string" }

"diff.delta"       = { fg = "blue" }
"diff.delta.moved" = { fg = "gray" }
"diff.minus"       = { fg = "red" }
"diff.plus"        = { fg = "green" }

"ui.background"                   = { bg = "dark_gray", fg = "text" }
"ui.background.separator"         = { fg = "text" }
"ui.cursor"                       = { bg = "yellow", fg = "black" }
"ui.cursor.insert"                = { bg = "yellow", fg = "black" }
"ui.cursor.match"                 = { bg = "light_gray" }
"ui.cursor.normal"                = { bg = "yellow", fg = "black" }
"ui.cursor.primary"               = { bg = "yellow", fg = "black" }
"ui.cursor.primary.insert"        = { bg = "yellow", fg = "black" }
"ui.cursor.primary.normal"        = { bg = "yellow", fg = "black" }
"ui.cursor.primary.select"        = { bg = "yellow", fg = "black" }
"ui.cursor.select"                = { bg = "yellow", fg = "black" }
"ui.cursorcolumn.primary"         = { bg = "gray" }
"ui.cursorcolumn.secondary"       = { bg = "gray" }
"ui.cursorline.primary"           = { bg = "gray" }
"ui.cursorline.secondary"         = { bg = "gray" }
"ui.debug.active"                 = { fg = "green" }
"ui.debug.breakpoint"             = { fg = "red" }
"ui.gutter"                       = { fg = "light_gray" }
"ui.gutter.selected"              = { fg = "light_gray" }
"ui.help"                         = { bg = "menu", fg = "text" }
"ui.highlight"                    = { bg = "light_gray" }
"ui.highlight.frameline"          = { fg = "gray" }
"ui.linenr"                       = { fg = "light_gray" }
"ui.linenr.selected"              = { fg = "yellow" }
"ui.menu"                         = { bg = "gray", fg = "text" }
"ui.menu.scroll"                  = { bg = "dark_gray", fg = "light_gray" }
"ui.menu.selected"                = { bg = "light_gray", fg = "text", modifiers = [ "bold" ] }
"ui.popup"                        = { bg = "menu", fg = "text" }
"ui.popup.info"                   = { bg = "menu", fg = "text" }
"ui.selection"                    = { bg = "selection" }
"ui.selection.primary"            = { bg = "selection" }
"ui.statusline"                   = { bg = "gray", fg = "text" }
"ui.statusline.inactive"          = { bg = "gray", fg = "light_gray" }
"ui.statusline.insert"            = { bg = "green" }
"ui.statusline.normal"            = { bg = "light_gray" }
"ui.statusline.select"            = { bg = "purple" }
"ui.statusline.separator"         = { fg = "dark_gray" }
"ui.text"                         = { fg = "text" }
"ui.text.focus"                   = { bg = "gray" }
"ui.text.inactive"                = { fg = "text" }
"ui.text.info"                    = { fg = "text" }
"ui.virtual.indent-guide"         = { fg = "light_gray" }
"ui.virtual.inlay-hint"           = { fg = "light_gray" }
"ui.virtual.inlay-hint.parameter" = { fg = "light_gray" }
"ui.virtual.inlay-hint.type"      = { fg = "light_gray" }
"ui.virtual.ruler"                = { bg = "light_gray" }
"ui.virtual.whitespace"           = { fg = "light_gray" }
"ui.virtual.wrap"                 = { fg = "light_gray" }
"ui.window"                       = { fg = "text" }

"error"   = { fg = "error" }
"hint"    = { fg = "hint" }
"info"    = { fg = "info" }
"warning" = { fg = "warning" }

"diagnostic.deprecated"  = { modifiers = [ "crossed_out" ] }
"diagnostic.error"       = { underline = { color = "error", style = "curl" } }
"diagnostic.hint"        = { underline = { color = "hint", style = "curl" } }
"diagnostic.info"        = { underline = { color = "info", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = [ "dim" ] }
"diagnostic.warning"     = { underline = { color = "warning", style = "curl" } }

[palette]
# interface
blue       = "#008DFF"
dark_gray  = "#242424"
gray       = "#2a2a2a"
light_gray = "#545454"
menu       = "#202020"
purple     = "#994c92"
selection  = "#3f3f3f"
yellow     = "#ffd900"

# syntax
comment   = "#6b6b6b"
constants = "#ff80f4"
error     = "#FF0000"
hint      = "#4DFF00"
info      = "#0092FF"
keywords  = "#ffd900"
string    = "#378b1d"
text      = "#FFFFFF"
warning   = "#FF9C00"
