# Author: Michael McClintock <michael.mcclintock@hey.com>
# License: MIT

# Yo - Themes for Helix inspired by Zenbones & Alabaster with Radix Colors.
# https://github.com/mrmcc3/yo-theme-helix

# background/text
"ui.background"           = { bg = "p2", fg = "p11" }
"ui.background.separator" = { fg = "p7" }
"ui.text"                 = { fg = "p11" }
"ui.text.focus"           = { fg = "p12", modifiers = [ "bold" ] }

# popups/menus
"ui.help"                 = { bg = "p2", fg = "p12" }
"ui.menu"                 = { bg = "p4", fg = "p11" }
"ui.menu.scroll"          = { bg = "p4", fg = "p8" }
"ui.menu.selected"        = { fg = "p12", modifiers = [ "bold" ] }
"ui.picker.header.column" = { underline.style = "line" }
"ui.popup"                = { bg = "p4", fg = "p12" }
"ui.popup.info"           = { bg = "p2", fg = "p12" }
"ui.text.info"            = { bg = "p2", fg = "p12" }
"ui.window"               = { fg = "p7" }

# cursor/selection
"ui.cursor"                = { bg = "p11", fg = "p2" }
"ui.cursor.insert"         = { bg = "keyword", fg = "p2" }
"ui.cursor.match"          = { fg = "p12", modifiers = [ "bold" ] }
"ui.cursor.primary"        = { bg = "p11", fg = "p2", modifiers = [ "bold" ] }
"ui.cursor.primary.insert" = { bg = "keyword", fg = "p2", modifiers = [ "bold" ] }
"ui.cursor.primary.select" = { bg = "p12", fg = "p2", modifiers = [ "bold" ] }
"ui.cursor.select"         = { bg = "p12", fg = "p2" }
"ui.cursorcolumn.primary"  = { bg = "p3" }
"ui.cursorline.primary"    = { bg = "p3" }
"ui.selection"             = { bg = "p4" }
"ui.selection.primary"     = { bg = "p5" }

# line numbers / diff
diff                 = { fg = "p8" }
"ui.linenr"          = { fg = "p7" }
"ui.linenr.selected" = { fg = "p11" }

# bufferline/statusline
"ui.bufferline"           = { bg = "p4", fg = "p11" }
"ui.bufferline.active"    = { bg = "p11", fg = "p2" }
"ui.statusline"           = { bg = "p4", fg = "p11" }
"ui.statusline.inactive"  = { bg = "p2", fg = "p11" }
"ui.statusline.insert"    = { bg = "keyword", fg = "p2" }
"ui.statusline.normal"    = { bg = "p11", fg = "p2" }
"ui.statusline.select"    = { bg = "p12", fg = "p2" }
"ui.statusline.separator" = { fg = "p7" }

# virtual
"ui.virtual" = { fg = "p6" }
"ui.virtual.inlay-hint" = { fg = "p7", underline.style = "dotted" }
"ui.virtual.jump-label" = { fg = "p12", modifiers = [
  "bold",
], underline = { color = "info", style = "curl" } }
"ui.virtual.ruler" = { bg = "p3" }

# diagnostics
"diagnostic.error"   = { fg = "error", modifiers = [ "bold" ] }
"diagnostic.hint"    = { fg = "info", modifiers = [ "bold" ] }
"diagnostic.info"    = { fg = "info", modifiers = [ "bold" ] }
"diagnostic.warning" = { fg = "warning", modifiers = [ "bold" ] }
error                = { fg = "error", modifiers = [ "bold" ] }
hint                 = { fg = "info", modifiers = [ "bold" ] }
info                 = { fg = "info", modifiers = [ "bold" ] }
warning              = { fg = "warning", modifiers = [ "bold" ] }
# "diagnostic.unnecessary" = {}
# "diagnostic.deprecated" = {}

# code
attribute               = { fg = "p10" }
comment                 = { fg = "info" }
constant                = { fg = "constant" }
constructor             = { fg = "p12" }
function                = { fg = "p11" }
keyword                 = { fg = "keyword" }
label                   = { fg = "p12" }
namespace               = { fg = "p10" }
operator                = { fg = "keyword" }
punctuation             = { fg = "p9" }
"punctuation.delimiter" = { fg = "p8" }
string                  = { fg = "string" }
"string.special.symbol" = { fg = "constant" }
tag                     = { fg = "keyword" }
type                    = { fg = "p12" }
variable                = { fg = "p10" }

# markup
"markup.bold"           = { modifiers = [ "bold" ] }
"markup.heading"        = { fg = "p12", modifiers = [ "bold" ] }
"markup.heading.marker" = { fg = "p8" }
"markup.italic"         = { modifiers = [ "italic" ] }
"markup.link.label"     = { underline.style = "dotted" }
"markup.link.url"       = { underline.style = "line" }
"markup.list"           = { fg = "p8" }
"markup.strikethrough"  = { modifiers = [ "crossed_out" ] }
# "markup.link.text" = {}
"markup.quote" = { fg = "p10" }
# "markup.raw" = {}

[palette] # https://www.radix-ui.com/colors

# grayDark
p1  = "#111111"
p10 = "#7b7b7b"
p11 = "#b4b4b4"
p12 = "#eeeeee"
p2  = "#191919"
p3  = "#222222"
p4  = "#2a2a2a"
p5  = "#313131"
p6  = "#3a3a3a"
p7  = "#484848"
p8  = "#606060"
p9  = "#6e6e6e"

error   = "#ec5d5e" # redDark-10
info    = "#3b9eff" # blueDark-10
warning = "#ff801f" # orangeDark-10

constant = "#9a5cd0" # purpleDark-10
keyword  = "#ae8c7e" # bronzeDark-10
string   = "#33b074" # greenDark-10
