# Zed OneLight
# Author : EricHenry

inherits = "zed_onedark"

"attribute"                = { fg = "green" }
"constant"                 = { fg = "green" }
"constant.builtin"         = { fg = "gold" }
"constant.builtin.boolean" = { fg = "green" }
"constant.numeric"         = { fg = "gold" }
"variable.builtin"         = { fg = "gold" }
"variable.other.member"    = { fg = "orange" }

"markup.heading" = { fg = "orange" }
"markup.list"    = { fg = "orange" }
"markup.quote"   = { fg = "green" }

"ui.cursor"         = { fg = "dark-blue", modifiers = [ "reversed" ] }
"ui.cursor.insert"  = { fg = "dark-blue" }
"ui.cursor.primary" = { fg = "dark-blue", modifiers = [ "reversed" ] }

"ui.cursorline.primary" = { bg = "faint-gray" }
"ui.selection.primary"  = { bg = "blue-gray" }

"ui.virtual.inlay-hint" = { fg = "violet", modifiers = [ "bold" ] }

"ui.statusline"          = { bg = "gray", fg = "black" }
"ui.statusline.inactive" = { bg = "light-black", fg = "white" }
"ui.statusline.insert"   = { bg = "green", fg = "white" }
"ui.statusline.normal"   = { bg = "blue", fg = "white" }
"ui.statusline.select"   = { bg = "purple", fg = "white" }

"ui.text.focus" = { bg = "gray", fg = "ui-text", modifiers = [ "bold" ] }

"ui.help"   = { bg = "dark-gray", fg = "black" }
"ui.popup"  = { bg = "dark-gray" }
"ui.window" = { fg = "dark-gray" }

[palette]
blue        = "#5b79e3ff"
cyan        = "#3882b7ff"
dark-blue   = "#4a62db"
gold        = "#ad6e25ff"
green       = "#649f57ff"
light-black = "#2e323a"
orange      = "#d3604fff"
purple      = "#a449abff"
red         = "#d36151ff"
violet      = "#9294beff"
yellow      = "#dabb7e"
# gray = "#dcdcdd"
blue-gray  = "#d9dcea"
dark-gray  = "#ebebec"
faint-gray = "#efefef"
gray       = "#eaeaed"
light-gray = "#a2a3a7ff"
linenr     = "#b0b1b3"

black            = "#383a41ff"
ui-text          = "#383a41ff"
ui-text-reversed = "#fafafaff"
white            = "#fafafaff"
