# Zed OneDark
# Author : EricHenry

"attribute"                 = { fg = "yellow" }
"comment"                   = { fg = "light-gray", modifiers = [ "italic" ] }
"constant"                  = { fg = "yellow" }
"constant.builtin"          = { fg = "yellow" }
"constant.builtin.boolean"  = { fg = "yellow" }
"constant.character.escape" = { fg = "yellow" }
"constant.numeric"          = { fg = "orange" }
"constructor"               = { fg = "blue" }
"function"                  = { fg = "blue" }
"function.builtin"          = { fg = "blue" }
"function.macro"            = { fg = "blue" }
"function.method"           = { fg = "blue" }
"keyword"                   = { fg = "purple" }
"label"                     = { fg = "ui-text" }
"namespace"                 = { fg = "ui-text" }
"operator"                  = { fg = "ui-text" }
"puncuation"                = { fg = "ui-text" }
"special"                   = { fg = "ui-text" }
"string"                    = { fg = "green" }
"type"                      = { fg = "cyan" }
"variable.builtin"          = { fg = "orange" }
"variable.other.member"     = { fg = "red" }
"variable.parameter"        = { fg = "ui-text" }

"markup.bold"          = { fg = "yellow", modifiers = [ "bold" ] }
"markup.heading"       = { fg = "red" }
"markup.italic"        = { fg = "purple", modifiers = [ "italic" ] }
"markup.link.text"     = { fg = "purple" }
"markup.link.url"      = { fg = "cyan", modifiers = [ "underlined" ] }
"markup.list"          = { fg = "red" }
"markup.quote"         = { fg = "yellow" }
"markup.raw.inline"    = { fg = "green" }
"markup.strikethrough" = { modifiers = [ "crossed_out" ] }

"diff.delta" = "yellow"
"diff.minus" = "red"
"diff.plus"  = "green"

"diagnostic.deprecated"        = { modifiers = [ "crossed_out" ] }
"diagnostic.error".underline   = { color = "red", style = "curl" }
"diagnostic.hint".underline    = { color = "green", style = "curl" }
"diagnostic.info".underline    = { color = "blue", style = "curl" }
"diagnostic.unnecessary"       = { modifiers = [ "dim" ] }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }
"error"                        = { fg = "red", modifiers = [ "bold" ] }
"hint"                         = { fg = "green", modifiers = [ "bold" ] }
"info"                         = { fg = "blue", modifiers = [ "bold" ] }
"warning"                      = { fg = "yellow", modifiers = [ "bold" ] }

"ui.background"           = { bg = "ui-text-reversed" }
"ui.gutter"               = { bg = "gray" }
"ui.virtual"              = { fg = "faint-gray" }
"ui.virtual.indent-guide" = { fg = "faint-gray" }
"ui.virtual.inlay-hint"   = { fg = "blue-gray", modifiers = [ "bold" ] }
"ui.virtual.jump-label"   = { fg = "purple", modifiers = [ "bold", "italic" ] }
"ui.virtual.ruler"        = { bg = "gray" }
"ui.virtual.whitespace"   = { fg = "light-gray" }

"ui.cursor"         = { fg = "white", modifiers = [ "reversed" ] }
"ui.cursor.match"   = { fg = "blue", modifiers = [ "underlined" ] }
"ui.cursor.primary" = { fg = "white", modifiers = [ "reversed" ] }
# Malformed ANSI: dark-blue. See 'https://github.com/helix-editor/helix/issues/5709'
# "ui.cursor.insert" = { fg = "dark-blue" }

"ui.cursorline.primary" = { bg = "gray" }
"ui.selection"          = { bg = "faint-gray" }
"ui.selection.primary"  = { bg = "#293b5bff" }

"ui.highlight"           = { bg = "gray" }
"ui.highlight.frameline" = { bg = "#97202a" }

"ui.linenr"          = { fg = "linenr" }
"ui.linenr.selected" = { fg = "ui-text" }

"ui.statusline"          = { bg = "gray", fg = "white" }
"ui.statusline.inactive" = { bg = "black", fg = "light-gray" }
"ui.statusline.insert"   = { bg = "green", fg = "black" }
"ui.statusline.normal"   = { bg = "blue", fg = "black" }
"ui.statusline.select"   = { bg = "purple", fg = "black" }

"ui.text"       = { fg = "ui-text" }
"ui.text.focus" = { bg = "gray", fg = "white", modifiers = [ "bold" ] }

"ui.help"          = { bg = "gray", fg = "white" }
"ui.menu"          = { bg = "gray", fg = "ui-text" }
"ui.menu.scroll"   = { bg = "light-gray", fg = "ui-text" }
"ui.menu.selected" = { bg = "blue", fg = "ui-text-reversed" }
"ui.popup"         = { bg = "gray" }
"ui.window"        = { fg = "gray" }

"ui.debug" = { fg = "red" }

[palette]
blue       = "#73ade9ff"
blue-gray  = "#5a6f89ff"
cyan       = "#6eb4bfff"
faint-gray = "#3B4048"
gray       = "#2f343ebf"
green      = "#a1c181ff"
light-gray = "#5d636fff"
linenr     = "#5d636fff"
orange     = "#bf956aff"
purple     = "#b477cfff"
red        = "#d07277ff"
yellow     = "#dfc184ff"

black = "#282c33ff"
white = "#c8ccd4ff"
# black and white are used for a lot of the UI text
ui-text          = "#c8ccd4ff" #white
ui-text-reversed = "#282c33ff" #black
