[package]
name              = "the-editor-renderer"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
env_logger = "0.11"
pollster   = "0.4"
thiserror  = "2.0"
wgpu       = "25.0"
wgpu_text  = "0.9"
winit      = "0.30"
