// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct App App;
void __swift_bridge__$App$_free(void* self);

void* __swift_bridge__$Vec_App$new(void);
void __swift_bridge__$Vec_App$drop(void* vec_ptr);
void __swift_bridge__$Vec_App$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_App$pop(void* vec_ptr);
void* __swift_bridge__$Vec_App$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_App$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_App$len(void* vec_ptr);
void* __swift_bridge__$Vec_App$as_ptr(void* vec_ptr);

typedef struct Document Document;
void __swift_bridge__$Document$_free(void* self);

void* __swift_bridge__$Vec_Document$new(void);
void __swift_bridge__$Vec_Document$drop(void* vec_ptr);
void __swift_bridge__$Vec_Document$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Document$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Document$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Document$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Document$len(void* vec_ptr);
void* __swift_bridge__$Vec_Document$as_ptr(void* vec_ptr);

typedef struct __swift_bridge__$EditorId { uint64_t value; } __swift_bridge__$EditorId;
typedef struct __swift_bridge__$Option$EditorId { bool is_some; __swift_bridge__$EditorId val; } __swift_bridge__$Option$EditorId;
typedef struct __swift_bridge__$Rect { uint16_t x; uint16_t y; uint16_t width; uint16_t height; } __swift_bridge__$Rect;
typedef struct __swift_bridge__$Option$Rect { bool is_some; __swift_bridge__$Rect val; } __swift_bridge__$Option$Rect;
typedef struct __swift_bridge__$Position { uint64_t row; uint64_t col; } __swift_bridge__$Position;
typedef struct __swift_bridge__$Option$Position { bool is_some; __swift_bridge__$Position val; } __swift_bridge__$Option$Position;
typedef struct __swift_bridge__$Color { uint8_t kind; uint32_t value; } __swift_bridge__$Color;
typedef struct __swift_bridge__$Option$Color { bool is_some; __swift_bridge__$Color val; } __swift_bridge__$Option$Color;
typedef struct __swift_bridge__$Style { bool has_fg; struct __swift_bridge__$Color fg; bool has_bg; struct __swift_bridge__$Color bg; bool has_underline_color; struct __swift_bridge__$Color underline_color; uint8_t underline_style; uint16_t add_modifier; uint16_t sub_modifier; } __swift_bridge__$Style;
typedef struct __swift_bridge__$Option$Style { bool is_some; __swift_bridge__$Style val; } __swift_bridge__$Option$Style;
typedef struct __swift_bridge__$RenderStyles { struct __swift_bridge__$Style selection; struct __swift_bridge__$Style cursor; struct __swift_bridge__$Style active_cursor; } __swift_bridge__$RenderStyles;
typedef struct __swift_bridge__$Option$RenderStyles { bool is_some; __swift_bridge__$RenderStyles val; } __swift_bridge__$Option$RenderStyles;
typedef struct RenderSpan RenderSpan;
void __swift_bridge__$RenderSpan$_free(void* self);

void* __swift_bridge__$Vec_RenderSpan$new(void);
void __swift_bridge__$Vec_RenderSpan$drop(void* vec_ptr);
void __swift_bridge__$Vec_RenderSpan$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_RenderSpan$pop(void* vec_ptr);
void* __swift_bridge__$Vec_RenderSpan$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_RenderSpan$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_RenderSpan$len(void* vec_ptr);
void* __swift_bridge__$Vec_RenderSpan$as_ptr(void* vec_ptr);

typedef struct RenderLine RenderLine;
void __swift_bridge__$RenderLine$_free(void* self);

void* __swift_bridge__$Vec_RenderLine$new(void);
void __swift_bridge__$Vec_RenderLine$drop(void* vec_ptr);
void __swift_bridge__$Vec_RenderLine$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_RenderLine$pop(void* vec_ptr);
void* __swift_bridge__$Vec_RenderLine$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_RenderLine$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_RenderLine$len(void* vec_ptr);
void* __swift_bridge__$Vec_RenderLine$as_ptr(void* vec_ptr);

typedef struct RenderCursor RenderCursor;
void __swift_bridge__$RenderCursor$_free(void* self);

void* __swift_bridge__$Vec_RenderCursor$new(void);
void __swift_bridge__$Vec_RenderCursor$drop(void* vec_ptr);
void __swift_bridge__$Vec_RenderCursor$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_RenderCursor$pop(void* vec_ptr);
void* __swift_bridge__$Vec_RenderCursor$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_RenderCursor$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_RenderCursor$len(void* vec_ptr);
void* __swift_bridge__$Vec_RenderCursor$as_ptr(void* vec_ptr);

typedef struct RenderSelection RenderSelection;
void __swift_bridge__$RenderSelection$_free(void* self);

void* __swift_bridge__$Vec_RenderSelection$new(void);
void __swift_bridge__$Vec_RenderSelection$drop(void* vec_ptr);
void __swift_bridge__$Vec_RenderSelection$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_RenderSelection$pop(void* vec_ptr);
void* __swift_bridge__$Vec_RenderSelection$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_RenderSelection$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_RenderSelection$len(void* vec_ptr);
void* __swift_bridge__$Vec_RenderSelection$as_ptr(void* vec_ptr);

typedef struct RenderPlan RenderPlan;
void __swift_bridge__$RenderPlan$_free(void* self);

void* __swift_bridge__$Vec_RenderPlan$new(void);
void __swift_bridge__$Vec_RenderPlan$drop(void* vec_ptr);
void __swift_bridge__$Vec_RenderPlan$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_RenderPlan$pop(void* vec_ptr);
void* __swift_bridge__$Vec_RenderPlan$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_RenderPlan$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_RenderPlan$len(void* vec_ptr);
void* __swift_bridge__$Vec_RenderPlan$as_ptr(void* vec_ptr);

void* __swift_bridge__$App$new(void);
struct __swift_bridge__$EditorId __swift_bridge__$App$create_editor(void* self, struct RustStr text, struct __swift_bridge__$Rect viewport, struct __swift_bridge__$Position scroll);
bool __swift_bridge__$App$remove_editor(void* self, struct __swift_bridge__$EditorId id);
bool __swift_bridge__$App$set_viewport(void* self, struct __swift_bridge__$EditorId id, struct __swift_bridge__$Rect viewport);
bool __swift_bridge__$App$set_scroll(void* self, struct __swift_bridge__$EditorId id, struct __swift_bridge__$Position scroll);
bool __swift_bridge__$App$set_active_cursor(void* self, struct __swift_bridge__$EditorId id, uint64_t cursor_id);
bool __swift_bridge__$App$clear_active_cursor(void* self, struct __swift_bridge__$EditorId id);
void* __swift_bridge__$App$cursor_ids(void* self, struct __swift_bridge__$EditorId id);
void* __swift_bridge__$App$render_plan(void* self, struct __swift_bridge__$EditorId id);
void* __swift_bridge__$App$render_plan_with_styles(void* self, struct __swift_bridge__$EditorId id, struct __swift_bridge__$RenderStyles styles);
void* __swift_bridge__$App$text(void* self, struct __swift_bridge__$EditorId id);
bool __swift_bridge__$App$insert(void* self, struct __swift_bridge__$EditorId id, struct RustStr text);
bool __swift_bridge__$App$delete_backward(void* self, struct __swift_bridge__$EditorId id);
bool __swift_bridge__$App$delete_forward(void* self, struct __swift_bridge__$EditorId id);
void __swift_bridge__$App$move_left(void* self, struct __swift_bridge__$EditorId id);
void __swift_bridge__$App$move_right(void* self, struct __swift_bridge__$EditorId id);
void __swift_bridge__$App$move_up(void* self, struct __swift_bridge__$EditorId id);
void __swift_bridge__$App$move_down(void* self, struct __swift_bridge__$EditorId id);
bool __swift_bridge__$App$add_cursor_above(void* self, struct __swift_bridge__$EditorId id);
bool __swift_bridge__$App$add_cursor_below(void* self, struct __swift_bridge__$EditorId id);
bool __swift_bridge__$App$collapse_to_cursor(void* self, struct __swift_bridge__$EditorId id, uint64_t cursor_id);
bool __swift_bridge__$App$collapse_to_first(void* self, struct __swift_bridge__$EditorId id);
void* __swift_bridge__$Document$new(void);
void* __swift_bridge__$Document$from_text(struct RustStr text);
void* __swift_bridge__$Document$text(void* self);
uintptr_t __swift_bridge__$Document$len_chars(void* self);
uintptr_t __swift_bridge__$Document$len_lines(void* self);
bool __swift_bridge__$Document$is_empty(void* self);
uint64_t __swift_bridge__$Document$version(void* self);
bool __swift_bridge__$Document$is_modified(void* self);
uintptr_t __swift_bridge__$Document$primary_cursor(void* self);
uintptr_t __swift_bridge__$Document$cursor_count(void* self);
void* __swift_bridge__$Document$all_cursors(void* self);
bool __swift_bridge__$Document$insert(void* self, struct RustStr text);
bool __swift_bridge__$Document$delete_backward(void* self);
bool __swift_bridge__$Document$delete_forward(void* self);
void __swift_bridge__$Document$move_left(void* self);
void __swift_bridge__$Document$move_right(void* self);
void __swift_bridge__$Document$move_up(void* self);
void __swift_bridge__$Document$move_down(void* self);
bool __swift_bridge__$Document$add_cursor_above(void* self);
bool __swift_bridge__$Document$add_cursor_below(void* self);
void __swift_bridge__$Document$collapse_to_primary(void* self);
bool __swift_bridge__$Document$commit(void* self);
bool __swift_bridge__$Document$undo(void* self);
bool __swift_bridge__$Document$redo(void* self);
uintptr_t __swift_bridge__$Document$char_to_line(void* self, uintptr_t char_idx);
uintptr_t __swift_bridge__$Document$line_to_char(void* self, uintptr_t line_idx);
uint16_t __swift_bridge__$RenderSpan$col(void* self);
uint16_t __swift_bridge__$RenderSpan$cols(void* self);
void* __swift_bridge__$RenderSpan$text(void* self);
bool __swift_bridge__$RenderSpan$has_highlight(void* self);
uint32_t __swift_bridge__$RenderSpan$highlight(void* self);
bool __swift_bridge__$RenderSpan$is_virtual(void* self);
uint16_t __swift_bridge__$RenderLine$row(void* self);
uintptr_t __swift_bridge__$RenderLine$span_count(void* self);
void* __swift_bridge__$RenderLine$span_at(void* self, uintptr_t index);
uint64_t __swift_bridge__$RenderCursor$id(void* self);
struct __swift_bridge__$Position __swift_bridge__$RenderCursor$pos(void* self);
uint8_t __swift_bridge__$RenderCursor$kind(void* self);
struct __swift_bridge__$Style __swift_bridge__$RenderCursor$style(void* self);
struct __swift_bridge__$Rect __swift_bridge__$RenderSelection$rect(void* self);
struct __swift_bridge__$Style __swift_bridge__$RenderSelection$style(void* self);
struct __swift_bridge__$Rect __swift_bridge__$RenderPlan$viewport(void* self);
struct __swift_bridge__$Position __swift_bridge__$RenderPlan$scroll(void* self);
uintptr_t __swift_bridge__$RenderPlan$line_count(void* self);
void* __swift_bridge__$RenderPlan$line_at(void* self, uintptr_t index);
uintptr_t __swift_bridge__$RenderPlan$cursor_count(void* self);
void* __swift_bridge__$RenderPlan$cursor_at(void* self, uintptr_t index);
uintptr_t __swift_bridge__$RenderPlan$selection_count(void* self);
void* __swift_bridge__$RenderPlan$selection_at(void* self, uintptr_t index);


