[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { workspace = true }
anyhow = { workspace = true }
events = { path = "../events" }
renderer = { path = "../renderer" }
text_engine = { path = "../text_engine" }
utils = { path = "../utils" }
