[package]
name              = "the-editor-stdx"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
regex-cursor.workspace         = true
ropey.workspace                = true
unicode-segmentation.workspace = true
